### PR TITLE
Add VSCode youcompleteme

### PR DESCRIPTION
**Pull request by richard1122**
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/598)

### CODE REVIEW

**Comment by richard1122** [comment]
And What's the appropriate API to call if I want to get method(signature help)? Is `GetDoc`?

What's the correct parameters of GetDoc? Is it the same as `GetType`, `GoToDefinition`?

Thanks.

**Comment by vheon** [comment]
> What's the correct parameters of GetDoc? Is it the same as GetType, GoToDefinition?

Since is a subcommand as anyone else it gets the same parameters. Did you tried and it didn't work?

**Comment by vheon** [comment]
I don't know if you knew this: http://puremourning.github.io/ycmd-1/#path--run_completer_command

Is a WIP documentation for the API (thanks to @puremourning) 👍

**Comment by richard1122** [comment]
Thanks @puremourning @vheon , it helps a lot.

**Comment by richard1122** [comment]
> Did you tried and it didn't work?
@vheon When I'm trying to get doc from the following code:
image

cursor position is after the `begin(`, It reports 
```
raise ValueError( NO_DOCUMENTATION_MESSAGE )\\nValueError: No documentation available for current context\\n\", \"message\": \"No documentation available for current context\"}"
```

It's also same for other functions like `vector.push_back` and more...

I'll read that doc to see If I missed anything.

**Comment by vheon** [comment]
What happen if you instead are with the cursor in the middle of `begin`?

**Comment by richard1122** [comment]
@vheon It's the same...

**Comment by richard1122** [comment]
I'm not sure is it relative to platform? I'm using win10 with mingw64 header files.

**Comment by vheon** [comment]
Now that I think about it IIRC the `GetDoc` subcommand returns the documentation that libclang extract from the source file, like doxygen. So unless the header file are documented in that way I don't think that will work. I just tried on my mac and I get the same results `ValueError: No documentation available for current context`

**Comment by richard1122** [comment]
Well, I guess you're right. I'll have a try on a linux virtual machine. 
Thank you very much!

**Comment by puremourning** [comment]
The c-familhy language completer returns that error when libclang returns no 'documentation' associated. @vheon is spot on that if the method signature doesn't have *doxygen* comments associated with it, then libclang returns nothing.
I've been thinking that we could *at least* try and return the signature (or type) info in that case, but it is surprisingly tricky to do.

**Comment by puremourning** [comment]
Wait correction, that's not the whole truth. We actually throw that error only if we can't parse the XML version. It's possible to return something meaningful anyway, so I will take a look at doing that (this has been bugging me too)

**Comment by Valloric** [comment]
I see discussion going on here, but it's not related to the PR, right? Can we merge this?

**Comment by richard1122** [comment]
Yes. Thanks.
And I will test get doc on linux.

**Comment by micbou** [comment]
A new client supporting ycmd. I am all for it.

:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/598#-:-KRSvflfkA20OhKDTdxv:bnnqn0f)*

**Comment by Valloric** [comment]
Always happy to see a new client! :)

@homu r=micbou

**Pull request merged**
