### PR TITLE
[READY] Fix CircleCI badge

### PR DESCRIPTION
**Pull request by micbou**
The CircleCI badge is not pointing to the right branch.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/902)

### CODE REVIEW

**Comment by bstaletic** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/902#-:-L3IAjgHl98fxvys7x6w:bnfp4nl)*

**Comment by puremourning** [comment]
OK stfu Codecov, you're wrong.

:lgtm:

@homu r+

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/902#-:-L3IOvoyI1SwChfjt5zB:b-9txomc)*

**Comment by puremourning** [comment]
Oops .

@zzbot r+

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/902#-:-L3IP2CB9sQ_HP9EcKJt:bkxxhb0)*

**Comment by bstaletic** [comment]
For some reason nothing was uploaded from CircleCI for the PR.

**Pull request merged**
