### PR TITLE
[READY] Add Format command to TypeScript completer

### PR DESCRIPTION
**Pull request by micbou**
Like the Java `Format` command:

typescript-format

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/977)

### CODE REVIEW

**Comment by bstaletic** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/977#-:-L8i9ylV9Ufgd7EvmVWQ:bnfp4nl)*

**Comment by puremourning** [comment]
:lgtm: with minor comments/quesitons

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[ycmd/completers/typescript/typescript_completer.py, line 686 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/977#-L96axzM22b6wstNu8Iv:-L96axzN4UtJDI9IX2ma:b1nglr) ([raw file](https://github.com/valloric/ycmd/blob/85ce1eefde8fe0d13ed80df83ca80422a7529ebc/ycmd/completers/typescript/typescript_completer.py#L686)):*
> ```Python
>     self._Reload( request_data )
> 
>     # TODO: support formatting options through tsconfig.json.
> ```

Could you elaborate on what this would involve and what the limitations/implications of not supporting this are?

---

*[ycmd/completers/typescript/typescript_completer.py, line 700 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/977#-L96bbi_-1iD-AH4DEQX:-L96bbi_-1iD-AH4DEQY:bgvw40e) ([raw file](https://github.com/valloric/ycmd/blob/85ce1eefde8fe0d13ed80df83ca80422a7529ebc/ycmd/completers/typescript/typescript_completer.py#L700)):*
> ```Python
>                                   _BuildTsFormatRange( request_data ) )
> 
>     contents = utils.SplitLines(
> ```

shouldn't this use your new `[ 'lines' ]` or `GetFileLines` thingies ?

---

*[ycmd/completers/typescript/typescript_completer.py, line 846 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/977#-L96c99l8tYqGXGNSoke:-L96c99l8tYqGXGNSokf:bg4265z) ([raw file](https://github.com/valloric/ycmd/blob/85ce1eefde8fe0d13ed80df83ca80422a7529ebc/ycmd/completers/typescript/typescript_completer.py#L846)):*
> ```Python
> def _BuildTsFormatRange( request_data ):
>   filepath = request_data[ 'filepath' ]
>   lines = utils.SplitLines(
> ```

`GetFileLines` ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/977#-:-L96cHtM48F9_szQEI_u:b51mc42)*

**Comment by micbou** [comment]
Reviewed 1 of 1 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[ycmd/completers/typescript/typescript_completer.py, line 686 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/977#-L96axzM22b6wstNu8Iv:-L96msBP1XfGWfv4IyDE:bi1k233) ([raw file](https://github.com/valloric/ycmd/blob/85ce1eefde8fe0d13ed80df83ca80422a7529ebc/ycmd/completers/typescript/typescript_completer.py#L686)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Could you elaborate on what this would involve and what the limitations/implications of not supporting this are?
</blockquote></details>

Updated the TODO.

---

*[ycmd/completers/typescript/typescript_completer.py, line 700 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/977#-L96bbi_-1iD-AH4DEQX:-L96lzkk7ixMXqJptUO0:bny2xov) ([raw file](https://github.com/valloric/ycmd/blob/85ce1eefde8fe0d13ed80df83ca80422a7529ebc/ycmd/completers/typescript/typescript_completer.py#L700)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

shouldn't this use your new `[ 'lines' ]` or `GetFileLines` thingies ?
</blockquote></details>

Of course.

---

*[ycmd/completers/typescript/typescript_completer.py, line 846 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/977#-L96c99l8tYqGXGNSoke:-L96m2SF4EL5bsIEGQcZ:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/85ce1eefde8fe0d13ed80df83ca80422a7529ebc/ycmd/completers/typescript/typescript_completer.py#L846)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

`GetFileLines` ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/977)*

**Comment by puremourning** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/977#-:-L96oW7E109ZedGE_Xvf:bnfp4nl)*

**Comment by bstaletic** [comment]
@zzbot r=puremourning

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/977#-:-L96p9D78_GyamOVouRp:b-7f0b5i)*

**Pull request merged**
