### PR TITLE
Enable TSServer log file

### PR DESCRIPTION
**Pull request by vheon**
[Review on Reviewable](https://reviewable.io/reviews/valloric/ycmd/265)

### CODE REVIEW

**Comment by vheon** [comment]
The log level for the moment is not specifiable. I wanted to use the same settings that we use for the `ycmd` server but apparently we don't push it to the user_options ( I could be wrong though ). If we need to implement it, I will do it in another PR.

**Comment by puremourning** [comment]
as mentioned, i think we can ask `logging`

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/completers/typescript/typescript_completer.py, line 65 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/265#-K4J83XlDPzaqy7V_WQV:-K4J83XlDPzaqy7V_WQW:-1948291235) ([raw file](https://github.com/valloric/ycmd/blob/cb9fb9c4c4ba6fa4d50f60bb6c4a5790341a1596/ycmd/completers/typescript/typescript_completer.py#L65)):*
I suspect we should only set `-level verbose` if the server logging level is debug? Otherwise the extra IO might be a performance penalty.

e.g.:

```python
      if _logger.isEnabledFor( logging.debug ):
        # set verbose logging
      else:
        # set standard logging
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/265#-:-K4J9vaEms6YsWR0_tGE:-736865711)*

**Comment by vheon** [comment]
I didn't know about this, I will look into it.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/265#-:-K4JAwhNwSerZ9Jd4taZ:1027227199)*

**Comment by vheon** [comment]
I've implemented the log level. Now the TSServer will use 'verbose' when ycmd log level is 'debug', 'normal' otherwise. I don't know if it enough.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/265#-:-K4JI8ur28n08T_YUitw:830042588)*

**Comment by vheon** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/completers/typescript/typescript_completer.py, line 65 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/265#-K4J83XlDPzaqy7V_WQV:-K4JJ1kulFz75ylm4dqZ:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/cb9fb9c4c4ba6fa4d50f60bb6c4a5790341a1596/ycmd/completers/typescript/typescript_completer.py#L65)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/265)*

**Comment by puremourning** [comment]
You probably know better than me, but my reading of the docs seems to indicate that `logging.isEnabledFor` is more complete, in that we're not checking if the level is set to a particular value, only that it is sufficiently verbose (could be more). `if _logger.isEnabledFor( logging.DEBUG )` would return True if the level was something like logging.SUPER_MEGA_VERBOSE, but getEffectiveLevel() == logging.DEBUG wouldn't.

At least that's my interpretation. I haven't actually tested it :)

---

Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/265#-:-K4JKRiv1wd9qY-oz2_-:-731451476)*

**Comment by puremourning** [comment]
Anyway, other than that pedantry, this LGTM

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/265#-:-K4JL86Fhs5FgfDjZHDc:52350749)*

**Comment by vheon** [comment]
I didn't read well the docs and I thought that it wasn't available for python 2.6, and that is why I choose the other method. Will amend in a sec ;)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/265#-:-K4JLpiQ5jPZiaZLtvHN:1311011649)*

**Comment by vheon** [comment]
Done

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/265#-:-K4JMyoSiCwUMA90I9Bf:676635175)*

**Comment by puremourning** [comment]
LGTM

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/265#-:-K4JPQjuVCZu3bztP_Jb:676834233)*

**Comment by Valloric** [comment]
Other than minor inline comments, this LGTM.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[ycmd/completers/typescript/typescript_completer.py, line 64 \[r3\]](https://reviewable.io:443/reviews/valloric/ycmd/265#-K4JUGtIA7N09BnBvYy4:-K4JUGtIA7N09BnBvYy5:-1202158405) ([raw file](https://github.com/valloric/ycmd/blob/a383b285ff160cc89eb2e4b3787deb59276e0165/ycmd/completers/typescript/typescript_completer.py#L64)):*
What does "tss" stand for? TS server?

---

*[ycmd/completers/typescript/typescript_completer.py, line 67 \[r3\]](https://reviewable.io:443/reviews/valloric/ycmd/265#-K4JUP2_ceS0UWvxj5ea:-K4JUP2_ceS0UWvxj5eb:-743870835) ([raw file](https://github.com/valloric/ycmd/blob/a383b285ff160cc89eb2e4b3787deb59276e0165/ycmd/completers/typescript/typescript_completer.py#L67)):*
Why are we setting this env var? Is this the way we specify which file the TS server should log to? If so, there should be a comment explaining that here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/265#-:-K4JUdpHr7FAav_HBCDD:573865234)*

**Comment by vheon** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/typescript/typescript_completer.py, line 64 \[r3\]](https://reviewable.io:443/reviews/valloric/ycmd/265#-K4JUGtIA7N09BnBvYy4:-K4JXuztdFvd-G22mOJh:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/a383b285ff160cc89eb2e4b3787deb59276e0165/ycmd/completers/typescript/typescript_completer.py#L64)):*
Done.

---

*[ycmd/completers/typescript/typescript_completer.py, line 67 \[r3\]](https://reviewable.io:443/reviews/valloric/ycmd/265#-K4JUP2_ceS0UWvxj5ea:-K4JXvwFPtfCPQCSPVpJ:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/a383b285ff160cc89eb2e4b3787deb59276e0165/ycmd/completers/typescript/typescript_completer.py#L67)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/265)*

**Comment by puremourning** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/265)*

**Comment by micbou** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[ycmd/completers/typescript/typescript_completer.py, line 67 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/265#-K4JapnKVnJ-mldZL6-c:-K4JapnKVnJ-mldZL6-d:179298024) ([raw file](https://github.com/valloric/ycmd/blob/f741e34d327bd5f22ec7471d0d5549fdde434697/ycmd/completers/typescript/typescript_completer.py#L67)):*
`through` instead of `though`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/265)*

**Comment by vheon** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[ycmd/completers/typescript/typescript_completer.py, line 67 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/265#-K4JapnKVnJ-mldZL6-c:-K4Ji0srdjk3oGWZIiOH:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/f741e34d327bd5f22ec7471d0d5549fdde434697/ycmd/completers/typescript/typescript_completer.py#L67)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/265)*

**Comment by micbou** [comment]
*[ycmd/completers/typescript/typescript_completer.py, line 67 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/265#-K4JapnKVnJ-mldZL6-c:-K4JihtkNJw6gkJ7K_Dl:1312644628) ([raw file](https://github.com/valloric/ycmd/blob/f741e34d327bd5f22ec7471d0d5549fdde434697/ycmd/completers/typescript/typescript_completer.py#L67)):*
Sorry but now it is `trhough`, should be `through`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/265)*

**Comment by vheon** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[ycmd/completers/typescript/typescript_completer.py, line 67 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/265#-K4JapnKVnJ-mldZL6-c:-K4JnT7gMPIHDzJtF4Mr:1259578729) ([raw file](https://github.com/valloric/ycmd/blob/f741e34d327bd5f22ec7471d0d5549fdde434697/ycmd/completers/typescript/typescript_completer.py#L67)):*
amended

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/265)*

**Comment by puremourning** [comment]
I think this is tpyo free now.

@homu r+

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/265#-:-K4JtEviVA-IJYfdmRkj:-1590433690)*

**Pull request merged**
