### PR TITLE
Use Xcode's libclang

### PR DESCRIPTION
**Pull request by haifengkao**
Use Xcode's libclang because it's always newer than Xcode command line tool's libclang
The current libclang in Xcode command line tool is too old.
Switch to libclang in Xcode 8 can fix this error.

**Actual**
```bash
./install.py --clang-completer --system-libclang
```
will output
```
Undefined symbols for architecture x86_64:
  "_clang_parseTranslationUnit2FullArgv", referenced from:
      YouCompleteMe::TranslationUnit::TranslationUnit(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<UnsavedFile, std::__1::allocator<UnsavedFile> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, void*) in TranslationUnit.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
ERROR: the build failed.
```

**Expected**
```
[134/134] Linking CXX shared library /Users/.../YouCompleteMe/third_party/ycmd/ycm_core.so
```

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/666)

### CODE REVIEW

**Comment by puremourning** [comment]
Seems not unreasonable, but why not just remove `--system-libclang` from the command and you get the version of libclang that we actually support and test?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/666#-:-KYIXm0X-AZrh62ZURXW:brptipp)*

**Comment by haifengkao** [comment]
Sorry, I forgot to mention that it's part of the changes (with https://github.com/Valloric/ycmd/pull/667) to make ycmd support `objective-c modules`. The `llvm.org` release cannot support it (and I still don't know why).

See https://github.com/Valloric/ycmd/issues/659, https://github.com/Valloric/YouCompleteMe/issues/1353

**Comment by puremourning** [comment]
@r4nt @d0k any idea why OSS libclang can't support obj c modules?

**Comment by haifengkao** [comment]
Xcode Command Line Tool 8.0 has resolved the error `Undefined symbols for architecture x86_64:
  "_clang_parseTranslationUnit2FullArgv"`.
However, the `libclang` from the command line tool is unable to handle `@import Foundation;` 

It is still necessary to use the `libclang` from Xcode.
Would you please merge this pull request for me?

**Comment by Valloric** [comment]
This seems fine to me. Thanks for the PR!

@puremourning @micbou @vheon Any objections? If not, let's merge this.

**Comment by micbou** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cpp/ycm/CMakeLists.txt, line 295 at r1](https://reviewable.io:443/reviews/valloric/ycmd/666#-KaRHppc82xiPOpjYxJj:-KaRHppc82xiPOpjYxJk:b-tcywp2) ([raw file](https://github.com/valloric/ycmd/blob/10001262a7a01a1547173f15ed3c09de0f8ae6bb/cpp/ycm/CMakeLists.txt#L295)):*
> ```CMake
>                   ${SYS_LLVM_PATHS}
>                   /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
>                   /Library/Developer/CommandLineTools/usr/lib)
> ```

Space before parenthesis.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/666)*

**Comment by vheon** [comment]
Aside the comment @micbou did this :lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/666#-:-KaStAO2q2vGoMoMkKJ7:b-d7r80h)*

**Comment by vheon** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/666)*

**Comment by puremourning** [comment]
:lgtm:  I haven't tested but I don't use system libclang on my macs but the approach seems legit. 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/666#-:-KaSuWgriVAIiYF70zhO:b-uczsyh)*

**Comment by Valloric** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[cpp/ycm/CMakeLists.txt, line 295 at r1](https://reviewable.io:443/reviews/valloric/ycmd/666#-KaRHppc82xiPOpjYxJj:-KaiIjskIDZgJ1Md5XeX:b-felpcw) ([raw file](https://github.com/valloric/ycmd/blob/10001262a7a01a1547173f15ed3c09de0f8ae6bb/cpp/ycm/CMakeLists.txt#L295)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Space before parenthesis.
</blockquote></details>

@haifengkao The above comment is the only one you need to address before we can merge this. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/666)*

**Comment by haifengkao** [comment]
done, but CI generates a lot of errors

**Comment by micbou** [comment]
Travis errors are due to flakiness and Appveyor ones are unrelated to this PR change (I'll look into them). 

@homu r+

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/666#-:-Kani0CF-sI-kS6Lyq0w:b-ifsc3r)*

**Pull request merged**
