### PR TITLE
[READY] Document .ycm_extra_conf.py format

### PR DESCRIPTION
**Pull request by puremourning**
It makes sense to actually document the file format, as mentioned in https://github.com/Valloric/YouCompleteMe/issues/2310

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/591)

### CODE REVIEW

**Comment by micbou** [comment]
[`flags_ready`](https://github.com/Valloric/ycmd/blob/master/ycmd/completers/cpp/flags.py#L93) should be mentioned along the `flags` and `do_cache` items.

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 250 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/591#-KQmAhImJrX5N-a4FaBU:-KQmAhInEUSEEE8VcDO_:b3g6hdn) ([raw file](https://github.com/valloric/ycmd/blob/94236e5913912c0cf26cd6d9ac83618dddb24b68/README.md#L250)):*
> ```Markdown
> 
> `VimClose()` is deprecated and retained only for legacy compatibility.  If both
> `Shutdown()` and `VimClose()` are defined, they are both called.
> ```

I would not mention the `VimClose` method. I don't think users need to know about it.

---

*[README.md, line 193 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/591#-KQnOba7YYMV6xhsUo0J:-KQnOba8F5OmvLCctXjF:blapo) ([raw file](https://github.com/valloric/ycmd/blob/a49cf0c46eea8827e1db3993cd7db221d8ecb7a9/README.md#L193)):*
> ```Markdown
> The `.ycm_extra_conf.py` module must define the following methods:
> 
> #### `FlagsForFile( file_name, **kwargs )`
> ```

`filename` instead of `file_name`? We use this variable name for all of our `.ycm_extra_conf.py` files.

---

*[README.md, line 195 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/591#-KQnOHtSUElT7HbYtE4f:-KQnOHtTrnWX5z-VVEwp:b-ke6q9n) ([raw file](https://github.com/valloric/ycmd/blob/a49cf0c46eea8827e1db3993cd7db221d8ecb7a9/README.md#L195)):*
> ```Markdown
> #### `FlagsForFile( file_name, **kwargs )`
> 
> Optional, required for c-family language support.
> ```

I would only say "Required for...". Saying that it is optional then required is confusing.

---

*[README.md, line 202 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/591#-KQnTaxEWb8BmYLv7IKs:-KQnTaxFDo78Fckoe2Fd:bvvd8x3) ([raw file](https://github.com/valloric/ycmd/blob/a49cf0c46eea8827e1db3993cd7db221d8ecb7a9/README.md#L202)):*
> ```Markdown
> configuration:
> 
> - `client_data` any additional data supplied by the client application.
> ```

Colon after `client_data`?

---

*[README.md, line 216 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/591#-KQnUN7J3ulRXxe5u8Of:-KQnUN7KgR5Wn6e7TyCv:bundoz9) ([raw file](https://github.com/valloric/ycmd/blob/a49cf0c46eea8827e1db3993cd7db221d8ecb7a9/README.md#L216)):*
> ```Markdown
>   -`do_cache`: a boolean indicating whether or not the result of this call
>     (i.e. the list of flags) should be cached for this file name. If you're
>     not sure what this means, just set it to `True`.
> ```

Missing space after the `-` for both items so that it is rendered as bullet points.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/591#-:-KQnRm-eNov29np6MPLc:b-ya230s)*

**Comment by puremourning** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 250 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/591#-KQmAhImJrX5N-a4FaBU:-KQq2cpE8BNnqPsOxHM4:b-ho5wpv) ([raw file](https://github.com/valloric/ycmd/blob/94236e5913912c0cf26cd6d9ac83618dddb24b68/README.md#L250)):*
<details><summary><i>Previously, micbou wrote…</i></summary>
> I would not mention the `VimClose` method. I don't think users need to know about it.
</details>
Agreed. Done.

---

*[README.md, line 193 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/591#-KQnOba7YYMV6xhsUo0J:-KQq2aejYJpd-iSFDw-1:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/a49cf0c46eea8827e1db3993cd7db221d8ecb7a9/README.md#L193)):*
<details><summary><i>Previously, micbou wrote…</i></summary>
> `filename` instead of `file_name`? We use this variable name for all of our `.ycm_extra_conf.py` files.
</details>
Done.

---

*[README.md, line 195 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/591#-KQnOHtSUElT7HbYtE4f:-KQq2b1b8p1bqGNaZzP9:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/a49cf0c46eea8827e1db3993cd7db221d8ecb7a9/README.md#L195)):*
<details><summary><i>Previously, micbou wrote…</i></summary>
> I would only say "Required for...". Saying that it is optional then required is confusing.
</details>
Done.

---

*[README.md, line 202 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/591#-KQnTaxEWb8BmYLv7IKs:-KQq2bVKqRpzQVb3qSk0:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/a49cf0c46eea8827e1db3993cd7db221d8ecb7a9/README.md#L202)):*
<details><summary><i>Previously, micbou wrote…</i></summary>
> Colon after `client_data`?
</details>
Done.

---

*[README.md, line 216 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/591#-KQnUN7J3ulRXxe5u8Of:-KQq2c14AKENGmqraspN:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/a49cf0c46eea8827e1db3993cd7db221d8ecb7a9/README.md#L216)):*
<details><summary><i>Previously, micbou wrote…</i></summary>
> Missing space after the `-` for both items so that it is rendered as bullet points.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/591)*

**Comment by micbou** [comment]
:lgtm:

Once this is merged, I'll update the `do_cache` documentation in PR #592 .

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/591#-:-KQqnsWl4Q-Wawk_V6Xe:bsie02y)*

**Comment by Valloric** [comment]
:lgtm:

Thanks! This needed some docs.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 240 \[r3\]](https://reviewable.io:443/reviews/valloric/ycmd/591#-KQup-DrB-jInEc4wLBH:-KQup-DrB-jInEc4wLBI:bxxflkc) ([raw file](https://github.com/valloric/ycmd/blob/d02c3fd6fe90fc890bc79db11ce77336718be71d/README.md#L240)):*
> ```Markdown
> Optional.
> 
> This method, if defined, is called by the server
> ```

Some weird line wrapping here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/591#-:-KQup96JT65oAv43Bv2z:b-cffn2v)*

**Comment by puremourning** [comment]
Updated in light of #592 and according to @valloric's comment. I also reworded the stuff about accepting the defaults.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/591#-:-KQwJ9sm26UXSPg72qgD:bd0yjvt)*

**Comment by puremourning** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 240 \[r3\]](https://reviewable.io:443/reviews/valloric/ycmd/591#-KQup-DrB-jInEc4wLBH:-KQwJJSIi3jpej4_Gtg9:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/d02c3fd6fe90fc890bc79db11ce77336718be71d/README.md#L240)):*
<details><summary><i>Previously, Valloric (Val Markovic) wrote…</i></summary>
> Some weird line wrapping here.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/591)*

**Comment by micbou** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 229 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/591#-KQwKQml2Sv90fWTmAqw:-KQwKQml2Sv90fWTmAqx:b-2tjaoe) ([raw file](https://github.com/valloric/ycmd/blob/f8e5d56719cc429996c63a32be2ed565a2208f7d/README.md#L229)):*
> ```Markdown
>     'do_cache': True
>   }
> ```
> ```

With #592 merged, the minimal example can be rewritten as:
```python
def FlagsForFile( filename, **kwargs ):
  return { 'flags': [ '-x', 'c++' ] }
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/591)*

**Comment by puremourning** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 229 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/591#-KQwKQml2Sv90fWTmAqw:-KQwNfSgWQw0t3U-IFa0:biq63hm) ([raw file](https://github.com/valloric/ycmd/blob/f8e5d56719cc429996c63a32be2ed565a2208f7d/README.md#L229)):*
<details><summary><i>Previously, micbou wrote…</i></summary>
> With #592 merged, the minimal example can be rewritten as:
> ```python
> def FlagsForFile( filename, **kwargs ):
>   return { 'flags': [ '-x', 'c++' ] }
> ```
</details>
yes, good point! done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/591)*

**Comment by micbou** [comment]
:lgtm:

@homu r+

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/591#-:-KQwOEf8-WZkwEUY1-e4:b33slzv)*

**Pull request merged**
