### PR TITLE
Update submodule from nsf/gocode to mdempsky/gocode

### PR DESCRIPTION
**Pull request by shafreeck**
nsf/gocode is not maintained anymore and it does not work
above go1.10.4

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1092)

### CODE REVIEW

**Comment by bstaletic** [comment]
Thanks for the PR. The builds are failing because now, gocode is being cloned from mdempsky's repo, but ycmd is still looking for the hash of the nsf's gocode commit.

You could solve this by running `git submodule sync`, but then all users will have to do the same once they update ycmd, which isn't really nice. A more userfriendly, but uglier option is to completely remove all traces of nsf's gocode and then place mdempsky's gocode in a new directory, such as `third_party/gocode_new`.

**Comment by shafreeck** [comment]
@bstaletic I removed the original submodel and added a new one.

**Comment by shafreeck** [comment]
Unfortunately, it cannot be built now, the new `gocode` repo cannot be built directly, I will try to fix it later

**Comment by shafreeck** [comment]
Unfortunately, it cannot be built now, the new `gocode` repo cannot be built directly, I will try to fix it later

**Comment by isaachier** [comment]
Added fix on @shafreeck's branch (https://github.com/shafreeck/ycmd/pull/1). If/when that is accepted, it should fix the build issues here.

**Comment by micbou** [comment]
See https://github.com/Valloric/ycmd/issues/1097#issuecomment-418200260.

**Comment by ChoppinBlockParty** [comment]
Since go has changed drastically their package system (for the best I think), `gocode` is basically a binary, that could be easily acquired (or updated) by `go get -u github.com/mdempsky/gocode`, you do not need to have any build instruction around it.  This binary could be used solely by `ycmd` or by other tools as well. I do not see a benefit of having it as a submodule in `ycmd` it is runtime requisite rather than a development dependency.

**Comment by micbou** [comment]
The benefit is to have a frozen version that we know is working with ycmd.

**Comment by ChoppinBlockParty** [comment]
All is done in `go_complete` is start/stop of `gocode` and API interaction. If they create a breaking API change, yes, it is a problem, and the user has to be on old version, until `ycmd` is migrated to a new API - it is like with every software, major/breaking version release. I meant that it ycmd does not need gocode source code in it database to be build, it is an external dependency.

**Comment by puremourning** [comment]
Our philosophy is to pin versions that we test. We don't plan to change that.

**Comment by shafreeck** [comment]
@isaachier Thanks a lot for your PR. The gocode cannot be built still, because of lack of GOPATH, would you like to fix this?

**Comment by bstaletic** [comment]
@shafreeck Take a look at #1098.

**Comment by shafreeck** [comment]
@bstaletic Cool, I will close this PR

**Pull request closed without merging**
