### PR TITLE
[READY] Convert triggers to unicode before compiling them as a regex

### PR DESCRIPTION
**Pull request by micbou**
Fixes Valloric/YouCompleteMe#2022.

Here's the full traceback from the error:
```python
Traceback (most recent call last):
  File "<string>", line 24, in <module>
  File "C:\\Users\\micbou\\.vim\\bundle\\YouCompleteMe\\autoload\..\python\ycm\setup.py", line 59, in SetUpYCM
    return YouCompleteMe( user_options_store.GetAll() )
  File "C:\\Users\\micbou\\.vim\\bundle\\YouCompleteMe\\autoload\..\python\ycm\youcompleteme.py", line 95, in __init__
    self._omnicomp = OmniCompleter( user_options )
  File "C:\\Users\\micbou\\.vim\\bundle\\YouCompleteMe\\autoload\..\python\ycm\omni_completer.py", line 38, in __init__
    super( OmniCompleter, self ).__init__( user_options )
  File "C:\Users\micbou\.vim\bundle\YouCompleteMe\python\ycm\..\..\third_party\ycmd\ycmd\completers\completer.py", line 113, in __init__
    if user_options[ 'auto_trigger' ] else None )
  File "C:\Users\micbou\.vim\bundle\YouCompleteMe\python\ycm\..\..\third_party\ycmd\ycmd\completers\completer_utils.py", line 38, in __init__
    dict( user_trigger_map ) ) if user_trigger_map else
  File "C:\Users\micbou\.vim\bundle\YouCompleteMe\python\ycm\..\..\third_party\ycmd\ycmd\completers\completer_utils.py", line 75, in _FiletypeTriggerDictFromSpec
    regexes = [ _PrepareTrigger( x ) for x in triggers ]
  File "C:\Users\micbou\.vim\bundle\YouCompleteMe\python\ycm\..\..\third_party\ycmd\ycmd\completers\completer_utils.py", line 138, in _PrepareTrigger
    if trigger.startswith( TRIGGER_REGEX_PREFIX ):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```

This is the most straightforward way to fix the issue but not sure if it is the right place. This is why I put the `RFC` tag. I would also like to add tests for this.

[Review on Reviewable](https://reviewable.io/reviews/valloric/ycmd/410)

### CODE REVIEW

**Comment by puremourning** [comment]
Code looks good. Is there any way to add a test for this?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/410#-:-KBoAukWS2XxZNQMzQQm:1074597233)*

**Comment by vheon** [comment]
Can't we just add a test with a unicode char in `completer_utils_test`?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/410#-:-KBoFVSZeUtxKK5rRUMZ:-1238087938)*

**Comment by puremourning** [comment]
LGTM assuming the tests pass :) Nice one!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/410#-:-KBoqIaeoKibRqYLVh9s:-300170466)*

**Comment by Valloric** [comment]
I think this is a solid way of doing it. :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/410#-:-KBp9qvc7mipqzb6LgMt:-1639124216)*

**Comment by Valloric** [comment]
@homu r+

**Pull request merged**
