### PR TITLE
[READY] Bump Boost version to 1.62.0

### PR DESCRIPTION
**Pull request by micbou**
Updated with the `update_boost` script.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/612)

### CODE REVIEW

**Comment by vheon** [comment]
:lgtm:

---

Review status: 0 of 294 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/612#-:-KSotxmG3LMWyV_n0izG:bnfp4nl)*

**Comment by Valloric** [comment]
:lgtm:

Nice work!

Saw WIP, so didn't trigger homu.

---

Review status: 0 of 294 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/612#-:-KSwOMWQsqi1iJixeuUz:b-caeh1i)*

**Comment by micbou** [comment]
Yes, I've marked it as WIP because the builds are failing on OS X. It is not related to the changes in this PR but to the installation of Node from Homebrew:
```
==> Installing node
==> Downloading https://nodejs.org/dist/v6.7.0/node-v6.7.0.tar.xz
==> ./configure --prefix=/usr/local/Cellar/node/6.7.0 --without-npm
==> make install

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```
Since the last update of Node, Homebrew is trying to compile it instead of installing the binary package probably because the OS X version on Travis is not supported anymore. We have two choices here:
 - use a more recent version of OS X (10.10 is a good candidate here; it's the latest version supported by Apple);
 - do not update Node: the one already installed is good enough for our use case.

I prefer the first solution but I'd like to hear your opinion on this.

---

Review status: 0 of 294 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/612#-:-KSwS3NzzQ0jEPeh8X2p:b-z7govh)*

**Comment by vheon** [comment]
> use a more recent version of OS X (10.10 is a good candidate here; it's the latest version supported by Apple);

Is it possible to ask for a version of OS X on Travis? would we have any downside in choosing the latest version? otherwise looks like a no-brainer to me, especially because 90% of macOS users will have the latest version of it so we would actually test the thing that most of the user actually use.

---

Review status: 0 of 294 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/612#-:-KSxJmyX3clvxqgGTBOG:bm4p5nf)*

**Comment by Valloric** [comment]
@micbou I'm fine with both approaches. Feel free to make the final choice based on whatever you think is best.

**Comment by micbou** [comment]
It's now ready.

---

Review status: 0 of 294 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/612#-:-KSzjFkqjjH1gZl4bd_j:b-mmxfs7)*

**Comment by Valloric** [comment]
@homu r=vheon

Thanks!

**Pull request merged**
