### PR TITLE
WIP: use rogpeppe/godef instead of Manishearth/godef

### PR DESCRIPTION
**Pull request by timfeirg**
required by https://github.com/Valloric/YouCompleteMe/pull/2991

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1005)

### CODE REVIEW

**Comment by bstaletic** [comment]
The builds failed because you didn't unregister the old submodule before registering a new one, so git is still looking for the commit from the Manisheart's fork, but now it is looking for it in the upstream repo.

Here's how submodules are unregistered: 
- https://stackoverflow.com/questions/1260748/how-do-i-remove-a-submodule/1260982#1260982
- `git submodule add <remote> third_party/godef`
- Commit and push

**Comment by timfeirg** [comment]
Travis CI goes wrong at `git submodule update --init --recursive`, but I can do this without a problem on my computer.

```shell
git clone git@github.com:timfeirg/ycmd.git
git submodule update --init --recursive
```

I really haven't worked with git submodules / travis-ci a whole lot, would you kindly give some advise on how I can solve this? @bstaletic

**Comment by bstaletic** [comment]
The latest commit should do the job. Let's see if the tests pass.

**Comment by timfeirg** [comment]
Building godef failed with dependency issues, see https://travis-ci.org/Valloric/ycmd/jobs/369066405.

I've added godep into `build.py` to see if it'll work.

**Comment by micbou** [comment]
This fails because the forked godef has [custom changes](https://github.com/Manishearth/godef/tree/da0b40ecd9d74d280b1fd88555405312d1c14780) to make it work.

@Manishearth Could you update your godef fork with the latest changes and prepare a PR?

---

Reviewed 2 of 5 files at r1, 1 of 1 files at r2.
Review status: 3 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/1005#-:-LAXgGrs8gp4x1qLd3yY:bxwmfvd)*

**Comment by timfeirg** [comment]
Since godep is an outdated tool, it could be a better idea to migrate from godep to dep for the godef project.
Or just exclude godef from ycm at all, that'd really unload the mess we're having in this PR, and just let user install godef on their own.

**Comment by bstaletic** [comment]
I have updated and rebased @Manishearth's changes in my godef fork. The ycmd branch with the updated godef is [here](https://github.com/bstaletic/ycmd/tree/godef_update).

@timfeirg Can you try my ycmd branch and confirm it fixes the jump to vendor bug?

**Comment by Manishearth** [comment]
I'll update my fork

We can't use the original since it needs gopath

**Comment by Manishearth** [comment]
Bumping the submodule pointer to https://github.com/Manishearth/godef/tree/ycmd_compat (c3b70c6) should be enough. I don't want to break older versions of YCMD so I'll keep that old branch around as ycmd_old and rename the new one.

**Comment by bstaletic** [comment]
Thanks @Manishearth! I've opened #1006 to update ycmd's submodule.

**Comment by micbou** [comment]
Superseded by PR #1006.

**Pull request closed without merging**
