### PR TITLE
TypeScript: Add GoToOccurences and GoToReferrences subcommands

### PR DESCRIPTION
**Pull request by icholy**
[Review on Reviewable](https://reviewable.io/reviews/valloric/ycmd/350)

### CODE REVIEW

**Comment by Valloric** [comment]
Nice! :)

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[ycmd/completers/typescript/typescript_completer.py, line 289 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/350#-K9pZJqUVIGMirX9dALo:-K9pZJqUVIGMirX9dALp:1115441601) ([raw file](https://github.com/valloric/ycmd/blob/167a70eaae94f5802dd530bcfaf5d8e5db8e9044/ycmd/completers/typescript/typescript_completer.py#L289)):*
It's "references", not "referrences".  :)

I'm assuming this works the way it's documented in YCM's README? 

What does GoToOccurrences do? We don't have any docs for it in YCM, so if we're exposing it, there should be a separate PR with docs.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/350#-:-K9pZdnRHLWuSANU2goN:-1979071344)*

**Comment by puremourning** [comment]
Nice. minor comments. Though I am curious what `GoToOcurrances` does compared with `GoToReferences` and why only the former comes with the line text .

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[ycmd/tests/typescript/subcommands_test.py, line 170 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/350#-K9rWFsHQn8YcLXPxpDs:-K9rWFsHQn8YcLXPxpDt:1273266834) ([raw file](https://github.com/valloric/ycmd/blob/167a70eaae94f5802dd530bcfaf5d8e5db8e9044/ycmd/tests/typescript/subcommands_test.py#L170)):*
the test should check the offsets too. like we have to maintain and test that we're returning 1-based offsets for everything.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/350#-:-K9rWZ0u3tWa6TsTPya5:-1833469430)*

**Comment by icholy** [comment]
`GoToOccurrences` only looks in the current file and doesn't return line text.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/typescript/typescript_completer.py, line 289 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/350#-K9pZJqUVIGMirX9dALo:-K9r_eYkP8f9ylMYSJkC:-1880737706) ([raw file](https://github.com/valloric/ycmd/blob/167a70eaae94f5802dd530bcfaf5d8e5db8e9044/ycmd/completers/typescript/typescript_completer.py#L289)):*
Derp, ok fixed the typo.

Yep, it works the way it's documented.

They both do the same thing, but `GoToOccurrences` only looks in the current file and doesn't return line text. I wouldn't be opposed to removing it. I just added it because it was there. 

---

*[ycmd/tests/typescript/subcommands_test.py, line 170 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/350#-K9rWFsHQn8YcLXPxpDs:-K9ratRHUMDySIedcK_f:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/167a70eaae94f5802dd530bcfaf5d8e5db8e9044/ycmd/tests/typescript/subcommands_test.py#L170)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/350#-:-K9r_rbGIgxHY8KEx9Tq:472668207)*

**Comment by puremourning** [comment]
I'm not super sure that there's much value in `GoToOcurrances` if you have `GoToReferences`. What do you think? IMO For a user, a single command which already works in other filetypes is better than 2 potentially confusing commands.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/350#-:-K9rb0hM3ZtnP09Wy1Mu:1602157846)*

**Comment by icholy** [comment]
I'm not going to be using it. I just saw that tsserver exposed it so I threw it in. I have no issues with removing it.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/350#-:-K9rbFDl3SKHYPdW_gmi:1714884589)*

**Comment by puremourning** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/completers/typescript/typescript_completer.py, line 289 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/350#-K9pZJqUVIGMirX9dALo:-K9rbICfVl7opRijieiB:1176573096) ([raw file](https://github.com/valloric/ycmd/blob/167a70eaae94f5802dd530bcfaf5d8e5db8e9044/ycmd/completers/typescript/typescript_completer.py#L289)):*
As I said, my vote goes to removing it for simplicity (for the user)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/350)*

**Comment by icholy** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/completers/typescript/typescript_completer.py, line 289 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/350#-K9pZJqUVIGMirX9dALo:-K9rbmdhrPYHvzhokqyl:2010597031) ([raw file](https://github.com/valloric/ycmd/blob/167a70eaae94f5802dd530bcfaf5d8e5db8e9044/ycmd/completers/typescript/typescript_completer.py#L289)):*
I removed it

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/350)*

**Comment by vheon** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/completers/typescript/typescript_completer.py, line 289 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/350#-K9pZJqUVIGMirX9dALo:-K9rbmQYG9bDwXQsq24_:-1757423878) ([raw file](https://github.com/valloric/ycmd/blob/167a70eaae94f5802dd530bcfaf5d8e5db8e9044/ycmd/completers/typescript/typescript_completer.py#L289)):*
I would remove it too.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/350)*

**Comment by puremourning** [comment]
zoot. :lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/350#-:-K9rbwM6i6UW4ur2t_P9:1830643997)*

**Comment by vheon** [comment]
Apart from the comment I just made :lgtm: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/tests/typescript/subcommands_test.py, line 145 \[r3\]](https://reviewable.io:443/reviews/valloric/ycmd/350#-K9rcFpw2EQ0t9f-Hvgy:-K9rcFpw2EQ0t9f-Hvgz:-382668878) ([raw file](https://github.com/valloric/ycmd/blob/127ef098167594598522dea56ac1da9d81b2c2fd/ycmd/tests/typescript/subcommands_test.py#L145)):*
Are these lines 80-char wide? If not just indent the dict :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/350#-:-K9rcQ1j6Onvc4PAYGbv:-1961683087)*

**Comment by icholy** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/tests/typescript/subcommands_test.py, line 145 \[r3\]](https://reviewable.io:443/reviews/valloric/ycmd/350#-K9rcFpw2EQ0t9f-Hvgy:-K9rctHwCRfed4GGLJwq:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/5ebccd380b8b9ba5e1bfa42e709b05f5ecee1903/ycmd/tests/typescript/subcommands_test.py#L145)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/350)*

**Comment by puremourning** [comment]
Thanks!

@homu r+

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/350#-:-K9rd4M1ndkIQuXqMjjs:-388066883)*

**Pull request merged**
