### PR TITLE
Continuous C# completions

### PR DESCRIPTION
**Pull request by mispencer**
While researching [NRefactory](https://github.com/icsharpcode/NRefactory), which our C# completer, [Omnisharp](https://github.com/OmniSharp/omnisharp-server), is a wrapper of, I noticed that it provided a "controlspace" parameter to a completion generator method. Upon investigation, it appears that [it should called with true for explicit completion (by, for example, pressing control-space), and with false for non-explicit completion (the completion-as-you-type that Ycmd is used for)](https://github.com/icsharpcode/SharpDevelop/blob/newNR/src/AddIns/BackendBindings/CSharpBinding/Project/Src/Completion/CSharpCompletionBinding.cs). This pull request implements this behavior.

When you are typing, the C# semantic completer is called in non-controlspace mode. Additionally, it is called everywhere, and is no longer restricted to locations matching the triggers. When it returns no completions, ycmd will fallback to the identifier completer. When you explicitly ask for completion (for example, by the completion key-bind in YouCompleteMe), the C# semantic completer is called in controlspace mode.

These two modes are not interchangeable, so this required altering the cache logic as well. We need to only return the cache if it matches the correct mode. I implemented this in a way which should not affect the other completers.

In my performance testing, the non-controlspace completions returns in sub-1/10 second in almost all cases. The only syntax which I noticed slowness is after a new keyword. The identifier completer results were rarely relevant in this case, and the semantic completions returns the constructors, so I feel this is acceptable.

Note also that this change required pulling forward our OmniSharpServer submodule. I have not noticed any regressions in my testing.

I have signed the CLA.

### CODE REVIEW

**Comment by Valloric** [comment]
I'm not sure how I feel about this PR. The model we have with identifier-based completion when typing "normally" works surprisingly well. We also present a very consistent user experience across languages; this PR would change that so we end up doing something entirely different for C# for possibly not a lot of benefit. 

This whole "doing something entirely different for C#" is my main concern (after performance, but you say that isn't an issue). I'd prefer presenting a simple mental model to the user that's consistent across languages.

Thoughts?

**Comment by mispencer** [comment]
In most cases, the semantic completer is going to be providing a list of identifiers, same as the identifier-based completer would. It's just that instead of the list being based on the buffers you have opened, it would be based on what identifiers the semantic completer knows are legal wherever you are completing. Without knowing the details of how ycmd works behind the scene, I'm not sure you could tell the difference.

The only exceptions are completing methods and constructors. Methods already are semantic completion, of course, and constructor completions are similar enough for semantic completions to be expected.

Having said that, if we want to continue with semantic completions on triggers, adding new trigger for new would get us most of the way there. I would especially like to see the completion for constructors.

In any case, I would love it if anyone who uses the ymcd C# completions regularly could check this out, and let us know what they think. I have been using this for awhile now, and I feel it's an improvement, but this is a subjective measure. Perhaps it is less of improvement, or even a setback on other code bases or programming styles.

**Comment by Valloric** [comment]
I could see this being merged in, but we need to have this tested out a bit by those who use YCM with C# (I'm not one such user). 

@metatheos @akhosravian Could you take a look at this?

**Comment by vheon** [comment]
@mispencer so did you tried with the regex trigger for the `new` keyword?

**Comment by mispencer** [comment]
I have tried using the regex for ```new```, but I prefer this pull request's solution. Before I implemented the change in this pull request, I was using a ```.``` regex trigger.

**Comment by akhosravian** [comment]
I'll try this out this week.

**Comment by akhosravian** [comment]
I've noticed some very long waits (sometimes minutes) when running :YcmCompleter GoTo since pulling this change - I haven't been able to identify a particular pattern to when this happens. Here's the omnisharp stdout log from one such run: https://gist.github.com/akhosravian/199c31fceeea8039f4e4 The stderr file was empty, and I didn't grab the ycm server log file. 

What info would be useful here?

**Comment by Valloric** [comment]
It could be related to the OmniSharp version bump.

**Comment by Valloric** [comment]
What's the state of this PR now?

**Comment by mispencer** [comment]
I just rebased it.

The goto performance is probably due to the Omnisharp version increase. Possibly related to https://github.com/OmniSharp/omnisharp-server/pull/153?

**Comment by akhosravian** [comment]
I've been running with this for a bit. The issue I previously mentioned appears to be related to using vimgrep on a relatively large project (i.e. several thousand files). I'll check whether the problem is actually related to this change or not later this week.

**Comment by akhosravian** [comment]
Sorry for the delay - without this change it looks like there's a different set of bad behavior from OmniSharp when using vimgrep over a large number of files. In other words: this change seems fine to me.

**Comment by Valloric** [comment]
OK, let's merge this in then. I'm wary of unintended breakage; not specifically the code, but the user's mental model.

But seeing reports of this being a solid change by those who have tested it out makes me more confident.

@homu r+

**Comment by Valloric** [comment]
Bah, Travis flaked.

@homu retry

**Pull request merged**
