### PR TITLE
Skip completion cache if force_semantic is set

### PR DESCRIPTION
**Pull request by vincentwoo**
This is a simple way to deal with the issues described in #430 as suggested by @puremourning in https://github.com/Valloric/ycmd/issues/430#issuecomment-201540248.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/443)

### CODE REVIEW

**Comment by puremourning** [comment]
Needs tests :/

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/443#-:-KDk0ataPcswG8jvTmYp:-537945060)*

**Comment by mispencer** [comment]
It's common for me to force completions, have it time out, force it again, and get completions from the  cache. I just tested this, and with this change, I can't get any completions at all, since it always times out.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/443#-:-KDk5EarDDKQWSV60iE-:-870972918)*

**Comment by micbou** [comment]
Another reason to add a `cache` parameter instead of using `force_semantic` in the request.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/443#-:-KDk8FsJz303GyvIQJIb:-1321736620)*

**Comment by Valloric** [comment]
Thanks for the PR! :)

I'm leaning towards not merging this because of the use-case @mispencer brought up. I too have used that in the past.

Thoughts?

@vincentwoo In the future, please make sure you're adding tests for any new changes. We don't accept PRs without tests. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/443#-:-KDkIBWfv9gcLG3qbwBn:-1199278700)*

**Comment by vincentwoo** [comment]
No prob. I'll redo this with an explicit new parameter (cache: false seems fine) as well as a test.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/443#-:-KDkWa3VvBZQxlDwoaXj:-148185615)*

**Comment by Valloric** [comment]
[See [my comment](https://github.com/Valloric/ycmd/issues/430#issuecomment-201656058) on #430 first]

Again, thank you for the PR! 

@micbou, @puremourning and I can't imagine a case where YCM, emacs-ycmd or the other clients in ycmd's designed-for category of clients would _ever_ set the `cache: false` param, so supporting it _forever_ (ycmd tries hard to not break backwards compatibility) does not seem worth it, sorry. We have a general rule that features need to be widely useful to be worth future maintenance.

**Comment by oblitum** [comment]
The suggested `cache` flag is very useful/important for https://github.com/Valloric/YouCompleteMe/pull/1300.

**Comment by oblitum** [comment]
Reason. It suggest multiplexing normal completion and hints from the same start_column, but conditioned to the presence of characters following the hint trigger or not. If the user forces completion after opening function parenthesis, for example, it should bring hints, if the user has typed any identifier character after the parenthesis and forces semantic completion, the expected is not to have hints anymore, so it should not bring the cache from start_column, it should force complete the standard way without hints.

**Comment by oblitum** [comment]
Just for reference, I've personally solved it this way: https://github.com/Valloric/ycmd/issues/491#issuecomment-219296474.

**Pull request closed without merging**
