### PR TITLE
[READY] Improve completion of include statements in C-family languages

### PR DESCRIPTION
**Pull request by micbou**
This PR fixes the issue where completion is interrupted after inserting a non-identifier character in include statements. See issues https://github.com/Valloric/YouCompleteMe/issues/281 and https://github.com/Valloric/YouCompleteMe/issues/1553.

This is done by moving the include completion logic from the filename completer to the Clang one and by setting the start column to the right position thanks to PR https://github.com/Valloric/ycmd/pull/681. A benefit of moving the logic to the Clang completer is that `<C-Space>` now works in include statements.

Here's a demo before the changes:

include-statement-before

and after:

include-statement-after

You'll notice that no error is shown to the user after inserting the dot.

Fixes https://github.com/Valloric/YouCompleteMe/issues/281.
Fixes https://github.com/Valloric/YouCompleteMe/issues/1553.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/843)

### CODE REVIEW

**Comment by micbou** [comment]
Had to move the code adding the macOS include paths outside of `PrepareFlagsForClang` because it was screwing the tests.

---

Reviewed 7 of 7 files at r1, 2 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/843#-:-KutHhgYf3vJDFa6gnHi:byf0v2z)*

**Comment by micbou** [comment]
Added a filename completer test to fix the coverage decrease.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/843#-:-KuuF556EFfVkP7qbTxw:b-z235x7)*

**Comment by puremourning** [comment]
Thanks! It’s really great to fix this. Will make a lot of people happy :)

Gave it a really light review. Will review fully ASAP. Generally approach looks good. 

---

Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[ycmd/completers/cpp/clang_completer.py, line 107 at r5](https://reviewable.io:443/reviews/valloric/ycmd/843#-KuvUhhrVzBTrZTXkBoi:-KuvUhhrVzBTrZTXkBoj:b-8j2748) ([raw file](https://github.com/valloric/ycmd/blob/c9e27d591b5223f70231bcf1954cc6520601d4a1/ycmd/completers/cpp/clang_completer.py#L107)):*
> ```Python
>   def GetIncludePaths( self, request_data ):
>     current_line = request_data[ 'line_value' ]
>     column_num = request_data[ 'column_num' ]
> ```

I realise this might be moved code, but Shouldn’t this be a column_codepoint? current_line is Unicode not bytes, so we’re indexing a Unicode string with a byte offset, which I think is wrong. 

---

*[ycmd/completers/cpp/clang_completer.py, line 607 at r5](https://reviewable.io:443/reviews/valloric/ycmd/843#-KuvWYjysoV1sCmmP5G2:-KuvWYjysoV1sCmmP5G3:b-mki4fz) ([raw file](https://github.com/valloric/ycmd/blob/c9e27d591b5223f70231bcf1954cc6520601d4a1/ycmd/completers/cpp/clang_completer.py#L607)):*
> ```Python
>       close_char_pos = line.find( close_char, match.end() )
>       if close_char_pos != -1:
>         include_value = line[ include_start : close_char_pos ]
> ```

I’m this branch we set `include_value` but not `start_codepoint`. The calling code assumes that start codepoint is set if include value is set. 

---

*[ycmd/completers/general/filename_completer.py, line 106 at r5](https://reviewable.io:443/reviews/valloric/ycmd/843#-KuvXLmNrTZ5OdqOIlBT:-KuvXLmNrTZ5OdqOIlBU:bsxpewa) ([raw file](https://github.com/valloric/ycmd/blob/c9e27d591b5223f70231bcf1954cc6520601d4a1/ycmd/completers/general/filename_completer.py#L106)):*
> ```Python
> 
>     return GenerateCandidatesForPaths(
>       _GetPathsStandardCase(
> ```

Optional: I guess we could rename his now. There’s only one case now (I think)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/843#-:-KuvXttsCgb36hwCnWg3:b-k4htrs)*

**Comment by puremourning** [comment]
Review status: 7 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/valloric/ycmd/843#-KuvYFHyXIA5q6-P9qnW:-KuvYFHzeo628HvConAb:bnj17ka) (no related file):*
I didn’t really follow why the mac flags thing had to change for this. I seem to recall there was a reason it was where it was, but I confess I don’t remember and if I didn’t comment it well enough then that’s on me!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/843)*

**Comment by micbou** [comment]
Reviewed 2 of 2 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/valloric/ycmd/843#-KuvYFHyXIA5q6-P9qnW:-KuxQ5ATNMuAZ3HPO592:b-hrzzr7) (no related file):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I didn’t really follow why the mac flags thing had to change for this. I seem to recall there was a reason it was where it was, but I confess I don’t remember and if I didn’t comment it well enough then that’s on me!
</blockquote></details>

Adding the mac include paths makes it impossible to check for the exact list of expected include paths in the tests because of all the system headers. I changed it so that when we specify the flags through the `compilation_flags` field in the request (which we often do in the tests), we don't add those include paths.

---

*[ycmd/completers/cpp/clang_completer.py, line 107 at r5](https://reviewable.io:443/reviews/valloric/ycmd/843#-KuvUhhrVzBTrZTXkBoi:-KuxRiAmrA0m582DnmQV:bq7h4ng) ([raw file](https://github.com/valloric/ycmd/blob/c9e27d591b5223f70231bcf1954cc6520601d4a1/ycmd/completers/cpp/clang_completer.py#L107)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I realise this might be moved code, but Shouldn’t this be a column_codepoint? current_line is Unicode not bytes, so we’re indexing a Unicode string with a byte offset, which I think is wrong. 
</blockquote></details>

Mistake on my part. This is new code. Fixed.

---

*[ycmd/completers/cpp/clang_completer.py, line 607 at r5](https://reviewable.io:443/reviews/valloric/ycmd/843#-KuvWYjysoV1sCmmP5G2:-KuxQxfDRo3uqTmznNSu:b-f0k7jz) ([raw file](https://github.com/valloric/ycmd/blob/c9e27d591b5223f70231bcf1954cc6520601d4a1/ycmd/completers/cpp/clang_completer.py#L607)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I’m this branch we set `include_value` but not `start_codepoint`. The calling code assumes that start codepoint is set if include value is set. 
</blockquote></details>

The calling code now checks that `start_codepoint` is set. Also, `start_codepoint` is now 1-based.

---

*[ycmd/completers/general/filename_completer.py, line 106 at r5](https://reviewable.io:443/reviews/valloric/ycmd/843#-KuvXLmNrTZ5OdqOIlBT:-KuxQpYsoSVIDMsrBhWs:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/c9e27d591b5223f70231bcf1954cc6520601d4a1/ycmd/completers/general/filename_completer.py#L106)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Optional: I guess we could rename his now. There’s only one case now (I think)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/843)*

**Comment by bstaletic** [comment]
I gave this a quick test, but I didn't have time to review it properly.

The issue I have noticed is that include path completion inside angled brackets doesn't seem to work any more. I just get no suggestions.

---

Reviewed 1 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/843#-:-KuxvioL66Uu3anx0Izc:bcmtb2s)*

**Comment by bstaletic** [comment]
Sorry for the hasty comment, the problem was caused by bad extra conf from when I tried to reproduce the gcc-7.2 bug.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/843#-:-KuxyUoWqz3KPICynu7q:b-vhbro3)*

**Comment by bstaletic** [comment]
Reviewed 2 of 7 files at r1, 1 of 3 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[ycmd/completers/cpp/clang_completer.py, line 607 at r5](https://reviewable.io:443/reviews/valloric/ycmd/843#-KuvWYjysoV1sCmmP5G2:-KuzA-NTcYa3mc7yRih7:b-rro8d7) ([raw file](https://github.com/valloric/ycmd/blob/c9e27d591b5223f70231bcf1954cc6520601d4a1/ycmd/completers/cpp/clang_completer.py#L607)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

The calling code now checks that `start_codepoint` is set. Also, `start_codepoint` is now 1-based.
</blockquote></details>

I think we should either set `start_codepoint` in this branch or have a comment that would explain why is it not set.

---

*[ycmd/completers/cpp/clang_completer.py, line 582 at r6](https://reviewable.io:443/reviews/valloric/ycmd/843#-Kuz9M98pPRD4L3ouf97:-Kuz9M99oBYrOp4oJVw0:b-q1i8xq) ([raw file](https://github.com/valloric/ycmd/blob/82220efd38601dbb0939b6a1fec2152ff82dd55b/ycmd/completers/cpp/clang_completer.py#L582)):*
> ```Python
> 
> def GetIncludeStatementValue( line, check_closing = True ):
>   """Returns include statement value and boolean indicating whether include
> ```

This comment suggest only two values are returned, but the function returns thee.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/843)*

**Comment by micbou** [comment]
Reviewed 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[ycmd/completers/cpp/clang_completer.py, line 607 at r5](https://reviewable.io:443/reviews/valloric/ycmd/843#-KuvWYjysoV1sCmmP5G2:-KuzsD73fkcYmKlVRJ6U:bsal4j8) ([raw file](https://github.com/valloric/ycmd/blob/c9e27d591b5223f70231bcf1954cc6520601d4a1/ycmd/completers/cpp/clang_completer.py#L607)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

I think we should either set `start_codepoint` in this branch or have a comment that would explain why is it not set.
</blockquote></details>

It's mentioned in the new docstring.

---

*[ycmd/completers/cpp/clang_completer.py, line 582 at r6](https://reviewable.io:443/reviews/valloric/ycmd/843#-Kuz9M98pPRD4L3ouf97:-Kuzq82Wmkwfbl1CAFCq:byew2g6) ([raw file](https://github.com/valloric/ycmd/blob/82220efd38601dbb0939b6a1fec2152ff82dd55b/ycmd/completers/cpp/clang_completer.py#L582)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

This comment suggest only two values are returned, but the function returns thee.
</blockquote></details>

I've rewritten the docstring. I think it's now clearer what the function does.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/843)*

**Comment by bstaletic** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[ycmd/completers/cpp/clang_completer.py, line 582 at r6](https://reviewable.io:443/reviews/valloric/ycmd/843#-Kuz9M98pPRD4L3ouf97:-Kv-7hZuYncVD_IVZVSd:by0a2ji) ([raw file](https://github.com/valloric/ycmd/blob/82220efd38601dbb0939b6a1fec2152ff82dd55b/ycmd/completers/cpp/clang_completer.py#L582)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

I've rewritten the docstring. I think it's now clearer what the function does.
</blockquote></details>

It's much better now. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/843)*

**Comment by Valloric** [comment]
This is pretty damn sweet! Thank you!

I gave this a light review; looks good, though at-a-glance it appears like it might benefit from some more tests. I saw lots of new non-trivial code but not quite as many tests as I'd expect. Let's try to hit really solid test coverage on the new code. 

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/843#-:-Kv4e8KNyq8DV1DeiChy:bt1eah0)*

**Comment by micbou** [comment]
Added 7 new tests for a total of 14 tests. In particular, separate tests for the `-I`, `-isystem`, and `-iquote` flags and for directories containing spaces.

---

Reviewed 1 of 1 files at r9, 3 of 3 files at r10.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/843#-:-Kv8dsoPwEdwyDXOip03:b-kdvekb)*

**Comment by bstaletic** [comment]
:lgtm:
This has good enough coverage in my opinion.

What is not covered is exception throwing in [`clang_completer.py`](https://codecov.io/gh/Valloric/ycmd/compare/aeeee206ce0e8a3464afa941997b28b25ac83f48...5d1cc7f9dc9e3a4e4ec97cf87b4c3fa24c6e46e5/diff#D1-131...133) as well as in [`flags.py`](https://codecov.io/gh/Valloric/ycmd/compare/aeeee206ce0e8a3464afa941997b28b25ac83f48...5d1cc7f9dc9e3a4e4ec97cf87b4c3fa24c6e46e5/diff#D6-615...616). I'm fine with both.

---

Reviewed 3 of 3 files at r10.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/843#-:-Kvbef1EKNjXXLUKZJiV:b3ya42d)*

**Comment by Valloric** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/valloric/ycmd/843#-KuvYFHyXIA5q6-P9qnW:-Kvclg8ZYFuePrL04I4j:b1ql4jn) (no related file):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Adding the mac include paths makes it impossible to check for the exact list of expected include paths in the tests because of all the system headers. I changed it so that when we specify the flags through the `compilation_flags` field in the request (which we often do in the tests), we don't add those include paths.
</blockquote></details>

:lgtm: , thanks!

Not triggering zzbot because I see @puremourning did a review pass but hasn't provided an LGTM yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/843)*

**Comment by puremourning** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/valloric/ycmd/843#-KuvYFHyXIA5q6-P9qnW:-Kv-eylPV2vFUn0oQFQP:bp1l1yr) (no related file):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Adding the mac include paths makes it impossible to check for the exact list of expected include paths in the tests because of all the system headers. I changed it so that when we specify the flags through the `compilation_flags` field in the request (which we often do in the tests), we don't add those include paths.
</blockquote></details>

Ah ok that seems reasonable. I doubt it is a regression for YCM, but we perhaps should check that no other clients use his part of the API

---

*[ycmd/completers/cpp/clang_completer.py, line 607 at r5](https://reviewable.io:443/reviews/valloric/ycmd/843#-KuvWYjysoV1sCmmP5G2:-KviXKwXtl_lefHadWKR:bfwkzqj) ([raw file](https://github.com/valloric/ycmd/blob/c9e27d591b5223f70231bcf1954cc6520601d4a1/ycmd/completers/cpp/clang_completer.py#L607)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

It's mentioned in the new docstring.
</blockquote></details>

I do feel that the API for this method is kinda wonky. Maybe we should just split it into two functions instead of having an argument that sort of fundamentally changes the outputs. Anyway, not really urgent/important and not a blocker.

---

*[ycmd/tests/clang/flags_test.py, line 445 at r10](https://reviewable.io:443/reviews/valloric/ycmd/843#-Kvi_WZmaTnc_UwRHbg-:-Kvi_WZmaTnc_UwRHbg0:b-x1fz1y) ([raw file](https://github.com/valloric/ycmd/blob/5d1cc7f9dc9e3a4e4ec97cf87b4c3fa24c6e46e5/ycmd/tests/clang/flags_test.py#L445)):*
> ```Python
> def AddMacIncludePaths_NoSysroot_test():
>   assert_that(
>     flags._AddMacIncludePaths( [ '-test', '--test1', '--test2=test' ] ),
> ```

I'm less convinced these tests are really testing that we really add mac flags anymore. I mean yes, we're testing that the function that add's mac include paths actually adds a path, but we're not really testing that the flags class ever actually calls that... unless we're proving that somewhere else ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/843#-:-Kvi_rrKjGNmHe1XNxyd:bb6ywmx)*

**Comment by micbou** [comment]
Reviewed 2 of 2 files at r11.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/valloric/ycmd/843#-KuvYFHyXIA5q6-P9qnW:-KvqEmWesFa2zpSgvxhq:b-jyxhvb) (no related file):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Ah ok that seems reasonable. I doubt it is a regression for YCM, but we perhaps should check that no other clients use his part of the API
</blockquote></details>

I don't think any clients use that API because it's not documented and relying on it means that the `-resource-dir` flag is not added to the list of flags so it won't work properly.

---

*[ycmd/completers/cpp/clang_completer.py, line 607 at r5](https://reviewable.io:443/reviews/valloric/ycmd/843#-KuvWYjysoV1sCmmP5G2:-KvqFZ6SfG5Y3ELm6jRh:bq14yyi) ([raw file](https://github.com/valloric/ycmd/blob/c9e27d591b5223f70231bcf1954cc6520601d4a1/ycmd/completers/cpp/clang_completer.py#L607)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I do feel that the API for this method is kinda wonky. Maybe we should just split it into two functions instead of having an argument that sort of fundamentally changes the outputs. Anyway, not really urgent/important and not a blocker.
</blockquote></details>

Split into two functions: `GetIncompleteIncludeValue` and `GetFullIncludeValue`.

---

*[ycmd/tests/clang/flags_test.py, line 445 at r10](https://reviewable.io:443/reviews/valloric/ycmd/843#-Kvi_WZmaTnc_UwRHbg-:-KvqXXAr1WFm2xTouggO:bf4j1b2) ([raw file](https://github.com/valloric/ycmd/blob/5d1cc7f9dc9e3a4e4ec97cf87b4c3fa24c6e46e5/ycmd/tests/clang/flags_test.py#L445)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I'm less convinced these tests are really testing that we really add mac flags anymore. I mean yes, we're testing that the function that add's mac include paths actually adds a path, but we're not really testing that the flags class ever actually calls that... unless we're proving that somewhere else ?
</blockquote></details>

Rewritten as `FlagsForFile` tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/843)*

**Comment by puremourning** [comment]
Reviewed 2 of 7 files at r1, 1 of 1 files at r4, 1 of 2 files at r5, 1 of 2 files at r6, 3 of 3 files at r10, 1 of 2 files at r11, 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/valloric/ycmd/843#-KuvYFHyXIA5q6-P9qnW:-Kvr5CDr12cf2yd04Izj:bnfp4nl) (no related file):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

I don't think any clients use that API because it's not documented and relying on it means that the `-resource-dir` flag is not added to the list of flags so it won't work properly.
</blockquote></details>

:lgtm:

---

*[ycmd/completers/cpp/clang_completer.py, line 607 at r5](https://reviewable.io:443/reviews/valloric/ycmd/843#-KuvWYjysoV1sCmmP5G2:-Kvr4hbCQZWphUKuZx3B:bmpcat2) ([raw file](https://github.com/valloric/ycmd/blob/c9e27d591b5223f70231bcf1954cc6520601d4a1/ycmd/completers/cpp/clang_completer.py#L607)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Split into two functions: `GetIncompleteIncludeValue` and `GetFullIncludeValue`.
</blockquote></details>

Yeah! I like this a lot more, thanks so much.

---

*[ycmd/tests/clang/flags_test.py, line 445 at r10](https://reviewable.io:443/reviews/valloric/ycmd/843#-Kvi_WZmaTnc_UwRHbg-:-Kvr5ASLIlEZvqqDBqvM:b-eugxf8) ([raw file](https://github.com/valloric/ycmd/blob/5d1cc7f9dc9e3a4e4ec97cf87b4c3fa24c6e46e5/ycmd/tests/clang/flags_test.py#L445)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Rewritten as `FlagsForFile` tests.
</blockquote></details>

Nice! awesome.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/843)*

**Comment by micbou** [comment]
Added a `GoToInclude` subcommand test to fully cover the `GetFullIncludeValue` function.

---

Reviewed 1 of 1 files at r12, 1 of 1 files at r13.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/843#-:-KvtGb7K38jDYSDLhjXP:b-86jqdl)*

**Comment by micbou** [comment]
I think it's time to merge. Thanks for the reviews.

@zzbot r+

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/843#-:-Kw0ZVtujhmpUL4Nk05F:b6qle2j)*

**Pull request merged**
