### PR TITLE
Update emacs-ycmd part in README

### PR DESCRIPTION
**Pull request by ptrv**
[Review on Reviewable](https://reviewable.io/reviews/valloric/ycmd/330)

### CODE REVIEW

**Comment by vheon** [comment]
I don't use Emacs so I will just trust you :+1: 

:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/330#-:-K9IZB_TBBCBzQTSU366:752039868)*

**Comment by micbou** [comment]
Seems fair.

@homu r+

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/330#-:-K9IZgL4z7tmgfEoP5NI:1235354600)*

**Comment by ptrv** [comment]
Thanks for merging. The Emacs client is definitely not experimental anymore.

**Comment by puremourning** [comment]
flake @homu retry

**Pull request merged**
