### PR TITLE
[READY] Update racerd to master

### PR DESCRIPTION
**Pull request by puremourning**
Fixes https://github.com/Valloric/YouCompleteMe/issues/2222#issuecomment-241806666 by updating racerd to master.

WIP because @jwilm thinks appveyor might barf.

Edit: Technically only fixes above issue when ycmd submodule updated in YCM

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/580)

### CODE REVIEW

**Comment by micbou** [comment]
:lgtm:

We may consider updating Rust to [the latest stable binaries](https://www.rust-lang.org/en-US/downloads.html) (1.11.0) on AppVeyor. Current version is 1.8.0.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/580#-:-KPseGKHyWrwJi2eU_yQ:b-f68zvv)*

**Comment by rillian** [comment]
:lgtm: Working for me locally.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/580#-:-KPxTmiPu60x6grNN-vR:bk33809)*

**Comment by vheon** [comment]
:lgtm:

> We may consider updating Rust to the latest stable binaries (1.11.0) on AppVeyor. Current version is 1.8.0.

Should we try it now?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/580#-:-KPyPSnr9i7WMsXeM39y:beb5t8t)*

**Comment by micbou** [comment]
> Should we try it now?

If @puremourning is willing to do it. We can always send a separate PR for this.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/580#-:-KPySR4sklvPs-p1bXzD:bisukfm)*

**Comment by puremourning** [comment]
I think separate PR. This fixes the issue, and Appveyor seems happy. We can update rust in another commit. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/580#-:-KPyaeFvYk0hoqYkTM41:brj36xs)*

**Comment by micbou** [comment]
Waiting for the `[READY]` tag then.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/580#-:-KPyb_EV2o6_30d8tOBQ:bjwipbs)*

**Comment by rillian** [comment]
What else needs to happen for this to land?

**Comment by puremourning** [comment]
This is ready. Sorry I am on mobile so can't edit the title.

**Comment by micbou** [comment]
@homu r+

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/580#-:-KQ7QvTqZzqnscZrO88h:b-iwbgq9)*

**Comment by rillian** [comment]
Thanks!

**Pull request merged**
