### PR TITLE
[READY] Replace NULL with nullptr

### PR DESCRIPTION
**Pull request by micbou**
[That's what our God recommends](http://www.stroustrup.com/bs_faq2.html#null).

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/900)

### CODE REVIEW

**Comment by bstaletic** [comment]
Once again, :lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/900#-:-L2rScwtTr7gpJSZ1yKD:b-788m56)*

**Comment by puremourning** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/900#-:-L2wMgY7TntvoRpjm4va:bnfp4nl)*

**Comment by bstaletic** [comment]
@zzbot r+

**Comment by bstaletic** [comment]
Let's try this again.

@zzbot retry

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/900#-:-L3I9PPJfZ0gyGMpsZsB:b-44c5b8)*

**Comment by bstaletic** [comment]
Uhm... ?
@zzbot r+

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/900#-:-L3I9zJmDoTDdew_8sZF:bj2veu8)*

**Pull request merged**
