### PR TITLE
Haiku build fix

### PR DESCRIPTION
**Pull request by miqlas**
Haiku got no rt

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/802)

### CODE REVIEW

**Comment by bstaletic** [comment]
Even though Haiku is not officially supported, this change is reall small and I'm not against it.
The ci failures seem to be unrelated.
Considering the official Haiku support status, I would like to wait for other's before giving this LGTM.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/802#-:-KpdUuYKHO9bb-j2U1ZL:b-frlj82)*

**Comment by miqlas** [comment]
@bstaletic bstaletic, look, how beautiful it is!
dbq

**Comment by Valloric** [comment]
It's such a small patch, why not merge it. :)

:lgtm:

Thanks for the PR!

**Comment by puremourning** [comment]
:lgtm: @zzbot r+

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/802#-:-Kpf9NIknxjIop4DQgOP:by5ago3)*

**Comment by puremourning** [comment]
@zzbot retry

Weird. 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/802#-:-KpfAN_VjYMfeSPZVakR:bjfuo97)*

**Comment by Valloric** [comment]
Grr, flakes.

@zzbot retry

**Comment by bstaletic** [comment]
Once again?
@zzbot retry

**Comment by bstaletic** [comment]
Can anyone explain the canceled builds on travis?
@zzbot retry

**Comment by miqlas** [comment]
SkyNet trying to disobey the mankind.

**Comment by puremourning** [comment]
Seems there is something very wrong with appveyor. It seems to be having connectivity flakes ?

**Comment by bstaletic** [comment]
Let's try this again.
@zzbot retry

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/802#-:-Kq3g5G6ZFxbfYBVw6PZ:b1x6obw)*

**Pull request merged**
