### PR TITLE
[READY] Uniformize debug informations

### PR DESCRIPTION
**Pull request by micbou**
This PR makes the string returned by the `DebugInfo` method more consistent throughout completers. It also adds more informations:
 - status of the `.ycm_extra_conf.py` file for the C-family completer;
 - subserver PID when relevant (needed for the tests in PR #282);
 - executable(s) used by the completer;
 - current solution for the C♯ completer;
 - Rust sources path for the Rust completer.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/533)

### CODE REVIEW

**Comment by vheon** [comment]
I know you're probably against this and I don't know if is worth it since later I guess you will change those to be json object instead of strings but right now we have something like:

```python
'TypeScript completer debug information:\n'
'  TSServer running\n'
'  TSServer process ID: {0}\n'
'  TSServer executable: {1}\n'
'  TSServer logfile: {2}'
```

in the implementation and

```python
'TypeScript completer debug information:\n'
'  TSServer running\n'
'  TSServer process ID: \d+\n'
'  TSServer executable: .+\n'
'  TSServer logfile: .+'
```

in the tests. Wouldn't be better to extract the one in the implementation into a variable and use it in the implementation as it is right now, and in the tests formatting the `{0}, {1}, ...` with the regex needed by that field? In the end, do we want to test that that kind of template is showed to the user or that that specific string is displayed? Personally I think the first is more valuable. What do you think?

---

Reviewed 3 of 26 files at r1.
Review status: 3 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/533#-:-KLHvf-p4qOzRPmblrr6:-14947601)*

**Comment by Valloric** [comment]
This looks good to me, but I do share @vheon's concern that we seem to be returning structured data in a string. Our tests also enforce that it has this particular structure.

So I'm :lgtm: on this, but worth considering other options too. It's not easy to tell what would be the best approach here.

---

Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/533#-:-KLIyPAvZu_mveS0lNyM:662511397)*

**Comment by micbou** [comment]
@vheon This is the same matter as in PR #528: should we check that such constant is used or such string is returned? To be honest, I don't have a definite answer. In this case, I went for the easiest approach.

> This looks good to me, but I do share @vheon's concern that we seem to be returning structured data in a string. Our tests also enforce that it has this particular structure.

The plan is to return a dictionary instead of a string but this needs some thoughts on how to structure such dictionary and this will require changes in the clients (at least the Vim client), thus delaying even further PR #282. So I prefer to uniformize the string for now and return a dictionary later. It should not be too difficult to adapt the tests.

---

Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/533#-:-KLJ6cURUb1NGoYfpsmb:-1109814844)*

**Comment by Valloric** [comment]
OK, if this is temporary and we want to move to returning a dictionary long-term, then I'm satisfied. Let's unblock the work that is currently block and come back to this later.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/533#-:-KLJK9CPcF-t_5AxWxAy:-1346631485)*

**Comment by vheon** [comment]
@micbou 
>This is the same matter as in PR #528:

That is why I said

> I know you're probably against this

:stuck_out_tongue_winking_eye: 

Anyway it was just to avoid the duplication, that's all.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/533#-:-KLMOYIT2ElfhIJ7FsK2:668358085)*

**Comment by vheon** [comment]
:lgtm: 

---

Reviewed 23 of 26 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/533#-:-KLQeBkDabmq-kL96JrY:1267966159)*

**Comment by vheon** [comment]
I guess we can call `homu` for this one right?

**Comment by puremourning** [comment]
:lgtm:

---

Reviewed 26 of 26 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/533#-:-KLlpYmI5NziGIx5BnOt:1417088721)*

**Comment by Valloric** [comment]
I see many LGTMs here. @homu r+

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/533#-:-KLlpgdu5ihs-cNy4urs:-1308769019)*

**Pull request merged**
