### PR TITLE
[READY] Catch build errors and point to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by puremourning**
We fairly frequently get issues raised due to build errors and we often have to ask for the full log, invocation, etc. I think this might be exacerbated by the way failures are presented like a python backtrace.

So I thought to catch the failure and print some weasel words about reading CONTRIBUTING.md and that it almost certainly isn't a bug.

The output looks like this:

```
FAILED: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -DBOOST_THREAD_DONT_USE_CHRONO -DUSE_CLANG_COMPLETER -DYCMD_CORE_VERSION=24 -Dycm_core_EXPORTS -I/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm -I/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/ClangCompleter -isystem /Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/BoostParts -isystem /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -isystem ycm/../clang+llvm-3.8.0-x86_64-apple-darwin/include -stdlib=libc++ -fcolor-diagnostics -O3 -DNDEBUG -fPIC   -std=c++0x -MMD -MT ycm/CMakeFiles/ycm_core.dir/Candidate.cpp.o -MF ycm/CMakeFiles/ycm_core.dir/Candidate.cpp.o.d -o ycm/CMakeFiles/ycm_core.dir/Candidate.cpp.o -c /Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/Candidate.cpp
/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/Candidate.cpp:56:3: error: use of undeclared identifier 'this_is__garbage'
  this_is__garbage;
  ^
1 error generated.
[124/134] Building CXX object ycm/CMakeFiles/ycm_core.dir/IdentifierCompleter.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "./build.py", line 371, in BuildYcmdLib
    subprocess.check_call( build_command )
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['cmake', '--build', '.', '--target', 'ycm_core', '--', '-j', '8']' returned non-zero exit status 1


*** ERROR ***: The build failed.

NOTE: It is *highly* unlikely that this is a bug. It is likely that this is a problem with the configuration of your system or a missing dependency. Please carefully read CONTRIBUTING.md and if you're sure that it is a bug, please raise an issue on the issue tracker, including the entire output of this script, including the invocation line.

```

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/549)

### CODE REVIEW

**Comment by Valloric** [comment]
I regret that I have but one :lgtm: to give.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.py, line 376 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/549#-KMqTjMlVHICplk3B5-l:-KMqTjMlVHICplk3B5-m:118962500) ([raw file](https://github.com/valloric/ycmd/blob/576383b8a78df101870b275a3ce4265a710b3778/build.py#L376)):*
> ```Python
>       sys.exit(
>         '\n\n*** ERROR ***: The build failed.\n\n'
>         'NOTE: It is *highly* unlikely that this is a bug. It is likely '
> ```

I'd add a newline char after each line here, but up to you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/549#-:-KMqTpu_bVB_QuyoSdW2:1240137108)*

**Comment by vheon** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/549#-:-KMsUlQwKXzR87casIEL:980077423)*

**Comment by micbou** [comment]
This is a good idea. I made some minor comments.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[build.py, line 375 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/549#-KMsV9QH66U_BoQzN-I5:-KMsV9QH66U_BoQzN-I6:1333400544) ([raw file](https://github.com/valloric/ycmd/blob/576383b8a78df101870b275a3ce4265a710b3778/build.py#L375)):*
> ```Python
>       traceback.print_exc()
>       sys.exit(
>         '\n\n*** ERROR ***: The build failed.\n\n'
> ```

For consistency, could we use the same format as the other error above (without the asterisks) or change the other error?

---

*[build.py, line 376 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/549#-KMsWTDYrS3qr902zlzY:-KMsWTDZAFiyU-_sp_KT:281668893) ([raw file](https://github.com/valloric/ycmd/blob/576383b8a78df101870b275a3ce4265a710b3778/build.py#L376)):*
> ```Python
>       sys.exit(
>         '\n\n*** ERROR ***: The build failed.\n\n'
>         'NOTE: It is *highly* unlikely that this is a bug. It is likely '
> ```

Could we avoid using twice the word `likely`? Maybe we could say:
`It is *highly* unlikely that this is a bug but rather a problem with...`

---

*[build.py, line 381 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/549#-KMsXyXsvnCyYD3wY2IQ:-KMsXyXsvnCyYD3wY2IR:888665652) ([raw file](https://github.com/valloric/ycmd/blob/576383b8a78df101870b275a3ce4265a710b3778/build.py#L381)):*
> ```Python
>         "and if you're sure that it is a bug, please raise an issue on the "
>         'issue tracker, including the entire output of this script, '
>         'including the invocation line.' )
> ```

Could we merge the two `including` into one: `including the entire output of this script and the invocation line`? This makes the read smoother.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/549#-:-KMsZB6__6AEYZI5k1NI:-831685565)*

**Comment by puremourning** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[build.py, line 375 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/549#-KMsV9QH66U_BoQzN-I5:-KMt1ftN3DZP_AhYHEh7:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/576383b8a78df101870b275a3ce4265a710b3778/build.py#L375)):*
<details><summary><i>Previously, micbou wrote…</i></summary>
> For consistency, could we use the same format as the other error above (without the asterisks) or change the other error?
</details>
Done.

---

*[build.py, line 376 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/549#-KMsWTDYrS3qr902zlzY:-KMt1YrOitlwO7ASSCkw:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/576383b8a78df101870b275a3ce4265a710b3778/build.py#L376)):*
<details><summary><i>Previously, micbou wrote…</i></summary>
> Could we avoid using twice the word `likely`? Maybe we could say:
> `It is *highly* unlikely that this is a bug but rather a problem with...`
> 
</details>
Done.

---

*[build.py, line 376 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/549#-KMqTjMlVHICplk3B5-l:-KMt1ZyxLRQgwIRcV_zn:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/576383b8a78df101870b275a3ce4265a710b3778/build.py#L376)):*
<details><summary><i>Previously, Valloric (Val Markovic) wrote…</i></summary>
> I'd add a newline char after each line here, but up to you.
</details>
Done.

---

*[build.py, line 381 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/549#-KMsXyXsvnCyYD3wY2IQ:-KMt1XZFU8Jw0jKyQrby:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/576383b8a78df101870b275a3ce4265a710b3778/build.py#L381)):*
<details><summary><i>Previously, micbou wrote…</i></summary>
> Could we merge the two `including` into one: `including the entire output of this script and the invocation line`? This makes the read smoother.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/549)*

**Comment by puremourning** [comment]
FWIW the new output is:

```
[125/151] Building CXX object ycm/CMakeFiles/ycm_core.dir/ClangCompleter/ClangHelpers.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/Users/ben/.vim/bundle/YouCompleteMe-Clean/third_party/ycmd/build.py", line 371, in BuildYcmdLib
    subprocess.check_call( build_command )
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['cmake', '--build', '.', '--target', 'ycm_core_tests', '--', '-j', '8']' returned non-zero exit status 1


ERROR: The build failed.

NOTE: It is *highly* unlikely that this is a bug but rather
that this is a problem with the configuration of your system,
or a missing dependency. Please carefully read CONTRIBUTING.md
and if you're sure that it is a bug, please raise an issue on the
issue tracker, including the entire output of this script
and the invocation line used to run it.
```

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/549#-:-KMt2dMqKPxuIx1bivLn:346611678)*

**Comment by micbou** [comment]
:lgtm:

@homu r+

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/549#-:-KMt2vGL6sKrd-vC6ztC:187772251)*

**Pull request merged**
