### PR TITLE
[READY] Fix one-liner style

### PR DESCRIPTION
**Pull request by bstaletic**
This makes sure there are no more

```c++
if ( condition )
  statement;
```

Instead the style should now be:

```c++
if ( condition ) {
  statement1;
} else if (condition ) {
  statement2;
} else {
  statement3;
}
```

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/909)

### CODE REVIEW

**Comment by bstaletic** [comment]
Review status: 0 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[cpp/ycm/Candidate.cpp, line 98 at r1](https://reviewable.io:443/reviews/valloric/ycmd/909#-L3cXXxNYqAuDUzYPMT3:-L3cXXxNYqAuDUzYPMT4:buhcwc4) ([raw file](https://github.com/valloric/ycmd/blob/e30e44c15ed039943d3cb96ca0621c3dcd87e09c/cpp/ycm/Candidate.cpp#L98)):*
> ```cpp
>         node = ( *root_node_ )[ nearest->indexOfFirstOccurrence ];
>       }
>     }
> ```

This `if{if}}{else{if}}` looks ugly. Should we change it a bit?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/909)*

**Comment by Valloric** [comment]
:lgtm:

Thanks for the PR!

**Comment by micbou** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[cpp/ycm/Candidate.cpp, line 98 at r1](https://reviewable.io:443/reviews/valloric/ycmd/909#-L3cXXxNYqAuDUzYPMT3:-L3dV1uVjTMRGzWWZNpi:bxga738) ([raw file](https://github.com/valloric/ycmd/blob/e30e44c15ed039943d3cb96ca0621c3dcd87e09c/cpp/ycm/Candidate.cpp#L98)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

This `if{if}}{else{if}}` looks ugly. Should we change it a bit?
</blockquote></details>

I think it's fine. It's removed in PR https://github.com/Valloric/ycmd/pull/894 anyway.

---

*[cpp/ycm/IdentifierDatabase.cpp, line 95 at r1](https://reviewable.io:443/reviews/valloric/ycmd/909#-L3dW199ItxA79hwvDV8:-L3dW199ItxA79hwvDV9:b-fh5s0t) ([raw file](https://github.com/valloric/ycmd/blob/e30e44c15ed039943d3cb96ca0621c3dcd87e09c/cpp/ycm/IdentifierDatabase.cpp#L95)):*
> ```cpp
>         if ( ContainsKey( seen_candidates, candidate ) ) {
>           continue;
> 	} else {
> ```

Wrong indentation. A tabulation is used instead of spaces. This applies to 3 other changes in that file.

---

*[cpp/ycm/Result.cpp, line 126 at r1](https://reviewable.io:443/reviews/valloric/ycmd/909#-L3dXM7yP7rCvj_LS9ts:-L3dXM7yP7rCvj_LS9tt:busazu1) ([raw file](https://github.com/valloric/ycmd/blob/e30e44c15ed039943d3cb96ca0621c3dcd87e09c/cpp/ycm/Result.cpp#L126)):*
> ```cpp
>           return word_boundary_char_utilization_ >
>                  other.word_boundary_char_utilization_;
> 	}
> ```

Spaces instead of a tabulation.

---

*[cpp/ycm/ClangCompleter/CompletionData.cpp, line 224 at r1](https://reviewable.io:443/reviews/valloric/ycmd/909#-L3dXfnSBHwUXdANDJWC:-L3dXfnSBHwUXdANDJWD:b-qrokxw) ([raw file](https://github.com/valloric/ycmd/blob/e30e44c15ed039943d3cb96ca0621c3dcd87e09c/cpp/ycm/ClangCompleter/CompletionData.cpp#L224)):*
> ```cpp
>               !saw_function_params &&
>               kind != CXCompletionChunk_RightParen &&
>               kind != CXCompletionChunk_Informative ) {
> ```

The last three conditions are not aligned with the first one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/909)*

**Comment by bstaletic** [comment]
Review status: 15 of 18 files reviewed at latest revision, 4 unresolved discussions.

---

*[cpp/ycm/IdentifierDatabase.cpp, line 95 at r1](https://reviewable.io:443/reviews/valloric/ycmd/909#-L3dW199ItxA79hwvDV8:-L3dftcnOLTR66mMSj7f:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/e30e44c15ed039943d3cb96ca0621c3dcd87e09c/cpp/ycm/IdentifierDatabase.cpp#L95)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Wrong indentation. A tabulation is used instead of spaces. This applies to 3 other changes in that file.
</blockquote></details>

Done.

---

*[cpp/ycm/Result.cpp, line 126 at r1](https://reviewable.io:443/reviews/valloric/ycmd/909#-L3dXM7yP7rCvj_LS9ts:-L3dfJbm6duslYPrBvtX:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/e30e44c15ed039943d3cb96ca0621c3dcd87e09c/cpp/ycm/Result.cpp#L126)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Spaces instead of a tabulation.
</blockquote></details>

Done.

---

*[cpp/ycm/ClangCompleter/CompletionData.cpp, line 224 at r1](https://reviewable.io:443/reviews/valloric/ycmd/909#-L3dXfnSBHwUXdANDJWC:-L3dfrYY24XfM20bjIvY:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/e30e44c15ed039943d3cb96ca0621c3dcd87e09c/cpp/ycm/ClangCompleter/CompletionData.cpp#L224)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

The last three conditions are not aligned with the first one.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/909)*

**Comment by micbou** [comment]
:lgtm:

@zzbot r+

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/909#-:-L3dgXonhf06Jjqr1ZFA:b-a2cmdb)*

**Comment by micbou** [comment]
@zzbot retry

**Pull request merged**
