### PR TITLE
[READY] Allow switching to a different JavaScript project with RestartServer

### PR DESCRIPTION
**Pull request by micbou**
Contrarily to what the YCM docs say, issuing the `:YcmCompleter RestartServer` command to switch to a different JavaScript project doesn't work. The reason is that we don't set the working directory when starting the Tern server. Same issue if the user starts the client outside a project and then open a file in that project. It's even worse in that case because no warning will be displayed to the user.

I considered passing the `request_data` object when initializing the completer but that doesn't work because the request is not always available. I also considered adding support for multiple projects similarly to what the C# completer does but I felt it was too much work. Finally, I went for starting the server on the `FileReadyToParse` event.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/875)

### CODE REVIEW

**Comment by micbou** [comment]
I did some refactoring in the tests by introducing an utility function to start the Tern server. Also, similarly to the recent changes in PR https://github.com/Valloric/ycmd/pull/857, I slightly changed the logic so that we only try to start the Tern server once. PR is ready.

---

Reviewed 6 of 6 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/875#-:-KzjVOHK9-OIz6tuOaqz:btltcon)*

**Comment by bstaletic** [comment]
Makes me wonder if we should start all semantic completers on `FileReadyToParse`.
:lgtm: 

---

Reviewed 2 of 6 files at r1, 3 of 4 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/875#-:-KzkicwKIi49Km0PObz8:b47si36)*

**Comment by Valloric** [comment]
:lgtm:

Thanks!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/completers/javascript/tern_completer.py, line 391 at r4](https://reviewable.io:443/reviews/valloric/ycmd/875#-KztKM4qaXarPFBP9fo9:-KztKM4qaXarPFBP9foA:bd23w3l) ([raw file](https://github.com/valloric/ycmd/blob/e587501bcc51c28186cb5285a9017b874a280926/ycmd/completers/javascript/tern_completer.py#L391)):*
> ```Python
>       _logger.info( 'Starting Tern server...' )
> 
>       filepath = request_data[ 'filepath' ]
> ```

This PR adds 10+ lines of code to a function with a TODO of "this function is too long". :(

Doesn't block this PR, but we should consider refactoring this sooner rather than later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/875#-:-KztL4NunhLnflQI_Fkm:b9benhj)*

**Comment by bstaletic** [comment]
> Doesn't block this PR, but we should consider refactoring this sooner rather than later.

So is it time to merge this?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/875#-:-KzxMNWsie9LEP9j6BBi:bxld3i0)*

**Comment by micbou** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/javascript/tern_completer.py, line 391 at r4](https://reviewable.io:443/reviews/valloric/ycmd/875#-KztKM4qaXarPFBP9fo9:-KzzDxErxf3z4vvgYNxP:buddlwo) ([raw file](https://github.com/valloric/ycmd/blob/e587501bcc51c28186cb5285a9017b874a280926/ycmd/completers/javascript/tern_completer.py#L391)):*
<details><summary><i>Previously, Valloric (Val Markovic) wrote…</i></summary><blockquote>

This PR adds 10+ lines of code to a function with a TODO of "this function is too long". :(

Doesn't block this PR, but we should consider refactoring this sooner rather than later.
</blockquote></details>

Did some simplifications and moved the new code to a separate function. It's now 54 lines instead of 74.

---

*[ycmd/completers/javascript/tern_completer.py, line 442 at r4](https://reviewable.io:443/reviews/valloric/ycmd/875#-KzzEt6gM8u6epnq4Hkr:-KzzEt6jzPGpjjeCQV-T:b-j6g1z7) ([raw file](https://github.com/valloric/ycmd/blob/e587501bcc51c28186cb5285a9017b874a280926/ycmd/completers/javascript/tern_completer.py#L442)):*
> ```Python
>       except Exception:
>         _logger.exception( 'Unable to start Tern server' )
>         self._CleanUp()
> ```

Removed this `try/except` block as it was unlikely to ever catch something (`CreateLogFile`, `OpenForStdHandle`, and `SafePopen` are never supposed to fail).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/875)*

**Comment by puremourning** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[ycmd/completers/javascript/tern_completer.py, line 157 at r5](https://reviewable.io:443/reviews/valloric/ycmd/875#-Kzz_Ke1OdjQX2k8gOAN:-Kzz_Ke2C2PUG8F1ka96:b-6a6fnm) ([raw file](https://github.com/valloric/ycmd/blob/7a1e2362b18d506a7167d79b9b3fe6975b985522/ycmd/completers/javascript/tern_completer.py#L157)):*
> ```Python
>     if not FindTernProjectFile( filepath ):
>       raise RuntimeError( 'Warning: Unable to detect a .tern-project file '
>                           'in the hierarchy before ' + filepath +
> ```

should this be a dir name rather than file name? totally optional. i'm ambivalent.

---

*[ycmd/completers/javascript/tern_completer.py, line 268 at r5](https://reviewable.io:443/reviews/valloric/ycmd/875#-Kzz_q-9qIbWjxavywkY:-Kzz_q-9qIbWjxavywkZ:bn1el97) ([raw file](https://github.com/valloric/ycmd/blob/7a1e2362b18d506a7167d79b9b3fe6975b985522/ycmd/completers/javascript/tern_completer.py#L268)):*
> ```Python
>     with self._server_state_mutex:
>       extras = [
>         responses.DebugInfoItem( key = 'configuration file',
> ```

should we call it "Tern project file", as that is a little clearer that it is specific to Tern rather than YCM ? I theory at least editors and ycmd itself might have "configuration files". Again, optional.

---

*[ycmd/completers/javascript/tern_completer.py, line 386 at r5](https://reviewable.io:443/reviews/valloric/ycmd/875#-KzzaJoEvQh4vpZD730d:-KzzaJoEvQh4vpZD730e:b5k095a) ([raw file](https://github.com/valloric/ycmd/blob/7a1e2362b18d506a7167d79b9b3fe6975b985522/ycmd/completers/javascript/tern_completer.py#L386)):*
> ```Python
>     if not self._server_project_file:
>       _logger.warning( 'No .tern-project file detected: %s', filepath )
>       self._server_working_dir = os.path.dirname( filepath )
> ```

I think this might be a slight regression, but I'm not sure.

Previously in this scenario we would use Vim's working dir, which _might_ turn out a better choice than the file's directory.

Example might be:

 -  a user is used to using the javascript completion without a tern project file
 - they typically `cd /some/path` 
 - the structure is like `/some/path/lib_one/*.js`, `/some/path/lib_two/*.js`
 - they use `vim lib_one/file.js`, which contains `var x = require( 'lib_two/another_file.js' )`

I don't know for certain if this would or would not have previously just about worked based on the wd of the term server being `/some/path`. But I'm pretty sure that it wouldn't with the wd of `/some/path/lib_one`. 

I guess the key question for discussion is: if we can't find a tern project file, should we really use the dirname of the file, or revert to the previous behaviour of using the WD of the client. I suspect that we should do the latter, for safety unless there's a good reason not to... or I totally missed the point, which is of course also possible!

---

*[ycmd/completers/javascript/tern_completer.py, line 442 at r5](https://reviewable.io:443/reviews/valloric/ycmd/875#-KzzgS00LBBkXtbsd0Gi:-KzzgS01FYPlvjT3_n2d:b-83qm92) ([raw file](https://github.com/valloric/ycmd/blob/7a1e2362b18d506a7167d79b9b3fe6975b985522/ycmd/completers/javascript/tern_completer.py#L442)):*
> ```Python
> 
>       if self._ServerIsRunning():
>         _logger.info( 'Tern Server started with pid: %s listening on port %s',
> ```

should these be %d ? just being pedantic, you can ignore.

---

*[ycmd/completers/javascript/tern_completer.py, line 489 at r5](https://reviewable.io:443/reviews/valloric/ycmd/875#-Kzzgi7-fXeHv8H_FI6A:-Kzzgi7-fXeHv8H_FI6B:b-qmrp1r) ([raw file](https://github.com/valloric/ycmd/blob/7a1e2362b18d506a7167d79b9b3fe6975b985522/ycmd/completers/javascript/tern_completer.py#L489)):*
> ```Python
>     self._server_started = False
>     self._server_working_dir = None
>     self._server_project_file = None
> ```

should we reset `do_tern_project_check` here ? I think it's not a new issue, but after restarting the server in some other directory, we probably want to re-scan for the tern project, and also re-warn for the "new" project.

---

*[ycmd/tests/javascript/event_notification_test.py, line 160 at r5](https://reviewable.io:443/reviews/valloric/ycmd/875#-KzzhHD-nUV0YlGCYTA_:-KzzhHD-nUV0YlGCYTAa:bxtgcxc) ([raw file](https://github.com/valloric/ycmd/blob/7a1e2362b18d506a7167d79b9b3fe6975b985522/ycmd/tests/javascript/event_notification_test.py#L160)):*
> ```Python
> 
>   # Finally, restart the server in a folder containing a .tern-project file. We
>   # expect no error in that case.
> ```

should we test that if we restart it in some other directory (which doesn't have a .tern-project) that we _do_ get another error (as mentioned, I think we don't, but i'm not 100% sure).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/875)*

**Comment by micbou** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[ycmd/completers/javascript/tern_completer.py, line 157 at r5](https://reviewable.io:443/reviews/valloric/ycmd/875#-Kzz_Ke1OdjQX2k8gOAN:-L-27_CK22ENA8oZLFqZ:bvcm8hs) ([raw file](https://github.com/valloric/ycmd/blob/7a1e2362b18d506a7167d79b9b3fe6975b985522/ycmd/completers/javascript/tern_completer.py#L157)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

should this be a dir name rather than file name? totally optional. i'm ambivalent.
</blockquote></details>

It's simpler to put the filepath here.

---

*[ycmd/completers/javascript/tern_completer.py, line 268 at r5](https://reviewable.io:443/reviews/valloric/ycmd/875#-Kzz_q-9qIbWjxavywkY:-KzzrUREx2eFcu3zd0BD:bb0ky0l) ([raw file](https://github.com/valloric/ycmd/blob/7a1e2362b18d506a7167d79b9b3fe6975b985522/ycmd/completers/javascript/tern_completer.py#L268)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

should we call it "Tern project file", as that is a little clearer that it is specific to Tern rather than YCM ? I theory at least editors and ycmd itself might have "configuration files". Again, optional.
</blockquote></details>

No need because this item is added in the `extras` field of the Tern `DebugInfoServer` object. It will appear as `Tern configuration file` in the output of `:YcmDebugInfo`.

---

*[ycmd/completers/javascript/tern_completer.py, line 386 at r5](https://reviewable.io:443/reviews/valloric/ycmd/875#-KzzaJoEvQh4vpZD730d:-L-1UqqW63LJm23K3v4n:b-55k077) ([raw file](https://github.com/valloric/ycmd/blob/7a1e2362b18d506a7167d79b9b3fe6975b985522/ycmd/completers/javascript/tern_completer.py#L386)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I think this might be a slight regression, but I'm not sure.

Previously in this scenario we would use Vim's working dir, which _might_ turn out a better choice than the file's directory.

Example might be:

 -  a user is used to using the javascript completion without a tern project file
 - they typically `cd /some/path` 
 - the structure is like `/some/path/lib_one/*.js`, `/some/path/lib_two/*.js`
 - they use `vim lib_one/file.js`, which contains `var x = require( 'lib_two/another_file.js' )`

I don't know for certain if this would or would not have previously just about worked based on the wd of the term server being `/some/path`. But I'm pretty sure that it wouldn't with the wd of `/some/path/lib_one`. 

I guess the key question for discussion is: if we can't find a tern project file, should we really use the dirname of the file, or revert to the previous behaviour of using the WD of the client. I suspect that we should do the latter, for safety unless there's a good reason not to... or I totally missed the point, which is of course also possible!
</blockquote></details>

I did some tests and Tern doesn't seem to rely at all on the working directory to resolve modules path (I tried with `/tmp` as the working directory and it works) so I don't think it matters. By the way, how's your example supposed to work without a `.tern-project` or `.tern-config` file (the `node` plugin is needed for module resolution)?

---

*[ycmd/completers/javascript/tern_completer.py, line 442 at r5](https://reviewable.io:443/reviews/valloric/ycmd/875#-KzzgS00LBBkXtbsd0Gi:-L-1UpKKDofG3oHS74FY:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/7a1e2362b18d506a7167d79b9b3fe6975b985522/ycmd/completers/javascript/tern_completer.py#L442)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

should these be %d ? just being pedantic, you can ignore.
</blockquote></details>

Done.

---

*[ycmd/completers/javascript/tern_completer.py, line 489 at r5](https://reviewable.io:443/reviews/valloric/ycmd/875#-Kzzgi7-fXeHv8H_FI6A:-L-1SmYJQdyrmledmzGp:b5nidw9) ([raw file](https://github.com/valloric/ycmd/blob/7a1e2362b18d506a7167d79b9b3fe6975b985522/ycmd/completers/javascript/tern_completer.py#L489)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

should we reset `do_tern_project_check` here ? I think it's not a new issue, but after restarting the server in some other directory, we probably want to re-scan for the tern project, and also re-warn for the "new" project.
</blockquote></details>

When restarting the server, the `do_tern_project_check` variable is set to `True` so we are going to warn the user again if there is no configuration file. However, this doesn't hurt to reset the variable here.

---

*[ycmd/tests/javascript/event_notification_test.py, line 160 at r5](https://reviewable.io:443/reviews/valloric/ycmd/875#-KzzhHD-nUV0YlGCYTA_:-L-1SD9d1uj1GBh7ytmx:b7ubfxz) ([raw file](https://github.com/valloric/ycmd/blob/7a1e2362b18d506a7167d79b9b3fe6975b985522/ycmd/tests/javascript/event_notification_test.py#L160)):*
This is tested just above:
> Restart the server and check that it raises it again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/875)*

**Comment by puremourning** [comment]
:lgtm:

---

Reviewed 2 of 6 files at r1, 3 of 4 files at r2, 1 of 1 files at r5.
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/completers/javascript/tern_completer.py, line 386 at r5](https://reviewable.io:443/reviews/valloric/ycmd/875#-KzzaJoEvQh4vpZD730d:-L-3MUcUzQiiISZOsbtv:bneezu1) ([raw file](https://github.com/valloric/ycmd/blob/7a1e2362b18d506a7167d79b9b3fe6975b985522/ycmd/completers/javascript/tern_completer.py#L386)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

I did some tests and Tern doesn't seem to rely at all on the working directory to resolve modules path (I tried with `/tmp` as the working directory and it works) so I don't think it matters. By the way, how's your example supposed to work without a `.tern-project` or `.tern-config` file (the `node` plugin is needed for module resolution)?
</blockquote></details>

Like i said i wasn't sure if it would work before, or if there are other Tern behaviours that use relative paths in some sense.

I should have said "something like `require( 'lib_two/....' )`" .

Thanks for testing anyway, let's assume this is grand. In any event the solution is to add a `.tern-project`.

---

*[ycmd/completers/javascript/tern_completer.py, line 489 at r5](https://reviewable.io:443/reviews/valloric/ycmd/875#-Kzzgi7-fXeHv8H_FI6A:-L-3MxUEqCrQXxvlJSB-:b-6mhywn) ([raw file](https://github.com/valloric/ycmd/blob/7a1e2362b18d506a7167d79b9b3fe6975b985522/ycmd/completers/javascript/tern_completer.py#L489)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

When restarting the server, the `do_tern_project_check` variable is set to `True` so we are going to warn the user again if there is no configuration file. However, this doesn't hurt to reset the variable here.
</blockquote></details>

Great, thanks.

---

*[ycmd/tests/javascript/event_notification_test.py, line 160 at r5](https://reviewable.io:443/reviews/valloric/ycmd/875#-KzzhHD-nUV0YlGCYTA_:-L-3MzycZPkt8IacSVYK:bdwkvgc) ([raw file](https://github.com/valloric/ycmd/blob/7a1e2362b18d506a7167d79b9b3fe6975b985522/ycmd/tests/javascript/event_notification_test.py#L160)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

This is tested just above:
> Restart the server and check that it raises it again.

</blockquote></details>

Heh ok sorry :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/875#-:-L-3N18sOyrx9b3Q1Cy5:bnfp4nl)*

**Comment by puremourning** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/875)*

**Comment by micbou** [comment]
Let's merge.

@zzbot r+

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/875#-:-L-4-l_PVqUDemoocZvl:b-ptzv6q)*

**Pull request merged**
