### PR TITLE
[READY] Improve AppVeyor configuration

### PR DESCRIPTION
**Pull request by micbou**
This PR does two things:
 - manually exit the batch script if an error is encountered after important commands;
 - update `get-pip.py` script URL. See PR Valloric/YouCompleteMe#1929.

[Review on Reviewable](https://reviewable.io/reviews/valloric/ycmd/316)

### CODE REVIEW

**Comment by vheon** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/316#-:-K8WGyO2_KFrKFHaX4vY:980077423)*

**Comment by puremourning** [comment]
With the caveat that batch scripting is something I remember from my childhood only, and that the only build failure was (presumably) an ongoing issue in Travis (I've retried it) and that the coverage result seems spurious.. This :lgtm:.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/316#-:-K8W_UNo29RA58N2rgS3:407847231)*

**Comment by micbou** [comment]
Looks like there are [some issues with Travis](https://www.traviscistatus.com/incidents/fcllblkclgmb). Runs are extremely long.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/316#-:-K8WcH-3bwthDnzxba08:1782027953)*

**Comment by micbou** [comment]
@homu r+

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/316#-:-K8WvFMlg5kZCzrphcL0:-1142673777)*

**Pull request merged**
