### PR TITLE
RFC: Suppress value error when cpp flags not ready

### PR DESCRIPTION
**Pull request by stevenschimmel**
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/545)

### CODE REVIEW

**Comment by puremourning** [comment]
Thanks for sending a PR!

Could you briefly explain the change and the use case or problem it is solving? We generally want users to know when there are no flags so that they know _why_ we aren't proving suggestions...

**Comment by Valloric** [comment]
We appreciate the PR, but we explicitly want to notify users when flags aren't ready.

**Comment by stevenschimmel** [comment]
There are a few reasons for the change. 1) The events in the editor that eventually trigger the ValueError in OnFileReadyToParse are not clearly a direct result of the user interacting with YCM. So when the error triggers, it is not immediately obvious to the user why it is showing up. 2) In some (large) build systems, it may take a while before flags are available for a file, leaving a long period in which the error can trigger. 3) In VIM, the message that is generated in response to the ValueError can be pretty disruptive, especially when it collides with other VIM messages generated around the same event, causing a "Press enter or type command to continue" prompt.

This change tries to strike a balance by suppressing the ValueError in OnFileReadyToParse (when the user didn't directly interact with YCM), but not in places where it is the result of the user interacting with YCM, for example in the completer subcommands.

A more elegant way of informing users if flags are available might be to implement a YcmStatus command, which returns a short string that describes the state of YCM for a given file. Users could add that status string to their editor's status bar.

**Comment by micbou** [comment]
All of this is specific to the Vim client so it should be done there.

**Comment by Valloric** [comment]
@stevenschimmel It might be worth thinking about a better way of informing the user of this error, but like @micbou said, the problem you're complaining is entirely a client issue (in your case, YCM) and should be handled there. The server (ycmd) should continue notifying about the error.

**Comment by stevenschimmel** [comment]
Ok, that sounds fair enough. I'll think about a client-side solution. Thank you all for considering the PR.

**Pull request closed without merging**
