### PR TITLE
[READY] Switch back to Boost regex

### PR DESCRIPTION
**Pull request by micbou**
There are two main issues with `std::regex`:
 - it can lead to crashes. See issue https://github.com/Valloric/YouCompleteMe/issues/2716. Probably related to [this GCC bug report](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61582). It's supposed to be fixed in GCC 7;
 - a program using `std::regex` can be compiled with versions of GCC that don't implement it. See [this post](https://stackoverflow.com/a/12665408). This means that one can successfully compile ycmd with broken tags support.

For these reasons, we switch back to the good old Boost regex component.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/800)

### CODE REVIEW

**Comment by Valloric** [comment]
Yeah, `std::regex` isn't ready. Let's revisit it a few years down the line.

:lgtm:

Thanks for the PR!

**Comment by bstaletic** [comment]
This looks :lgtm:, is there a reason it's marked `[WIP]`?

---

Reviewed 108 of 108 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/800#-:-KpRNqEIWNv1b1da_g2Q:b-1b9h3c)*

**Comment by micbou** [comment]
Just wanted to make sure that all was good. The failures on AppVeyor are unrelated. This can be merged.

---

Reviewed 4 of 108 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/800#-:-KpRVHxd1N_O9ZSec5nO:bwvefs)*

**Comment by puremourning** [comment]
I took a look at the changes, and I confess I didn't review them really closely, but I'm assuming this reverts the related code back to the exact point before the change to `std::regex`. As such, this all :lgtm:.

It's got a ready flag, and the build failures are not related.


As such: let's go!

@zzbot r+

---

Reviewed 1 of 108 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/800#-:-KpS8kor07jW-N7e1ObA:b56012z)*

**Comment by micbou** [comment]
@zzbot retry

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/800#-:-KpSMxoHlIgob6-Ig88H:b-kc0oa4)*

**Pull request merged**
