### PR TITLE
[READY] Add swagger API documentation

### PR DESCRIPTION
**Pull request by puremourning**
So about 2 years ago, I wrote this documentation for the API. It's been up on http://puremourning.github.io/ycmd-1 for that time and I know at least a few people have found it useful. I have used it myself on occasion, though the code is still strictly the only true documentation :)

As I happened to just be updating it for the `working_dir` addition, I realised that the best way to keep it up to date in the future would be to get it in to the main repo.

So here it is, largely unchanged since 2 years ago, and therefore missing some recent changes, but hopefully some docs are better than no docs and we can update it incrementally.

# How it works

It uses:

* swagger v2.0, which was current when I wrote it. There's now a swagger v4.0 or something, which seems completely different. the useful parts are: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject and https://tools.ietf.org/html/draft-fge-json-schema-validation-00
* some third-party module to render the swagger yaml format into a simple HTML which is what is displayed on my gh-pages. This is done in the gh-pages branch of my repo: https://github.com/puremourning/ycmd-1/tree/gh-pages

# Updating the docs

The idea, as shown in the readme is that the api docs are updated in the swagger alongside the code changes (as opposed to having to do 2 commits). I'll send a PR to copy my gh-pages to Val's ycmd gh-pages (which is not currently used), then we can periodically update it, like we do for YCM's website.

Instructions for doing all that are in the READMEs.

Updating the actual yaml is a bit of a labour of love. The format isn't super human-writable, but hopefully there is enough in there as examples.

RFC because it's reasonable for you guys to be like "Yeah, I CBA to maintain that, Ben" :)

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/890)

### CODE REVIEW

**Comment by bstaletic** [comment]
I'm pretty much fine with this.

We should also have a link, perhaps in the main `README.md`, to the web page of the parsed `api/README.md`.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[api/swagger.yaml, line 88 at r1](https://reviewable.io:443/reviews/valloric/ycmd/890#-L11PAZzbXih6eg2J9WA:-L11PA_-9ctumPRHA3DX:bpuv23y) ([raw file](https://github.com/valloric/ycmd/blob/93b1316379830940cef8f616f6eff931d5001e32/api/swagger.yaml#L88)):*
> a random 16 byte of random data 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/890#-:-L11PUxbCk0DNKx7yfSc:b-k3yqkz)*

**Comment by Valloric** [comment]
I'm fine with this, but we then _really_ need to keep it up-to-date. Through painful personal experience, I've found obsolete docs to be worse than no docs; seeing there's no docs tells me I need to go read the code, but obsolete docs will make me think the system works in a different way than it actually does, which ends up wasting my time and I _still_ need to go read the code at the end.

**Comment by bstaletic** [comment]
> I've found obsolete docs to be worse than no docs

As someone less experienced with real world projects, my way of thinking is "well, we just won't merge a PR until the submitter updates the docs too, how hard can it be?"

I assume, in practice, there's a human factor at play.

@puremourning 
This is :lgtm: as far as I can tell. But I have to ask, is anything here out -of-date? You did mention updating it first.

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/890#-:-L1LvKhP833ms9r1DXg6:b-vgv7dm)*

**Comment by puremourning** [comment]
There _could_ be stuff that's out of date. I would have to check the last 2 years' PRs. :)

I don't think we've made many changes to the API in that time, but it's possible. I think keeping it up to date should be as easy as keeping the tests up to date, we just enforce it in code review. With it being in the same repo, that's tons easier.

Nothing worse than the docs being in a different place (like a wiki) where it is all too easy to say "don't forget to update the docs!" to which the response is "you betcha!" and forgetting to update them due to some other emergency!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[api/swagger.yaml, line 88 at r1](https://reviewable.io:443/reviews/valloric/ycmd/890#-L11PAZzbXih6eg2J9WA:-L1PR_kx9jmI6gV4ufbO:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/93b1316379830940cef8f616f6eff931d5001e32/api/swagger.yaml#L88)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

> a random 16 byte of random data 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/890#-:-L1PR7MHQYZitZjAWMcp:bik0d0m)*

**Comment by puremourning** [comment]
I pushed some updates after scanning the log.

The main one remaining is the `debug_info` that needs to change, but @micbou is [taking care of that](http://micbou.github.io/ycmd/#path--debug_info).

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/890#-:-L1PbAuRPOoemuMcbqR4:b-of9kt6)*

**Comment by micbou** [comment]
The docs should be up to date now. :lgtm: except minor comments about the `.gitignore` and `README.md` files.

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[api/.gitignore, line 1 at r5](https://reviewable.io:443/reviews/valloric/ycmd/890#-L1TA5Q4aVowalIqqXH0:-L1TA5Q4aVowalIqqXH1:bc1cs2o) ([raw file](https://github.com/valloric/ycmd/blob/832e4073b9ffbc303d5190f393c9bd7067e66986/api/.gitignore#L1)):*
> ```
> node_modules
> ```

Why is this needed? I don't see any `node_modules` folder in `api` after generating the docs.

---

*[api/README.md, line 4 at r3](https://reviewable.io:443/reviews/valloric/ycmd/890#-L1St_Mq0engMdQA8Tc-:-L1St_MrSsG8ePhez8T2:b-88s9jt) ([raw file](https://github.com/valloric/ycmd/blob/753b3afe73461fe0bc1b8c0b126b169be3a7fec1/api/README.md#L4)):*
> ```Markdown
> 
> Check out the `gh-pages` branch and read its README.md. You will need the
> `swagger.yaml` from this directory (e.g. use 
> ```

Trailing space.

---

*[api/README.md, line 5 at r3](https://reviewable.io:443/reviews/valloric/ycmd/890#-L1RrLCMhfaeZJkpK9GK:-L1RrLCN-bR1j88qboP-:begp06w) ([raw file](https://github.com/valloric/ycmd/blob/753b3afe73461fe0bc1b8c0b126b169be3a7fec1/api/README.md#L5)):*
> ```Markdown
> Check out the `gh-pages` branch and read its README.md. You will need the
> `swagger.yaml` from this directory (e.g. use 
> `get worktree add -b gh-pages <new dir>` to get a working copy of the gh-pages
> ```

`git` instead of `get`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/890#-:-L1TAM9-rEdNkINtyy6c:b-ze22mk)*

**Comment by puremourning** [comment]
All done

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[api/README.md, line 4 at r3](https://reviewable.io:443/reviews/valloric/ycmd/890#-L1St_Mq0engMdQA8Tc-:-L1TJVgbal5dVh0_5NUc:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/753b3afe73461fe0bc1b8c0b126b169be3a7fec1/api/README.md#L4)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Trailing space.
</blockquote></details>

Done.

---

*[api/README.md, line 5 at r3](https://reviewable.io:443/reviews/valloric/ycmd/890#-L1RrLCMhfaeZJkpK9GK:-L1TJW1a1kYqs1OPbrc8:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/753b3afe73461fe0bc1b8c0b126b169be3a7fec1/api/README.md#L5)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

`git` instead of `get`.
</blockquote></details>

Done.

---

*[api/.gitignore, line 1 at r5](https://reviewable.io:443/reviews/valloric/ycmd/890#-L1TA5Q4aVowalIqqXH0:-L1TJWGQGBCdCiUbRZx8:bpz8hyz) ([raw file](https://github.com/valloric/ycmd/blob/832e4073b9ffbc303d5190f393c9bd7067e66986/api/.gitignore#L1)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Why is this needed? I don't see any `node_modules` folder in `api` after generating the docs.
</blockquote></details>

It isn't. I must have originally tried to generate the html in this directory.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/890#-:-L1TJSY_CH6NM2OjpONP:b-4zy5ve)*

**Comment by micbou** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/890#-:-L1TK5kDqd_GrEZlYZB4:b-jbsf8z)*

**Comment by puremourning** [comment]
Thanks. Marking the PR as ready.

**Comment by bstaletic** [comment]
Let's merge this!
@zzbot r=micbou

---

Reviewed 1 of 1 files at r3, 1 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/890#-:-L1VZKLhNllW_ukc8R0t:bs53spk)*

**Pull request merged**
