### PR TITLE
[READY] Update boost to 1.65.0

### PR DESCRIPTION
**Pull request by micbou**
[Boost 1.65.0 was just released](http://www.boost.org/users/history/version_1_65_0.html).

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/816)

### CODE REVIEW

**Comment by vheon** [comment]
5K lines added? :confused: 

:lgtm: 

---

Review status: 0 of 275 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/816#-:-Ks8izuqC4Zg-9HERvtw:bjiwcdq)*

**Comment by bstaletic** [comment]
Reviewed 1 of 281 files at r1.
Review status: 1 of 275 files reviewed at latest revision, 1 unresolved discussion.

---

*[update_boost.py, line 34 at r1](https://reviewable.io:443/reviews/valloric/ycmd/816#-Ks93JCvPJKqL0JO5Tc6:-Ks93JCwxwR8SuzImkpA:ble2n1g) ([raw file](https://github.com/valloric/ycmd/blob/f3fa6a47f7ceec28393cc8442b11137ce8e0ba0a/update_boost.py#L34)):*
> ```Python
> BOOST_VERSION_REGEX = re.compile( 'Version (\d+\.\d+\.\d+)' )
> BOOST_URL = (
>   'http://dl.bintray.com/boostorg/release/{version}/source/{archive}' )
> ```

I think we should keep the sourceforge URL. It does update a little later (updated two hours ago), but it has older versions as well (oldest vesion is 1.20.2). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/816)*

**Comment by micbou** [comment]
Reviewed 1 of 281 files at r1.
Review status: 1 of 275 files reviewed at latest revision, 1 unresolved discussion.

---

*[update_boost.py, line 34 at r1](https://reviewable.io:443/reviews/valloric/ycmd/816#-Ks93JCvPJKqL0JO5Tc6:-Ks9NAIVRXB2CUfnU3j0:bbhshsb) ([raw file](https://github.com/valloric/ycmd/blob/f3fa6a47f7ceec28393cc8442b11137ce8e0ba0a/update_boost.py#L34)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

I think we should keep the sourceforge URL. It does update a little later (updated two hours ago), but it has older versions as well (oldest vesion is 1.20.2). 
</blockquote></details>

I don't mind changing back to the old URL but I feel we are going to do this each time there is a new release; [we already did last time](https://github.com/Valloric/ycmd/pull/741#issuecomment-295545251).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/816)*

**Comment by bstaletic** [comment]
Review status: 1 of 275 files reviewed at latest revision, 1 unresolved discussion.

---

*[update_boost.py, line 34 at r1](https://reviewable.io:443/reviews/valloric/ycmd/816#-Ks93JCvPJKqL0JO5Tc6:-Ks9Sh2JCATovp7zTGEa:b-z8cjj3) ([raw file](https://github.com/valloric/ycmd/blob/f3fa6a47f7ceec28393cc8442b11137ce8e0ba0a/update_boost.py#L34)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

I don't mind changing back to the old URL but I feel we are going to do this each time there is a new release; [we already did last time](https://github.com/Valloric/ycmd/pull/741#issuecomment-295545251).
</blockquote></details>

I don't mind staying on this URL. We could stay on sourceforge and just be less eager to update boost.

I won't trigger @zzbot, but I consider this :LGTM: anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/816)*

**Comment by Valloric** [comment]
I don't care what URL we use as long as it works.

:lgtm:

Thanks for the PR!

@zzbot r=vheon

**Pull request merged**
