### PR TITLE
[READY] Avoid LNK 1104 error when compiling on Windows

### PR DESCRIPTION
**Pull request by micbou**
Do not attempt to build on Windows if the `ycmd` server is up (more precisely, if `ycm_core` is in use) because the compilation will fail during linking with the following error:
```
LINK : fatal error LNK1104: cannot open file '<path_to_ycmd_folder>\ycm_core.pyd'
```
We check this by trying to open the `ycm_core` file in append mode.

Discussed in issue Valloric/YouCompleteMe#1891 and PR Valloric/YouCompleteMe#1922.

[Review on Reviewable](https://reviewable.io/reviews/valloric/ycmd/399)

### CODE REVIEW

**Comment by vheon** [comment]
I see you've also renamed the `BuildYcmdLib` :+1: 

:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/399#-:-KBUWgk9xssTNl9otzjJ:127059458)*

**Comment by Valloric** [comment]
Nice!
 
:lgtm: with minor comment

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[build.py, line 299 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/399#-KBUg_yorNTnFm8-Bn1A:-KBUg_yorNTnFm8-Bn1B:2011699056) ([raw file](https://github.com/valloric/ycmd/blob/b444cb58c730c9c323d0ced5977c867d80aa1361/build.py#L299)):*
"exit early the script" -> "exit the script early"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/399#-:-KBUgiLR1-nwb6wRN0Kw:825088281)*

**Comment by micbou** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.py, line 299 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/399#-KBUg_yorNTnFm8-Bn1A:-KBUh9ss0w4zgicU2zPD:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/b444cb58c730c9c323d0ced5977c867d80aa1361/build.py#L299)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/399)*

**Comment by micbou** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/399)*

**Comment by Valloric** [comment]
@homu r+

**Pull request merged**
