### PR TITLE
[READY] Add OrganizeImports command to TypeScript completer

### PR DESCRIPTION
**Pull request by micbou**
A recent addition to TSServer:

typescript-organize-imports

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/978)

### CODE REVIEW

**Comment by bstaletic** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/978#-:-L8i7NE1BBZ9mXVDw8yb:bnfp4nl)*

**Comment by puremourning** [comment]
:lgtm:

> recent addition to TSServer

IIRC we don't have a way to enforce the TSServer version. I guess this is why we're adding the TSServer version to the debug info ?

What happens if this command is fired on an older TSServer ?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/978#-:-L96cYh70w9246glPuT4:b44z474)*

**Comment by bstaletic** [comment]
Can we state which TSServer we support?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/978#-:-L96dvvw88STu7Q3XCt_:b31lypf)*

**Comment by micbou** [comment]
> IIRC we don't have a way to enforce the TSServer version. I guess this is why we're adding the TSServer version to the debug info ?

Yes, that's one of the reasons.

> What happens if this command is fired on an older TSServer ?

The command returns "RuntimeError: Unrecognized JSON command: organizeImports", which is not too bad.

> Can we state which TSServer we support?

With this command, the last version is required: 2.8.1.

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/978#-:-L96no7K2KegH1RoZc0k:bheyv2o)*

**Comment by bstaletic** [comment]
Sorry for not being clear. I wanted to suggest to put in the README that these commands require TSServer 2.8.1.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/978#-:-L96qrjZ35rFdIVrCfPL:bo4e1rf)*

**Comment by micbou** [comment]
> Sorry for not being clear. I wanted to suggest to put in the README that these commands require TSServer 2.8.1.

Agreed. Just need to remember to do that when we'll update ycmd submodule.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/978#-:-L96rDr_DsefU6UPPFgj:bv03qth)*

**Comment by micbou** [comment]
Conflicts fixed.

---

Reviewed 2 of 2 files at r3, 2 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/978#-:-L97Nbyq8gWHbhZmu_iV:b-wlrssi)*

**Comment by micbou** [comment]
@zzbot r+

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/978#-:-L98dE6K9SZjCqVBwsZ1:bi59kwd)*

**Pull request merged**
