### PR TITLE
Added GoTo include file functionality

### PR DESCRIPTION
**Pull request by davits**
Added GoToInclude sub-command for c family languages.
Changed logic to use paths specified with -iquote flag only for quoted includes. (https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html)
Added unit tests for new functionality.

[Review on Reviewable](https://reviewable.io/reviews/valloric/ycmd/244)

### CODE REVIEW

**Comment by Valloric** [comment]
Thanks for sending a PR!

I did a light review pass on this; variable/function naming seems like it needs the most work. I'll give a more thorough review once these issues are addressed.

---

Review status: 0 of 10 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[ycmd/completers/cpp/clang_completer.py, line 54 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-Ah9VGcJIcKpxQl2d-)** ([raw file](https://github.com/valloric/ycmd/blob/452385eb1732cfb4fae92bd0f6de12ce67a239d0/ycmd/completers/cpp/clang_completer.py#L54)):</sup>
There's already a regex for includes/imports in filename_completer.py. Is it possible to have one regex for both use-cases? If so, then let's declare it in a common location.

---

<sup>**[ycmd/completers/cpp/clang_completer.py, line 269 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-AhcMYyqBx5AIzqzUI)** ([raw file](https://github.com/valloric/ycmd/blob/452385eb1732cfb4fae92bd0f6de12ce67a239d0/ycmd/completers/cpp/clang_completer.py#L269)):</sup>
Longer than 80 chars.

---

<sup>**[ycmd/completers/cpp/clang_completer.py, line 271 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-AhlAx0DknpvdFSDFu)** ([raw file](https://github.com/valloric/ycmd/blob/452385eb1732cfb4fae92bd0f6de12ce67a239d0/ycmd/completers/cpp/clang_completer.py#L271)):</sup>
`f` is too short. Please use a more readable name.

---

<sup>**[ycmd/completers/cpp/clang_completer.py, line 521 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-Ai44TP28vt0qBISce)** ([raw file](https://github.com/valloric/ycmd/blob/452385eb1732cfb4fae92bd0f6de12ce67a239d0/ycmd/completers/cpp/clang_completer.py#L521)):</sup>
A better name for this function would be `GetAbsolutePath`.

`paths` should be named `include_paths`, since they're not just any paths.

---

<sup>**[ycmd/completers/cpp/clang_completer.py, line 523 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-Ahw-2UniDAIKKhi6m)** ([raw file](https://github.com/valloric/ycmd/blob/452385eb1732cfb4fae92bd0f6de12ce67a239d0/ycmd/completers/cpp/clang_completer.py#L523)):</sup>
`fp` is too short as well. 

---

<sup>**[ycmd/completers/cpp/flags.py, line 115 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-AiIapcvNPvnHL2s9x)** ([raw file](https://github.com/valloric/ycmd/blob/452385eb1732cfb4fae92bd0f6de12ce67a239d0/ycmd/completers/cpp/flags.py#L115)):</sup>
I see qfl, pfl, it, fl etc. These names are not acceptable. Please use descriptive variable names.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by davits** [comment]
<sup>**[ycmd/completers/cpp/clang_completer.py, line 54 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-Ah9VGcJIcKpxQl2d-)** ([raw file](https://github.com/valloric/ycmd/blob/452385eb1732cfb4fae92bd0f6de12ce67a239d0/ycmd/completers/cpp/clang_completer.py#L54)):</sup>
I have some thoughts about writing a single regex to replace existing 3, it will complicate logic a little bit, but it should be OK. I'll give it a try.
Is the completers/comleter_utils.py appropriate as a common location?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by vheon** [comment]
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[ycmd/completers/cpp/clang_completer.py, line 54 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-Ah9VGcJIcKpxQl2d-)** ([raw file](https://github.com/valloric/ycmd/blob/452385eb1732cfb4fae92bd0f6de12ce67a239d0/ycmd/completers/cpp/clang_completer.py#L54)):</sup>
What do you mean by:

> it will complicate logic a little bit

??

---

<sup>**[ycmd/completers/cpp/clang_completer.py, line 274 \[r3\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-FUAfrvR6JQ_Gkdq4g)** ([raw file](https://github.com/valloric/ycmd/blob/e54f76d3ad4e2f547356c4a3003cb6cd5d80f373/ycmd/completers/cpp/clang_completer.py#L274)):</sup>
Use named parameter for the magic numbers

---

<sup>**[ycmd/completers/cpp/clang_completer.py, line 278 \[r3\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-FUOafKqAWVR-tmdz9)** ([raw file](https://github.com/valloric/ycmd/blob/e54f76d3ad4e2f547356c4a3003cb6cd5d80f373/ycmd/completers/cpp/clang_completer.py#L278)):</sup>
Use named parameter for the magic numbers

---

<sup>**[ycmd/tests/subcommands_test.py, line 179 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-Eqw9-qHzbR-VvfjSt)** ([raw file](https://github.com/valloric/ycmd/blob/452385eb1732cfb4fae92bd0f6de12ce67a239d0/ycmd/tests/subcommands_test.py#L179)):</sup>
I would write this in a different test for this, like `RunCompleterCommand_GoToInclude_Clang_NotFound_test`, and write it in an assert like format. There are assert for raising exceptions.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by vheon** [comment]
Reviewed 1 of 3 files at r3.
Review status: 1 of 10 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[ycmd/tests/subcommands_test.py, line 156 \[r3\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-FfRxVrIFz8_FCDGJJ)** ([raw file](https://github.com/valloric/ycmd/blob/e54f76d3ad4e2f547356c4a3003cb6cd5d80f373/ycmd/tests/subcommands_test.py#L156)):</sup>
`comon_request` is not really needed in this case, you can easily build the goto_data like:

```python
  filepath = PathToTestFile( 'test-include', 'main.cpp' )
  goto_data = BuildRequest( filepath = filepath,
                            filetype = 'cpp',
                            contents = open( filepath ).read() ,
                            command_arguments = ['GoToInclude'],
                            line_num   : test['request'][0],
                            column_num : test['request'][1] )
```
same with `common_response`: to me doesn't make much sense to build a "common" thing to be used just one time.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by davits** [comment]
<sup>**[ycmd/completers/cpp/clang_completer.py, line 54 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-Ah9VGcJIcKpxQl2d-)** ([raw file](https://github.com/valloric/ycmd/blob/452385eb1732cfb4fae92bd0f6de12ce67a239d0/ycmd/completers/cpp/clang_completer.py#L54)):</sup>
It will require more checks to ensure matching for other 2 cases, like group emptiness or match length. It is not solid yet, so other approaches and/or suggestions are welcomed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by davits** [comment]
<sup>**[ycmd/completers/cpp/clang_completer.py, line 274 \[r3\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-FUAfrvR6JQ_Gkdq4g)** ([raw file](https://github.com/valloric/ycmd/blob/e54f76d3ad4e2f547356c4a3003cb6cd5d80f373/ycmd/completers/cpp/clang_completer.py#L274)):</sup>
Wouldn't it be over-caring?
I would like to avoid cursor change here, since there is no specific place to jump for this case.  Beside vim can be configured to jump to the last location when opening file, and this is breaking it.
It would be nice to have GoTo response just with file, but YouCompleteMe need to be updated as well, and I'm not sure how to synchronize these changes.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by davits** [comment]
<sup>**[ycmd/tests/subcommands_test.py, line 179 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-Eqw9-qHzbR-VvfjSt)** ([raw file](https://github.com/valloric/ycmd/blob/452385eb1732cfb4fae92bd0f6de12ce67a239d0/ycmd/tests/subcommands_test.py#L179)):</sup>
Could you please point out an example in existing tests?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by vheon** [comment]
Reviewed 6 of 10 files at r1.
Review status: 7 of 10 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[ycmd/completers/cpp/clang_completer.py, line 274 \[r3\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-FUAfrvR6JQ_Gkdq4g)** ([raw file](https://github.com/valloric/ycmd/blob/e54f76d3ad4e2f547356c4a3003cb6cd5d80f373/ycmd/completers/cpp/clang_completer.py#L274)):</sup>
I'm sorry, I'm not following you, all I was referring to was to rewrite that line to:

```python
return responses.BuildGoToResponse( include_file_path,
                                    line_num = 1,
                                    column_num = 1 )
```

So what were you talking about?


---

<sup>**[ycmd/tests/subcommands_test.py, line 179 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-Eqw9-qHzbR-VvfjSt)** ([raw file](https://github.com/valloric/ycmd/blob/452385eb1732cfb4fae92bd0f6de12ce67a239d0/ycmd/tests/subcommands_test.py#L179)):</sup>
You could try with pyhamcrest using `calling` and `raises` or `assertRaises` from `unittest`


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by davits** [comment]
<sup>**[ycmd/tests/subcommands_test.py, line 179 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-Eqw9-qHzbR-VvfjSt)** ([raw file](https://github.com/valloric/ycmd/blob/452385eb1732cfb4fae92bd0f6de12ce67a239d0/ycmd/tests/subcommands_test.py#L179)):</sup>
Thanks.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by davits** [comment]
<sup>**[ycmd/completers/cpp/clang_completer.py, line 274 \[r3\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-FUAfrvR6JQ_Gkdq4g)** ([raw file](https://github.com/valloric/ycmd/blob/e54f76d3ad4e2f547356c4a3003cb6cd5d80f373/ycmd/completers/cpp/clang_completer.py#L274)):</sup>
Ahh, I see. 
I thought what you mean was:
```
first_line = 1
first_column = 1
...BuildGoToResponse( include_file_path, first_line, first_column )
```
I am still thinking in C++ :)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by Valloric** [comment]
Review status: 5 of 11 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[ycmd/completers/completer_utils.py, line 164 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-QvPIPnsxzazuPQTpX)** ([raw file](https://github.com/valloric/ycmd/blob/69df1a040c2d6ff51fb280a349110e76d9611567/ycmd/completers/completer_utils.py#L164)):</sup>
What does `check_closing` do?  It's not obvious at-a-glance. A comment might be useful here.


---

<sup>**[ycmd/completers/cpp/flags.py, line 130 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-QwVSoT86uom7gzBbh)** ([raw file](https://github.com/valloric/ycmd/blob/69df1a040c2d6ff51fb280a349110e76d9611567/ycmd/completers/cpp/flags.py#L130)):</sup>
Instead of using `\`, wrap the expression in parens.


---

<sup>**[ycmd/completers/general/filename_completer.py, line 24 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-Qwbumdulwu6AAVUlP)** ([raw file](https://github.com/valloric/ycmd/blob/69df1a040c2d6ff51fb280a349110e76d9611567/ycmd/completers/general/filename_completer.py#L24)):</sup>
Seems longer than 80 chars.


---

<sup>**[ycmd/completers/general/filename_completer.py, line 102 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-QwkjAX2kAiALdXrvT)** ([raw file](https://github.com/valloric/ycmd/blob/69df1a040c2d6ff51fb280a349110e76d9611567/ycmd/completers/general/filename_completer.py#L102)):</sup>
Similar as before, avoid use of `\` for line continuation, use `(...)`.

Do this in other places as well.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by davits** [comment]
<sup>**[ycmd/tests/subcommands_test.py, line 171 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-Eqw9-qHzbR-VvfjSt)** ([raw file](https://github.com/valloric/ycmd/blob/452385eb1732cfb4fae92bd0f6de12ce67a239d0/ycmd/tests/subcommands_test.py#L171)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by vheon** [comment]
Reviewed 2 of 5 files at r4.
Review status: 7 of 11 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by micbou** [comment]
It would make sense to also add this feature to `GoTo` and `GoToImprecise` subcommands so that users can jump to headers, definitions, and declarations using only one shortcut key.


---

Reviewed 5 of 10 files at r1, 1 of 3 files at r3, 4 of 5 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[ycmd/completers/cpp/clang_completer.py, line 281 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-PWb70mW7RO4IvsjbA)** ([raw file](https://github.com/valloric/ycmd/blob/69df1a040c2d6ff51fb280a349110e76d9611567/ycmd/completers/cpp/clang_completer.py#L281)):</sup>
Missing space before `)`.


---

<sup>**[ycmd/tests/subcommands_test.py, line 139 \[r5\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-StLOtaMXdn3iB0rh-)** ([raw file](https://github.com/valloric/ycmd/blob/3c795c8cc56d4794f51be988a38d631a4ed33afa/ycmd/tests/subcommands_test.py#L139)):</sup>
Missing space before `)`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by davits** [comment]
Good Idea :+1: , shame didn't think of that myself :)


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by vheon** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[ycmd/tests/subcommands_test.py, line 139 \[r5\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-StLOtaMXdn3iB0rh-)** ([raw file](https://github.com/valloric/ycmd/blob/3c795c8cc56d4794f51be988a38d631a4ed33afa/ycmd/tests/subcommands_test.py#L139)):</sup>
and inside the []


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by davits** [comment]
Just noted that you can write include statements like this: '#    include  "a.hpp" '. 
Is anyone familiar with objective c? who can confirm or repute possibility of similar # import .


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by davits** [comment]
After manual testing: clang allows # import style imports.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by vheon** [comment]
Reviewed 2 of 3 files at r6.
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by micbou** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[ycmd/tests/subcommands_test.py, line 184 \[r6\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-eXRJmfvnAvbFhV8Ce)** ([raw file](https://github.com/valloric/ycmd/blob/1b2c6255d1938603ec60c5a63d8a82f03f4f60e5/ycmd/tests/subcommands_test.py#L184)):</sup>
I took a look at this and this is due to the way `webtest` is storing the Exception: the RuntimeError message is surrounded by two pairs of commas. Thus, the comma in `Can't` is escaped two times. So we need to use the string
```python
'Can\\\\\'t jump to definition or declaration.'
```
or better
```python
r'Can\\\'t jump to definition or declaration'
```


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by davits** [comment]
<sup>**[ycmd/tests/subcommands_test.py, line 184 \[r6\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-eXRJmfvnAvbFhV8Ce)** ([raw file](https://github.com/valloric/ycmd/blob/1b2c6255d1938603ec60c5a63d8a82f03f4f60e5/ycmd/tests/subcommands_test.py#L184)):</sup>
Thanks


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by Valloric** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[ycmd/completers/cpp/clang_completer.py, line 295 \[r7\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-iqTcT_oq5I7yFRlCp)** ([raw file](https://github.com/valloric/ycmd/blob/8cd87e2a230be51c60a75babadf3f6470e91dadb/ycmd/completers/cpp/clang_completer.py#L295)):</sup>
Whitespace needed inside parens.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by Valloric** [comment]
Reviewed 5 of 10 files at r1, 1 of 5 files at r4, 2 of 4 files at r5, 2 of 3 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by davits** [comment]
<sup>**[ycmd/completers/cpp/clang_completer.py, line 295 \[r7\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-iqTcT_oq5I7yFRlCp)** ([raw file](https://github.com/valloric/ycmd/blob/8cd87e2a230be51c60a75babadf3f6470e91dadb/ycmd/completers/cpp/clang_completer.py#L295)):</sup>
Damn I forgot them again :S This style is so unusual to me. 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by Valloric** [comment]
LGTM


---

Review status: 10 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by micbou** [comment]
Reviewed 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[ycmd/tests/subcommands_test.py, line 184 \[r7\]](https://reviewable.io:443/reviews/valloric/ycmd/244#-K-ip0gbVvpHunip_Gqo)** ([raw file](https://github.com/valloric/ycmd/blob/8cd87e2a230be51c60a75babadf3f6470e91dadb/ycmd/tests/subcommands_test.py#L184)):</sup>
We can now remove this comment.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by micbou** [comment]
Great work.

@homu r+


---

Reviewed 1 of 1 files at r9.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by vheon** [comment]
Looks like something went wrong when setting up the environment for one of the tests.

Let's try again.

@homu retry

**Comment by davits** [comment]
Thanks for all your help :)


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/244)

**Comment by puremourning** [comment]
The last phase to get this live is to get a PR in YouCompleteMe repo to update the README.md, and combine with an update to bump the ycmd version.

**Comment by Valloric** [comment]
@puremourning Ugh, I forgot about the ycmd version bump. Should have asked to have it in this PR. Oh well, no big deal. We can do it separately.

**Comment by vheon** [comment]
When we do this, we should remember to put `close Valloric/YouCompleteMe#334` in the commit message

**Pull request merged**
