### PR TITLE
Implement diagnostic information for TypeScript

### PR DESCRIPTION
**Pull request by mikeperri**
YCMD already uses the TypeScript [tsserver](https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-(tsserver)) for code completion. This change just implements diagnostic information (i.e. it shows compiler errors) similar to how it's implemented for C#.
screen shot 2017-03-11 at 5 35 48 pm
Related: https://github.com/Valloric/YouCompleteMe/issues/2442

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/718)

### CODE REVIEW

**Comment by vheon** [comment]
Thanks for the PR!

First thing first the tests are not passing and the failure looks related to these changes.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/718#-:-KezmhqSPjSSeQukr0z9:b15say7)*

**Comment by vheon** [comment]
I gave a very quick review

---

Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[ycmd/completers/typescript/typescript_completer.py, line 142 at r1](https://reviewable.io:443/reviews/valloric/ycmd/718#-KezpN9DePmPsOY5lJEg:-KezpN9DePmPsOY5lJEh:b6pzjah) ([raw file](https://github.com/valloric/ycmd/blob/7c1701209eb25acee270e7863d9724958de6d2c1/ycmd/completers/typescript/typescript_completer.py#L142)):*
> ```Python
>   if (start_difference >= 0) and (end_difference <= 0):
>     return 0
>   else:
> ```

there is no need for the `else` branch. The early return is enough

---

*[ycmd/completers/typescript/typescript_completer.py, line 441 at r1](https://reviewable.io:443/reviews/valloric/ycmd/718#-KezpY5NWSMspgppHoFA:-KezpY5NWSMspgppHoFB:bj41hxr) ([raw file](https://github.com/valloric/ycmd/blob/7c1701209eb25acee270e7863d9724958de6d2c1/ycmd/completers/typescript/typescript_completer.py#L441)):*
> ```Python
>                         for x in diagnostics ]
> 
>     return diagnostic_data
> ```

I think we can directly return the list comprehension

---

*[ycmd/completers/typescript/typescript_completer.py, line 445 at r1](https://reviewable.io:443/reviews/valloric/ycmd/718#-Kezo6NmBd8zU4G203hv:-Kezo6NmBd8zU4G203hw:b-qvatc6) ([raw file](https://github.com/valloric/ycmd/blob/7c1701209eb25acee270e7863d9724958de6d2c1/ycmd/completers/typescript/typescript_completer.py#L445)):*
> ```Python
> 
>   def GetTsDiagnosticsForCurrentFile( self, filename, request_data ):
>     # This returns the data the TypeScript server responded with.
> ```

Wouldn't make more sense to move this comment right before we call `TsDiagnosticToYcmdDiagnostic`? There it would explain why we call it.

---

*[ycmd/completers/typescript/typescript_completer.py, line 446 at r1](https://reviewable.io:443/reviews/valloric/ycmd/718#-KeznME1GR6b3KJWfvr3:-KeznME1GR6b3KJWfvr4:b-fk4xpc) ([raw file](https://github.com/valloric/ycmd/blob/7c1701209eb25acee270e7863d9724958de6d2c1/ycmd/completers/typescript/typescript_completer.py#L446)):*
> ```Python
>   def GetTsDiagnosticsForCurrentFile( self, filename, request_data ):
>     # This returns the data the TypeScript server responded with.
>     # Note that its that "offset" values represent codepoint offsets,
> ```

I'm not a native English speaker but I'm not sure `that its that` reads well :confused: 

---

*[ycmd/completers/typescript/typescript_completer.py, line 450 at r1](https://reviewable.io:443/reviews/valloric/ycmd/718#-KeznI6bg56936_A5vS7:-KeznI6cSe2t3yy3WTN_:bc2j4xf) ([raw file](https://github.com/valloric/ycmd/blob/7c1701209eb25acee270e7863d9724958de6d2c1/ycmd/completers/typescript/typescript_completer.py#L450)):*
> ```Python
> 
>     ts_diagnostics = itertools.chain(
>       self._GetSemanticDiagnostics(filename),
> ```

spaces inside the `(`

---

*[ycmd/completers/typescript/typescript_completer.py, line 480 at r1](https://reviewable.io:443/reviews/valloric/ycmd/718#-KezotUUO9fEaOMEv1vL:-KezotUUO9fEaOMEv1vM:bgk5jdb) ([raw file](https://github.com/valloric/ycmd/blob/7c1701209eb25acee270e7863d9724958de6d2c1/ycmd/completers/typescript/typescript_completer.py#L480)):*
> ```Python
>     ) )
> 
>     if len(ts_diagnostics_on_line) is 0:
> ```

is more Pythonic to just write `if not ts_diagnostics_on_line`

---

*[ycmd/completers/typescript/typescript_completer.py, line 493 at r1](https://reviewable.io:443/reviews/valloric/ycmd/718#-Kezp1m3aVAr50Z80a9c:-Kezp1m3aVAr50Z80a9d:bn4275a) ([raw file](https://github.com/valloric/ycmd/blob/7c1701209eb25acee270e7863d9724958de6d2c1/ycmd/completers/typescript/typescript_completer.py#L493)):*
> ```Python
>       )
>       if ( distance < distance_to_closest_ts_diagnostic
>             or closest_ts_diagnostic is None ):
> ```

`or not closest_ts_diagnostic`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/718#-:-KezphuMdh4McDOq4FPD:blvzttn)*

**Comment by vheon** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[ycmd/completers/typescript/typescript_completer.py, line 490 at r2](https://reviewable.io:443/reviews/valloric/ycmd/718#-Kf6FXMTb6gu9rtRa5PA:-Kf6FXMTb6gu9rtRa5PB:bljvi8v) ([raw file](https://github.com/valloric/ycmd/blob/2931096bbdc1fb543aef9f46926fad26db958444/ycmd/completers/typescript/typescript_completer.py#L490)):*
> ```Python
>         ts_diagnostic
>       )
>       if ( distance < distance_to_closest_ts_diagnostic
> ```

You have to change the order here:

```python
if ( not closest_ts_diagnostic or distance < distance_to_closest_ts_diagnostic )
```

because otherwise you will get an error of comparison between `None` and integer on the first run. That is why one of the test still fails

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/718)*

**Comment by mikeperri** [comment]
Thanks for bearing with me @vheon. I tried setting up the Vagrant image but for some reason the build inside the Vagrant box hangs sometimes. Seems like it's running out of memory or something. (I'm on Mac OS Sierra and I have 8GB RAM, as far as I know there isn't anything non-standard about my setup.) So I've been running tests by doing `./run_tests.py ycmd.tests.typescript`.

By the way,
> Wouldn't make more sense to move this comment right before we call TsDiagnosticToYcmdDiagnostic? There it would explain why we call it.

That's the only part of your feedback I didn't apply - the function is called in two places so I think it's best to keep the comment in the function itself.

Let me know if there's anything else I should do.

**Comment by micbou** [comment]
Thanks, this is a great addition to the TypeScript completer. I made some comments but this looks solid.

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 21 unresolved discussions, some commit checks failed.

---

*[ycmd/completers/typescript/typescript_completer.py, line 138 at r3](https://reviewable.io:443/reviews/valloric/ycmd/718#-KfBDSspu-kTWouoOaSF:-KfBDSsqrGf7Kwfn9_tq:b-sudm75) ([raw file](https://github.com/valloric/ycmd/blob/9bee7fd222c1f6f311e03dc43c78ec030f075642/ycmd/completers/typescript/typescript_completer.py#L138)):*
> ```Python
> 
>   start_difference = codepoint_offset - ts_start_offset
>   end_difference = codepoint_offset - (ts_end_offset - 1)
> ```

Missing space inside parentheses.

---

*[ycmd/completers/typescript/typescript_completer.py, line 140 at r3](https://reviewable.io:443/reviews/valloric/ycmd/718#-KfBDNcHesVsS_vRwjN2:-KfBDNcHesVsS_vRwjN3:b-oxuwln) ([raw file](https://github.com/valloric/ycmd/blob/9bee7fd222c1f6f311e03dc43c78ec030f075642/ycmd/completers/typescript/typescript_completer.py#L140)):*
> ```Python
>   end_difference = codepoint_offset - (ts_end_offset - 1)
> 
>   if (start_difference >= 0) and (end_difference <= 0):
> ```

Parentheses are not needed.

---

*[ycmd/completers/typescript/typescript_completer.py, line 143 at r3](https://reviewable.io:443/reviews/valloric/ycmd/718#-KfBDPHE6D7HrZUolTNj:-KfBDPHFrPIbrJiDnUYW:b-36ch98) ([raw file](https://github.com/valloric/ycmd/blob/9bee7fd222c1f6f311e03dc43c78ec030f075642/ycmd/completers/typescript/typescript_completer.py#L143)):*
> ```Python
>     return 0
> 
>   return min(abs(start_difference), abs(end_difference))
> ```

Missing spaces inside parentheses.

---

*[ycmd/completers/typescript/typescript_completer.py, line 439 at r3](https://reviewable.io:443/reviews/valloric/ycmd/718#-KfBEfiWtCNdKYh-vb-z:-KfBEfiWtCNdKYh-vb0-:b-ry8nad) ([raw file](https://github.com/valloric/ycmd/blob/9bee7fd222c1f6f311e03dc43c78ec030f075642/ycmd/completers/typescript/typescript_completer.py#L439)):*
> ```Python
>     diagnostics = self.GetDiagnosticsForCurrentFile( request_data )
>     return [ responses.BuildDiagnosticData( x )
>                         for x in diagnostics ]
> ```

Whole return can be put on one line.

---

*[ycmd/completers/typescript/typescript_completer.py, line 462 at r3](https://reviewable.io:443/reviews/valloric/ycmd/718#-KfBE-0uvUTDsu6ffVDv:-KfBE-0uvUTDsu6ffVDw:b81aga1) ([raw file](https://github.com/valloric/ycmd/blob/9bee7fd222c1f6f311e03dc43c78ec030f075642/ycmd/completers/typescript/typescript_completer.py#L462)):*
> ```Python
> 
>     return [ TsDiagnosticToYcmdDiagnostic( filename, line_value, x )
>              for x in ts_diagnostics ]
> ```

Similarly to what we do in the Clang and C# completers, the number of diagnostics should be limited by the option `max_diagnostics_to_display`.

---

*[ycmd/completers/typescript/typescript_completer.py, line 502 at r3](https://reviewable.io:443/reviews/valloric/ycmd/718#-KfBF0CsW6TIiJR87nav:-KfBF0CsW6TIiJR87naw:banx3tc) ([raw file](https://github.com/valloric/ycmd/blob/9bee7fd222c1f6f311e03dc43c78ec030f075642/ycmd/completers/typescript/typescript_completer.py#L502)):*
> ```Python
> 
>     return responses.BuildDisplayMessageResponse(
>       closest_diagnostic.text_ )
> ```

There is enough place to put this on the same line.

---

*[ycmd/completers/typescript/typescript_completer.py, line 516 at r3](https://reviewable.io:443/reviews/valloric/ycmd/718#-KfBFABk1SyucOt2HvaT:-KfBFABk1SyucOt2HvaU:bbo0r0g) ([raw file](https://github.com/valloric/ycmd/blob/9bee7fd222c1f6f311e03dc43c78ec030f075642/ycmd/completers/typescript/typescript_completer.py#L516)):*
> ```Python
>       'file': filename,
>       'includeLinePosition': True
>     })
> ```

Missing space before parenthesis.

---

*[ycmd/tests/typescript/diagnostics_test.py, line 2 at r3](https://reviewable.io:443/reviews/valloric/ycmd/718#-KfBCremQxTlTfMpwuqp:-KfBCrenmp0bSoqEEhHY:b-2ocvo2) ([raw file](https://github.com/valloric/ycmd/blob/9bee7fd222c1f6f311e03dc43c78ec030f075642/ycmd/tests/typescript/diagnostics_test.py#L2)):*
> ```Python
> 
> #
> ```

Those two lines can be removed.

---

*[ycmd/tests/typescript/diagnostics_test.py, line 36 at r3](https://reviewable.io:443/reviews/valloric/ycmd/718#-KfBCpFeI6TJqtQ8RKjr:-KfBCpFeI6TJqtQ8RKjs:b-oxuwln) ([raw file](https://github.com/valloric/ycmd/blob/9bee7fd222c1f6f311e03dc43c78ec030f075642/ycmd/tests/typescript/diagnostics_test.py#L36)):*
> ```Python
> 
> from ycmd.tests.typescript import PathToTestFile, SharedYcmd
> from ycmd.tests.test_utils import ( BuildRequest )
> ```

Parentheses are not needed.

---

*[ycmd/tests/typescript/diagnostics_test.py, line 58 at r3](https://reviewable.io:443/reviews/valloric/ycmd/718#-KfOvjj9zjdFL6iauNCg:-KfOvjj9zjdFL6iauNCh:b-jo5k5d) ([raw file](https://github.com/valloric/ycmd/blob/9bee7fd222c1f6f311e03dc43c78ec030f075642/ycmd/tests/typescript/diagnostics_test.py#L58)):*
> ```Python
> 
>   expected_text = 'Property \'nonExistingMethod\' ' \
>                   'does not exist on type \'Bar\'.'
> ```

We prefer to use parentheses for multi-line statement.

---

*[ycmd/tests/typescript/diagnostics_test.py, line 66 at r3](https://reviewable.io:443/reviews/valloric/ycmd/718#-KfBCFdxHnWtlTV4MP6e:-KfBCFdyjbNHLErfhV2B:b-8snan0) ([raw file](https://github.com/valloric/ycmd/blob/9bee7fd222c1f6f311e03dc43c78ec030f075642/ycmd/tests/typescript/diagnostics_test.py#L66)):*
> ```Python
>                  'location': has_entries( {
>                    'column_num': 1,
>                    'filepath': ends_with( 'test.ts' ),
> ```

We could directly use `main_filepath` here and below instead of `ends_with( 'test.ts' )`.

---

*[ycmd/tests/typescript/diagnostics_test.py, line 99 at r3](https://reviewable.io:443/reviews/valloric/ycmd/718#-KfOst4sL-8RJt3bH_g2:-KfOst4sL-8RJt3bH_g3:b-a0hcwl) ([raw file](https://github.com/valloric/ycmd/blob/9bee7fd222c1f6f311e03dc43c78ec030f075642/ycmd/tests/typescript/diagnostics_test.py#L99)):*
> ```Python
>                             contents = main_contents,
>                             line_num = 35,
>                             column_num = 6 )
> ```

Those four parameters are not aligned with the one above.

---

*[ycmd/tests/typescript/diagnostics_test.py, line 104 at r3](https://reviewable.io:443/reviews/valloric/ycmd/718#-KfOtEaHES-zBq36cCrZ:-KfOtEaHES-zBq36cCr_:b-jo5k5d) ([raw file](https://github.com/valloric/ycmd/blob/9bee7fd222c1f6f311e03dc43c78ec030f075642/ycmd/tests/typescript/diagnostics_test.py#L104)):*
> ```Python
> 
>   expected_message = 'Property \'nonExistingMethod\' ' \
>                      'does not exist on type \'Bar\'.'
> ```

We prefer to use parentheses for multi-line statement.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/718#-:-KfOreIUCqKyD5-E48_l:bw24vza)*

**Comment by micbou** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/718#-:-KfzuoTIGpmjY282HhFT:bnfp4nl)*

**Comment by Valloric** [comment]
:lgtm: 

This is fantastic! Thanks for sending a PR!

Not triggering a merge with homu because I see @vheon left some comments and hasn't yet left an LGTM.

Other than that, this is good to go IMO.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/718#-:-Kg0UReGkEOfzeUrLWmv:b-f7fg86)*

**Comment by vheon** [comment]
:lgtm: @homu r+

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/718#-:-Kg1BsN0yZhcR3tec-kC:b-2cbojr)*

**Comment by micbou** [comment]
@mikeperri Will you open a PR on YCM repository to include this new feature or do you want us to take care of it?

**Comment by mikeperri** [comment]
@micbou I got it.

**Pull request merged**
