### PR TITLE
[READY] Removing ycm_client_support

### PR DESCRIPTION
**Pull request by Valloric**
It was around to supply the `FilterAndSortCandidates` function to Vim.
This has now been replaced with a `/filter_and_sort_candidates` handler in
ycmd that behaves the same as the function.

The point of all this is that we don't want to have any ycmd compiled
libs loaded into Vim (through YCM). Loading the lib would mean that the
Python version that YCM uses in Vim and the Python version that ycmd
runs on would have to be the same. So py2 or py3 for both because we
only build ycmd for one Python interpreter.

Since we now don't load the ycm_client_support (or any other) library
into Vim, YCM and ycmd can use completely different Python interpreter
versions. One can be py2, the other can be py3 (or any other
combination). This is the holy grail of Python compatibility for us.

In theory, this new architecture will cause extra latency for YCM
completions that use the OmniCompleter. In practice, it's imperceptible.
The extra latency should be *at most* 5-10ms and the whole thing is
still well below 100ms. I have the YCM part of this change done and
having played with Ruby omnicompletion before and after this change, I
couldn't notice any latency difference.

Note that this changes YCM's build products; we now only have `ycm_core.so`. 
@d0k @r4nt

[Review on Reviewable](https://reviewable.io/reviews/valloric/ycmd/386)

### CODE REVIEW

**Comment by vheon** [comment]
Oh man really!? I was working on this on my local machine :stuck_out_tongue_closed_eyes: 

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/386#-:-KBF69zxRh4GJvRv6-eZ:27628352)*

**Comment by Valloric** [comment]
@vheon Well you should have said something! :D

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/386#-:-KBF76714i9Tm8f_Sjse:-1028728575)*

**Comment by vheon** [comment]
I had barely started, but I'm glad that it wasn't a bad idea after all. The use for me was to use vim from Cygwin with its version of python but compiling `ycmd` with MSVC and the standard version of Python; and soon I will!

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/tests/misc_handlers_test.py, line 30 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/386#-KBF7flifKmq4MdjE57z:-KBF7fljI4gSLBcA4Xbj:-314702176) ([raw file](https://github.com/valloric/ycmd/blob/a7a66e29a04c113ad7fe031caab75ebbbef719e8/ycmd/tests/misc_handlers_test.py#L30)):*
why the parenthesis and the trailing comma?

---

*[ycmd/utils.py, line 39 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/386#-KBF7t_U05-vtOoo1Jqi:-KBF7t_U05-vtOoo1Jqj:2037245012) ([raw file](https://github.com/valloric/ycmd/blob/a7a66e29a04c113ad7fe031caab75ebbbef719e8/ycmd/utils.py#L39)):*
What is the use of those?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/386#-:-KBF8BhLt92qxi3tazV4:1286310069)*

**Comment by Valloric** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[ycmd/tests/misc_handlers_test.py, line 30 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/386#-KBF7flifKmq4MdjE57z:-KBFHZ7G9vTdewSxnbeT:-532973020) ([raw file](https://github.com/valloric/ycmd/blob/a7a66e29a04c113ad7fe031caab75ebbbef719e8/ycmd/tests/misc_handlers_test.py#L30)):*
Bah, c/p from another file that had a long hamcrest import line. Fixed now.

---

*[ycmd/utils.py, line 39 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/386#-KBF7t_U05-vtOoo1Jqi:-KBFHi-8njzi5ll2lAGu:-349196425) ([raw file](https://github.com/valloric/ycmd/blob/a7a66e29a04c113ad7fe031caab75ebbbef719e8/ycmd/utils.py#L39)):*
Currently, we don't use them, but we've used `RunningInsideVim` up until this PR (which this new constant is replacing). I'd be surprised if we didn't need this again at some point.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/386)*

**Comment by micbou** [comment]
I really like this change. The build issue on Windows is fixed by PR #387.

---

Reviewed 12 of 13 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[ycmd/completers/completer_utils.py, line 31 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/386#-KBGd1-pfkTHEg7WWJ4e:-KBGd1-qHu6jQKoyGXP_:1723784979) ([raw file](https://github.com/valloric/ycmd/blob/599de71575d542d4fc5c33344c65b3931e4d7ed2/ycmd/completers/completer_utils.py#L31)):*
Not a big deal but we should agree on some convention for importing Python modules:
 - `import` or `from` first?
 - blank line between `import` and `from` lines?
 - alphabetical order?

---

*[ycmd/tests/request_wrap_test.py, line 166 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/386#-KBGanuTkTPt79obisCY:-KBGanuTkTPt79obisCZ:583631449) ([raw file](https://github.com/valloric/ycmd/blob/599de71575d542d4fc5c33344c65b3931e4d7ed2/ycmd/tests/request_wrap_test.py#L166)):*
Extra blank line.

---

*[ycmd/utils.py, line 39 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/386#-KBF7t_U05-vtOoo1Jqi:-KBGe9niBCU2VPk0beuN:1765009454) ([raw file](https://github.com/valloric/ycmd/blob/a7a66e29a04c113ad7fe031caab75ebbbef719e8/ycmd/utils.py#L39)):*
I think we should still remove it. If one day we need it, we'll readd it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/386#-:-KBGcmcQme8sHfSoK0Eq:757434442)*

**Comment by Valloric** [comment]
Review status: 9 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[ycmd/completers/completer_utils.py, line 31 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/386#-KBGd1-pfkTHEg7WWJ4e:-KBJLeBHtEbJMJmlPBoF:-222177137) ([raw file](https://github.com/valloric/ycmd/blob/599de71575d542d4fc5c33344c65b3931e4d7ed2/ycmd/completers/completer_utils.py#L31)):*
I agree that we should come up with a convention, but we should have a tool that enforces that convention. I wanted to take a closer look at [pylint](https://www.pylint.org/); maybe it can be configured to enforce our style guide. I don't have the time to play around with it with all the py3 work; do you want to take it for a spin? 

It probably has a way to specify import order.

For this PR, I'm not going to bother too much with import lines because we're inconsistent about it throughout the codebase. My general approach has been that stdlib imports come first, then third_party imports, then our imports. No ordering within the groups and an empty line between them.

But this is all up in the air now that we have to have the `future` imports first. Maybe we could make it:

1. Mandatory `future` block
2. stdlib imports
3. third_party imports
4. our imports

With empty lines in between.

But again, not this PR.

---

*[ycmd/utils.py, line 39 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/386#-KBF7t_U05-vtOoo1Jqi:-KBJMezgY5_UXHF--Bux:478249658) ([raw file](https://github.com/valloric/ycmd/blob/a7a66e29a04c113ad7fe031caab75ebbbef719e8/ycmd/utils.py#L39)):*
My instincts agree with you. Don't know why I went against them here. Removed.

---

*[ycmd/tests/request_wrap_test.py, line 166 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/386#-KBGanuTkTPt79obisCY:-KBJMdn25fGbxe1R_a-k:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/599de71575d542d4fc5c33344c65b3931e4d7ed2/ycmd/tests/request_wrap_test.py#L166)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/386)*

**Comment by micbou** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[ycmd/completers/completer_utils.py, line 31 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/386#-KBGd1-pfkTHEg7WWJ4e:-KBJzyxhE7tFPK0ddr7O:1484155787) ([raw file](https://github.com/valloric/ycmd/blob/599de71575d542d4fc5c33344c65b3931e4d7ed2/ycmd/completers/completer_utils.py#L31)):*
Ok, I'll take a look at pylint.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/386#-:-KBK0dujnWd6vPLembp_:1417088721)*

**Comment by vheon** [comment]
:lgtm: @homu r+

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 2 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/386#-:-KBK2i3kFX32uqcWCDiQ:-141632775)*

**Comment by puremourning** [comment]
Just wanted to say that this (and the related changes for ycm_core) is a kickass change. Removing the python binary coupling is such a big win, I'm blown over. Just flat out kills a hole load of potential and real issues. Thanks so much!

**Comment by Valloric** [comment]
:D

**Pull request merged**
