### PR TITLE
[READY] Add FixIt command to TypeScript completer

### PR DESCRIPTION
**Pull request by micbou**
This is implemented similarly to the Clang completer i.e. the FixIts are stored in the diagnostics. Demo:

typescript-fixit

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/976)

### CODE REVIEW

**Comment by bstaletic** [comment]
:lgtm: 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[ycmd/responses.py, line 236 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/976#-L8iADIG71EhPkJl8sq_:-L8iADIH0UnjFCDkBcvG:bocyvmz) ([raw file](https://github.com/valloric/ycmd/blob/9a8f1eb0c83fe4646ad20166f458def5523aa54e/ycmd/responses.py#L236)):*
> ```Python
>     'text': diagnostic.text_,
>     'kind': kind,
>     'fixit_available': len( diagnostic.fixits_ ) > 0,
> ```

Unrelated to this PR, but should we make a suggestion for LSP to support something like this?\\\\\

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/976#-:-L8iBjOzAZQ4s48uc20B:bg7igkv)*

**Comment by puremourning** [comment]
:lgtm: 

The one thought I had is that we optimistically generate the fixits as ycmd fixits. One option would be to store the raw TSServer data and only convert when applied. This would then defer that work to the synchronous FixIt command rather than the OnFileReadyToParse event. It's probably not a noticeable difference, and I don't write typescript in anger so I don't know how likely it is that it would be.

@zzbot r+

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ycmd/responses.py, line 236 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/976#-L8iADIG71EhPkJl8sq_:-L96_-qmDGp6auvm6gO5:bcemmex) ([raw file](https://github.com/valloric/ycmd/blob/9a8f1eb0c83fe4646ad20166f458def5523aa54e/ycmd/responses.py#L236)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Unrelated to this PR, but should we make a suggestion for LSP to support something like this?\\\\\
</blockquote></details>

you can do the LSP thing, by sending a codeaction request, but we would need to send it for every diagnostic would would be a performance issue, and tbh might not do exactly what we want.

---

*[ycmd/responses.py, line 155 at r2](https://beta.reviewable.io/reviews/valloric/ycmd/976#-L96ZmnpAmBZ9cIh8b3W:-L96ZmnpAmBZ9cIh8b3X:bpwf28x) ([raw file](https://github.com/valloric/ycmd/blob/033b5ac083523555161b80f640f3cf00083eadca/ycmd/responses.py#L155)):*
> ```
>   def __init__ ( self, ranges,
>                        location,
> ```
 
seems strange to break at second comma and align with ranges, rather than break at comma and align with first argument. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/976#-:-L96aPfU0hkjKdjYR1PM:b-4qess7)*

**Comment by bstaletic** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[ycmd/responses.py, line 236 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/976#-L8iADIG71EhPkJl8sq_:-L96fJvF1fzrOxv8_fiU:b-xci413) ([raw file](https://github.com/valloric/ycmd/blob/9a8f1eb0c83fe4646ad20166f458def5523aa54e/ycmd/responses.py#L236)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

you can do the LSP thing, by sending a codeaction request, but we would need to send it for every diagnostic would would be a performance issue, and tbh might not do exactly what we want.
</blockquote></details>

Still not as nice as if it would be if part of the protocol.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/976)*

**Comment by micbou** [comment]
@zzbot r+

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/responses.py, line 155 at r2](https://beta.reviewable.io/reviews/valloric/ycmd/976#-L96ZmnpAmBZ9cIh8b3W:-L96gP1u8qNh7kBCaRGH:bt2vr1b) ([raw file](https://github.com/valloric/ycmd/blob/033b5ac083523555161b80f640f3cf00083eadca/ycmd/responses.py#L155)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

> ```
>   def __init__ ( self, ranges,
>                        location,
> ```
 
seems strange to break at second comma and align with ranges, rather than break at comma and align with first argument. 
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/976#-:-L96gS2oEZOa2ympu5Mj:bi59kwd)*

**Pull request merged**
