### PR TITLE
[READY] Bump Tern version to 0.19.0

### LINKED ISSUE #543: Update package.json ...ycmd/third_party/tern_runtime/package.json
This tool is indispensable for **JS/node autocomplete**

The latest version of **tern.js is 0.19**

### PR DESCRIPTION
**Pull request by micbou**
Closes #543.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/544)

### CODE REVIEW

**Comment by puremourning** [comment]
It's possible that we can now use the Tern timeout feature again, but that can be a different PR if we so choose. TBH I haven't seen any need to do so yet.

:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/544#-:-KMVnIfAUJpn_ZjrgJ87:-1708295180)*

**Comment by Valloric** [comment]
:lgtm: provided there's a good rationale for deleting the `makedirs` call we currently have.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[build.py, line 445 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/544#-KMWSxvLLgKxPck8_iNw:-KMWSxvLLgKxPck8_iNx:-1231608725) ([raw file](https://github.com/valloric/ycmd/blob/cc87a9c5fc659f488879c3cb5bce090a966cbb70/build.py#L445)):*
> ```Python
>                                    'tern_runtime' )
>   try:
>     os.makedirs( TERN_RUNTIME_DIR )
> ```

Why is this getting deleted?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/544#-:-KMWT-pku1XcsbdJRcbt:-569067607)*

**Comment by micbou** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[build.py, line 445 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/544#-KMWSxvLLgKxPck8_iNw:-KMYarLxbfZc_EhjSkSx:-794971659) ([raw file](https://github.com/valloric/ycmd/blob/cc87a9c5fc659f488879c3cb5bce090a966cbb70/build.py#L445)):*
<details><summary><i>Previously, Valloric (Val Markovic) wrote…</i></summary>
> Why is this getting deleted?
</details>
Because there is no reason to create a folder that already exists. My guess is that the `third_party/tern_runtime` folder was initially empty and since Git does not track empty folder, it was necessary to create it. With the presence of `package.json`, it is not. @puremourning may confirm this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/544)*

**Comment by Valloric** [comment]
Good enough for me; thanks for the PR!

@homu r=puremourning

**Pull request merged**
