### PR TITLE
[READY] Extract filtering of tags as a generator

### PR DESCRIPTION
**Pull request by vheon**
Looking at the coverage of the Python layer of ycmd I noticed that one of the least tested file was the `identifier_completer.py` file. I understand that this file is actually just a thin wrapper around the cpp class (conversion to/from ycm_core data structure) so is understandable that is not 100% tested, but one big section that was not tested is the tag insertion: before inserting the file paths into an array and passing it to the cpp class we filter some paths based on the last update time of the file. So I extracted that section of the function as a generator and unit tested that function. I've marked this as WIP because I'm adding also a test that actually exercise the feature end-to-end.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/637)

### CODE REVIEW

**Comment by Valloric** [comment]
Is that class a thin wrapper or not does not have any bearing on whether it should have good unit test coverage; the answer is "yes it should." :D

I'm fine with submitting this PR as-is and then have a subsequent one that adds yet more testing. I don't really see a need to do it all in one big PR.

Thanks for doing this!

:lgtm: 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/637#-:-KVb5cOpjMCmA2BWaly9:b-zbsgho)*

**Comment by vheon** [comment]
> I'm fine with submitting this PR as-is and then have a subsequent one that adds yet more testing. I don't really see a need to do it all in one big PR.

Too late, I already added the test 😉

**Comment by micbou** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/tests/get_completions_test.py, line 44 at r2](https://reviewable.io:443/reviews/valloric/ycmd/637#-KVeBANus0KNEgZcBbiE:-KVeBANv9NBuP26YAkKY:b-ea0m9k) ([raw file](https://github.com/valloric/ycmd/blob/a564cfda2b6915990c70a67f5d401585d5a301b6/ycmd/tests/get_completions_test.py#L44)):*
> ```Python
>                          'cpp', 'ycm',
>                          'tests',
>                          'testdata' )
> ```

Maybe it would be better to copy the `basic.tags` file to `ycmd/tests/testdata` and use [the `PathToTestData` function](https://github.com/Valloric/ycmd/blob/master/ycmd/tests/__init__.py#L34).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/637)*

**Comment by vheon** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/tests/get_completions_test.py, line 44 at r2](https://reviewable.io:443/reviews/valloric/ycmd/637#-KVeBANus0KNEgZcBbiE:-KVeeSGmNhK-vlrw9CyO:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/a564cfda2b6915990c70a67f5d401585d5a301b6/ycmd/tests/get_completions_test.py#L44)):*
<details><summary><i>Previously, micbou wrote…</i></summary>
> Maybe it would be better to copy the `basic.tags` file to `ycmd/tests/testdata` and use [the `PathToTestData` function](https://github.com/Valloric/ycmd/blob/master/ycmd/tests/__init__.py#L34).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/637)*

**Comment by micbou** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/tests/identifier_completer_test.py, line 40 at r3](https://reviewable.io:443/reviews/valloric/ycmd/637#-KVefLfuPx8w6DIjTAJa:-KVefLfuPx8w6DIjTAJb:bokbcgr) ([raw file](https://github.com/valloric/ycmd/blob/6b957a93c4b37c105960121e4b8297e5512d3366/ycmd/tests/identifier_completer_test.py#L40)):*
> ```Python
>                          'cpp', 'ycm',
>                          'tests',
>                          'testdata' )
> ```

Sorry, I should have mentioned it in my previous comment but this can also be replaced by `PathToTestData`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/637)*

**Comment by vheon** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/tests/identifier_completer_test.py, line 40 at r3](https://reviewable.io:443/reviews/valloric/ycmd/637#-KVefLfuPx8w6DIjTAJa:-KVemEW103EqUsmI2lxZ:b-e1pmpj) ([raw file](https://github.com/valloric/ycmd/blob/6b957a93c4b37c105960121e4b8297e5512d3366/ycmd/tests/identifier_completer_test.py#L40)):*
<details><summary><i>Previously, micbou wrote…</i></summary>
> Sorry, I should have mentioned it in my previous comment but this can also be replaced by `PathToTestData`.
</details>
I should've checked myself :wink:  Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/637)*

**Comment by vheon** [comment]
Apparently it failed a build both on Travis and Appveyor for different reasons unrelated to this change 😕

**Comment by micbou** [comment]
:lgtm:

@homu r+

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/637#-:-KVidJ8uP1Je6C89mNM0:b33slzv)*

**Pull request merged**
