### PR TITLE
[WIP] Tests for IdentifierCompleter, IdentifierDatabase and IdentifierUtils

### PR DESCRIPTION
**Pull request by bstaletic**
The idea of these tests is to get 100% test coverage for `IdentifierUtils.cpp`, `IdentifierCompleter.cpp` and every file having any function called from these two files (for example `IdentifierDatabase.cpp`).

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/730)

### CODE REVIEW

**Comment by bstaletic** [comment]
I thought I solved the problem with appveyor builds, but I was wrong. I see nothing wrong with the tests and I don't have a windows machine to check.

**Comment by micbou** [comment]
You need to export [this `IdentifierCompleter` constructor](https://github.com/Valloric/ycmd/blob/43fac50d85c8d9fe401ecef7464fda61720cc53d/cpp/ycm/IdentifierCompleter.h#L42-L44) with the `YCM_DLL_EXPORT` macro for compiling the tests on Windows.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cpp/ycm/tests/IdentifierCompleter_test.cpp, line 325 at r1](https://reviewable.io:443/reviews/valloric/ycmd/730#-KgCFUcTy8EgRbjvByQH:-KgCFUcTy8EgRbjvByQI:bja7jkj) ([raw file](https://github.com/valloric/ycmd/blob/87e99ddcf11a005e27f62be5326df974574b6743/cpp/ycm/tests/IdentifierCompleter_test.cpp#L325)):*
> ```cpp
>                    "foobartest",
>                    "Foobartest" ),
> 		 std::string( "c" ),
> ```

Spaces instead of tabs.

---

*[cpp/ycm/tests/IdentifierUtils_test.cpp, line 80 at r1](https://reviewable.io:443/reviews/valloric/ycmd/730#-KgCFbRN1bhMXlyQzvG5:-KgCFbRN1bhMXlyQzvG6:bau70qt) ([raw file](https://github.com/valloric/ycmd/blob/87e99ddcf11a005e27f62be5326df974574b6743/cpp/ycm/tests/IdentifierUtils_test.cpp#L80)):*
> ```cpp
>   EXPECT_THAT( ExtractIdentifiersFromTagsFile( testfile ),
>                ContainerEq( FiletypeIdentifierMap() ) );
> }
> ```

Missing two blank lines between tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/730#-:-KgCH09rKHw5b23D8No0:b-aeesll)*

**Comment by bstaletic** [comment]
Thanks for that. Fixed. 

---

Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[cpp/ycm/tests/IdentifierCompleter_test.cpp, line 325 at r1](https://reviewable.io:443/reviews/valloric/ycmd/730#-KgCFUcTy8EgRbjvByQH:-KgCPrkTi-JC4C3p5Q2j:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/87e99ddcf11a005e27f62be5326df974574b6743/cpp/ycm/tests/IdentifierCompleter_test.cpp#L325)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Spaces instead of tabs.
</blockquote></details>

Done.

---

*[cpp/ycm/tests/IdentifierUtils_test.cpp, line 80 at r1](https://reviewable.io:443/reviews/valloric/ycmd/730#-KgCFbRN1bhMXlyQzvG5:-KgCPsv1i4V2PXTSzne1:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/87e99ddcf11a005e27f62be5326df974574b6743/cpp/ycm/tests/IdentifierUtils_test.cpp#L80)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Missing two blank lines between tests.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/730#-:-KgCPjVmtVLLoJffkmTT:b-aaa88s)*

**Comment by Valloric** [comment]
A PR that adds only tests? Hard not  to like that. :) Thanks!

:lgtm: 

---

Review status: 1 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/730#-:-KgG4YF7NUgJgwkDCmy1:b-424utn)*

**Comment by micbou** [comment]
:lgtm:

@homu r+

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/730#-:-KgG7tvHOMTmHokjikBI:b33slzv)*

**Pull request merged**
