### PR TITLE
Fix build on FreeBSD with Boost 1.67 python-libs

### PR DESCRIPTION
**Pull request by movsw**
Add the BOOST_PYTHON_SUFFIX for cmake

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1011)

### CODE REVIEW

**Comment by bstaletic** [comment]
I don't see how  this solves anything because we have completely removed Boost.Python.
Did you face any error since we switched to Boost 1.67.0?

**Comment by movsw** [comment]
Yes I do. The cmake can't find "boost_python" from the Boost 1.67:

> pwd
/usr/home/user/.vim/bundle/YouCompleteMe

> git log
commit 84554d2194b66666b6243a09af51fdb2b1bd6260 (HEAD -> master, origin/master, origin/auto, origin/HEAD)
Merge: e4c6750a f4472368
Author: zzbot <val+zzbot@markovic.io>
Date:   Mon Apr 23 14:35:42 2018 -0700

I try to build the ycm_core:
> setenv LD_LIBRARY_PATH /usr/local/llvm50/lib
> python2.7 install.py --clang-completer --system-libclang --system-boost
...
CMake Error at /usr/local/share/cmake/Modules/FindBoost.cmake:2045 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.67.0

  Boost include path: /usr/local/include

  Could not find the following Boost libraries:

          boost_python
...

My PR solve this problem.

> uname -v | cut -d\: -f1
FreeBSD 11.1-RELEASE #0 r326634M

> pkg info | grep boost
boost-all-1.67.0               The "meta-port" for boost libraries
boost-docs-1.67.0              Documentation for libraries from boost.org
boost-libs-1.67.0_1            Free portable C++ libraries (without Boost.Python)
py27-boost-libs-1.67.0         Framework for interfacing Python and C++

> pkg info | grep cmake
cmake-3.11.0_2

**Comment by bstaletic** [comment]
Ycmd isn't looking for `boost_python` at all as of [this PR](https://github.com/Valloric/ycmd/commit/21fae11dc2073b91249e1a6e1ea419ba0005c9ae#diff-e84b5c6d195cd3812d3ebe817f362b1f). Did you update ycmd before trying to build it?

**Comment by movsw** [comment]
I have updated third_party/ycmd/ and it solve the problem. Thank you! The VundleVim can't update it by himself.

**Comment by micbou** [comment]
Closing then.

**Comment by bstaletic** [comment]
@movsw For the record, Vundle doesn't update ycmd because Valloric/YouCompleteMe#2995 isn't yet merged.

**Pull request closed without merging**
