### PR TITLE
[READY] Additional test for the identifier completer

### PR DESCRIPTION
**Pull request by vheon**
I continued to look at the coverage for this file and I added more tests for it. I've also make private all the methods used only in this class that are not part of the Completer interface.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/640)

### CODE REVIEW

**Comment by vheon** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/completers/all/identifier_completer.py, line 97 at r1](https://reviewable.io:443/reviews/valloric/ycmd/640#-KVlyo8yxA5FCiqK_u4R:-KVlyo8yxA5FCiqK_u4S:bans8qr) ([raw file](https://github.com/valloric/ycmd/blob/1b7940792372ff03ba90af8d243d0d06a4726eba/ycmd/completers/all/identifier_completer.py#L97)):*
> ```Python
>   def AddIdentifierUnderCursor( self, request_data ):
>     cursor_identifier = _GetCursorIdentifier( request_data )
>     if not cursor_identifier:
> ```

I've removed this check because is already done in the `_AddIdentifier` method so there is no need to do it here also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/640)*

**Comment by Valloric** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/completers/all/identifier_completer.py, line 96 at r1](https://reviewable.io:443/reviews/valloric/ycmd/640#-KVmMHNeXv5uTA-Msb2f:-KVmMHNeXv5uTA-Msb2g:bxw9p5s) ([raw file](https://github.com/valloric/ycmd/blob/6771d93fac7de5c3f670b3959bc81d4b094c1d5b/ycmd/completers/all/identifier_completer.py#L96)):*
> ```Python
> 
>   def _AddIdentifierUnderCursor( self, request_data ):
>     self._AddIdentifier( _GetCursorIdentifier( request_data ), request_data )
> ```

Why do we not need the old check anymore? It would skip calling into c++ code needlessly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/640)*

**Comment by vheon** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/completers/all/identifier_completer.py, line 96 at r1](https://reviewable.io:443/reviews/valloric/ycmd/640#-KVmMHNeXv5uTA-Msb2f:-KVnb3bo7oC9hXKcnvYo:b5lkfmt) ([raw file](https://github.com/valloric/ycmd/blob/6771d93fac7de5c3f670b3959bc81d4b094c1d5b/ycmd/completers/all/identifier_completer.py#L96)):*
<details><summary><i>Previously, Valloric (Val Markovic) wrote…</i></summary>
> Why do we not need the old check anymore? It would skip calling into c++ code needlessly.
</details>
I thoght I lefted a comment here on reviewable :confused:  Anyway the `_AddIdentifier` already does the check so is not needed here and we would not hit he c++ code if not necessary anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/640)*

**Comment by Valloric** [comment]
:lgtm:

Thanks for more tests!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/640#-:-KVpAsYiauCBkJ5cWZHF:b499qa6)*

**Comment by micbou** [comment]
:lgtm:

@homu r+

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/640#-:-KVpC5lfw3mMvpubCJ0b:b33slzv)*

**Pull request merged**
