### PR TITLE
[READY] Fix javascript subcommand errors for relative paths.

### PR DESCRIPTION
**Pull request by puremourning**
The Tern server returns relative paths. When using a
.tern-project file, paths are returned relative to that file. When
no .tern-project file exists, paths are relative to the working
directory of the Tern server.

Fixes https://github.com/Valloric/YouCompleteMe/issues/2322

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/596)

### CODE REVIEW

**Comment by micbou** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/596#-:-KRPxnRmQ7KnJlLy8fi4:bnfp4nl)*

**Comment by vheon** [comment]
:lgtm: @homu r=micbou

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/596#-:-KRQ2873D48KVkJ_a39s:b-v6qh3o)*

**Comment by puremourning** [comment]
Sorry I mangled the branch push. Like a total noob i forgot to `git add` before `git commit --amend --no-edit && git push ....`.

Should be fixed now :S

**Comment by micbou** [comment]
@homu r+

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/596#-:-KRQIcv0UrYzvhqZUfam:b-iwbgq9)*

**Pull request merged**
