### PR TITLE
[READY] Drop Vagrant setup

### PR DESCRIPTION
**Pull request by micbou**
Our Vagrant setup is not working since almost one year now and no one in the team is willing to fix it and maintain it (at least not me). Having instructions to develop ycmd that doesn't work is detrimental to the project as this may refrain users from contributing. For these reasons, I propose to completely drop Vagrant. 

This PR also includes small improvements to the `TESTS.md` file.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/939)

### CODE REVIEW

**Comment by bstaletic** [comment]
I agree that we shouldn't have broken instructions, and I have left a few comments, but this is :lgtm:.

---

Reviewed 7 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[TESTS.md, line 61 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/939#-L6HHrVV7N7ekJfONg_U:-L6HHrVV7N7ekJfONg_V:b-lr6hpz) ([raw file](https://github.com/valloric/ycmd/blob/4cd23d062c9bc6ad9328dd44ab4dd277a03a18d5/TESTS.md#L61)):*
> ```Markdown
> 
> * `./run_tests.py ycmd/tests/subcommands_test.py:Subcommands_Basic_test`
> * `./run_tests.py ycmd.tests.subcommands_test`
> ```

The second example can also be `./run_tests.py ycmd/tests/subcommands_test.py`. Same effect, but much nicer because it allows shell completion to be used.

---

*[DEBUG.md, line 100 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/939#-L6HHUoC2yH7pflYScdI:-L6HHUoC2yH7pflYScdJ:btkafzg) ([raw file](https://github.com/valloric/ycmd/blob/4cd23d062c9bc6ad9328dd44ab4dd277a03a18d5/DEBUG.md#L100)):*
> ```Markdown
>   Don't ask why. It's for security.
> 
> 3. Here you have choices: either use a Python debugger to break the tests, or
> ```

Shouldn't this be `4.`? We already have `3.`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/939#-:-L6HIfF7AUjKM5LpzDgk:b-9mmn1q)*

**Comment by micbou** [comment]
Reviewed 5 of 8 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[TESTS.md, line 61 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/939#-L6HHrVV7N7ekJfONg_U:-L6HQw3S-kINmmUrV99U:b-nfmg2z) ([raw file](https://github.com/valloric/ycmd/blob/4cd23d062c9bc6ad9328dd44ab4dd277a03a18d5/TESTS.md#L61)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

The second example can also be `./run_tests.py ycmd/tests/subcommands_test.py`. Same effect, but much nicer because it allows shell completion to be used.
</blockquote></details>

I agree. Updated.

---

*[DEBUG.md, line 100 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/939#-L6HHUoC2yH7pflYScdI:-L6HQgm33vhNYHtG5Fwx:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/4cd23d062c9bc6ad9328dd44ab4dd277a03a18d5/DEBUG.md#L100)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Shouldn't this be `4.`? We already have `3.`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/939)*

**Comment by puremourning** [comment]
It's fine with me :lgtm:, thought vagrant support was added by @valloric so interested in his thoughts.

my 2p: having working vagrant would be great, but having non-working vagrant is just confusing.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[TESTS.md, line 61 at r1](https://reviewable.io:443/reviews/valloric/ycmd/939#-L6HHrVV7N7ekJfONg_U:-L6IudKUKbB2V4VUQz-h:b-4i8wdr) ([raw file](https://github.com/valloric/ycmd/blob/4cd23d062c9bc6ad9328dd44ab4dd277a03a18d5/TESTS.md#L61)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

I agree. Updated.
</blockquote></details>

What's the reason for removing the module syntax from the examples? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/939#-:-L6IuvQ2GA9TeDWW0Jiy:b-d9ma2j)*

**Comment by puremourning** [comment]
Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/939)*

**Comment by micbou** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[TESTS.md, line 61 at r1](https://reviewable.io:443/reviews/valloric/ycmd/939#-L6HHrVV7N7ekJfONg_U:-L6IwqmScXrRJSfJLe3H:bfxpdg5) ([raw file](https://github.com/valloric/ycmd/blob/4cd23d062c9bc6ad9328dd44ab4dd277a03a18d5/TESTS.md#L61)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

What's the reason for removing the module syntax from the examples? 
</blockquote></details>

The path syntax is more convenient to use because of path completion. I can revert the example to the module syntax but it feels wrong to suggest a less efficient way to run a specific set of tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/939)*

**Comment by puremourning** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[TESTS.md, line 61 at r1](https://reviewable.io:443/reviews/valloric/ycmd/939#-L6HHrVV7N7ekJfONg_U:-L6J-K1K-5nNjdAmrzeu:b299pe6) ([raw file](https://github.com/valloric/ycmd/blob/4cd23d062c9bc6ad9328dd44ab4dd277a03a18d5/TESTS.md#L61)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

The path syntax is more convenient to use because of path completion. I can revert the example to the module syntax but it feels wrong to suggest a less efficient way to run a specific set of tests.
</blockquote></details>

It's fine I was just curious.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/939)*

**Comment by micbou** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[TESTS.md, line 61 at r1](https://reviewable.io:443/reviews/valloric/ycmd/939#-L6HHrVV7N7ekJfONg_U:-L6J30gf_vEoZd9kjacE:bxcbwad) ([raw file](https://github.com/valloric/ycmd/blob/4cd23d062c9bc6ad9328dd44ab4dd277a03a18d5/TESTS.md#L61)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

It's fine I was just curious.
</blockquote></details>

Just swapped the two examples as it feels more natural.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/939)*

**Comment by puremourning** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/939)*

**Comment by Valloric** [comment]
I'm fine with dropping this since it's broken and I agree, that discourages contributions. I'm likely to resurrect it in the future with a working configuration.

:lgtm: from me.

**Comment by micbou** [comment]
@zzbot r=Valloric

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/939#-:-L6OLBJWe0rsryXdyxHa:b50kpk7)*

**Pull request merged**
