### PR TITLE
Support using Python embedded distribution.

### PR DESCRIPTION
**Pull request by abutcher-gh**
See https://docs.python.org/3/using/windows.html#embedded-distribution

In the embedded distribution, the Python standard library is provided as
a zip archive containing pre-compiled and optimized .pyc files.  This
means that looking for 'os.py' to determine the standard library path
doesn't work.

This patch supports locating the standard library path when an embedded
distribution is used.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/786)

### CODE REVIEW

**Comment by Valloric** [comment]
Thanks for the PR!

This will need a test though.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/786#-:-KnlT3exWhfvuQNrNkfi:b-q84539)*

**Comment by micbou** [comment]
Thanks for adding tests.

:lgtm: except minor comments.

---

Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/tests/server_utils_test.py, line 237 at r3](https://reviewable.io:443/reviews/valloric/ycmd/786#-KnnYRtnPub0tOOk6kOv:-KnnYRtnPub0tOOk6kOw:b-l5j1hs) ([raw file](https://github.com/valloric/ycmd/blob/b40b8685eef394f674e457ebc9e51895b5fd4be7/ycmd/tests/server_utils_test.py#L237)):*
> ```Python
>   PathToTestFile( 'python-future', 'another', 'path' ) ] )
> def GetStandardLibraryIndexInSysPath_FindFullStandardLibrary_test( *args ):
>   assert_that( GetStandardLibraryIndexInSysPath(), equal_to( 1 ) )
> ```

It's better to use `True` than `1` for a boolean.

---

*[ycmd/tests/server_utils_test.py, line 246 at r3](https://reviewable.io:443/reviews/valloric/ycmd/786#-KnnYZGjA5Atr3p90-7M:-KnnYZGjA5Atr3p90-7N:benpsw9) ([raw file](https://github.com/valloric/ycmd/blob/b40b8685eef394f674e457ebc9e51895b5fd4be7/ycmd/tests/server_utils_test.py#L246)):*
> ```Python
>   PathToTestFile( 'python-future', 'another', 'path' ) ] )
> def GetStandardLibraryIndexInSysPath_FindEmbeddedStandardLibrary_test( *args ):
>   assert_that( GetStandardLibraryIndexInSysPath(), equal_to( 1 ) )
> ```

Same comment as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/786#-:-KnnXTJKhDpIejiY-N6X:b-sjhsav)*

**Comment by abutcher-gh** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/tests/server_utils_test.py, line 237 at r3](https://reviewable.io:443/reviews/valloric/ycmd/786#-KnnYRtnPub0tOOk6kOv:-KnnjMJ06nKuqMwlbjSq:bnm4dzr) ([raw file](https://github.com/valloric/ycmd/blob/b40b8685eef394f674e457ebc9e51895b5fd4be7/ycmd/tests/server_utils_test.py#L237)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

It's better to use `True` than `1` for a boolean.
</blockquote></details>

GetStandardLibraryIndexInSysPath() is returning an index which the test is asserting has the value 1.  It is not a predicate.

---

*[ycmd/tests/server_utils_test.py, line 246 at r3](https://reviewable.io:443/reviews/valloric/ycmd/786#-KnnYZGjA5Atr3p90-7M:-KnnjfpNlFgWubxIq_Hq:bs4q9op) ([raw file](https://github.com/valloric/ycmd/blob/b40b8685eef394f674e457ebc9e51895b5fd4be7/ycmd/tests/server_utils_test.py#L246)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Same comment as above.
</blockquote></details>

Ditto.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/786)*

**Comment by micbou** [comment]
:lgtm_strong: then.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/tests/server_utils_test.py, line 237 at r3](https://reviewable.io:443/reviews/valloric/ycmd/786#-KnnYRtnPub0tOOk6kOv:-KnnkCDFEBJFw1zGzJLf:by505ml) ([raw file](https://github.com/valloric/ycmd/blob/b40b8685eef394f674e457ebc9e51895b5fd4be7/ycmd/tests/server_utils_test.py#L237)):*
<details><summary><i>Previously, abutcher-gh wrote…</i></summary><blockquote>

GetStandardLibraryIndexInSysPath() is returning an index which the test is asserting has the value 1.  It is not a predicate.
</blockquote></details>

Sorry. I wonder why I was thinking that this function returned a boolean.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/786#-:-KnnkbD211X-PPFxqvYx:b-ouieea)*

**Comment by vheon** [comment]
:lgtm: @zzbot r=micbou

---

Reviewed 1 of 1 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/786#-:-KnoWOTBjLVdIO1tl8Rg:b-1hvkbu)*

**Pull request merged**
