### PR TITLE
[READY] Clean up Boost.Python in BoostParts

### PR DESCRIPTION
**Pull request by bstaletic**
#925 follow-up.
Removes another 188k lines of code from `cpp/BoostParts`.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1000)

### CODE REVIEW

**Comment by micbou** [comment]
:lgtm:

---

Reviewed 2 of 1272 files at r1.
Review status: 2 of 1272 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/1000#-:-LA2uqCK2cdkkLEOvkQ4:bnfp4nl)*

**Comment by puremourning** [comment]
I take is the coverage data is not a worry? I looked at it but as per usual couldn't make any sense of it. :lgtm:

---

Reviewed 1272 of 1272 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/1000#-:-LA4GiYNAj-kLSeS5nYU:b-nh97yb)*

**Comment by bstaletic** [comment]
Once again, Reviewable is completely useless for me with a PR this big.

@puremourning I can't make sense of the coverage as well.
I think codecov just got confused because there were two pushes (one was a force push) in a short time span. I could be wrong though.

**Comment by puremourning** [comment]
@zzbot r+

**Pull request merged**
