### PR TITLE
[READY] Adding vagrant setup for ycmd development

### LINKED ISSUE #273: Create Vagrantfile to ease ramp up and full testing
Testing all ycmd is not an easy to do due to the amount of dependency we have:

- python (with headers and all)
- compiler
- cmake
- Omnisharp
  - mono
- Tern.js
 - node
 - npm
- gocode
- typescript

And I'm sure I'm forgetting something... So for a new contributor who want to add a feature and want to run all the tests a Vagrantfile with all the dependency baked in would be nice.

### PR DESCRIPTION
**Pull request by Valloric**
Should make our lives easier, especially since we'll want to easily switch between Python 2 and 3 for local dev and test running.

Fixes #273.

[Review on Reviewable](https://reviewable.io/reviews/valloric/ycmd/334)

### CODE REVIEW

**Comment by Valloric** [comment]
And _another_ flaky failure, this time JediHTTP timing out. Hm, might be something to do with Travis.

**Comment by vheon** [comment]
We should add that if fixes https://github.com/Valloric/ycmd/issues/273

> And another flaky failure, this time JediHTTP timing out. Hm, might be something to do with Travis.

I really doubt that JediHTTP would have problem to be spawned and to be ready to serve so I suspect that Travis have problem spawning other servers? :confused: 

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Vagrantfile, line 7 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/334#-K9TayfxeaCT_1kpV_ca:-K9TayfxeaCT_1kpV_cb:-1738917435) ([raw file](https://github.com/valloric/ycmd/blob/e514ab01476eb892b084124bc5df43bc77e97dc2/Vagrantfile#L7)):*
I assume that the default method for synchronize is to use the shared folder of Vagrant, am I correct? Then one downside of this is that if for example I'm on OSX then after running the tests I would have the compiled library for ubuntu. How would I overcome this? (Sorry for the comment on a blank like)

---

*[Vagrantfile, line 12 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/334#-K9Ta8VSrlASgLmnYJn7:-K9Ta8VSrlASgLmnYJn8:167437215) ([raw file](https://github.com/valloric/ycmd/blob/e514ab01476eb892b084124bc5df43bc77e97dc2/Vagrantfile#L12)):*
Question: where does this magic come from? :stuck_out_tongue_closed_eyes: 

---

*[Vagrantfile, line 20 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/334#-K9TaHIqiHTFm5qCt9E8:-K9TaHIqiHTFm5qCt9E9:1772923896) ([raw file](https://github.com/valloric/ycmd/blob/e514ab01476eb892b084124bc5df43bc77e97dc2/Vagrantfile#L20)):*
In my local Vagrantfile I used only `1024` for `memory` and a swap file but I think is reasonable for today standards to ask for 2Gb of ram and 2 cpu...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/334#-:-K9T_TSJ4ZcWyj6OcLYC:1929296915)*

**Comment by Valloric** [comment]
Yeah I don't think the issue was with JediHTTP itself, but either Travis or the way we've written our tests.

Added that this fixes #273.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Vagrantfile, line 7 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/334#-K9TayfxeaCT_1kpV_ca:-K9TrYVo9was5T_5WTgj:-579405885) ([raw file](https://github.com/valloric/ycmd/blob/e514ab01476eb892b084124bc5df43bc77e97dc2/Vagrantfile#L7)):*
I had the exact problem today and I realize the easiest fix is to develop in folder that I'm not loading by default in vim. That's it really.

---

*[Vagrantfile, line 12 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/334#-K9Ta8VSrlASgLmnYJn7:-K9Trl4k-0-5ToRDPIWw:-63938843) ([raw file](https://github.com/valloric/ycmd/blob/e514ab01476eb892b084124bc5df43bc77e97dc2/Vagrantfile#L12)):*
Random stackoverflow posts. They didn't go into details on why it worked otherwise I would have linked them here. All I know is that these lines made the VM have the same internet connection speed as the host instead of 10x slower. Apparently it's a common issue.

---

*[Vagrantfile, line 20 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/334#-K9TaHIqiHTFm5qCt9E8:-K9Tt7Vn_NDkVXZZfSuy:1775589054) ([raw file](https://github.com/valloric/ycmd/blob/e514ab01476eb892b084124bc5df43bc77e97dc2/Vagrantfile#L20)):*
I agree.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/334#-:-K9TrMbHWvDsFo1CXt3-:1103501944)*

**Comment by vheon** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Vagrantfile, line 7 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/334#-K9TayfxeaCT_1kpV_ca:-K9TtuKLrzpsrVj6t4AG:-295890209) ([raw file](https://github.com/valloric/ycmd/blob/e514ab01476eb892b084124bc5df43bc77e97dc2/Vagrantfile#L7)):*
I used the `rsync` method on mine, this way the sync can be configured to be only one way and exclude certain file. The downside is that on windows you have to download rsync or use cygwin to install it. But honestly I don't know which is better :confused: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/334)*

**Comment by Valloric** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Vagrantfile, line 7 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/334#-K9TayfxeaCT_1kpV_ca:-K9Uo2OhVutRkFTO2OHx:1467675240) ([raw file](https://github.com/valloric/ycmd/blob/e514ab01476eb892b084124bc5df43bc77e97dc2/Vagrantfile#L7)):*
I'm not sure how you would use rsync here. Either way, seems like overkill. Let's keep things simple, at least for now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/334)*

**Comment by Valloric** [comment]
Note that the Travis failure is caused by flakiness (and this doesn't change any code, so can't really break anything).

---

Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/334#-:-K9VdGdcexbavftu93xE:-999208388)*

**Comment by vheon** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[Vagrantfile, line 7 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/334#-K9TayfxeaCT_1kpV_ca:-K9YWYE_qPnl_8uQN-uR:813065473) ([raw file](https://github.com/valloric/ycmd/blob/e514ab01476eb892b084124bc5df43bc77e97dc2/Vagrantfile#L7)):*
Vagrant has native support for rsync so I had this in my Vagrantfile

```ruby
  config.vm.synced_folder ".", "/home/vagrant/ycmd", type: "rsync",
    # default value but without the "--delete" argument
    # so the guest can keep the libclang archive and builded binaries
    rsync__args: [ "--verbose", "--archive", "-z", "--copy-links" ],
    rsync__exclude: [ ".git/", "ycm_core.so", "ycm_client_support.so", "libclang.dylib" ]
```

Naturally it comes with a downside which is that you have to `vagrant rsync` before re-running the test to sync the code. But I agree that the default sync folder is straightforward and less complex.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/334#-:-K9YXHM3NXGXeOozvk_l:980077423)*

**Comment by Valloric** [comment]
Thanks for the review! 

@homu r+

**Comment by puremourning** [comment]
flake. @homu retry

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/334#-:-K9Yuz0vsDG76i_4EEdU:-1288271755)*

**Pull request merged**
