### PR TITLE
[READY] Create temporary files in a secure manner

### PR DESCRIPTION
**Pull request by micbou**
Fixes Valloric/YouCompleteMe#2395.

---

This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/629)

### CODE REVIEW

**Comment by vheon** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/629)*

**Comment by Valloric** [comment]
:lgtm:

Thanks for doing this!

Does this not resolve the issue that was filed for this? If so, shouldn't it have "fixes #number" in the description?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/629#-:-KU_2PukcAz637eVFl32:b9dzyw3)*

**Comment by micbou** [comment]
Sorry, I was away a few days. I updated the commit message and the description.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/629#-:-KUlCV_vMhTS8Qgu--q0:bnzz3ll)*

**Comment by vheon** [comment]
:lgtm: @homu r=Valloric

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/629#-:-KUsOsMSd8xiL9GHm-ve:b9nem37)*

**Pull request merged**
