### PR TITLE
Add GetReferences for C-family languages

### PR DESCRIPTION
**Pull request by ddcien**
I am using YCM for embedded software development on Linux platform with C/CPP language.
So I add "GetReference" function for C-famliy languages.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/647)

### CODE REVIEW

**Comment by vheon** [comment]
Thanks for the PR! Anyway we can't accept this as it is: there are no unit tests, there are style issue (like missing spaces inside `(...)`), the tests are not passing and I see at least a `TODO` in there. Can you mark this as `[WIP]` in the meantime?

**Comment by ddcien** [comment]
Hi vheon, I have a new commit that fixed the style problem, and remove the "TODO"s, casue they are really not necessary.

**Comment by vheon** [comment]
I did a quick review, but more importantly:

- Tests are still not passing.
- You need to add unit test for the new code.

---

Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[cpp/ycm/ClangCompleter/ClangCompleter.cpp, line 177 at r2](https://reviewable.io:443/reviews/valloric/ycmd/647#-KWrKR7pppCJuQNNS5yK:-KWrKR7qDlFoOQSY32g8:b-8jm2a7) ([raw file](https://github.com/valloric/ycmd/blob/6159ceb9168c20d6e81222e78fe4aba7821f6202/cpp/ycm/ClangCompleter/ClangCompleter.cpp#L177)):*
> ```cpp
> 
>   if ( !unit ) {
>     return std::vector< Location >();;
> ```

why the double `;` here?

---

*[cpp/ycm/ClangCompleter/ClangCompleter.cpp, line 180 at r2](https://reviewable.io:443/reviews/valloric/ycmd/647#-KWrKW-lk3NoLLYg4O_Q:-KWrKW-lk3NoLLYg4O_R:b-iqkr3u) ([raw file](https://github.com/valloric/ycmd/blob/6159ceb9168c20d6e81222e78fe4aba7821f6202/cpp/ycm/ClangCompleter/ClangCompleter.cpp#L180)):*
> ```cpp
>   }
> 
>   return unit->GetReferencesLocationList( line, column, unsaved_files, reparse );
> ```

This like looks like is over the 80 column.

---

*[cpp/ycm/ClangCompleter/TranslationUnit.cpp, line 245 at r2](https://reviewable.io:443/reviews/valloric/ycmd/647#-KWrMDh_w1qffn8xpkqk:-KWrMDh_w1qffn8xpkql:b-racl8x) ([raw file](https://github.com/valloric/ycmd/blob/6159ceb9168c20d6e81222e78fe4aba7821f6202/cpp/ycm/ClangCompleter/TranslationUnit.cpp#L245)):*
> ```cpp
> }
> 
> static enum CXVisitorResult __visitor(void *context, CXCursor cursor, CXSourceRange range) {
> ```

This line is over the 80 column. Also missing spaces inside the parenthesis.

---

*[cpp/ycm/ClangCompleter/TranslationUnit.cpp, line 246 at r2](https://reviewable.io:443/reviews/valloric/ycmd/647#-KWrMMm0EswFUXYKI9n7:-KWrMMm0EswFUXYKI9n8:b4oqve0) ([raw file](https://github.com/valloric/ycmd/blob/6159ceb9168c20d6e81222e78fe4aba7821f6202/cpp/ycm/ClangCompleter/TranslationUnit.cpp#L246)):*
> ```cpp
> 
> static enum CXVisitorResult __visitor(void *context, CXCursor cursor, CXSourceRange range) {
>   // Ignore the range parameter
> ```

Is there a specific reason *why* we ignore the range parameter? If so I think it should be in the comment.

---

*[cpp/ycm/ClangCompleter/TranslationUnit.cpp, line 247 at r2](https://reviewable.io:443/reviews/valloric/ycmd/647#-KWrM_K-CTN8BIoOt9GQ:-KWrM_K-CTN8BIoOt9GR:bfeo5oq) ([raw file](https://github.com/valloric/ycmd/blob/6159ceb9168c20d6e81222e78fe4aba7821f6202/cpp/ycm/ClangCompleter/TranslationUnit.cpp#L247)):*
> ```cpp
> static enum CXVisitorResult __visitor(void *context, CXCursor cursor, CXSourceRange range) {
>   // Ignore the range parameter
>   (void)range;
> ```

I guess you're doing that to avoid warning from the compiler about unused parameter, if so I would prefer to comment the variable name in the parameter like:

```cpp
static enum CXVisitorResult __visitor( void *context, CXCursor cursor, CXSourceRange /*range*/ )
```

I don't know how the others feels about this.

---

*[cpp/ycm/ClangCompleter/TranslationUnit.cpp, line 282 at r2](https://reviewable.io:443/reviews/valloric/ycmd/647#-KWrNgHUhKloEFGMJ4Kh:-KWrNgHUhKloEFGMJ4Ki:b-8qu9ud) ([raw file](https://github.com/valloric/ycmd/blob/6159ceb9168c20d6e81222e78fe4aba7821f6202/cpp/ycm/ClangCompleter/TranslationUnit.cpp#L282)):*
> ```cpp
>   };
> 
>   // Ignore the result here
> ```

Why are we ignoring the result?

---

*[examples/example_client.py, line 172 at r2](https://reviewable.io:443/reviews/valloric/ycmd/647#-KWrNy3SyKYwO8lFiHeX:-KWrNy3SyKYwO8lFiHeY:b-5ct7b6) ([raw file](https://github.com/valloric/ycmd/blob/6159ceb9168c20d6e81222e78fe4aba7821f6202/examples/example_client.py#L172)):*
> ```Python
> 
>   def SendGetReferencesRequest( self,
>                        test_filename,
> ```

align the rest of the parameters to `self`

---

*[examples/example_client.py, line 177 at r2](https://reviewable.io:443/reviews/valloric/ycmd/647#-KWrO1JJ64lKcmWBKURx:-KWrO1JJ64lKcmWBKURy:bu3mx8u) ([raw file](https://github.com/valloric/ycmd/blob/6159ceb9168c20d6e81222e78fe4aba7821f6202/examples/example_client.py#L177)):*
> ```Python
>                        column_num ):
>     request_json = BuildRequestData( test_filename = test_filename,
>                                      command_arguments = ['GetReferences'],
> ```

missing spaces inside `[]`

---

*[examples/example_client.py, line 473 at r2](https://reviewable.io:443/reviews/valloric/ycmd/647#-KWrO7h6Oss_MwdTGvkB:-KWrO7h6Oss_MwdTGvkC:b5u6i8y) ([raw file](https://github.com/valloric/ycmd/blob/6159ceb9168c20d6e81222e78fe4aba7821f6202/examples/example_client.py#L473)):*
> ```Python
> 
>   server.SendGetReferencesRequest( test_filename = 'some_cpp.cpp',
>                           filetype = 'cpp',
> ```

align the rest of the parameters to `test_filename`

---

*[ycmd/completers/cpp/clang_completer.py, line 192 at r2](https://reviewable.io:443/reviews/valloric/ycmd/647#-KWrONBjaT3poAEE-NYz:-KWrONBjaT3poAEE-NZ-:b-pjhm29) ([raw file](https://github.com/valloric/ycmd/blob/6159ceb9168c20d6e81222e78fe4aba7821f6202/ycmd/completers/cpp/clang_completer.py#L192)):*
> ```Python
>     return _ResponseForLocation( location )
> 
>   def _GetReferences( self, request_data ):
> ```

I'll leave a single comment here but you're missing the space inside all the parenthesis here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/647#-:-KWrOy7sb_rgZqHe2dEw:bs2vqel)*

**Comment by vheon** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[cpp/ycm/ClangCompleter/TranslationUnit.cpp, line 248 at r2](https://reviewable.io:443/reviews/valloric/ycmd/647#-KWrdpyRXv0eJJeSvIac:-KWrdpySNtKDT3Q-1nQo:b-ynch0x) ([raw file](https://github.com/valloric/ycmd/blob/6159ceb9168c20d6e81222e78fe4aba7821f6202/cpp/ycm/ClangCompleter/TranslationUnit.cpp#L248)):*
> ```cpp
>   // Ignore the range parameter
>   (void)range;
>   std::vector< Location > *locations = (std::vector< Location > *)context;
> ```

prefer a c++ kind of cast, I'm not sure if a `static_cast` will work here but a `reinterpret_cast` for sure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/647)*

**Comment by puremourning** [comment]
TBH I'm not sure this is sufficiently effective to be useful. Users will expect this to work across TUs and do all sorts of stuff like rtags. This has come up multiple times before and (unless I'm missing something) this isn't really solving the whole problem,  it creating a weak and difficult to define new behaviour.

**Comment by vheon** [comment]
> Users will expect this to work across TUs and do all sorts of stuff like rtags

I didn't thought of that 😭

**Comment by Valloric** [comment]
Agreed with @puremourning, this can't currently work the way users are going to expect it to work. What we need is to build a full codebase index with libclang. That's possible, but a massive amount of work. Also, it would basically be a re-implementation of [rtags](https://github.com/Andersbakken/rtags) or something very similar to it.

@ddcien Thank you for your PR and enthusiasm, but this feature can't be implemented this way. As such, we'll close this.

**Pull request closed without merging**
