### PR TITLE
[READY] Search the Python library in lib64 folder in addition to lib

### PR DESCRIPTION
**Pull request by micbou**
On some distributions, the Python dynamic library can be found in the `lib64` folder of the base Python installation instead of `lib`. These distributions may not patch the `get_python_lib` function to return the right folder and thus our build script is unable to find the Python library. To fix that, we reproduce what the `get_python_lib` function does except that we look for both directories: `lib` and `lib64`.

Closes #747.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/754)

### CODE REVIEW

**Comment by bstaletic** [comment]
:lgtm: 

The codecov report here has the exact same problem as in #751.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/754#-:-KjnTUclHhufv4Hraj8n:b-a30sdr)*

**Comment by micbou** [comment]
Yes, definitely a codecov issue. I've looked at [the uploaded coverage files](https://codecov.io/gh/Valloric/ycmd/commit/ff770b4f47e793a7c7e839f41861e564ef6a7caf/build) and the ones from AppVeyor contain the lines in `ycmd/utils.py` that codecov reports as not covered:
```xml
<class branch-rate="0" complexity="0" filename="utils.py" line-rate="0.8131" name="utils.py">
	<methods/>
	<lines>
                 ...
		<line hits="1" number="218"/>
		<line hits="1" number="219"/>
		...						
	</lines>
</class>
```
				

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/754#-:-KjnUaZlOVNxHmIAsI-A:b-uyd3v)*

**Comment by bstaletic** [comment]
> Yes, definitely a codecov issue.

That proves it. Have you already reported the problem on codecov support gitter? If not, I could do it.

**Comment by micbou** [comment]
> That proves it. Have you already reported the problem on codecov support gitter? If not, I could do it.

No, I didn't.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/754#-:-KjnYL51PXSlC4etxZTN:b-yh5md3)*

**Comment by bstaletic** [comment]
@micbou What about the `go_completer.py`? That is not reported in those files as covered. But for as far as I can remember the coverage of go completer remained the same. What happened?

Any way, I reported the issue to codecov's gitter, so we'll see what's up with this soon.

**Comment by Valloric** [comment]
:lgtm:

Thanks for the PR!

**Comment by bstaletic** [comment]
This has `[READY]` tag and all relevant discussions are resolved.

@homu r+

**Comment by Valloric** [comment]
I'm trying to set up a custom instance of homu so I'm asking people to abstain from merging this PR; I'll use it to test out the new bot once it's ready.

**Comment by Valloric** [comment]
This isn't likely to work, but let's give it a shot:

@zzbot r+

**Comment by Valloric** [comment]
@zzbot retry

**Comment by Valloric** [comment]
@zzbot retry

**Comment by Valloric** [comment]
@zzbot retry

**Comment by Valloric** [comment]
Once more!

@zzbot retry

**Comment by Valloric** [comment]
@zzbot retry

**Comment by Valloric** [comment]
@zzbot retry

**Comment by Valloric** [comment]
@zzbot retry

**Comment by Valloric** [comment]
@homu retry

**Pull request merged**
