### PR TITLE
New completion format

### PR DESCRIPTION
**Pull request by Qusic**
See also https://github.com/Valloric/ycmd/pull/124

I have removed all unnecessary changes and it looks much cleaner now.

> Completion objects have these properties:
* `typed_string`<br />Text that users would be expected to type to get this completion result. 
* `display_string`<br />Text that is displayed for users.
* `completion_chunks`<br />An array of completion chunk objects.
* `result_type`<br />Such as 'int', 'void', 'unsigned long'.
* `kind`<br />Such as 'function', 'class', 'variable'.
* `doc_string`<br />Doc string.
* `extra_data`<br />An object contains completer-specific data.

> Completion chunk objects have these properties:
* `chunk`<br />String value of the chunk.
* `placeholder`<br />Bool value that indicates whether this chunk should be inserted directly as a literal string or as a placeholder for users to insert code.

> Two examples are below.
```
{
  "typed_string": "vector",
  "display_string": "vector<typename _Tp, typename _Alloc>",
  "kind": "CLASS",
  "completion_chunks": [
    { "chunk": "vector<", "placeholder": false },
    { "chunk": "typename _Tp", "placeholder": true },
    { "chunk": ", ", "placeholder": false },
    { "chunk": "typename _Alloc", "placeholder": true },
    { "chunk": ">", "placeholder": false }
  ]
}
{
  "typed_string": "withArg2:withArg3:",
  "display_string": "test:withArg2:(int) withArg3:(int)",
  "result_type": "void",
  "kind": "FUNCTION",
  "completion_chunks": [
    { "chunk": "withArg2:", "placeholder": false },
    { "chunk": "(int)", "placeholder": true },
    { "chunk": " withArg3:", "placeholder": false },
    { "chunk": "(int)", "placeholder": true }
  ]
}
```

(CLA signed)

### CODE REVIEW

**Comment by Valloric** [comment]
Either I'm missing something, or this PR is still mixing code refactoring with changing the API. It's also adding the completion chunks section. (Feel free to elaborate if I really am misunderstanding things here.)

Here's an idea of how to structure the changes you want to make, in a reasonable order:

1. PR for adding the completion_chunks section. This PR does that and only that; no other unrelated changes, only the minimum necessary to implement completion_chunks (with tests).
2. PR for changing the API. No extra refactoring, _just_ the API changes.
3. PR for the refactoring.

**Comment by Qusic** [comment]
As for the third one, refactoring, the problem is these two functions:
* [CompletionData::CompletionData(const CXCompletionResult &completion_result)](https://github.com/Valloric/ycmd/blob/master/cpp/ycm/ClangCompleter/CompletionData.cpp#L177)
* [void CompletionData::ExtractDataFromChunk(...)](https://github.com/Valloric/ycmd/blob/master/cpp/ycm/ClangCompleter/CompletionData.cpp#L219)

I re-wrote them because
* they didn't process all kinds of chunks
* they were somewhat obscure

The proposed implementation to extract data from `CXCompletionString` is much shorter, simpler and easier to understand.
Completion chunks, display string and other completion data are all done at the same time and I have no way to split them up.
The related changes are all in these three files:
* cpp/ycm/ClangCompleter/CompletionData.h
* cpp/ycm/ClangCompleter/CompletionData.cpp
* cpp/ycm/ClangCompleter/ClangHelpers.cpp

----

Meanwhile, API changes accordingly and there are actually more than renaming. It doesn't make much sense to do renaming in a separate PR.

```
kind            ==> kind (unchanged)
extra_data      ==> extra_data (unchanged)
extra_menu_info ==> result_type (renamed)
menu_text       ==> display_string (renamed)
insertion_text  ==> (deleted)
detailed_info   ==> (deleted)
                ==> typed_string (added)
                ==> completion_chunks (added)
                ==> doc_string (added)
```

So you will see changes related to `BuildCompletionChunk` `BuildCompletionData`, and `BuildSimpleCompletionData`.
* ycmd/responses.py

`BuildCompletionChunk` is just like its name implies.
`BuildCompletionData` is changed to receive array of chunks as arguments and `BuildSimpleCompletionData` receives single non-placeholder string to handle simple occasions conveniently.

Now it is done.

----

The following changes are all to adopt the new names, to get code compiling or to get tests passing. Nothing important.

* cpp/ycm/ycm_core.cpp
* cpp/ycm/CandidateRepository.cpp
* cpp/ycm/tests/ClangCompleter/ClangCompleter_test.cpp
* ycmd/completers/completer.py
* ycmd/completers/all/identifier_completer.py
* ycmd/completers/cpp/clang_completer.py
* ycmd/completers/cs/cs_completer.py
* ycmd/completers/general/filename_completer.py
* ycmd/completers/general/ultisnips_completer.py
* ycmd/completers/go/gocode_completer.py
* ycmd/completers/python/jedi_completer.py
* ycmd/completers/general/tests/filename_completer_test.py
* ycmd/completers/go/tests/gocode_completer_test.py
* ycmd/tests/get_completions_test.py

**Comment by Valloric** [comment]
@Qusic It seems like you have solid reasons for wanting to have the refactoring done before implementing the completion chunk stuff. Could you then send an PR with just the refactoring changes first? Those can then be reviewed and merged in before any of the API work that would have to depend on that.

If putting that together is truly the only thing that makes sense, then do that. But I can also see what appear to be logic changes in your PR (like removing the deduplication in `ToCompletionDataVector`) and it's hard for me to tease out which changes are necessary and which aren't. Note that while I might be OK with changing the API of ycmd and then updating all the clients, I am _not_ ok with changing the user experience of YCM (like what removing the deduplication seems to be doing, at a glance) without an _exceptionally_ good reason.

So we can add more stuff to the response and change the API between the client and server, but any change to user-facing functionality is to be avoided (without good reasoning).

In general, it's much easier to review PRs and analyze the potential fallout of them _the smaller they are_. So I again encourage you to split stuff out as much as you can if at all possible. Since the changes you want to make are extensive, if this blows up in some way, figuring out what went wrong will too benefit from smaller PRs that will need to be re-reviewed. 

So how are you planning to proceed?

**Comment by Qusic** [comment]
I am quite free these days and want to continue working on this.

One question about removing the deduplication is which one to keep. Is it the one without any optional parameters or the one with all optional parameters?

I am going to split it into three PRs in this order:
1. (c) (d) (f)
2. (e) (g)
3. Refactor clang completer and adopt the `completion_chunks` field

    (a) kind            ==> kind (unchanged)
    (b) extra_data      ==> extra_data (unchanged)
    (c) extra_menu_info ==> result_type (renamed)
    (d) menu_text       ==> display_string (renamed)
    (e) insertion_text  ==> completion_chunks (converted)
    (f) detailed_info   ==> doc_string (merged)
    (g)                 ==> typed_string (added)

**Comment by vheon** [comment]
> I am going to split it into three PRs in this order:
1. (c) (d) (f)
2. (e) (g)
3. Refactor clang completer and adopt the completion_chunks field

Look like a good plan :+1:

**Pull request closed without merging**
