### PR TITLE
[READY] Automatically include clang includes on OS X

### PR DESCRIPTION
**Pull request by puremourning**
OS X (by default) has 2 ways to set up development environment: Xcode.app and
installation of the CommandLineTools. As previously known, libclang does not
automatically add these system include paths as clang's own driver does.
Previously, ycmd would add the Xcode.app c++ include directories. This change
ensures that we add the system include paths when only the CommandLineTools are
installed (they are significantly lighter weight than xcode and installed
automatically when first attempting to run things like clang).

Additionally, around Xcode 7, additional include paths became required which are
located in versioned directories. These headers are clang-specific headers (such
as stddef.h). This change includes a mechanism to find such includes by
selecting the highest versioned set of headers that can be detected.

Fixes: https://github.com/Valloric/YouCompleteMe/issues/1992
Fixes: https://github.com/Valloric/ycmd/issues/304
Fixes: https://github.com/Valloric/ycmd/issues/254

Replaces: https://github.com/Valloric/ycmd/pull/385

I've tested this with Xcode 7 & Xcode 6 with and without the Command Line Tools. Admittedly I haven't tested the cartesian product of those configurations, but I'm fairly confident that this doesn't introduce a regression and does select a working set of includes on OS X. It shouldn't need fiddling after further changes by Apple either (hopefully!).

It's also worth noting that I believe a future change (waiting on upstream) by @d0k will make this hacking redundant, so we can remove it (yay!).

@indianajohn apologies, I didn't mean to clobber your work (I certainly used it for inspiration!), but this issue has been bugging me so I wanted to fix it anyway. Thanks for your work on it though!

(off topic note: it seems that the PR template is clobbered by the commit message when the PR is a single commit. FWIW - I'm aware of contributing guide/code of conduct, etc. :))

[Review on Reviewable](https://reviewable.io/reviews/valloric/ycmd/415)

### CODE REVIEW

**Comment by Valloric** [comment]
:lgtm: with minor comments. We'll need to bump the ycmd version used in YCM as well sooner rather than later since I'm guessing this a major issue.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/cpp/flags.py, line 355 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/415#-KC7il_t7XFjCGKRC8-6:-KC7il_t7XFjCGKRC8-7:-116018076) ([raw file](https://github.com/valloric/ycmd/blob/01bf31b8396d092fd66c1c259961fba299718f0c/ycmd/completers/cpp/flags.py#L355)):*
I'm not sure I'm a big fan of having a constant conditionally declared. I'd rather have it be an empty list on other systems. I know this is only used `OnMac()` as well, but still seems fragile.

---

*[ycmd/completers/cpp/flags.py, line 362 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/415#-KC7iNuShENPhmbLKC6U:-KC7iNuShENPhmbLKC6V:1752334560) ([raw file](https://github.com/valloric/ycmd/blob/01bf31b8396d092fd66c1c259961fba299718f0c/ycmd/completers/cpp/flags.py#L362)):*
Instead of using `\`, just wrap the expression in parens. Far more reliable.whole

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/415#-:-KC7hSvUbZbpClAYwz-9:1991712437)*

**Comment by puremourning** [comment]
Thanks for the review :)

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/cpp/flags.py, line 355 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/415#-KC7il_t7XFjCGKRC8-6:-KC7jWv5XdkBlaSh1dYs:782479765) ([raw file](https://github.com/valloric/ycmd/blob/01bf31b8396d092fd66c1c259961fba299718f0c/ycmd/completers/cpp/flags.py#L355)):*
Yes good point. I actually had it this way before and probably lost it when tidying up.

---

*[ycmd/completers/cpp/flags.py, line 362 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/415#-KC7iNuShENPhmbLKC6U:-KC7jalcLL-q46UHYUD_:-1171225672) ([raw file](https://github.com/valloric/ycmd/blob/01bf31b8396d092fd66c1c259961fba299718f0c/ycmd/completers/cpp/flags.py#L362)):*
I tried that and it complained that the type of `MAC_INCLUDE_PATHS` was `tuple` not `list` which is how we need it. Probably just me running out of talent. I'll see if I can make it better ;)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/415#-:-KC7jnHT0n3-BRC9Iitx:1382864255)*

**Comment by micbou** [comment]
I can't test it but this looks fine.

> (off topic note: it seems that the PR template is clobbered by the commit message when the PR is a single commit. FWIW - I'm aware of contributing guide/code of conduct, etc. :))

There is no template for the `ycmd` repository, not yet.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[ycmd/completers/cpp/flags.py, line 26 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/415#-KC7fyr61qbuRJylCOe8:-KC7fyr7QRiPfr8jz1yn:-350437375) ([raw file](https://github.com/valloric/ycmd/blob/01bf31b8396d092fd66c1c259961fba299718f0c/ycmd/completers/cpp/flags.py#L26)):*
Unneeded blank line.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/415#-:-KC7fsU8yQ_s7vm-JrzR:-230140972)*

**Comment by puremourning** [comment]
Good point on the template. ^_^

Fixed.

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[ycmd/completers/cpp/flags.py, line 26 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/415#-KC7fyr61qbuRJylCOe8:-KC7lxEyHYFNuYvcY--W:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/01bf31b8396d092fd66c1c259961fba299718f0c/ycmd/completers/cpp/flags.py#L26)):*
Done.

---

*[ycmd/completers/cpp/flags.py, line 355 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/415#-KC7il_t7XFjCGKRC8-6:-KC7lP4a7Zz16xP_HXTK:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/01bf31b8396d092fd66c1c259961fba299718f0c/ycmd/completers/cpp/flags.py#L355)):*
Done.

---

*[ycmd/completers/cpp/flags.py, line 362 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/415#-KC7iNuShENPhmbLKC6U:-KC7lH3Dzfltqplo7L6-:-1454072775) ([raw file](https://github.com/valloric/ycmd/blob/01bf31b8396d092fd66c1c259961fba299718f0c/ycmd/completers/cpp/flags.py#L362)):*
OK, well yes of course `(` and `)` work fine. I must have blamed them unfairly and had a different bug. Fixed!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/415#-:-KC7lzypjYmvy5ODVd1R:1453496777)*

**Comment by Valloric** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/415)*

**Comment by puremourning** [comment]
OK tests don't work on windows. I will fix

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/415#-:-KC8-xXiiyn5nGGnbn0F:-952314893)*

**Comment by Valloric** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/415#-:-KC86VKjvcmBzJNWCPGQ:-1868698381)*

**Comment by micbou** [comment]
:lgtm:

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/415#-:-KC86zMqUyAaPdpFXceF:1417088721)*

**Comment by micbou** [comment]
:lgtm_cancel:

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/415#-:-KC870h9rfIfLnV2iyEP:1263137098)*

**Comment by puremourning** [comment]
It may be the software engineering equivalent of a Brummie Screwdriver, but I decided to just run the new tests on OS X.

---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/415#-:-KC8D_mXwSHU9206STHw:-1878544393)*

**Comment by puremourning** [comment]
OK yes tests all fixed... ready to go ?

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/415#-:-KC8Wa1lWecZa1pcXcUc:-881346337)*

**Comment by micbou** [comment]
:lgtm:

@homu r+

---

Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/415#-:-KC8drmCiI49Z9gcCs-D:187772251)*

**Pull request merged**
