### PR TITLE
[READY] Update Boost to 1.66.0

### PR DESCRIPTION
**Pull request by micbou**
This version of Boost fixes the issue where `ycm_core` cannot be imported when compiling with the `-fvisibility=hidden` flag. With this new version, downgrading Boost in PR https://github.com/Valloric/ycmd/pull/848 won't be needed.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/887)

### CODE REVIEW

**Comment by bstaletic** [comment]
:lgtm:

As for #848, is it okay to just drop the commit that downgrades boost and then force push thee branch?
Last time I foce pushed, github got confused and closed the pull request.

---

Reviewed 167 of 167 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/887#-:-L0fNAgcrN8tbvcwC9rH:bocq8t4)*

**Comment by micbou** [comment]
> As for #848, is it okay to just drop the commit that downgrades boost and then force push thee branch?

Yes, that should work.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/887#-:-L0fP5yRA_8aK5r17Nv6:b-u3p3fw)*

**Comment by puremourning** [comment]
:lgtm: @zzbot r+

Thanks!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/887#-:-L0upUrB1HrCL-3FxVU4:bdx9jmd)*

**Comment by puremourning** [comment]
Reviewed 167 of 167 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/887)*

**Pull request merged**
