### PR TITLE
Add include flag '-idirafter' and tests.

### PR DESCRIPTION
**Pull request by ekratzer**
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/877)

### CODE REVIEW

**Comment by bstaletic** [comment]
:lgtm:
Thanks for the pull request.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/877#-:-KzZsf93HlftxEhSmk_C:bzdgxqu)*

**Comment by micbou** [comment]
I don't think adding `-idirafter` to the `MakeRelativePathsInFlagsAbsolute` tests was necessary but it doesn't hurt so :lgtm:

@zzbot r+

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/877#-:-Kz_2ZsCW_WgIBvMl6qe:b-1aragz)*

**Comment by bstaletic** [comment]
Let's try this again.

@zzbot retry

**Comment by bstaletic** [comment]
I'm starting to think that zzbot doesn't like me.

@zzbot retry

**Pull request merged**
