### PR TITLE
[READY] Update boost to 1.68

### PR DESCRIPTION
**Pull request by bstaletic**
Nothing much to see here.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1077)

### CODE REVIEW

**Comment by Valloric** [comment]
:lgtm:

Thanks for the PR!

**Comment by Valloric** [comment]
@zzbot r+

**Comment by bstaletic** [comment]
Right... zzbot is broken when called from reviewable.

@zzbot retry

**Comment by micbou** [comment]
@zzbot retry

**Pull request merged**
