### PR TITLE
[READY] Update Clang to 5.0.0

### PR DESCRIPTION
**Pull request by micbou**
[Clang 5.0.0 has just been released](http://lists.llvm.org/pipermail/llvm-announce/2017-September/000075.html). It's an important release for Windows as it fixes the really common assertion failure:
```
Program: ...\local\YouCompleteMe\third_party\ycmd\libclang.dll
File: C:\src\llvm_package_4.0.1\llvm\tools.../SourceLocation.h
Line: 319

Expression: SrcMgr == Loc.SrcMgr && "Loc comes from another SourceManager!"
```
Here's a trivial example that was raising the assertion:
```c++
#include <locale>
```
with the `.ycm_extra_conf.py` file:
```python
def FlagsForFile( filename ):
  return { 'flags': [ '-Dtest' ] }
```
See https://github.com/Valloric/YouCompleteMe/issues/2758 for another example.

This version also improves the following aspects:
 - the parameters default value is now displayed in the function signature;
 - the fully qualified name is returned when the cursor is on a type.

The `MemberFunctionsWithDefaults` and `GetType` tests were updated because of these improvements.

This PR will be ready once Clang prebuilt binaries for Linux are available (we can't use the SuSE ones; they depend on `libc++`).

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/832)

### CODE REVIEW

**Comment by Valloric** [comment]
Looking forward to this one! :)

**Comment by puremourning** [comment]
:lgtm: once the bins are available and assuming thntsts are all good :)

---

Reviewed 1 of 41 files at r1.
Review status: 1 of 41 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/832#-:-KtTRw4gxBIoVy-917xL:b8rtze1)*

**Comment by bstaletic** [comment]
Precompiled binaries are missing only for linux as of right now.

---

Review status: 1 of 41 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[cpp/ycm/CMakeLists.txt, line 102 at r1](https://reviewable.io:443/reviews/valloric/ycmd/832#-KtVu1esFZN498VUBJns:-KtVu1esFZN498VUBJnt:b1j292n) ([raw file](https://github.com/valloric/ycmd/blob/12462afc66f767737dbc4a9b74933d957bc2653d/cpp/ycm/CMakeLists.txt#L102)):*
> ```CMake
>     message( "Downloading Clang ${CLANG_VERSION}" )
> 
>     set( CLANG_URL "http://releases.llvm.org/${CLANG_VERSION}" )
> ```

Is there a reason for URL change? I tried both and 5.0.0 is on both URLs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/832#-:-KtVuCr6srUWGMjrkEh9:b51ebw8)*

**Comment by micbou** [comment]
Reviewed 4 of 41 files at r1.
Review status: 4 of 41 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[cpp/ycm/CMakeLists.txt, line 102 at r1](https://reviewable.io:443/reviews/valloric/ycmd/832#-KtVu1esFZN498VUBJns:-KtW0bf2zDg32K1d4G67:bmsrai9) ([raw file](https://github.com/valloric/ycmd/blob/12462afc66f767737dbc4a9b74933d957bc2653d/cpp/ycm/CMakeLists.txt#L102)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Is there a reason for URL change? I tried both and 5.0.0 is on both URLs.
</blockquote></details>

`llmv.org/releases` redirects to `releases.llvm.org`. It's preferable to use the real URL in case the redirection is removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/832)*

**Comment by micbou** [comment]
Prebuilt binaries are available for Linux. Tests are passing. This is ready.

---

Reviewed 1 of 1 files at r2.
Review status: 4 of 41 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/832#-:-KtcQ3Cl8RTfv6PZgg4U:b9lniz0)*

**Comment by vheon** [comment]
:lgtm: @zzbot r=puremourning 

---

Reviewed 1 of 41 files at r1.
Review status: 4 of 41 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/832#-:-Ktccjb5p8rfhfzGlLUc:b-52cvgg)*

**Pull request merged**
