### PR TITLE
 scheme identifier 

### PR DESCRIPTION
**Pull request by jnhe**
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/964)

### CODE REVIEW

**Comment by bstaletic** [comment]
Codecov is talking nonsense again...

@jnhe You can just push a new commit to address the review comments.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ycmd/identifier_utils.py, line 159 at r1](https://reviewable.io:443/reviews/valloric/ycmd/964#-L81nWh3k24w1__6twZp:-L81nWh4X3Aey8CAvFDp:bj6jygg) ([raw file](https://github.com/valloric/ycmd/blob/fbf2286f044f1f6a07dbabc8a04f39af0e61fee6/ycmd/identifier_utils.py#L159)):*
> ```Python
>     # eg. λ (U+03BB) is vailed identifier
>     'scheme': re.compile(r"\+|\-|\.\.\.|"
>                          r"(?:->|(:?\\x[0-9A-Fa-f]+;|[!$%&*/:<=>?~_^A-Za-z]))"
> ```

@micbou Should the final `A-Za-z` in this line be `\w` too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/964#-:-L81nspE16yxdff9VwVu:b-lqmq5d)*

**Comment by micbou** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ycmd/identifier_utils.py, line 159 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/964#-L81nWh3k24w1__6twZp:-L82DvcBBWc-pI8yJzrk:bvqr3vk) ([raw file](https://github.com/valloric/ycmd/blob/fbf2286f044f1f6a07dbabc8a04f39af0e61fee6/ycmd/identifier_utils.py#L159)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

@micbou Should the final `A-Za-z` in this line be `\w` too?
</blockquote></details>

No because `\w` includes numbers. We should use the same pattern as the one in the default identifier regex: `[^\W\d]` to only match letters and the underscore. This line could be rewritten as:
```python
r"(?:->|(:?\\x[0-9A-Fa-f]+;|[!$%&*/:<=>?~^]|[^\W\d]))"
```
It's not perfect (mathematical symbols and some punctuation characters won't be matched) but it's still an improvement over the current regex.

---

*[ycmd/identifier_utils.py, line 160 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/964#-L82D_IG3FmPpjcwEgho:-L82D_IG3FmPpjcwEghp:b-w9z4z1) ([raw file](https://github.com/valloric/ycmd/blob/fbf2286f044f1f6a07dbabc8a04f39af0e61fee6/ycmd/identifier_utils.py#L160)):*
> ```Python
>     'scheme': re.compile(r"\+|\-|\.\.\.|"
>                          r"(?:->|(:?\\x[0-9A-Fa-f]+;|[!$%&*/:<=>?~_^A-Za-z]))"
>                          r"(?:\\x[0-9A-Fa-f]+;|[-+.@!$%&*/:<=>?~_^\d\w])*",
> ```

`\w` already includes `\d` and `_` so the last part could be replaced with `[-+.@!$%&*/:<=>?~^\w]`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/964)*

**Comment by micbou** [comment]
Looks good. Could you squash the commits into one?

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[ycmd/identifier_utils.py, line 157 at r2](https://beta.reviewable.io/reviews/valloric/ycmd/964#-L8NY8M402RxEr6fzHMw:-L8NY8M402RxEr6fzHMx:b-7c0ek2) ([raw file](https://github.com/valloric/ycmd/blob/4562243000bfde73281d60591d911f15f9a79496/ycmd/identifier_utils.py#L157)):*
> ```Python
>     # 127 and whose category is Lu, Ll, Lt, Lm, Lo, Mn,
>     # Nl, No, Pd, Pc, Po, Sc, Sm, Sk, So, or Co⟩
>     # eg. λ (U+03BB) is vailed identifier
> ```

I suppose we can remove the `TODO`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/964#-:-L8NYIxMErAPQPxVgLEc:bjokxdx)*

**Comment by puremourning** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[ycmd/identifier_utils.py, line 157 at r2](https://reviewable.io:443/reviews/valloric/ycmd/964#-L8NZ0N-ASM38kBon4mW:-L8NZ0N-ASM38kBon4mX:bjmyfjl) ([raw file](https://github.com/valloric/ycmd/blob/4562243000bfde73281d60591d911f15f9a79496/ycmd/identifier_utils.py#L157)):*
> ```Python
>     # 127 and whose category is Lu, Ll, Lt, Lm, Lo, Mn,
>     # Nl, No, Pd, Pc, Po, Sc, Sm, Sk, So, or Co⟩
>     # eg. λ (U+03BB) is vailed identifier
> ```

valied -> " a valid identifier".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/964)*

**Comment by bstaletic** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/964#-:-L8TsJzjDDEfqOy1WHe_:bnfp4nl)*

**Comment by Valloric** [comment]
This is LGTM, assuming commits get squashed.

**Comment by micbou** [comment]
Thanks. :lgtm:

@zzbot r+

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/964#-:-L92SsvYAc7_R52DXj4X:bueuojq)*

**Pull request merged**
