### PR TITLE
[READY] Inform user if maximum number of diagnostics is exceeded

### PR DESCRIPTION
**Pull request by micbou**
See issue https://github.com/Valloric/YouCompleteMe/issues/2392.

If the number of diagnostics exceed the value of `max_diagnostics_to_display`, a diagnostic with the message "Maximum number of diagnostics exceeded." is added at the top of the current file to inform the user.

The language server completer didn't honor the `max_diagnostics_to_display` option. It now does.

Similarly to [the `-ferror-limit` Clang flag](https://clang.llvm.org/docs/UsersManual.html#cmdoption-ferror-limit), a value of `0` for `max_diagnostics_to_display` now means that the number of diagnostics is unlimited.

Closes https://github.com/Valloric/YouCompleteMe/issues/2392.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1051)

### CODE REVIEW

**Comment by bstaletic** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1051#-:-LEdDCEt4oOKj_PmX9i9:bnfp4nl)*

**Comment by puremourning** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[ycmd/responses.py, line 248 at r1](https://reviewable.io/reviews/valloric/ycmd/1051#-LEdp7jV0HhAt0Mxhx4C:-LEdp7jV0HhAt0Mxhx4D:b-2uy6wu) ([raw file](https://github.com/valloric/ycmd/blob/e88d0d0940913c97545e5ab3bd02ea4d12fffdd5/ycmd/responses.py#L248)):*
> ```Python
>     location = Location( 1, 1, filename )
>     location_extent = Range( location, location )
>     diagnostics.append( Diagnostic(
> ```

I don't think it is a problem, and certainly no need to change it, but there is a slight irony that in the case that we exceed the max number of diags, we send exactly the max number of diags _plus one_ diagnostics.

---

*[ycmd/completers/cpp/clang_completer.py, line 361 at r1](https://reviewable.io/reviews/valloric/ycmd/1051#-LEdpkhN-8GHJx6BJ_Gt:-LEdpkhN-8GHJx6BJ_Gu:b5fi50y) ([raw file](https://github.com/valloric/ycmd/blob/e88d0d0940913c97545e5ab3bd02ea4d12fffdd5/ycmd/completers/cpp/clang_completer.py#L361)):*
> ```Python
>     self._diagnostic_store = DiagnosticsToDiagStructure( diagnostics )
>     return responses.BuildDiagnosticResponse( diagnostics,
>                                               filename,
> ```

hmm in this case, the special extra diagnostic is associated with the file name of the TU. In the case of a huge unity build, this might not be the file the user is editing. I feel like we should be sticking this diagnostic on the request_data[ 'filepath' ] so that it is prominent for the user?

---

*[ycmd/completers/language_server/language_server_completer.py, line 643 at r1](https://reviewable.io/reviews/valloric/ycmd/1051#-LEdqBqy8gkBJ7-rHK_w:-LEdqBqy8gkBJ7-rHK_x:b-nmw3ip) ([raw file](https://github.com/valloric/ycmd/blob/e88d0d0940913c97545e5ab3bd02ea4d12fffdd5/ycmd/completers/language_server/language_server_completer.py#L643)):*
> ```Python
>     super( LanguageServerCompleter, self ).__init__( user_options )
> 
>     self._max_diagnostics_to_display = user_options[
> ```

we might consider hoisting this up into the Completer base class? It's now appearing in a number of places.

---

*[ycmd/tests/language_server/language_server_completer_test.py, line 456 at r1](https://reviewable.io/reviews/valloric/ycmd/1051#-LEdt9hc4zhZp2CCiGTQ:-LEdt9hc4zhZp2CCiGTR:b-kqvy1b) ([raw file](https://github.com/valloric/ycmd/blob/e88d0d0940913c97545e5ab3bd02ea4d12fffdd5/ycmd/tests/language_server/language_server_completer_test.py#L456)):*
> ```Python
> 
> def LanguageServerCompleter_Diagnostics_MaxDiagnosticsNumberExceeded_test():
>   completer = MockCompleter( { 'max_diagnostics_to_display': 1 } )
> ```

what was the reason to use a mock here, rather than requesting the actual diagnostics? I was curious to see how this affected diags across multiple files as reported by jdt.ls. I realise that the diagnostics tests for java are quite fiddly.

---


*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1051)*

**Comment by puremourning** [comment]
:lgtm: with a couple observations

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1051#-:-LEdysqT4lIOHzaEwQU0:b-f8xmpv)*

**Comment by micbou** [comment]
Reviewed 15 of 15 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[ycmd/responses.py, line 248 at r1](https://reviewable.io/reviews/valloric/ycmd/1051#-LEdp7jV0HhAt0Mxhx4C:-LEduMrbDhY9n2u6JJ59:b-9rime2) ([raw file](https://github.com/valloric/ycmd/blob/e88d0d0940913c97545e5ab3bd02ea4d12fffdd5/ycmd/responses.py#L248)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I don't think it is a problem, and certainly no need to change it, but there is a slight irony that in the case that we exceed the max number of diags, we send exactly the max number of diags _plus one_ diagnostics.
</blockquote></details>

Yes, I thought about it and I know that Clang handles this by removing a diagnostic but I think that, while technically correct, it's not intuitive e.g. the limit is 30 and there are 31 errors but only 29 of the 30 expected errors appear?

---

*[ycmd/completers/cpp/clang_completer.py, line 361 at r1](https://reviewable.io/reviews/valloric/ycmd/1051#-LEdpkhN-8GHJx6BJ_Gt:-LEe3klo-4KhjsJ0ejRY:b-b45qjt) ([raw file](https://github.com/valloric/ycmd/blob/e88d0d0940913c97545e5ab3bd02ea4d12fffdd5/ycmd/completers/cpp/clang_completer.py#L361)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

hmm in this case, the special extra diagnostic is associated with the file name of the TU. In the case of a huge unity build, this might not be the file the user is editing. I feel like we should be sticking this diagnostic on the request_data[ 'filepath' ] so that it is prominent for the user?
</blockquote></details>

I completely forgot about the TU thing. Thanks for catching this. Fixed.

---

*[ycmd/completers/language_server/language_server_completer.py, line 643 at r1](https://reviewable.io/reviews/valloric/ycmd/1051#-LEdqBqy8gkBJ7-rHK_w:-LEe4ZMp5X2AMsy_Jtj8:bctpdcc) ([raw file](https://github.com/valloric/ycmd/blob/e88d0d0940913c97545e5ab3bd02ea4d12fffdd5/ycmd/completers/language_server/language_server_completer.py#L643)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

we might consider hoisting this up into the Completer base class? It's now appearing in a number of places.
</blockquote></details>

Makes sense. Done.

---

*[ycmd/tests/language_server/language_server_completer_test.py, line 456 at r1](https://reviewable.io/reviews/valloric/ycmd/1051#-LEdt9hc4zhZp2CCiGTQ:-LEe4c9yCK3c7EsEI_v5:b94sxfj) ([raw file](https://github.com/valloric/ycmd/blob/e88d0d0940913c97545e5ab3bd02ea4d12fffdd5/ycmd/tests/language_server/language_server_completer_test.py#L456)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

what was the reason to use a mock here, rather than requesting the actual diagnostics? I was curious to see how this affected diags across multiple files as reported by jdt.ls. I realise that the diagnostics tests for java are quite fiddly.
</blockquote></details>

I didn't add tests to the Java completer because I don't want to make the CI builds even more flaky.

---


*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1051)*

**Comment by puremourning** [comment]
:lgtm:

---

Review status: 0 of 2 LGTMs obtained (and 2 stale)

---

*[ycmd/completers/cpp/clang_completer.py, line 361 at r1](https://reviewable.io/reviews/valloric/ycmd/1051#-LEdpkhN-8GHJx6BJ_Gt:-LEkj7JJ1lS06aZlmMG7:btxguhx) ([raw file](https://github.com/valloric/ycmd/blob/e88d0d0940913c97545e5ab3bd02ea4d12fffdd5/ycmd/completers/cpp/clang_completer.py#L361)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

I completely forgot about the TU thing. Thanks for catching this. Fixed.
</blockquote></details>

:D its my pet feature :)

---

*[ycmd/tests/language_server/language_server_completer_test.py, line 456 at r1](https://reviewable.io/reviews/valloric/ycmd/1051#-LEdt9hc4zhZp2CCiGTQ:-LEkjEPr0Zn6rEVyQFwR:b-t8xni1) ([raw file](https://github.com/valloric/ycmd/blob/e88d0d0940913c97545e5ab3bd02ea4d12fffdd5/ycmd/tests/language_server/language_server_completer_test.py#L456)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

I didn't add tests to the Java completer because I don't want to make the CI builds even more flaky.
</blockquote></details>

Makes sense :/

---


*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1051#-:-LEkjH69ATJWXkyV3COY:bnfp4nl)*

**Comment by micbou** [comment]
@zzbot r+

---

Review status: 1 of 2 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1051#-:-LEkm2c3CI17Yc4UZz-G:bi59kwd)*

**Pull request merged**
