### PR TITLE
[READY] Increase MEMFILE_MAX to 10MB

### PR DESCRIPTION
**Pull request by bijancn**
See discussion [here](https://github.com/Valloric/YouCompleteMe/issues/624).

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/560)

### CODE REVIEW

**Comment by puremourning** [comment]
Hang on. Something is up with this. It says "1 of 2 LGTMs" so i think it is all confused and associated all the triggers, etc. with the other review. I suspect there is some issue with github workflow when merging master-master.

**Comment by bijancn** [comment]
Mh nope. I see 0 of 2 LGTM here in #560

**Comment by bijancn** [comment]
And now it shows 1 of 2.. Something is really strange here.

**Comment by bijancn** [comment]
I keeps swapping the reviewable link between 559 and 560. But CI always point to 560.

**Comment by puremourning** [comment]
I've closed the 559 review and done a little admin on this PR title. I hope you don't mind.

**Comment by puremourning** [comment]
:lgtm: assuming the CI builds succeed!

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/560#-:-KNacCmvJ4_e5I9CqlEA:955259063)*

**Comment by Valloric** [comment]
:lgtm: with minor comment

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ycmd/handlers.py, line 44 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/560#-KNc5uQ8BGbzPGQEJBmQ:-KNc5uQ8BGbzPGQEJBmR:1390676870) ([raw file](https://github.com/valloric/ycmd/blob/e3a7dde6eff43237970ca8dfea376edbda705344/ycmd/handlers.py#L44)):*
> ```Python
> # num bytes for the request body buffer; request.json only works if the request
> # size is less than this
> bottle.Request.MEMFILE_MAX = 10000 * 1024
> ```

This should be `1024 * 1024 * 10` so that it's obvious it's 10 MB.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/560#-:-KNc60dOVzp6Y4L4Eegh:-1144525623)*

**Comment by bijancn** [comment]
Can someone explain to me why one of these builds failed and what the differences of the builds are (beyond python version and USE_CLANG_COMPLETER)? 
https://travis-ci.org/Valloric/ycmd/builds/147418829
It seems that both .4 and .6 are using python 3.3 and USE_CLANG_COMPLETER=TRUE so I don't see why one fails.

**Comment by bijancn** [comment]
How can I reduce coverage by 1% when I only change constants? ^^

**Comment by puremourning** [comment]
> How can I reduce coverage by 1% when I only change constants? 
I think the coverage bot is a little flaky. Possibly the coverage goes down if the build or test fails.

**Comment by puremourning** [comment]
> Can someone explain to me why one of these builds failed 
Flake? we can manually re-run if needed tho it looks like the build is re-running anyway (i guess you pushed your branch )

**Comment by bijancn** [comment]
Travis now passed. So seems to have been a hickup. But in appveyor there are already fails again:
```AttributeError: 'FlakesChecker' object has no attribute 'with_doctest'```
Is this due to my changes?

**Comment by Valloric** [comment]
@bijancn The appveyor fail is not because of your change.

Thanks for the PR!

@homu r+

**Pull request merged**
