### PR TITLE
[READY] Update JediHTTP submodule

### PR DESCRIPTION
**Pull request by micbou**
You rarely (never?) want to jump to an import statement in Python.

Update JediHTTP submodule to include https://github.com/vheon/JediHTTP/pull/22.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/585)

### CODE REVIEW

**Comment by puremourning** [comment]
Hmmm...

What's the behaviour of something like this:


 == file1.py ==
```python
FILE1='test'
```

== file2.py ==
```python
from file1 import FILE1 as OBFUSCATED_NAME

def Test():
  print( "Test: {0}".format( OBFUSCATED_NAME )   
```

What does `GoTo` do for `OBFUSCATED_NAME` ? Does it jump to `FILE1=` in `file1.py` ? I somehow feel like that is less good than jumping to the `as OBFUSCATED_NAME` in the `import`.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/585#-:-KQFnds5TcHmJysMXuNm:b-wzyu1e)*

**Comment by micbou** [comment]
> What does GoTo do for OBFUSCATED_NAME ? Does it jump to FILE1= in file1.py ?

As you suspected, it jumps to `file1.py`.

> I somehow feel like that is less good than jumping to the as OBFUSCATED_NAME in the import.

Yes, it may be confusing to the user. I proposed this change because of [this comment from Jedi author](https://github.com/davidhalter/jedi-vim/issues/607#issuecomment-240236478) but I am now having some doubts about it. For this reason, I am changing the purpose of this PR to only update JediHTTP (we have two issue reports that depend on it: https://github.com/Valloric/YouCompleteMe/issues/2298 and https://github.com/Valloric/YouCompleteMe/issues/2365). We may reconsider the `follow_imports` option later.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/585#-:-KQdsy3jmmaq7ts-8q3h:b9sdec7)*

**Comment by puremourning** [comment]
Nice

:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/585#-:-KTGHHJteNdy4rrXw-Yo:bmu9b66)*

**Comment by vheon** [comment]
:lgtm: @homu r=puremourning 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/585#-:-KTGi2_Ug5UK5k6huphE:bpw2qui)*

**Pull request merged**
