### PR TITLE
[READY] Publish API docs to GitHub Page

### PR DESCRIPTION
**Pull request by micbou**
Here's the result on my fork: http://micbou.github.io/ycmd/

I wrote a script (`update_api_docs.py`) to ease the docs generation. The `swagger.yaml` file was moved to the `docs` folder as I don't think we need two folders for the API docs. It was also renamed to `openapi.yaml` since OpenAPI is the new name of Swagger.

@Valloric once these changes are included, the page is activated by clicking on the _Settings_ tab of the repository, changing the source to _master branch /docs folder_ in the _GitHub Pages_ section and finally clicking on _Save_. It will takes a few minutes before the page shows up.

This PR should be manually merged.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/896)

### CODE REVIEW

**Comment by Valloric** [comment]
:lgtm:

Thanks for the PR!

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/896#-:-L2NA9dw0WxJy8Wdye_q:b-19kv2l)*

**Comment by bstaletic** [comment]
:lgtm:
@zzbot r=Valloric

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/896#-:-L2OblyC7wUzb11Td8xU:b-4kezxp)*

**Comment by bstaletic** [comment]
@zzbot retry

**Comment by bstaletic** [comment]
Again...
@zzbot retry

**Pull request merged**
