### PR TITLE
[READY] Update boost to 1.67.0

### PR DESCRIPTION
**Pull request by bstaletic**
Should silence the following message:
```
Info: Boost.Config is older than your compiler version - probably nothing bad will happen - but you may wish to look for an update Boost version.
Define BOOST_CONFIG_SUPPRESS_OUTDATED_MESSAGE to suppress this message.
```

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1004)

### CODE REVIEW

**Comment by micbou** [comment]
I can confirm this suppresses these warnings.

:lgtm:

---

Reviewed 74 of 78 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/1004#-:-LAEeHOKAeg9hoyaYdYH:b7zkdfj)*

**Comment by bstaletic** [comment]
It suppresses the warnings by commenting out the code that emits them and adds a comment saying something like "meh, we don't care enough".

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/1004#-:-LAEfBdhB8LF71GLvlDM:b8xblv2)*

**Comment by puremourning** [comment]
:lgtm:

---

Reviewed 1 of 78 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/1004#-:-LAFSltz1QvW3C6GP40x:bnfp4nl)*

**Comment by micbou** [comment]
@zzbot r+

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/1004#-:-LAFsk5e0tBSHzYF0ETR:bi59kwd)*

**Pull request merged**
