### PR TITLE
Fix language detection

### PR DESCRIPTION
**Pull request by abigagli**
This superseeds #262 and follows received suggestions of using regex and adding specific tests.

[Review on Reviewable](https://reviewable.io/reviews/valloric/ycmd/266)

### CODE REVIEW

**Comment by vheon** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/cpp/flags.py, line 24 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/266#-K4P5DQDAVbhkjLzgGGq:-K4P5DQDAVbhkjLzgGGr:-473949452) ([raw file](https://github.com/valloric/ycmd/blob/3eb6767e0ad936c530d21fe23c1f49cccc8fb6cf/ycmd/completers/cpp/flags.py#L24)):*
why this blank line here?

---

*[ycmd/completers/cpp/flags.py, line 229 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/266#-K4P5FppWx0X9MeUAy2r:-K4P5FppWx0X9MeUAy2s:638464986) ([raw file](https://github.com/valloric/ycmd/blob/3eb6767e0ad936c530d21fe23c1f49cccc8fb6cf/ycmd/completers/cpp/flags.py#L229)):*
Why use `\d+` instead of just `\d`? I don't see any reason at the moment. If we decide to keep the `+` in the regex I would some test covering the `+`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/266)*

**Comment by abigagli** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/cpp/flags.py, line 24 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/266#-K4P5DQDAVbhkjLzgGGq:-K4P7rkoACAesMfU2lcb:964128361) ([raw file](https://github.com/valloric/ycmd/blob/3eb6767e0ad936c530d21fe23c1f49cccc8fb6cf/ycmd/completers/cpp/flags.py#L24)):*
Just a habit I have to separate include statements from the rest of the code in C/C++. If that's frowned upon in python I can remove it no problem

---

*[ycmd/completers/cpp/flags.py, line 229 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/266#-K4P5FppWx0X9MeUAy2r:-K4P8JmTgMNAXA50vahD:2089382250) ([raw file](https://github.com/valloric/ycmd/blob/3eb6767e0ad936c530d21fe23c1f49cccc8fb6cf/ycmd/completers/cpp/flags.py#L229)):*
Well, I thought while I was at it I'd make it more general in the (admittedly unlikely) case some major/minor/patch number gets > 9. I tested it manually, but forgot to add to the test case. I'll add some coverage for it in the tests. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/266)*

**Comment by abigagli** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/cpp/flags.py, line 24 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/266#-K4P5DQDAVbhkjLzgGGq:-K4P9P7MBQuUZRyvUc9i:1091938254) ([raw file](https://github.com/valloric/ycmd/blob/3eb6767e0ad936c530d21fe23c1f49cccc8fb6cf/ycmd/completers/cpp/flags.py#L24)):*
Oh, the following statements are actually imports as well, now I see why you asked...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/266)*

**Comment by micbou** [comment]
*[ycmd/completers/cpp/flags.py, line 229 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/266#-K4P5FppWx0X9MeUAy2r:-K4P9kNpmezBrE0GPyfz:-1248892051) ([raw file](https://github.com/valloric/ycmd/blob/3eb6767e0ad936c530d21fe23c1f49cccc8fb6cf/ycmd/completers/cpp/flags.py#L229)):*
The regex should be compiled and defined as a global variable at the top of this file:
```python
CPP_COMPILER_REGEX = re.compile( '\+\+(-\d+(\.\d+){0,2})?$' )
```
and the condition becomes:
```python
CPP_COMPILER_REGEX.search( flags[ 0 ] )
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/266)*

**Comment by abigagli** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/cpp/flags.py, line 229 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/266#-K4P5FppWx0X9MeUAy2r:-K4PI1mhvFzFUPddKXSA:-1596978215) ([raw file](https://github.com/valloric/ycmd/blob/3eb6767e0ad936c530d21fe23c1f49cccc8fb6cf/ycmd/completers/cpp/flags.py#L229)):*
I agree, as that regex is going to be used as many times as there are files in the *compile_commands.json* file.
I initially thought about making it an instance variable but then noticed that function is not is a method but a free function and was worried about adding a global variable as I'm not sure what the consensus about globals is in python.
Unfortunately my unfamiliarity with python forces me to move in a "touch as few things as possilbe" ways, as I wouldn't want to mess up anything for such a minimal change...
I'll go ahead and follow your suggestion to add a compiled global. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/266)*

**Comment by vheon** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/266)*

**Comment by micbou** [comment]
LGTM.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/266#-:-K4SynjnmRVPu_SyCtmQ:-492975211)*

**Comment by micbou** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/266)*

**Comment by vheon** [comment]
LGTM, @homu r+

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/266#-:-K4T_75sEFIk0HZQf3z5:48453751)*

**Pull request merged**
