### PR TITLE
[READY] Boost 1.69 update

### PR DESCRIPTION
**Pull request by bstaletic**
Boost.System is now a header only library, but `error_code.cpp` still exists with one empty function, so that people can still link against it, for backwards compatibility.

In `update_boost.py` I added `system` to `BOOST_LIBS_FOLDERS_TO_REMOVE`, but I have not removed `system` from the required components of system boost in `cpp/ycm/CMakeLists.txt` so that we don't break system boost older than 1.69 and get similar complaints to the ones about `libclang.so.7`.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1152)

### CODE REVIEW

**Comment by Valloric** [comment]
:lgtm:

Thanks for the PR!

**Comment by puremourning** [comment]
> Though this SO says it doesn't work on macOS.

I'll try it

**Comment by puremourning** [comment]
```
-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   filesystem
--   regex
--   system
```

**Comment by bstaletic** [comment]
@zzbot r=puremourning

**Pull request merged**
