### PR TITLE
[READY] Definitely fix IndexError exception from C++

### PR DESCRIPTION
**Pull request by micbou**
PR #453 did not completely fix the IndexError issue, but moved it to other parts of the C++ code. The exception is now raised by the [`NodeListForLetter` method in `QueryMatchResult`](https://github.com/Valloric/ycmd/blob/master/cpp/ycm/Candidate.cpp#L96) when the query contains non-ascii characters. Since we don't support this kind of query, we want to deal with it as early as possible: in the `CandidatesForQueryAndType` and `FilterAndSortCandidates` functions. We don't check for non-ascii characters but for nonprintable ones as [we already do for candidates](https://github.com/Valloric/ycmd/blob/master/cpp/ycm/CandidateRepository.cpp#L136).

Added two tests for the `CandidatesForQuery` function: `EmptyCandidatesForUnicode` is failing without this PR but not `EmptyCandidatesForNonPrintable` because nonprintable candidates are ignored.

No tests for `FilterAndSortCandidates` because it will be tested by the Python layer in PR #455.

Core version bumped.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/463)

### CODE REVIEW

**Comment by vheon** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cpp/ycm/CandidateRepository.cpp, line 25 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/463#-KFuMqyfP-rpvXXWRuKb:-KFuMqyfP-rpvXXWRuKc:1900112338) ([raw file](https://github.com/valloric/ycmd/blob/be00c50b0faa671f12f9f9a78d18455037498a20/cpp/ycm/CandidateRepository.cpp#L25)):*
I would move this import here to `Candidate.cpp`

---

*[cpp/ycm/CandidateRepository.cpp, line 34 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/463#-KFuMewl-qeClA_TVYFj:-KFuMewmTfUQ6_9s4Lmi:-1221113409) ([raw file](https://github.com/valloric/ycmd/blob/be00c50b0faa671f12f9f9a78d18455037498a20/cpp/ycm/CandidateRepository.cpp#L34)):*
Those `using` statements are not needed anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/463)*

**Comment by Valloric** [comment]
Review status: 6 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[cpp/ycm/tests/IdentifierCompleter_test.cpp, line 275 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/463#-KFuRUW_6WIGP0Iu_uJf:-KFuRUW_6WIGP0Iu_uJg:-232406093) ([raw file](https://github.com/valloric/ycmd/blob/be00c50b0faa671f12f9f9a78d18455037498a20/cpp/ycm/tests/IdentifierCompleter_test.cpp#L275)):*
There's probably a matcher like `IsEmpty`. Let's use that instead, it's clearer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/463)*

**Comment by Valloric** [comment]
:lgtm: Thanks!

---

Review status: 6 of 8 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/463#-:-KFuReXhQ2yiNljCuqi-:-971291639)*

**Comment by micbou** [comment]
Reviewed 6 of 8 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cpp/ycm/CandidateRepository.cpp, line 25 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/463#-KFuMqyfP-rpvXXWRuKb:-KFuRVqflaBmYn9c7ir4:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/be00c50b0faa671f12f9f9a78d18455037498a20/cpp/ycm/CandidateRepository.cpp#L25)):*
Done.

---

*[cpp/ycm/CandidateRepository.cpp, line 34 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/463#-KFuMewl-qeClA_TVYFj:-KFuRWSkZu-wsNIbVm4z:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/be00c50b0faa671f12f9f9a78d18455037498a20/cpp/ycm/CandidateRepository.cpp#L34)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/463)*

**Comment by puremourning** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/463#-:-KFuTtYzMV5k05yH2WJs:1417088721)*

**Comment by micbou** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cpp/ycm/tests/IdentifierCompleter_test.cpp, line 275 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/463#-KFuRUW_6WIGP0Iu_uJf:-KFuZHvrA8J9EDGSXBLH:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/be00c50b0faa671f12f9f9a78d18455037498a20/cpp/ycm/tests/IdentifierCompleter_test.cpp#L275)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/463)*

**Comment by puremourning** [comment]
@homu r=Valloric

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/463#-:-KFugiuaHfTO6-LYFd4O:-768409623)*

**Pull request merged**
