### PR TITLE
Fix the error that ycmd encountered when remove generated cmake files on windows.

### PR DESCRIPTION
**Pull request by lorry-lee**
Some of the generated cmake files are readonly, so rmtree will raise an
exception. Now when get that exception, it will try to remove readonly
property and try the function rmtree again.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/803)

### CODE REVIEW

**Comment by Valloric** [comment]
:lgtm:

Thanks for the PR!

**Comment by puremourning** [comment]
Seems reasonable to me, but i don't have a Windows environment to test it in.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/803#-:-KptcMhWubjS5r2K0qwI:b-k0v10j)*

**Comment by puremourning** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/803)*

**Comment by Valloric** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[build.py, line 393 at r1](https://reviewable.io:443/reviews/valloric/ycmd/803#-Kpv6v-oRIgfQ3y9nAtk:-Kpv6v-oRIgfQ3y9nAtl:bltckbd) ([raw file](https://github.com/valloric/ycmd/blob/e2145438ca45a575e299d1cfb1a06bbde44fc0a2/build.py#L393)):*
> ```Python
>         func(path)
>     else:
>         raise
> ```

Should use 2 space indent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/803)*

**Comment by vheon** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[build.py, line 387 at r1](https://reviewable.io:443/reviews/valloric/ycmd/803#-KpvHCrmIN_Cau0SDl7S:-KpvHCrmIN_Cau0SDl7T:bxklst4) ([raw file](https://github.com/valloric/ycmd/blob/e2145438ca45a575e299d1cfb1a06bbde44fc0a2/build.py#L387)):*
> ```Python
>                 'Stop all ycmd instances before compilation.' )
> 
> def TryRemoveReadonly(func, path, exc):
> ```

Missing spaces inside the parenthesis. This is valid for all the change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/803)*

**Comment by vheon** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[build.py, line 402 at r1](https://reviewable.io:443/reviews/valloric/ycmd/803#-KpvHMfZmClwxg_NSzf4:-KpvHMfZmClwxg_NSzf5:ba2g1nz) ([raw file](https://github.com/valloric/ycmd/blob/e2145438ca45a575e299d1cfb1a06bbde44fc0a2/build.py#L402)):*
> ```Python
>       print( 'The supplied build directory ' + build_dir + ' exists, '
>              'deleting it.' )
>       rmtree( build_dir, ignore_errors = OnTravisOrAppVeyor(), onerror=TryRemoveReadonly)
> ```

missing space before `)`

---

*[build.py, line 454 at r1](https://reviewable.io:443/reviews/valloric/ycmd/803#-KpvHPNKBJgw9RwrrYCz:-KpvHPNKBJgw9RwrrYD-:ba2g1nz) ([raw file](https://github.com/valloric/ycmd/blob/e2145438ca45a575e299d1cfb1a06bbde44fc0a2/build.py#L454)):*
> ```Python
>       print( 'The build files are in: ' + build_dir )
>     else:
>       rmtree( build_dir, ignore_errors = OnTravisOrAppVeyor(), onerror=TryRemoveReadonly)
> ```

missing space before `)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/803)*

**Comment by vheon** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/803)*

**Comment by puremourning** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[build.py, line 402 at r1](https://reviewable.io:443/reviews/valloric/ycmd/803#-KpvHMfZmClwxg_NSzf4:-KpvHTfzAynqUOora6iY:bpw0gdr) ([raw file](https://github.com/valloric/ycmd/blob/e2145438ca45a575e299d1cfb1a06bbde44fc0a2/build.py#L402)):*
<details><summary><i>Previously, vheon (Andrea Cedraro) wrote…</i></summary><blockquote>

missing space before `)`
</blockquote></details>

also does this sneak over 80 chars :o

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/803)*

**Comment by micbou** [comment]
@lorry-lee Could you give more context? On which version of Windows and CMake is this happening? Which CMake generated files? I am frequently compiling ycmd on Windows and never got such error.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/803#-:-KqIA3bU-3uEn0JU1ikJ:b-bi39ux)*

**Comment by micbou** [comment]
We can't merge without more info. Closing.

**Pull request closed without merging**
