### PR TITLE
[READY] Disable Ninja auto-detection

### PR DESCRIPTION
**Pull request by micbou**
The build system [Ninja](https://ninja-build.org/) is supposed to be faster for incremental builds but this project is too small to notice a difference (a few seconds at best). Also, this is the second time a user has an issue with it because the `ninja` executable on the PATH is not the build system but another software. See https://github.com/Valloric/YouCompleteMe/issues/2941#issuecomment-372259295 (the first time was reported on Gitter). For these reasons, I am proposing to completely remove support for this build system.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/955)

### CODE REVIEW

**Comment by bstaletic** [comment]
I'm up for this. :lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/955#-:-L7PrQTGza_TalLLh-3x:b-xf9sxu)*

**Comment by puremourning** [comment]
Ninja automatically picks the right level of parallelism, which is why I always use it when the build system/generator supports it. It's also quieter.

anecdotally, I also think Ninja is faster for incremental builds (e.g. after using `--build-dir`). Perhaps we can keep it, but just ditch the auto-Ninja-detection (instead add `--with-generator=Ninja` or something ?).

I also think that 2 users having issues isn't such a large problem.

So I guess I would vote against this as it stands.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/955#-:-L7PplR3E3XFHLLOn722:blwsofb)*

**Comment by micbou** [comment]
> Ninja automatically picks the right level of parallelism, which is why I always use it when the build system/generator supports it.

We already do that in the `build.py` script by specifying the `-j` option.

> It's also quieter.

True but we have the `--quiet` option which is even more quiet.

> anecdotally, I also think Ninja is faster for incremental builds (e.g. after using --build-dir).

Like I said, the project is too small to make a difference.

> Perhaps we can keep it, but just ditch the auto-Ninja-detection (instead add --with-generator=Ninja or something ?).

Won't this annoy you to have to pass the option each time you run the script?

> I also think that 2 users having issues isn't such a large problem.

Sure but we also have better things to do that explain to users that it's not working because they don't have the right `ninja` in their path. If there was a real non-cosmetic advantage over Make for this project, we could at least give a good reason why we look for Ninja but no, we can't even do that.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/955#-:-L7PzMcCs2GoBbj3Krsw:b20676w)*

**Comment by puremourning** [comment]
OK fair enough :)

> We already do that in the build.py script by specifying the -j option.

I guess we do. I was sort of thinking about the incremental case, but that's actually a rare case.

> True but we have the --quiet option which is even more quiet.

I should search out whoever it was that added that!

> Like I said, the project is too small to make a difference.

I don't find that at work. I find that on a slow filesystem the difference is more pronounced, but tbh this again isn't a common use case.

> Won't this annoy you to have to pass the option each time you run the script?

Meh, I already have fairly sophisticated `build.py` invocations. I could probably remember to add one more, but sure - 'if there's an option to not have an option, take the no-option option' :)

> Sure but we also have better things to do

You had me at "better things to do" ! :D

Before we merge, it's worth checking with @valloric who (IIRC) added support for Ninja in the first place.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/955#-:-L7QMO-a-GSdxY5fys6b:bvvedb2)*

**Comment by Valloric** [comment]
I'd hate to see ninja support for this to go away; we should just remove ninja auto-detection. I'd totally pass the flag every time. :)

Note that we're likely to see issue requests about adding ninja auto-detection if we remove it. :D

**Comment by micbou** [comment]
I removed Ninja auto-detection and added the `--ninja` option to build with Ninja.

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/955#-:-L8e67pUBPM8Qkn23v_Y:blefzxl)*

**Comment by Valloric** [comment]
> I removed Ninja auto-detection and added the --ninja option to build with Ninja.

:dancer: Woohoo! :D

:lgtm: Thanks for the PR!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/955#-:-L8erFtpAofOewtG3heJ:b-l2ug2s)*

**Comment by bstaletic** [comment]
@zzbot r=bstaletic

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/955#-:-L8ewR3L0BmraiZjeoij:b1kuxdk)*

**Pull request merged**
