### PR TITLE
use release omnisharp

### PR DESCRIPTION
**Pull request by corngood**
Using the release configuration of OmniSharp.

*** There are currently bugs with the Release configuration that need to be fixed with https://github.com/OmniSharp/omnisharp-server/pull/206, so this shouldn't be merged until the OmniSharp fix is merged and the submodule updated.  I'll update this PR if/when that happens.

### CODE REVIEW

**Comment by corngood** [comment]
This change now contains the submodule update to include the fix in omnisharp-server.

**Comment by vheon** [comment]
What I didn't understand is what this should bring to the user and at this point why we were using the debug version of Omnisharp.

**Comment by Valloric** [comment]
Thanks!

@homu r+

@vheon AFAIR for .Net projects the distinction between debug/release isn't really significant. There isn't a large perf difference as with C++ projects. [More info](http://stackoverflow.com/questions/4043821/performance-differences-between-debug-and-release-builds).

**Comment by corngood** [comment]
I'm not sure why it was originally using Debug, but it could be because of the solution configuration problem I referenced above.  Release in the omnisharp .sln was building the silverlight configuration of some dependencies, which stopped it from locating mscorlib etc.

As far as performance goes, I unfortunately don't have hard numbers at the moment, but I did this originally because I was trying to profile a severe performance problem in one of the code issue modules (https://github.com/icsharpcode/NRefactory/issues/476).  This sort of thing is CPU limited managed code, so there is a decent improvement.

**Pull request merged**
