### PR TITLE
[READY] Update racerd to 0.3.3

### PR DESCRIPTION
**Pull request by micbou**
Fixes `GetCompletions_NoCompletionsFound` test and updates Travis and AppVeyor configurations by using `rustup` to install `rustc` and `cargo`.

Closes #676.
Closes #689.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/699)

### CODE REVIEW

**Comment by micbou** [comment]
Added a test that covers the case where the `rust_src_path` option is given but no completions are returned by racerd. This should make codecov happy.

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/699#-:-KbzFUaFLAaPfSRU0IFY:b-5ky87h)*

**Comment by Valloric** [comment]
:lgtm:

Thanks!

---

Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/699#-:-KbzyBzgJs0gCyfnzqPH:b9benhj)*

**Comment by micbou** [comment]
I encountered an issue with [`UserOption`](https://github.com/Valloric/ycmd/blob/master/ycmd/tests/test_utils.py#L159-L168) while using it in the new Rust test. This function updates an option and reverts it by replacing [our `ServerState` instance](https://github.com/Valloric/ycmd/blob/master/ycmd/handlers.py#L50) with a new one, losing all references to the already initialized completers. In particular, this makes it impossible to stop a completer server (e.g. racerd) that was already started once this function is called. I think we should completely drop this function since it leads to unexpected behavior. For now, I only removed its usage in the Rust tests and added a parameter to `SetUpApp` and `IsolatedYcmd` to customize options.

---

Reviewed 1 of 1 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, 2 of 4 files at r6, 4 of 4 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/699#-:-Kc-DS8JwT0KuPXklNeO:bpz7kqp)*

**Comment by vheon** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 4 of 4 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/699#-:-Kc-nXBixn3yV3X3RTqV:bnfp4nl)*

**Comment by Valloric** [comment]
@micbou Not against your plan, that function does seem like it might have issues.

**Comment by micbou** [comment]
It's now ready.

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/699#-:-Kc0KF_mgdzqjxaJ-YiY:b-mmxfs7)*

**Comment by Valloric** [comment]
Thanks again!

@homu r+

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/699#-:-Kc0szTKJjKeLdUQGW6u:b-f9rgub)*

**Comment by jwilm** [comment]
@micbou thank you so much for making this happen! Sorry about the last one being abandoned.

**Comment by oblitum** [comment]
Ops, I was not part of the review. Minor detail, I noticed that racerd's version in `Cargo.lock` in the tree is `0.3.2`, inside `Cargo.toml` it's `0.3.3`, which leaves the repositories dirty after the build (b/c `Cargo.lock` is updated to 0.3.3 in the build process).

**Pull request merged**
