### PR TITLE
[READY] Fix strange characters in DEV_SETUP.md

### PR DESCRIPTION
**Pull request by puremourning**
For some reason, the characters in the examples were not the correct ascii chars, so you can't copy/paste them. Replaced them with the correct incantations.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/529)

### CODE REVIEW

**Comment by micbou** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[DEV_SETUP.md, line 13 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/529#-KKdvXk3Il4_n7x1JjB7:-KKdvXk4QOMz-IGtUr2_:935283681) ([raw file](https://github.com/valloric/ycmd/blob/ebc255d106bf1ccdfd5b7f801364ea56f9f2d0fc/DEV_SETUP.md#L13)):*
> ```Markdown
> 2. `cd` into the folder where you checked out ycmd.
> 3. `$ vagrant up && vagrant ssh`. This will take a while because the VM is being
> 	 built and set up. Only needs to happen once though.
> ```

Looks like there is a `<TAB>` character here.

---

*[DEV_SETUP.md, line 49 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/529#-KKdvq2eHgz2ff6p9Sjc:-KKdvq2eHgz2ff6p9Sjd:1164367521) ([raw file](https://github.com/valloric/ycmd/blob/ebc255d106bf1ccdfd5b7f801364ea56f9f2d0fc/DEV_SETUP.md#L49)):*
> ```Markdown
> 
> ```sh
> ./run_tests --skip-build --no-flake8 ycmd/tests/get_completions_test.py
> ```

`run_tests.py` instead of `run_tests`.

---

*[DEV_SETUP.md, line 73 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/529#-KKdvwMo-Mbi1tFFL6L5:-KKdvwMo-Mbi1tFFL6L6:886361481) ([raw file](https://github.com/valloric/ycmd/blob/ebc255d106bf1ccdfd5b7f801364ea56f9f2d0fc/DEV_SETUP.md#L73)):*
> ```Markdown
> 
> ```sh
> ./run_tests --skip-build --no-flake8 ycmd/tests/get_completions_test.py
> ```

Same comment as above.

---

*[DEV_SETUP.md, line 107 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/529#-KKdv3Zf_S48DmVkhsRK:-KKdv3ZgTnXqcZeHU5A9:706262373) ([raw file](https://github.com/valloric/ycmd/blob/ebc255d106bf1ccdfd5b7f801364ea56f9f2d0fc/DEV_SETUP.md#L107)):*
> ```Markdown
> ```sh
>     pyenv shell 2.7.11
>     ./build.py —all --enable-debug
> ```

There is a strange character here too for the `--all` option.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/529)*

**Comment by vheon** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/529)*

**Comment by puremourning** [comment]
Thanks.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[DEV_SETUP.md, line 13 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/529#-KKdvXk3Il4_n7x1JjB7:-KKdyWCEl6sVvaTh74y7:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/3eb5cd13fcb4f5f55dc51f8067e0b295d5ec24aa/DEV_SETUP.md#L13)):*
<details><summary><i>Previously, micbou wrote…</i></summary>
> Looks like there is a `<TAB>` character here.
</details>
Done.

---

*[DEV_SETUP.md, line 49 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/529#-KKdvq2eHgz2ff6p9Sjc:-KKdydtAIe9kXDwkGBM7:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/3eb5cd13fcb4f5f55dc51f8067e0b295d5ec24aa/DEV_SETUP.md#L49)):*
<details><summary><i>Previously, micbou wrote…</i></summary>
> `run_tests.py` instead of `run_tests`.
</details>
Done.

---

*[DEV_SETUP.md, line 73 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/529#-KKdvwMo-Mbi1tFFL6L5:-KKdyeYC3rosRK4JoSpc:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/3eb5cd13fcb4f5f55dc51f8067e0b295d5ec24aa/DEV_SETUP.md#L73)):*
<details><summary><i>Previously, micbou wrote…</i></summary>
> Same comment as above.
</details>
Done.

---

*[DEV_SETUP.md, line 107 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/529#-KKdv3Zf_S48DmVkhsRK:-KKdyfAgRIFIFuXCfvlA:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/3eb5cd13fcb4f5f55dc51f8067e0b295d5ec24aa/DEV_SETUP.md#L107)):*
<details><summary><i>Previously, micbou wrote…</i></summary>
> There is a strange character here too for the `--all` option.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/529#-:-KKdymVmaWdDTUiiAZ1o:-1834867264)*

**Comment by micbou** [comment]
I don't see the changes. Is there some issue with GitHub? This is not the first time it happens this week-end.

**Comment by vheon** [comment]
> I don't see the changes. Is there some issue with GitHub? This is not the first time it happens this week-end.

Codecov is also having trouble communicating with github aparently 😕

**Comment by puremourning** [comment]
no that was my stupidity. i forgot to push the brandh

**Comment by micbou** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/529#-:-KKe0ivgFXyUd8kSnjQO:1417088721)*

**Comment by Valloric** [comment]
Nice! 

@homu r+

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/529#-:-KKjVMaU-yVk5F3dxeEk:-1276609493)*

**Pull request merged**
