### PR TITLE
Using python2 binary for build.py if available

### PR DESCRIPTION
**Pull request by Valloric**
See: http://stackoverflow.com/a/26056481/2606953

This is replacing the stalled #241 PR by @abspoel.

[Review on Reviewable](https://reviewable.io/reviews/valloric/ycmd/302)

### CODE REVIEW

**Comment by puremourning** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[build.py, line 4 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/302#-K7bns7B1ESQqSsqgvp-:-K7bns7CJX-lIQI4qxSK:1177223869) ([raw file](https://github.com/valloric/ycmd/blob/ad644bb039137c28b2122b5e8b1b75642167e81d/build.py#L4)):*
Should this exit 1 so that the ret code if usable?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/302)*

**Comment by Valloric** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.py, line 4 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/302#-K7bns7B1ESQqSsqgvp-:-K7bqi8dRZuZ6H-Z4ErL:-715893715) ([raw file](https://github.com/valloric/ycmd/blob/ad644bb039137c28b2122b5e8b1b75642167e81d/build.py#L4)):*
Excellent point!

I _think_ my changes will make it happen, but this is all a bit esoteric magic so I'm not completely sure.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/302)*

**Comment by micbou** [comment]
Bad news. It doesn't work in the `cmd.exe` command prompt. It returns the following error:
```cmd
>build.py
Unable to create process using '/bin/sh "C:\Users\micbou\.vim\bundle\YouCompleteMe\third_party\ycmd\build.py" '
```

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/302#-:-K7bsfqwsx8tmxO71RZ8:-1976113144)*

**Comment by Valloric** [comment]
I don't get it. Does `cmd.exe` actually process shebang lines? How did it work before? I thought that for windows we were doing the equivalent of `python build.py`.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/302#-:-K7buDSHITNOZg-jmhdF:553243347)*

**Comment by vheon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/302)*

**Comment by micbou** [comment]
Files with `.py` extension are associated to a default Python interpreter. So, it is possible to run directly `build.py` without prefixing `python`. Python is also doing some magic with [shebang line on Windows](https://docs.python.org/3.5/using/windows.html#shebang-lines).

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/302#-:-K7buzjM0ja94j7nbTwB:-1233633694)*

**Comment by Valloric** [comment]
Great, so it's Python interpreter magic that's causing issues. _sigh_... Ok, abandoning PR.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/302#-:-K7c5JUsBsPdAb3Akoy8:-1488363269)*

**Pull request closed without merging**
