### PR TITLE
[READY] C++ <-> Python bindings tests

### PR DESCRIPTION
**Pull request by bstaletic**
These tests test the behaviour of the classes, functions etc. exposed to the python layer from ycm_core.so. The purpose is of testing this is that pull requests such as #925 don't surprise us with bug that are difficult to debug.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/942)

### CODE REVIEW

**Comment by puremourning** [comment]
Moar tests is always good. particularly if you're planning to change the underlying. we now have regression-proof tests. Awesome!

:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[ycmd/tests/bindings/cpp_bindings_general_test.py, line 23 at r1](https://reviewable.io:443/reviews/valloric/ycmd/942#-L6lskb17qX2CcpCSA2K:-L6lskb17qX2CcpCSA2L:b-pmrnpy) ([raw file](https://github.com/valloric/ycmd/blob/830b30296e3d57ef1f0aa13c20c688195126817c/ycmd/tests/bindings/cpp_bindings_general_test.py#L23)):*
> ```Python
> from __future__ import absolute_import
> # Not installing aliases from python-future; it's unreliable and slow.
> from builtins import *  # noqaimport ycm_core
> ```

comment looks strange

---

*[ycmd/tests/bindings/cpp_bindings_general_test.py, line 24 at r1](https://reviewable.io:443/reviews/valloric/ycmd/942#-L6lsmPTiIV9Zkq7flkz:-L6lsmPTiIV9Zkq7fll-:bvdsdvb) ([raw file](https://github.com/valloric/ycmd/blob/830b30296e3d57ef1f0aa13c20c688195126817c/ycmd/tests/bindings/cpp_bindings_general_test.py#L24)):*
> ```Python
> # Not installing aliases from python-future; it's unreliable and slow.
> from builtins import *  # noqaimport ycm_core
> from ycmd.utils import ToCppStringCompatible as ToCppStr
> ```

insert an empty line ?

---

*[ycmd/tests/bindings/cpp_bindings_vectors_test.py, line 23 at r1](https://reviewable.io:443/reviews/valloric/ycmd/942#-L6ltZdFET596tAlWEsO:-L6ltZdFET596tAlWEsP:bhsyiky) ([raw file](https://github.com/valloric/ycmd/blob/830b30296e3d57ef1f0aa13c20c688195126817c/ycmd/tests/bindings/cpp_bindings_vectors_test.py#L23)):*
> ```Python
> from __future__ import absolute_import
> # Not installing aliases from python-future; it's unreliable and slow.
> from builtins import *  # noqaimport ycm_core
> ```

here also

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/942#-:-L6lu6QFDs4Fp8eWfmEs:b-clp6fm)*

**Comment by bstaletic** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[ycmd/tests/bindings/cpp_bindings_general_test.py, line 23 at r1](https://reviewable.io:443/reviews/valloric/ycmd/942#-L6lskb17qX2CcpCSA2K:-L6lvJrfo0STtUE7TNHM:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/830b30296e3d57ef1f0aa13c20c688195126817c/ycmd/tests/bindings/cpp_bindings_general_test.py#L23)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

comment looks strange
</blockquote></details>

Done.

---

*[ycmd/tests/bindings/cpp_bindings_general_test.py, line 24 at r1](https://reviewable.io:443/reviews/valloric/ycmd/942#-L6lsmPTiIV9Zkq7flkz:-L6lvKZzlmeddnD9xCr6:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/830b30296e3d57ef1f0aa13c20c688195126817c/ycmd/tests/bindings/cpp_bindings_general_test.py#L24)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

insert an empty line ?
</blockquote></details>

Done.

---

*[ycmd/tests/bindings/cpp_bindings_vectors_test.py, line 23 at r1](https://reviewable.io:443/reviews/valloric/ycmd/942#-L6ltZdFET596tAlWEsO:-L6lvLxlXSURnWn-uKy0:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/830b30296e3d57ef1f0aa13c20c688195126817c/ycmd/tests/bindings/cpp_bindings_vectors_test.py#L23)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

here also
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/942)*

**Comment by bstaletic** [comment]
I tried the tests with pybind11 and the tests found two problems.

- Pybind11 doesn't implement `extend()` for its vectors (`StringVector()`).
  - Instead, the tests now use `append()`.
- One bug went completely unnoticed.
  - Rewrote the diagnostics test to make sure it can catch the bug.

- When no constructor is defined, Boost.Python and Pybind11 raise different exceptions, but that's to be expected.

Now I'm confident that these tests are ready.

---

Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/942#-:-L6omokmllySWe_EnGmy:bd69bi0)*

**Comment by puremourning** [comment]
:lgtm:

nice

---

Review status: 3 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/942#-:-L6s5ZJHw9-1cN4c9DiT:b-jwumhe)*

**Comment by puremourning** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/942)*

**Comment by bstaletic** [comment]
#952 introduced a new binding, so I added another test here.

---

Review status: 3 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/942#-:-L7mLPD8EeOt4A3t6oiO:b-9b1f33)*

**Comment by Valloric** [comment]
:lgtm: with minor comments. Thanks!

---

Review status: 3 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[ycmd/tests/bindings/cpp_bindings_general_test.py, line 209 at r3](https://beta.reviewable.io/reviews/valloric/ycmd/942#-L8dvKlS3nt3TgbGOK3W:-L8dvKlS3nt3TgbGOK3X:bhjq6j9) ([raw file](https://github.com/valloric/ycmd/blob/d4022765f3d1aaf0c9b5214608d1718b4ba64e3c/ycmd/tests/bindings/cpp_bindings_general_test.py#L209)):*
> ```Python
>   del flags
>   del clang_completer
>   del reparse
> ```

Do we need all these `del` lines? If we do, can we somehow reduce this boilerplate?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/942#-:-L8dvUfu7gkDFgiIOuxW:b7ldy3g)*

**Comment by bstaletic** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ycmd/tests/bindings/cpp_bindings_general_test.py, line 209 at r3](https://beta.reviewable.io/reviews/valloric/ycmd/942#-L8dvKlS3nt3TgbGOK3W:-L8ezQKbAWVBLPleKAhx:bmf5m88) ([raw file](https://github.com/valloric/ycmd/blob/d4022765f3d1aaf0c9b5214608d1718b4ba64e3c/ycmd/tests/bindings/cpp_bindings_general_test.py#L209)):*
<details><summary><i>Previously, Valloric (Val Markovic) wrote…</i></summary><blockquote>

Do we need all these `del` lines? If we do, can we somehow reduce this boilerplate?
</blockquote></details>

The point of those `del` lines is to make sure that objects our functionality depends on do not depend on the life time of other objects.

I tried two things to reduce boilerplate - writing a `delete_args( *args )` function and using a `for delete_this in [ foo, bar ]:`. Both approaches resulted in argument copying and then only the copy was deleted.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/942)*

**Pull request merged**
