### PR TITLE
[READY] Upgrade to jdt.ls 0.14.0. Make tests more reliable.

### PR DESCRIPTION
**Pull request by puremourning**
jdt.ls changed the order of FixIt suggestions. We don't care about the
sequence, so we just don't check.

jdt.ls architecture means that it doesn't always return complete
results the "first time". The only plausible way to make this work
reliably is to retry the flaky tests.

This change adds a decorator that retries the test for up to 30s
until it passes, along with other retry loops.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/946)

### CODE REVIEW

**Comment by bstaletic** [comment]
Reviewed 4 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/language_server/language_server_completer.py, line 1236 at r2](https://reviewable.io:443/reviews/valloric/ycmd/946#-L6iTQxz2ARTUtGSxxq-:-L6iTQxz2ARTUtGSxxq0:b-thpl6h) ([raw file](https://github.com/valloric/ycmd/blob/626b76b7fcf4c4153983b0c24a01ac4348fb4cef/ycmd/completers/language_server/language_server_completer.py#L1236)):*
> ```Python
>             sync = 1
> 
>         self._sync_type = SYNC_TYPE[ sync ]
> ```

I might be wrong, but shouldn't we forget about the sync type in case sync was a dictionary?

---

*[ycmd/tests/java/diagnostics_test.py, line 449 at r2](https://reviewable.io:443/reviews/valloric/ycmd/946#-L6iRHcapVwzfyJHku8R:-L6iRHcbwic2JyWuHOyM:b-uhoc47) ([raw file](https://github.com/valloric/ycmd/blob/626b76b7fcf4c4153983b0c24a01ac4348fb4cef/ycmd/tests/java/diagnostics_test.py#L449)):*
> ```Python
>   # It can take a while for the diagnostics to be ready
>   expiration = time.time() + 10
>   while True:
> ```

Couldn't `@WithRetry` have been used here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/946)*

**Comment by puremourning** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/language_server/language_server_completer.py, line 1236 at r2](https://reviewable.io:443/reviews/valloric/ycmd/946#-L6iTQxz2ARTUtGSxxq-:-L6iaQjUBUvWHJa7tJXr:b-6froji) ([raw file](https://github.com/valloric/ycmd/blob/626b76b7fcf4c4153983b0c24a01ac4348fb4cef/ycmd/completers/language_server/language_server_completer.py#L1236)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

I might be wrong, but shouldn't we forget about the sync type in case sync was a dictionary?
</blockquote></details>

probably eventually if/when we support the other options. currently all i did was effectively back port it to what we had before.

tbh i don't think any server really expects deltas, and if they do, they wouldn't get them anyway!

---

*[ycmd/tests/java/diagnostics_test.py, line 449 at r2](https://reviewable.io:443/reviews/valloric/ycmd/946#-L6iRHcapVwzfyJHku8R:-L6iajy1NVWFsH71ChFh:b-579fn9) ([raw file](https://github.com/valloric/ycmd/blob/626b76b7fcf4c4153983b0c24a01ac4348fb4cef/ycmd/tests/java/diagnostics_test.py#L449)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Couldn't `@WithRetry` have been used here?
</blockquote></details>

no because this is an @IsolatedYcmd test. All we'd end up doing is starting and stopping the server without really getting closer to the result

this case we have to spin on the request, not the server startup.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/946)*

**Comment by bstaletic** [comment]
This looks good to me. :lgtm: 

---

Reviewed 1 of 1 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/946#-:-L6ovdlt-VN6YZEqmeGl:bwjsdgf)*

**Comment by micbou** [comment]
:lgtm: except a minor comment.

---

Reviewed 3 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[ycmd/tests/java/subcommands_test.py, line 188 at r3](https://reviewable.io:443/reviews/valloric/ycmd/946#-L6lXgqL4L3Yqb1lOewV:-L6lXgqL4L3Yqb1lOewW:byc82cf) ([raw file](https://github.com/valloric/ycmd/blob/90b833bb322f29e3eb7766c450fc2c004de953e9/ycmd/tests/java/subcommands_test.py#L188)):*
> ```Python
>                              command_arguments = [ 'GetDoc' ],
>                              completer_target = 'filetype_default' )
> ```

Unnecessary blank line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/946#-:-L6lXvZ88klrGr8uIJrb:b-p7f74f)*

**Comment by puremourning** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/tests/java/subcommands_test.py, line 188 at r3](https://reviewable.io:443/reviews/valloric/ycmd/946#-L6lXgqL4L3Yqb1lOewV:-L74xMkV8pXYEnuTZmEV:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/90b833bb322f29e3eb7766c450fc2c004de953e9/ycmd/tests/java/subcommands_test.py#L188)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Unnecessary blank line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/946)*

**Comment by micbou** [comment]
@zzbot r+

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/946#-:-L750mO6VuHUs6InC86F:bi59kwd)*

**Pull request merged**
