### PR TITLE
Update JediHTTP

### PR DESCRIPTION
**Pull request by vheon**
In the latest JediHTTP it uses the master branch instead of fixing it on
the latest version released wich was 1 year old. Accorging to the
https://github.com/davidhalter/jedi/blob/master/CONTRIBUTING.md the
master branch is stable anyway but can be updated more frequently. This was already tested by a user successfully apparently, see https://github.com/vheon/JediHTTP/issues/20#issuecomment-239313857

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/573)

### CODE REVIEW

**Comment by puremourning** [comment]
Assuming that the test failures on 2.6 are due to the change @micbou pointed out, :lgtm:

**Comment by micbou** [comment]
Yes, we should merge https://github.com/Valloric/ycmd/pull/570 first.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/573#-:-KP31UR31mPwH8F3Q1VL:b8s0j42)*

**Comment by Valloric** [comment]
LGTM from me as well.

**Comment by micbou** [comment]
:lgtm:

@homu r+

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/573#-:-KP7tXBT_eXxCHuiT1e6:b33slzv)*

**Pull request merged**
