### PR TITLE
[READY] Update API documentation

### PR DESCRIPTION
**Pull request by micbou**
The website containing the API docs wasn't updated when merging PR https://github.com/Valloric/ycmd/pull/857 (the `/receive_messages` handler is missing). This PR fixes some typos, renames `openapi.yaml` to `openapi.yml`, and updates the website.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/911)

### CODE REVIEW

**Comment by Valloric** [comment]
:lgtm:

Thanks for the PR!

**Comment by bstaletic** [comment]
:lgtm:

@zzbot r=Valloric

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/911#-:-L3gRvIRjpc6x55EpEkI:b-hgv6jp)*

**Comment by bstaletic** [comment]
@zzbot retry

**Comment by micbou** [comment]
@zzbot retry

**Pull request merged**
