### PR TITLE
[WIP] Add a Hack completer

### PR DESCRIPTION
**Pull request by cweagans**
Related to https://github.com/Valloric/ycmd/issues/97. Not entirely sure how to test this, so posting early for feedback and possibly a nudge in the right direction?

### CODE REVIEW

**Comment by Valloric** [comment]
I see you are shelling out to `hh_client`; is there a way for ycmd to talk to `hh_server` directly? that would be much faster than going through the command-line and all the serialization/deserialization and process startup/teardown overhead.

**Comment by cweagans** [comment]
I'm not sure. The hh_server API is undocumented as far as I'm aware, but I can take a look at the hh_client source and see what I can dig up.

**Comment by Valloric** [comment]
Ah, so is hh_client the "correct" way to talk to hh_server then? That would be sad, since it's wildly inefficient. I decided against integrating support for Racer because it too had this "call a command-line client" approach instead of a library API.

**Comment by cweagans** [comment]
Technically, yeah. That's how the official vim plugin does it. It's pretty dumb, but I'll look and see if there's a real API somewhere.

**Comment by vheon** [comment]
@cweagans: Why just for Hack and not for PHP too? From what I understand Hack is a superset of PHP infact according to their github page they run Wordpress for example which, to my knowledge, is a PHP CMS.

Anyway I was looking at the `hh_client` the other night since I was bored so I will just write here what I found. I didn't know that the client and the server are written in ML, which being a declarative programming language is pretty easy to read :+1: 

* From what I understand the client will start a server when it is needed, so If you do two consecutive requests the server is started on the first and for the second request it is already running so It will be much faster. The sad thing about using the client is that the path of our request would be: from the vim client we preper a json for ycmd, then ycmd will call the hhvm completer which will shell out to `hh_client`, to call the `hh_client` we grab the json, put the token into the contents and pass it on stdin to the `hh_client` which then it will take stdin, make it a string, then repack it into a json and then send it to the server. It seems a lot of overhead.
* The server have to have a knowledge about the directory of the project from what I understand, in fact, when the client starts the server it do it like this: https://github.com/facebook/hhvm/blob/29ef150d79ace0c6a00de7d44d8b5501c56fc4d3/hphp/hack/src/client/clientStart.ml#L42-L45 which practically it will do `hh_server -d root_path something_that_i_dont_understand` and apparently that directory could go out of sync but I didn't look well the protocol there.
* The server can do a lots of things: https://github.com/facebook/hhvm/blob/29ef150d79ace0c6a00de7d44d8b5501c56fc4d3/hphp/hack/src/client/clientEnv.ml#L13-L34 these are the kinds of request that you can make to the server, but I would start small with just autocompletion.

**Comment by cweagans** [comment]
@vheon I've already looked into this extensively. The Hack completer would be based on hh_client, and would use the hhvm typechecker's built-in autocomplete functionality. For PHP, we need to do something different because the typechecker doesn't support autocompleting normal PHP. To that end, I've hired someone to extract the CodeIntel library from Komodo Edit and write a completer that uses it in ycmd. That effort is ongoing and should hopefully be done next month.

Ideally, we'd write our own client for hh_server instead of just shelling out to hh_client, but that's going to be a ton of effort. Also, the existing vim plugin just shells out to hh_client and it seems to be fast enough. I'm inclined to go with the simple option for now, and then if it's a problem going forward, then implement our own client.

**Comment by Valloric** [comment]
What's the state of this PR?

**Comment by cweagans** [comment]
I haven't touched it in a while. I'm not sure how to talk directly to hh_server, so https://github.com/Valloric/ycmd/pull/98#issuecomment-76244869 is still an open question I guess.

**Comment by Valloric** [comment]
That's perfectly fine; I'll close this PR for now then. We can reopen in the future if needed.

**Comment by icholy** [comment]
The Go completer shells out to `gocode` for every completion request. `hh_client` seems pretty similar to me.

**Comment by Valloric** [comment]
@icholy Correct, and that's pretty damn unfortunate. I've heard from gocode devs that this is something they want to change, and rightly so.

**Comment by icholy** [comment]
gocode does have a client/server architecture (using [net/rpc](http://golang.org/pkg/net/rpc/)). I think they use some type of codegen to create the client methods from the server code. AFAIK it's in maintenance mode though, so I'd be surprised if any big changes came down the pipeline.

Regardless, I don't see a problem with it. And I mean that literally. I use gocode every day and have never had it choke or lag. Is it as efficient as it could be? No. Does it really matter? I don't think so.

Point being, end users would have appreciated a hack completer. The fact that it shelled out would (probably) not have made a noticeable difference in the UX.

**Comment by Valloric** [comment]
If the perf hit is truly not noticeable (like with gocode), then I'd be fine with shelling out to hh_client.

**Comment by icholy** [comment]
Ok, I might look into resurrecting this PR at some point.

**Pull request closed without merging**
