### PR TITLE
[READY] Tag file reading sanity checks

### PR DESCRIPTION
**Pull request by bstaletic**
In `IdentifierUtils.cpp` call to `ReadUtf8File()` is wrapped in a `try/catch` block, but `boost::filesystem::path`, on its own, never throws and never checks anything.

Instead there are methods like `boost::filesystem::is_regular_file(Path)` and `bost::filesystem::is_empty(Path)` that can be used to make sanity checks. `is_empty()` can throw `basic_filesystem_error` exception, as explained in the comment.

As an added bonus, the `catch` block is now reachable and should be covered with the new tests.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/726)

### CODE REVIEW

**Comment by vheon** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cpp/ycm/tests/IdentifierUtils_test.cpp, line 63 at r2](https://reviewable.io:443/reviews/valloric/ycmd/726#-Kfwy41S6YEBVi3Ixpo9:-Kfwy41S6YEBVi3IxpoA:b-o9drr4) ([raw file](https://github.com/valloric/ycmd/blob/9123799654637a6353abbcecfd5e78e61bceb744/cpp/ycm/tests/IdentifierUtils_test.cpp#L63)):*
> ```cpp
>   FiletypeIdentifierMap expected;
> 
>   EXPECT_THAT( ExtractIdentifiersFromTagsFile( testfile ), ContainerEq( expected ) );
> ```

This looks like is longer than 80 char

---

*[cpp/ycm/tests/IdentifierUtils_test.cpp, line 71 at r2](https://reviewable.io:443/reviews/valloric/ycmd/726#-Kfwy0U0n-TFelF7q8LZ:-Kfwy0U1y-Anci4hUjpD:b-oshfom) ([raw file](https://github.com/valloric/ycmd/blob/9123799654637a6353abbcecfd5e78e61bceb744/cpp/ycm/tests/IdentifierUtils_test.cpp#L71)):*
> ```cpp
>   FiletypeIdentifierMap expected;
> 
>   EXPECT_THAT( ExtractIdentifiersFromTagsFile( testfile ), ContainerEq( expected ) );
> ```

I think we can inline this like:

```cpp
EXPECT_THAT( ExtractIdentifiersFromTagsFile( testfile ),
             ContainerEq( FiletypeIdentifierMap() ) );
```

I'm not sure if it reads better this way, so is just an idea :+1: 

The same apply for the one below

---

*[cpp/ycm/tests/IdentifierUtils_test.cpp, line 79 at r2](https://reviewable.io:443/reviews/valloric/ycmd/726#-Kfwx8caxmG7auGojlfw:-Kfwx8caxmG7auGojlfx:b-73tqpj) ([raw file](https://github.com/valloric/ycmd/blob/9123799654637a6353abbcecfd5e78e61bceb744/cpp/ycm/tests/IdentifierUtils_test.cpp#L79)):*
> ```cpp
>   FiletypeIdentifierMap expected;
> 
>   EXPECT_THAT( ExtractIdentifiersFromTagsFile( testfile ), ContainerEq( expected ) );
> ```

looks like this exceed the 80 char column

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/726)*

**Comment by bstaletic** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[cpp/ycm/tests/IdentifierUtils_test.cpp, line 63 at r2](https://reviewable.io:443/reviews/valloric/ycmd/726#-Kfwy41S6YEBVi3Ixpo9:-Kfx06j50ciQSqqgcP8u:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/9123799654637a6353abbcecfd5e78e61bceb744/cpp/ycm/tests/IdentifierUtils_test.cpp#L63)):*
<details><summary><i>Previously, vheon (Andrea Cedraro) wrote…</i></summary><blockquote>

This looks like is longer than 80 char
</blockquote></details>

Done.

---

*[cpp/ycm/tests/IdentifierUtils_test.cpp, line 71 at r2](https://reviewable.io:443/reviews/valloric/ycmd/726#-Kfwy0U0n-TFelF7q8LZ:-Kfx0E2x-EuG6hYwzSmx:b-5sribe) ([raw file](https://github.com/valloric/ycmd/blob/9123799654637a6353abbcecfd5e78e61bceb744/cpp/ycm/tests/IdentifierUtils_test.cpp#L71)):*
<details><summary><i>Previously, vheon (Andrea Cedraro) wrote…</i></summary><blockquote>

I think we can inline this like:

```cpp
EXPECT_THAT( ExtractIdentifiersFromTagsFile( testfile ),
             ContainerEq( FiletypeIdentifierMap() ) );
```

I'm not sure if it reads better this way, so is just an idea :+1: 

The same apply for the one below
</blockquote></details>

Actually it can be applied to all the added tests. I went ahead and made the change.

---

*[cpp/ycm/tests/IdentifierUtils_test.cpp, line 79 at r2](https://reviewable.io:443/reviews/valloric/ycmd/726#-Kfwx8caxmG7auGojlfw:-Kfx0BkyABaFPT7BCCPi:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/9123799654637a6353abbcecfd5e78e61bceb744/cpp/ycm/tests/IdentifierUtils_test.cpp#L79)):*
<details><summary><i>Previously, vheon (Andrea Cedraro) wrote…</i></summary><blockquote>

looks like this exceed the 80 char column
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/726)*

**Comment by vheon** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/726#-:-KfxD1DD51uqDY9hC9f_:bnfp4nl)*

**Comment by micbou** [comment]
:lgtm: with a minor comment.

---

Reviewed 4 of 4 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cpp/ycm/Utils.cpp, line 40 at r1](https://reviewable.io:443/reviews/valloric/ycmd/726#-KfvMciILzFDWmWXearp:-KfvMciILzFDWmWXearq:bct81dd) ([raw file](https://github.com/valloric/ycmd/blob/1c5f8686bd0ff535181df2b560319a9e4141ba8e/cpp/ycm/Utils.cpp#L40)):*
> ```cpp
>   // in case filepath's file_status is "other".
>   // "other" in this case means everything that is not a regular file,
>   // directory or a smylink.
> ```

Typo in symlink.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/726#-:-KfxmoSfz7xOTZYZuChs:bshw4f8)*

**Comment by bstaletic** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[cpp/ycm/Utils.cpp, line 40 at r1](https://reviewable.io:443/reviews/valloric/ycmd/726#-KfvMciILzFDWmWXearp:-KfxnpWKZsaum-I373ms:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/1c5f8686bd0ff535181df2b560319a9e4141ba8e/cpp/ycm/Utils.cpp#L40)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Typo in symlink.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/726)*

**Comment by micbou** [comment]
Thanks.

@homu r+

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/726#-:-Kfxo49hZVafNtBa5FjB:bxfgyh6)*

**Pull request merged**
