### PR TITLE
[READY] b64encode the JediHTTP HMAC secret only when passing it

### PR DESCRIPTION
**Pull request by vheon**
[Review on Reviewable](https://reviewable.io/reviews/valloric/ycmd/402)

### CODE REVIEW

**Comment by Valloric** [comment]
Nice! :lgtm: 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/402#-:-KBcp0LtQRV0_pp8vVXY:929109843)*

**Comment by Valloric** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/402)*

**Comment by puremourning** [comment]
LGTM. As this involves a subproject also being up to date, I'll let you pull the trigger @vheon 

Nice one :)

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/402#-:-KBdQ9AuqR8bxBmD8WzK:-1343329049)*

**Comment by vheon** [comment]
:smiley: @homu r=Valloric

**Pull request merged**
