### PR TITLE
[READY] Do not isolate Java subcommand tests

### PR DESCRIPTION
**Pull request by micbou**
We don't need to isolate these tests.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/962)

### CODE REVIEW

**Comment by puremourning** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/tests/java/subcommands_test.py, line 253 at r1](https://reviewable.io:443/reviews/valloric/ycmd/962#-L7vQKD_MF5GLLnyANkI:-L7vQKD_MF5GLLnyANkJ:b-l5f9tb) ([raw file](https://github.com/valloric/ycmd/blob/3cfd0cfb904559d914d448ee30fd446460ad1ea1/ycmd/tests/java/subcommands_test.py#L253)):*
> ```Python
> @SharedYcmd
> def Subcommands_GetType_NoKnownType_test( app ):
>   StartJavaCompleterServerInDirectory( app,
> ```

Is this call needed if we're not isolating? I think the reaon this call is here is due to isolation, or perhaps vice-versa/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/962)*

**Comment by micbou** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/tests/java/subcommands_test.py, line 253 at r1](https://reviewable.io:443/reviews/valloric/ycmd/962#-L7vQKD_MF5GLLnyANkI:-L7vSAoZ18snv_PBU0wC:bfj7cs0) ([raw file](https://github.com/valloric/ycmd/blob/3cfd0cfb904559d914d448ee30fd446460ad1ea1/ycmd/tests/java/subcommands_test.py#L253)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Is this call needed if we're not isolating? I think the reaon this call is here is due to isolation, or perhaps vice-versa/
</blockquote></details>

Oops, I completely forgot about that. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/962)*

**Comment by puremourning** [comment]
:lgtm: thanks

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/962#-:-L7vTGb_B-T5IwdrNiji:b-v6ynew)*

**Comment by puremourning** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/962)*

**Comment by bstaletic** [comment]
:lgtm:
@zzbot r=puremourning

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/962#-:-L7yTUefTCZjueq93shV:bsrfr92)*

**Pull request merged**
