### PR TITLE
[READY] Update Unicode Standard to 11.0.0

### PR DESCRIPTION
**Pull request by micbou**
[Unicode 11.0.0 has just been released](http://blog.unicode.org/2018/06/announcing-unicode-standard-version-110.html).

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1049)

### CODE REVIEW

**Comment by bstaletic** [comment]
Reviewable can ignore files that are marked as generated. Should we mark the `UnicodeTable.inc` as such?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[update_unicode.py, line 450 at r1](https://reviewable.io/reviews/valloric/ycmd/1049#-LENkSQh7e7isypdQP3I:-LENkSQh7e7isypdQP3J:bk3dgh) ([raw file](https://github.com/valloric/ycmd/blob/9f6803045210883e2629f7fb179884511fcd5173/update_unicode.py#L450)):*
> ```Python
>       else:
>         raise RuntimeError( 'Cannot handle Extended_Pictographic combined with '
>                             '{} property'.format( break_property ) )
> ```

Can this exception really be raised?

---

*[cpp/ycm/Character.cpp, line 101 at r1](https://reviewable.io/reviews/valloric/ycmd/1049#-LENk1wr-r10uzCEk81q:-LENk1ws820Eco4AONs-:b91lmx6) ([raw file](https://github.com/valloric/ycmd/blob/3db4f3b2d723007c46891c11fce53a0dc4363493/cpp/ycm/Character.cpp#L101)):*
> ```cpp
>       case BreakProperty::E_MODIFIER:
>       case BreakProperty::GLUE_AFTER_ZWJ:
>       case BreakProperty::E_BASE_GAZ:
> ```

No `ExtPict` here?

---

*[cpp/ycm/Word.cpp, line 183 at r1](https://reviewable.io/reviews/valloric/ycmd/1049#-LENmj5M-PnwMdhS8fFV:-LENmj5M-PnwMdhS8fFW:b520f6h) ([raw file](https://github.com/valloric/ycmd/blob/9f6803045210883e2629f7fb179884511fcd5173/cpp/ycm/Word.cpp#L183)):*
> ```cpp
>             within_emoji_modifier = false;
>             break;
>           // Rule GB11: do not break within emoji modifier sequences of emoji
> ```

What happened to rule 10?

---


*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1049#-:-LENnbX82vsGHRlAo9YW:b-qqykc2)*

**Comment by bstaletic** [comment]
Fair enough. :lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1049#-:-LEP4sH02iS18Tyx2AUb:b-ijqvmt)*

**Comment by puremourning** [comment]
I have essentially reviewed this syntactically. The whole unicode stuff is so far beyond my understanding at this point that I'm not really adding any value as a reviewer. :lgtm: based on that.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[update_unicode.py, line 313 at r2](https://reviewable.io/reviews/valloric/ycmd/1049#-LEdui9WA-2r4bjJL0II:-LEdui9WA-2r4bjJL0IJ:b29whhv) ([raw file](https://github.com/valloric/ycmd/blob/ae44dc1345b15e7544cc0bd847611c2d3ddff3c7/update_unicode.py#L313)):*
> ```Python
>   nb_code_points = 0
>   emoji_data = defaultdict( list )
>   for line in data:
> ```

for the record, this is all magic to me. As an offline tool, I haven't spent the time to really grok and review it properly. If you think that's useful, then I can, just shout.

---


*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1049#-:-LEdvfWG7rVzL38bYz_A:b-finkrv)*

**Comment by puremourning** [comment]
Reviewed 8 of 11 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1049)*

**Comment by micbou** [comment]
Sure, I can't really expect you to go through the Unicode specs to make sure the changes in this PR are sound. The important part is to see that new tests has been added for that version of Unicode (extracted from [`NormalizationTest.txt`](https://unicode.org/Public/UCD/latest/ucd/NormalizationTest.txt) and [`GraphemeBreakTest.txt`](https://www.unicode.org/Public/UCD/latest/ucd/auxiliary/GraphemeBreakTest.txt)) and that those tests are passing. Still, thanks for taking your time to review this (even if only syntactically).

@zzbot r+

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[update_unicode.py, line 313 at r2](https://reviewable.io/reviews/valloric/ycmd/1049#-LEdui9WA-2r4bjJL0II:-LEe9HfMD63k-B4kMqy7:brns0oi) ([raw file](https://github.com/valloric/ycmd/blob/ae44dc1345b15e7544cc0bd847611c2d3ddff3c7/update_unicode.py#L313)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

for the record, this is all magic to me. As an offline tool, I haven't spent the time to really grok and review it properly. If you think that's useful, then I can, just shout.
</blockquote></details>

No, I am confident this part of the script is doing what it's supposed to i.e. extracting the properties of the Emoji code points from [emoji-data.txt](https://unicode.org/Public/emoji/latest/emoji-data.txt) and storing them into the dictionary: code point value -> list of properties.

---


*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1049#-:-LEeBc-I1Nhee1gZLXN_:b55llhh)*

**Comment by micbou** [comment]
I cancelled the build because the core version wasn't bumped anymore.

@zzbot r+

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1049#-:-LEenD_MBqRdMQciVHXH:bz88uac)*

**Pull request merged**
