### PR TITLE
Update requests submodule to 2.8.1

### PR DESCRIPTION
**Pull request by micbou**
It should fix issues Valloric/YouCompleteMe#1674 and Valloric/YouCompleteMe#1767.

Once this PR is merged, I will send another in YCM repository to remove the `requests` submodule (YCM will use the one from ycmd) and update to the latest ycmd.

[Review on Reviewable](https://reviewable.io/reviews/valloric/ycmd/259)

### CODE REVIEW

**Comment by puremourning** [comment]
@micbou out of curiosity did you manage to reproduce the reported hangs? I don't think I've seen them myself, but I do find that with YCM, startup time on Windows is about 30 seconds :/

**Comment by micbou** [comment]
30 seconds?! Startup time on my machine is ~1s. And no, I can't reproduce the hangs.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/259)

**Comment by puremourning** [comment]
Yeah, I need to do some digging. It's quite possible that it is to do with our network at the office. My VIMFILES is on a network share and my work PC isn't exactly alienware.

**Comment by vheon** [comment]
LGTM


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/259)

**Comment by puremourning** [comment]
LGTM too. Lots of people have reported that upgrading urllib3 fixes a number of performance issues, and we know that requests upstream have updated urllib3. Also, I noticed some changes to the way it messages with meta_path which might solve some other issues that i've seen with custom-built python. 

So @micbou d'you wanna merge this now or wait for appveyor on the PR?

**Comment by micbou** [comment]
Let's wait. I will merge just after.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/259)

**Comment by micbou** [comment]
@homu r+


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/259)

**Comment by Valloric** [comment]
I'd like to add that I _loooove_ seeing you guys review, LGTM and merge changes without me. :) I hate being a single point of failure, and having the rest of you be confident about the whole process of landing changes is awesome!

The higher our [bus factor](https://en.wikipedia.org/wiki/Bus_factor), the better.

**Pull request merged**
