### PR TITLE
[READY] Fix finding node on Debian-based distributions

### PR DESCRIPTION
**Pull request by micbou**
On Debian-based distributions, `node` is installed by default as `nodejs`. See issue https://github.com/Valloric/YouCompleteMe/issues/2532. We fix that by looking for `nodejs` before `node`. We also need to change how we start the `tsserver` script because it contains the line `#!/usr/bin/env node` at the top.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/711)

### CODE REVIEW

**Comment by Valloric** [comment]
:lgtm:

Seems like reasonable approach. Thanks for the PR!

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/711#-:-Kdc-8P62BQqLV-IiyAl:bkfsxrh)*

**Comment by puremourning** [comment]
Is the travis failure a failure of travis, or did something break?

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[ycmd/completers/javascript/tern_completer.py, line 53 at r2](https://reviewable.io:443/reviews/valloric/ycmd/711#-KdqSP-J0jRmLlYzxB1T:-KdqSP-J0jRmLlYzxB1U:b-5u37fc) ([raw file](https://github.com/valloric/ycmd/blob/01d59104022bd9dfc01017437540f66f194c9d86/ycmd/completers/javascript/tern_completer.py#L53)):*
> ```Python
> 
> # On Debian-based distributions, node is by default installed as nodejs.
> PATH_TO_NODE = utils.PathToFirstExistingExecutable( [ 'node', 'nodejs' ] )
> ```

I feel like these should be the other way round. I think there is a real thing called `node` on Debian-based systems, which is different from the nodejs that we want. I think this will find the path to that `node`, but we actually want to find `nodejs`. In the installer script, we do the check the other way round, so i feel like it should be consistent. Did i miss something?

---

*[ycmd/completers/typescript/typescript_completer.py, line 48 at r2](https://reviewable.io:443/reviews/valloric/ycmd/711#-KdqSvByaH9W311F8uGJ:-KdqSvByaH9W311F8uGK:b16vlhg) ([raw file](https://github.com/valloric/ycmd/blob/01d59104022bd9dfc01017437540f66f194c9d86/ycmd/completers/typescript/typescript_completer.py#L48)):*
> ```Python
> 
> # On Debian-based distributions, node is by default installed as nodejs.
> PATH_TO_NODE = utils.PathToFirstExistingExecutable( [ 'node', 'nodejs' ] )
> ```

Same here, i think we should look for `nodejs` first

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/711#-:-KdqTeeJjuemRwwy_Nl9:bliwuxk)*

**Comment by puremourning** [comment]
Reviewed 2 of 3 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/711)*

**Comment by micbou** [comment]
PR #712 fixed the issue. This one is now ready.

---

Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/javascript/tern_completer.py, line 53 at r2](https://reviewable.io:443/reviews/valloric/ycmd/711#-KdqSP-J0jRmLlYzxB1T:-KdqdawXyRbOyD2NBcQj:b6xu9x) ([raw file](https://github.com/valloric/ycmd/blob/01d59104022bd9dfc01017437540f66f194c9d86/ycmd/completers/javascript/tern_completer.py#L53)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I feel like these should be the other way round. I think there is a real thing called `node` on Debian-based systems, which is different from the nodejs that we want. I think this will find the path to that `node`, but we actually want to find `nodejs`. In the installer script, we do the check the other way round, so i feel like it should be consistent. Did i miss something?
</blockquote></details>

No, you are right. Done.

---

*[ycmd/completers/typescript/typescript_completer.py, line 48 at r2](https://reviewable.io:443/reviews/valloric/ycmd/711#-KdqSvByaH9W311F8uGJ:-KdqdlQ-eQYubOlEKtk9:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/01d59104022bd9dfc01017437540f66f194c9d86/ycmd/completers/typescript/typescript_completer.py#L48)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Same here, i think we should look for `nodejs` first
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/711#-:-KdqdUrPPVCn9T9baqoo:b-y7pz9v)*

**Comment by puremourning** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/711#-:-KdqhgM1zOELhvWOcJhp:bnfp4nl)*

**Comment by vheon** [comment]
:lgtm: @homu r=valloric

---

Reviewed 1 of 3 files at r1, 2 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/711#-:-Kdrc6BA77-EayWAoEix:b8kx2cz)*

**Pull request merged**
