### PR TITLE
Increase MEMFILE_MAX to 10MB

### PR DESCRIPTION
**Pull request by bijancn**
See discussion [here](https://github.com/Valloric/YouCompleteMe/issues/624)

### CODE REVIEW

**Comment by puremourning** [comment]
:lgtm:

However, the CI builds haven't triggered, so i'm a little cautious.

Could you try force-pushing your branch again to see if it triggers?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/559#-:-KNaMJsCDBNmpOvbhWfJ:-53024342)*

**Comment by puremourning** [comment]
Also, thanks for going to the trouble of doing this.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/559#-:-KNaMauM5ZvsgqVxKGf9:710096967)*

**Comment by bijancn** [comment]
Mh. Maybe because I didn't make a feature branch but just pushed from master? Tests were successful on my machine. How do I force push?

**Comment by puremourning** [comment]
> Maybe because I didn't make a feature branch but just pushed from master? 

Could be. Would you mind doing so something like:

```
ycmd> git checkout -b increase-max-filesize master
ycmd> git fetch valloric # or whatever remote you have for ycmd master
ycmd> git rebase valloric/master
ycmd> git push origin increase-max-filesize
````

FWIW you can force-push a branch with:

```
ycmd> git push +<branch>
```

**Comment by bijancn** [comment]
Ok I did that and the moment I started the second pull request the CI popped up here (I think, maybe I didn't refresh and it was already due to the commands?). So maybe close the duplicate?

**Comment by puremourning** [comment]
Well, thanks very much for sorting it. Yes I think we can close one of them.

Must be a github flake. It didn't fire the events, but then when something else pushed it woke up and remembered that was its job.

**Comment by bijancn** [comment]
The reviewable link points to 560 although this is 559.. The CI builds also have been started for 560. Some maybe it is better to close 559 (which was master->master) and accept 560.

**Comment by puremourning** [comment]
Sounds good. The topic->master one will likely work better ^_^

**Pull request closed without merging**
