### PR TITLE
[READY] Fix assignment operator signature in IdentifierCompleter class

### PR DESCRIPTION
**Pull request by micbou**
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1019)

### CODE REVIEW

**Comment by puremourning** [comment]
Shrug. It's = delete, so this has no real impact, but fine :lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1019#-:-LBNManl8qWiu8x-W0Yb:b-kwjkql)*

**Comment by puremourning** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1019)*

**Comment by micbou** [comment]
It's just for consistency. In all other places where we delete the operator, we use the right signature.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1019#-:-LBNN_ht4gpqeT74lRVP:b-hbu1j0)*

**Comment by bstaletic** [comment]
:lgtm:
@zzbot r=puremourning

**Pull request merged**
