### PR TITLE
Upgrade jdt.ls to snapshot 0.18.0

### PR DESCRIPTION
**Pull request by puremourning**
There aren't too many changes that affect us, though there are some new code actions.

However, upstream changes [might improve test stability](https://github.com/eclipse/eclipse.jdt.ls/issues/604#issuecomment-388494773)

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1027)

### CODE REVIEW

**Comment by bstaletic** [comment]
:lgtm:

For a separate PR, but should we do anything about the coverage? Once again codecov is reporting those two lines randomly it seems.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1027#-:-LCJ_983DUzgRq9Y0PdD:b-29iv10)*

**Comment by micbou** [comment]
:lgtm:

@zzbot r+

> For a separate PR, but should we do anything about the coverage? Once again codecov is reporting those two lines randomly it seems.

Writing a test to always cover these lines is tricky because it involves resetting the subprocess handle without waiting for the process to be terminated which I suspect is causing the "Handle is invalid" errors on Windows.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1027#-:-LCJbwtHCniKbxOWOsXz:bt1e91x)*

**Comment by micbou** [comment]
@zzbot retry

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1027#-:-LCLJt3s7ZSimJSfQC4I:b-kc0oa4)*

**Comment by bstaletic** [comment]
@zzbot retry

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1027#-:-LCLYxQX732-u3RF-kJg:b-kc0oa4)*

**Pull request merged**
