### PR TITLE
Remove extra whitespace from typescript signatures

### PR DESCRIPTION
**Pull request by icholy**
[Review on Reviewable](https://reviewable.io/reviews/valloric/ycmd/414)

### CODE REVIEW

**Comment by Valloric** [comment]
Needs a test. :)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/414#-:-KByM1zv9VEh3uVDXmds:-577668774)*

**Comment by icholy** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ycmd/tests/typescript/get_completions_test.py, line 68 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/414#-KCHdY6THfGh95fz0MwU:-KCHdY6THfGh95fz0MwV:-686264757) ([raw file](https://github.com/valloric/ycmd/blob/90612dc6f01e762ec5e1fa2522db4679e3a97ff4/ycmd/tests/typescript/get_completions_test.py#L68)):*
Flake8 isn't happy about this line being so long, but I'm not sure how else to write it. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/414)*

**Comment by Valloric** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/tests/typescript/get_completions_test.py, line 68 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/414#-KCHdY6THfGh95fz0MwU:-KCI0bP70prFBG_1m5_R:-284915669) ([raw file](https://github.com/valloric/ycmd/blob/90612dc6f01e762ec5e1fa2522db4679e3a97ff4/ycmd/tests/typescript/get_completions_test.py#L68)):*
It's a string, and python concats consecutive strings. So this works:

```python
'foo bar zoo' == (
  'foo '
  'bar zoo' )
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/414)*

**Comment by icholy** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/tests/typescript/get_completions_test.py, line 68 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/414#-KCHdY6THfGh95fz0MwU:-KCI18d7Jl7RJfqtQSZR:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/90612dc6f01e762ec5e1fa2522db4679e3a97ff4/ycmd/tests/typescript/get_completions_test.py#L68)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/414)*

**Comment by vheon** [comment]
Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/typescript/typescript_completer.py, line 417 \[r3\]](https://reviewable.io:443/reviews/valloric/ycmd/414#-KCI3TY0gtUF3bo87VCZ:-KCI3TY1X8DgmgviYaaK:-881433422) ([raw file](https://github.com/valloric/ycmd/blob/7160703a5221021db0b384b7ab0fdb53e8854d6d/ycmd/completers/typescript/typescript_completer.py#L417)):*
so without this what would be the signature of `methodC`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/414)*

**Comment by icholy** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/typescript/typescript_completer.py, line 417 \[r3\]](https://reviewable.io:443/reviews/valloric/ycmd/414#-KCI3TY0gtUF3bo87VCZ:-KCI4kp6RLt4KIVrdh5L:-2023371226) ([raw file](https://github.com/valloric/ycmd/blob/7160703a5221021db0b384b7ab0fdb53e8854d6d/ycmd/completers/typescript/typescript_completer.py#L417)):*
`methodC (method) Foo.methodC(a: {\n    foo: string;\n    bar: number;\n}): void`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/414)*

**Comment by vheon** [comment]
:lgtm: with minor comment

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/typescript/typescript_completer.py, line 417 \[r3\]](https://reviewable.io:443/reviews/valloric/ycmd/414#-KCI3TY0gtUF3bo87VCZ:-KCI5P7lALnVKMrX4gtk:563493055) ([raw file](https://github.com/valloric/ycmd/blob/7160703a5221021db0b384b7ab0fdb53e8854d6d/ycmd/completers/typescript/typescript_completer.py#L417)):*
Ok thanks. I'm not sure If is the case to put a comment there to signal this even something like `needed to strip new lines and indentation from the signature`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/414#-:-KCI5hcoh6cmxgiwzQ_O:-1144525623)*

**Comment by icholy** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/typescript/typescript_completer.py, line 417 \[r3\]](https://reviewable.io:443/reviews/valloric/ycmd/414#-KCI3TY0gtUF3bo87VCZ:-KCI6qSZFwhslpx6vRXO:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/7160703a5221021db0b384b7ab0fdb53e8854d6d/ycmd/completers/typescript/typescript_completer.py#L417)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/414)*

**Comment by micbou** [comment]
:lgtm:

@homu r+

---

Reviewed 2 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/414#-:-KCIIXASTWwai9sd-tR6:187772251)*

**Pull request merged**
