### PR TITLE
Update racerd to 0.3.2

### PR DESCRIPTION
**Pull request by jwilm**
Has fix for issue with builds on newest rust compiler.

cc jwilm/racerd#60

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/676)

### CODE REVIEW

**Comment by puremourning** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/valloric/ycmd/676#-KZbMeLELw5KG-k_t7hm:-KZbMeLELw5KG-k_t7hn:b-q9quz8) (no related file):*
Tests seem to be failing with "Received error from racerd while retrieving completions. You did not set the rust_src_path option, which is probably causing this issue. See YCM docs for details."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/676)*

**Comment by Valloric** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/valloric/ycmd/676#-KZbMeLELw5KG-k_t7hm:-KZbjK1BsENuqzKHMqgU:b-ph05yq) (no related file):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Tests seem to be failing with "Received error from racerd while retrieving completions. You did not set the rust_src_path option, which is probably causing this issue. See YCM docs for details."
</blockquote></details>

Thanks for the PR!

I agree with @puremourning, Travis needs to be happy for us to merge this. Weird that bumping racerd would cause that error. Needs investigation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/676)*

**Comment by jwilm** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/valloric/ycmd/676#-KZbMeLELw5KG-k_t7hm:-KZcUdR9Q3c1Ty60umrB:be6f7k1) (no related file):*
<details><summary><i>Previously, Valloric (Val Markovic) wrote…</i></summary><blockquote>

Thanks for the PR!

I agree with @puremourning, Travis needs to be happy for us to merge this. Weird that bumping racerd would cause that error. Needs investigation.
</blockquote></details>

Also agree; will get back to this as time permits. Can someone who works on this regularly remind me of the command to run just the rust tests? :grin: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/676)*

**Comment by micbou** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/valloric/ycmd/676#-KZbMeLELw5KG-k_t7hm:-KZcVgixRgaE60kCI5DR:bov0tpa) (no related file):*
<details><summary><i>Previously, jwilm (Joe Wilm) wrote…</i></summary><blockquote>

Also agree; will get back to this as time permits. Can someone who works on this regularly remind me of the command to run just the rust tests? :grin: 
</blockquote></details>

```
./run_tests.py --skip-build ycmd/tests/rust
```

You can also add the `--no-flake8` flag to disable the code checker. This will speed up things.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/676)*

**Comment by jwilm** [comment]
@micbou thanks!

Had a chance to look into this. Racerd is panicking on the rust_src_path not set test. ycmd expects a 200 response with an empty completions list. However, since I need to make a chance in racerd anyways, I think it makes sense to turn this into a 400 response and update ycm to handle that instead of the empty completions check. Thoughts?

**Comment by Valloric** [comment]
@jwilm Sounds reasonable, though we'll have a better idea once we see the code. I don't forsee any issues though.

**Comment by rillian** [comment]
NB to run tests locally for reproduction:
```
pip install future flake8 nose PyHamcrest mock webtest
./run_tests.py --skip-build ycmd/tests/rust/
```

**Comment by micbou** [comment]
You should to this instead:
```
pip install -r test_requirements.txt
```

**Comment by rillian** [comment]
thanks!

**Comment by puremourning** [comment]
There's also https://github.com/Valloric/ycmd/blob/master/DEV_SETUP.md

**Pull request closed without merging**
