### PR TITLE
[READY] Do not disable Flake8 on Python 2.6 Travis but restrict its version

### LINKED ISSUE #660: AttributeError: 'module' object has no attribute 'OrderedDict'
I am following https://github.com/Valloric/ycmd/blob/master/TESTS.md to execute the test cases.
However, when I execute `./run_tests.py`, I got 
```
AttributeError: 'module' object has no attribute 'OrderedDict'
```
The vagrant intentionally installs python 2.6.6, but `flake8` uses `OrderedDict` which is not available until python 2.7.

I guess we need some patch for the `vagrant_bootstrap.sh`

### PR DESCRIPTION
**Pull request by micbou**
See issue https://github.com/Valloric/ycmd/issues/660. This reverts PR #570 and adds a version requirement to Flake8 for Python 2.6 and 3.3. Once this is merged, I'll prepare a similar PR for YCM repository.

Fixes #660.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/665)

### CODE REVIEW

**Comment by puremourning** [comment]
:lgtm: with a throwaway comment. 

TBH I feel like we should be considering dropping 2.6 support :/

---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[test_requirements.txt, line 2 at r1](https://reviewable.io:443/reviews/valloric/ycmd/665#-KYGY2I63T85G0BGihJx:-KYGY2I62zleWZ8W-hxE:b7o9wpj) ([raw file](https://github.com/valloric/ycmd/blob/3d0fa1acf45817e395b3b9528e57b9e2d024a5ec/test_requirements.txt#L2)):*
> ```
> # Flake8 3.x dropped support of Python 2.6 and 3.3
> flake8       <  3.0.0; python_version == '2.6' or python_version == '3.3'
> ```

This comment might be banal, but do we even want to support running the tests on Python 3.3? Iirc this version has serious problems, like it isn't possible to make a shared lib version on OSX. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/665#-:-KYGZpE63MN2_nhJ6tGW:b-dte6pz)*

**Comment by puremourning** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/665)*

**Comment by micbou** [comment]
I guess this comment from @Valloric in PR #570 still holds:

> We can't yet drop support for Python 2.6, old RHEL versions people may be forced to use still have it. I'm typing this on one.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test_requirements.txt, line 2 at r1](https://reviewable.io:443/reviews/valloric/ycmd/665#-KYGY2I63T85G0BGihJx:-KYGb2XGAWxWZuHg3Rhm:b2odytn) ([raw file](https://github.com/valloric/ycmd/blob/3d0fa1acf45817e395b3b9528e57b9e2d024a5ec/test_requirements.txt#L2)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

This comment might be banal, but do we even want to support running the tests on Python 3.3? Iirc this version has serious problems, like it isn't possible to make a shared lib version on OSX. 
</blockquote></details>

I think we do. [Python 3.3 is still maintained until September 2017](https://docs.python.org/devguide/index.html#status-of-python-branches).

Are you sure we can't build a shared library of Python 3.3 on OS X? Isn't what [we actually do on Travis](https://github.com/Valloric/ycmd/blob/master/ci/travis/travis_install.osx.sh#L27)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/665#-:-KYGcYYy8552GLHVpy2M:b1ca259)*

**Comment by puremourning** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test_requirements.txt, line 2 at r1](https://reviewable.io:443/reviews/valloric/ycmd/665#-KYGY2I63T85G0BGihJx:-KYGfgNO4OK-YvOfD-Ni:b-yqu55e) ([raw file](https://github.com/valloric/ycmd/blob/3d0fa1acf45817e395b3b9528e57b9e2d024a5ec/test_requirements.txt#L2)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

I think we do. [Python 3.3 is still maintained until September 2017](https://docs.python.org/devguide/index.html#status-of-python-branches).

Are you sure we can't build a shared library of Python 3.3 on OS X? Isn't what [we actually do on Travis](https://github.com/Valloric/ycmd/blob/master/ci/travis/travis_install.osx.sh#L27)?
</blockquote></details>

I could be misremembering. There's a particular version that doesn't work. Maybe it's just under pyenv or maybe it isn't--enable-shared. Anyway, you're right. This is cool. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/665)*

**Comment by Valloric** [comment]
:lgtm:

Thanks for the PR!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test_requirements.txt, line 2 at r1](https://reviewable.io:443/reviews/valloric/ycmd/665#-KYGY2I63T85G0BGihJx:-KYKhFv2B6eV92-e8N4-:b-lrkh2l) ([raw file](https://github.com/valloric/ycmd/blob/3d0fa1acf45817e395b3b9528e57b9e2d024a5ec/test_requirements.txt#L2)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I could be misremembering. There's a particular version that doesn't work. Maybe it's just under pyenv or maybe it isn't--enable-shared. Anyway, you're right. This is cool. 
</blockquote></details>

I didn't even know this syntax for the requirements file was possible! Huh, TIL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/665#-:-KYKhOkP35sRfryapImA:b-19kv2l)*

**Comment by micbou** [comment]
I think we can merge this.

@homu r+

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/665#-:-KZHYZ178CXdtlizFYGl:b-9cgog6)*

**Pull request merged**
