### PR TITLE
TypeScript: Add GoToType command

### PR DESCRIPTION
**Pull request by icholy**
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/458)

### CODE REVIEW

**Comment by Valloric** [comment]
Thanks for the PR!

Looks good in general, but the coverage bot says coverage decreases with this PR; that's not good. Please improve test coverage.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/458#-:-KFL0UMabeQFf1QE80TO:-1756430183)*

**Comment by vheon** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/458#-:-KFLZmUfqP0_TOhBTL3i:1417088721)*

**Comment by Valloric** [comment]
Nice!

@homu r=vheon

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/458#-:-KFL_VrRhxG9jx6Ro66o:165669495)*

**Comment by Valloric** [comment]
I think we might have pulled the trigger too early on this PR. I thought we had a `GoToType` subcommand already supported in one of the other completers, but we don't. The reason why is that this is just the `GoTo` command. There should be no need for a separate `GoToType` subcommand.

@icholy Could you send a separate PR to rename the new subcommand to `GoTo`? We'll also need a separate PR to YCM that updates the docs (typescript should be listed as supported for `GoTo`).

**Comment by vheon** [comment]
> I think we might have pulled the trigger too early on this PR. I thought we had a GoToType subcommand already supported in one of the other completers, but we don't. The reason why is that this is just the GoTo command. There should be no need for a separate GoToType subcommand.

Well they are not the same thing. A `GoTo` try to go to the definition or the declaration of what is under the cursor while this command moves you to declaration of the type of the thing under the cursor. So in the positive test that we have now a `GoTo` would tell you that you already are in the declaration of what is under thee cursor, while the `GoToType` moves you on the declaration of the `Foo` type.

**Comment by Valloric** [comment]
@vheon You're right. My mind is fully in statically typed languages, where you'd use GoTo on the variable to jump to the declaration and GoTo on the type in the decl to jump to the type definition. But with TS, the type is possibly not there, so a separate GoToType subcomman makes sense.

I take what I said back then. We just need docs for the new GoToType subcommand.

**Pull request merged**
