### PR TITLE
[READY] Update JediHTTP

### PR DESCRIPTION
**Pull request by micbou**
Include PR https://github.com/vheon/JediHTTP/pull/16.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/525)

### CODE REVIEW

**Comment by Valloric** [comment]
Heh, we must be doing something wrong with codecov configuration if it's saying this PR reduces coverage.

LGTM

**Comment by micbou** [comment]
I think this is because coverage from AppVeyor is missing.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/525#-:-KKLo0lAv6d3mU42vzBp:-1634598560)*

**Comment by vheon** [comment]
:lgtm:

I guess now that #526 is merged the AppVeyor builds will succeed.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/525#-:-KKPmPBSCjAmTDTjmSrL:-1456298854)*

**Comment by micbou** [comment]
No coverage drop anymore and tests are now passing.

@homu r+

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/525#-:-KKQD562SS36LVhNdCb6:1436260503)*

**Pull request merged**
