### PR TITLE
[READY] Remove all traces of MSVC 12

### PR DESCRIPTION
**Pull request by micbou**
Add the list of supported compilers to the docs.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1041)

### CODE REVIEW

**Comment by bstaletic** [comment]
One small comment, but :lgtm:.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 72 at r1](https://reviewable.io/reviews/valloric/ycmd/1041#-LDDxAPs0APrwsJW1gIr:-LDDxAPs0APrwsJW1gIs:b-hkd8qq) ([raw file](https://github.com/valloric/ycmd/blob/0cf7e7c2030d2b8cbf5b05dfd403a700f494e736/README.md#L72)):*
> ```Markdown
> 
> - GCC 4.8 and later
> - Clang 3.4 and later
> ```

`cpp/CMakeFiles.txt` checks for Clang 3.3 and newer.

---


*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1041#-:-LDDy02Y8WNCFB9eot5s:b7hndk8)*

**Comment by micbou** [comment]
Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 72 at r1](https://reviewable.io/reviews/valloric/ycmd/1041#-LDDxAPs0APrwsJW1gIr:-LDDyopP0ydtU_6e_Pvv:b-wls6fc) ([raw file](https://github.com/valloric/ycmd/blob/0cf7e7c2030d2b8cbf5b05dfd403a700f494e736/README.md#L72)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

`cpp/CMakeFiles.txt` checks for Clang 3.3 and newer.
</blockquote></details>

Right. We don't test that version unfortunately.

---


*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1041)*

**Comment by bstaletic** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 72 at r1](https://reviewable.io/reviews/valloric/ycmd/1041#-LDDxAPs0APrwsJW1gIr:-LDDzJ0QCQFrtptz9myF:b-l2vgy9) ([raw file](https://github.com/valloric/ycmd/blob/0cf7e7c2030d2b8cbf5b05dfd403a700f494e736/README.md#L72)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Right. We don't test that version unfortunately.
</blockquote></details>

Because it's really old an unavailable on travis.

---


*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1041#-:-LDDzRHT-25eXw-Z7GvR:b-uwkowd)*

**Comment by puremourning** [comment]
FWIW I checked with compiler explorer and both gcc and clang at the declared versions correctly implement the static log guard.

So this :lgtm: @zzbot r+

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1041#-:-LE-cdkY96OCfwhNEhnR:b-u9qf44)*

**Comment by micbou** [comment]
@zzbot retry

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1041#-:-LE0HPcsAl3P6kioD3wG:b-kc0oa4)*

**Pull request merged**
