### PR TITLE
Exchange call to open with OpenForStdHandle in completers

### PR DESCRIPTION
**Pull request by ptrv**
[Review on Reviewable](https://reviewable.io/reviews/valloric/ycmd/420)

### CODE REVIEW

**Comment by micbou** [comment]
You need to update all the completers.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/420#-:-KCHwxPWCfogddmJhK-v:1568664176)*

**Comment by vheon** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[ycmd/completers/python/jedi_completer.py, line 172 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/420#-KCI5-nNcHjUZGRRO_aR:-KCI5-nNcHjUZGRRO_aS:-1807782450) ([raw file](https://github.com/valloric/ycmd/blob/a8471ed68696a4db9f088bca6538326c7f5ba979/ycmd/completers/python/jedi_completer.py#L172)):*
Since you're importing the function directly why use the `utils` prefix?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/420)*

**Comment by ptrv** [comment]
Ok. I see

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/420#-:-KCIN6S_7O7bHzj2l_rs:-1274971991)*

**Comment by Valloric** [comment]
:lgtm:

Thanks for the PR!

---

Reviewed 1 of 1 files at r2, 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/420#-:-KCJAEhbb_tIr-b-H5gy:1921727927)*

**Comment by ptrv** [comment]
*[ycmd/completers/python/jedi_completer.py, line 172 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/420#-KCI5-nNcHjUZGRRO_aR:-KCKKArdsnVGVkF-0FSj:-37230672) ([raw file](https://github.com/valloric/ycmd/blob/a8471ed68696a4db9f088bca6538326c7f5ba979/ycmd/completers/python/jedi_completer.py#L172)):*
I removed the import

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/420)*

**Comment by micbou** [comment]
:lgtm:

@homu r+

---

Reviewed 1 of 1 files at r2, 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/420#-:-KCKnte8gymTmcXtDN6r:187772251)*

**Pull request merged**
