### PR TITLE
[WIP] Cache includes from system include paths.

### PR DESCRIPTION
**Pull request by davits**
Caches include entries extracted from include paths specified by -isystem flag.
On corporate environments where everything is on NFS drives and there are lot of include paths and headers it reduces include completion from several seconds to instantaneous.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/873)

### CODE REVIEW

**Comment by puremourning** [comment]
Haven’t looked in detail yet, but fist thanks for looking at this! Filesystem metadata perf is a problem for me too. 

Second I was wondering how/if the cache is invalidated. I often have Vim running for days and thing s like overnight builds etc will change the dependencies. I wonder if we can be smart and c the mtime for the dir?

**Comment by bstaletic** [comment]
@puremourning As it is now, the cache is never invalidated, but only `-isystem` flags are cached. Those shouldn't change over night.

@davits Tomorrow I should be able to test this over a remote sshfs. Should be a fun exercise.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[ycmd/completers/cpp/include_cache.py, line 33 at r1](https://reviewable.io:443/reviews/valloric/ycmd/873#-KyU9glMmysgedoSPc-8:-KyU9glNOXMBValnhvIV:b-z4atif) ([raw file](https://github.com/valloric/ycmd/blob/c6b85fd4bb515f665b1f4832a64e8274bb72dae1/ycmd/completers/cpp/include_cache.py#L33)):*
> ```Python
> from ycmd import responses
> 
> EXTRA_INFO_MAP = { 1 : '[File]', 2 : '[Dir]', 3 : '[File&Dir]' }
> ```

Why do we need the third option? Something is either a file or a directory. Even in the case of a symlink to a directory, python's `os.path` module treats it as a directory.

I understand that the `self._includes[ include.name ] |= include.entry_type` can end up with a value of 1, 2 or , but I don't see a reason not to use `=` instead of `|=`.

---

*[ycmd/completers/cpp/include_cache.py, line 39 at r1](https://reviewable.io:443/reviews/valloric/ycmd/873#-KyUfRxnGMIAXncxo056:-KyUfRxofMNHnmqtw2fe:b-lsbluo) ([raw file](https://github.com/valloric/ycmd/blob/c6b85fd4bb515f665b1f4832a64e8274bb72dae1/ycmd/completers/cpp/include_cache.py#L39)):*
> ```Python
> 
>   def __init__( self, name, entry_type ):
>     self.name = name
> ```

I think all the classes here should have some kind of comment/docstring, but `name` in particular should be explained.

Is it a full path to a file inside include path?
Is it a relative path?
Or is it whatever `GetInclompleteIncludeValue()` returns as `include_value` + a file/directory in `include_value` directory (which is what a user would have in his/her `#include` statement)?
Or perhaps it is a path from user's `-I`, `-isystem` or `-iquote` flag + `GetInclompleteIncludeValue()`'s `include_value` + something from that directory?

---

*[ycmd/completers/cpp/include_cache.py, line 84 at r1](https://reviewable.io:443/reviews/valloric/ycmd/873#-KyUYVRcFe4m_usqb_aM:-KyUYVRdY66Op_hzwFY2:bie6ked) ([raw file](https://github.com/valloric/ycmd/blob/c6b85fd4bb515f665b1f4832a64e8274bb72dae1/ycmd/completers/cpp/include_cache.py#L84)):*
> ```Python
>       names = os.listdir( path )
>     except Exception:
>       names = []
> ```

If an exception is raised, `names` will be [] and the `for` loop will iterate over an empty list.
So this can be an early `return []`, but I'm not sure if that would hurt readability.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/873#-:-KyUTLg6-3JeZTOwxQow:b-7o483z)*

**Comment by davits** [comment]
Good idea! That didn't go though my mind since I restart my vim sessions pretty often :)

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[ycmd/completers/cpp/include_cache.py, line 33 at r1](https://reviewable.io:443/reviews/valloric/ycmd/873#-KyU9glMmysgedoSPc-8:-KyUpGO73kJJL69Pobkj:b-8e68r8) ([raw file](https://github.com/valloric/ycmd/blob/c6b85fd4bb515f665b1f4832a64e8274bb72dae1/ycmd/completers/cpp/include_cache.py#L33)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Why do we need the third option? Something is either a file or a directory. Even in the case of a symlink to a directory, python's `os.path` module treats it as a directory.

I understand that the `self._includes[ include.name ] |= include.entry_type` can end up with a value of 1, 2 or , but I don't see a reason not to use `=` instead of `|=`.
</blockquote></details>

This logic was introduced long time ago by me and the reason was Qt header structure and the way we specify Qt include paths.
If both `qt/include` and `qt/include/QtCore` are added to the include paths, when one types "QtCore" it is both file and directory.
But it can be removed from the path completion logic. I'll see to it.

---

*[ycmd/completers/cpp/include_cache.py, line 39 at r1](https://reviewable.io:443/reviews/valloric/ycmd/873#-KyUfRxnGMIAXncxo056:-KyUtVLeq2U7UdkX7N6A:bvg3zc6) ([raw file](https://github.com/valloric/ycmd/blob/c6b85fd4bb515f665b1f4832a64e8274bb72dae1/ycmd/completers/cpp/include_cache.py#L39)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

I think all the classes here should have some kind of comment/docstring, but `name` in particular should be explained.

Is it a full path to a file inside include path?
Is it a relative path?
Or is it whatever `GetInclompleteIncludeValue()` returns as `include_value` + a file/directory in `include_value` directory (which is what a user would have in his/her `#include` statement)?
Or perhaps it is a path from user's `-I`, `-isystem` or `-iquote` flag + `GetInclompleteIncludeValue()`'s `include_value` + something from that directory?
</blockquote></details>

Include entry is a single file/dir from include path, it basically becomes single completion candidate.
Docs aren't my strongest side, I'll try to add some documentation.

---

*[ycmd/completers/cpp/include_cache.py, line 84 at r1](https://reviewable.io:443/reviews/valloric/ycmd/873#-KyUYVRcFe4m_usqb_aM:-KyUsfEn-U0E-6t5RW17:b32w0x) ([raw file](https://github.com/valloric/ycmd/blob/c6b85fd4bb515f665b1f4832a64e8274bb72dae1/ycmd/completers/cpp/include_cache.py#L84)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

If an exception is raised, `names` will be [] and the `for` loop will iterate over an empty list.
So this can be an early `return []`, but I'm not sure if that would hurt readability.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/873#-:-KyUrIDzqtzuz46wLFUv:bclfxx2)*

**Comment by bstaletic** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/cpp/include_cache.py, line 33 at r1](https://reviewable.io:443/reviews/valloric/ycmd/873#-KyU9glMmysgedoSPc-8:-KyUzvxsNOokTHnFr4uR:bulfub0) ([raw file](https://github.com/valloric/ycmd/blob/c6b85fd4bb515f665b1f4832a64e8274bb72dae1/ycmd/completers/cpp/include_cache.py#L33)):*
<details><summary><i>Previously, davits (Davit Samvelyan) wrote…</i></summary><blockquote>

This logic was introduced long time ago by me and the reason was Qt header structure and the way we specify Qt include paths.
If both `qt/include` and `qt/include/QtCore` are added to the include paths, when one types "QtCore" it is both file and directory.
But it can be removed from the path completion logic. I'll see to it.
</blockquote></details>

I've never worked with Qt, so I didn't know about its file hierarchy. Since there is a case where the same looking completion can represent a file and a directory, I'm fine with leaving this as is.

Alternative would probably mean having two completion entries with the same text that should be inserted, which would be worse, as it would pollute the completion menu.

---

*[ycmd/completers/cpp/include_cache.py, line 39 at r1](https://reviewable.io:443/reviews/valloric/ycmd/873#-KyUfRxnGMIAXncxo056:-KyV-VUGpunauIyor3xt:b1hecn2) ([raw file](https://github.com/valloric/ycmd/blob/c6b85fd4bb515f665b1f4832a64e8274bb72dae1/ycmd/completers/cpp/include_cache.py#L39)):*
<details><summary><i>Previously, davits (Davit Samvelyan) wrote…</i></summary><blockquote>

Include entry is a single file/dir from include path, it basically becomes single completion candidate.
Docs aren't my strongest side, I'll try to add some documentation.
</blockquote></details>

I managed to understand on my own what `name` and thus `IncludeEntry` is. I was just trying to point out the need for docs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/873)*

**Comment by bstaletic** [comment]
For the record, I did give this a test, but specifying `-isystem` flags to point to my laptop a couple of blocks away over sshfs didn't slow ycmd's header completion enough for me to notice anything.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/873#-:-KzA4KgsbXssxwnskXkh:br522cw)*

**Comment by davits** [comment]
@bstaletic, thanks for the test. I suppose it takes couple of several other factors like hard disc and/or network load to slow down header completion.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/873#-:-KzD1YXddEPl3itrGXdW:b-356c06)*

**Comment by davits** [comment]
"couple of several" :smile:  sorry for my English.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/873#-:-KzD2NGMX9Ao2bHHZYeI:b-1po8zk)*

**Comment by bstaletic** [comment]
I'm mostly satisfied with this right now, but I've left a few more comments.

Unfortunately I still have no way of testing this anywhere where include path completion would be slow, so I wonder what will @puremourning say.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[ycmd/completers/cpp/clang_completer.py, line 188 at r2](https://reviewable.io:443/reviews/valloric/ycmd/873#-L-4-61VNYroPa3pSIwS:-L-3UWom_LVpp0YpIfEA:b-hxw590) ([raw file](https://github.com/valloric/ycmd/blob/054cf68c8fdab2366506fc6f4fc6fa611f61840f/ycmd/completers/cpp/clang_completer.py#L188)):*
> ```Python
>          self._ClearCompilationFlagCache() ),
>       'ClearIncludeCache'        : ( lambda self, request_data, args:
>          self._ClearIncludeCache() ),
> ```

Do we need the new subcommand with the `mtime` logic in place?

---

*[ycmd/completers/cpp/include_cache.py, line 71 at r2](https://reviewable.io:443/reviews/valloric/ycmd/873#-L-4-_plpCaBg2GziMgD:-L-4-_plpCaBg2GziMgE:bh5yn6h) ([raw file](https://github.com/valloric/ycmd/blob/054cf68c8fdab2366506fc6f4fc6fa611f61840f/ycmd/completers/cpp/include_cache.py#L71)):*
> ```Python
> 
>   def __init__( self ):
>     self._cache = {}
> ```

It's not quite obvious what does this dictionary actually contain.
It contains `{ 'dir': ( mtime, [ IncludeEntry_list_appropriate_for_the_dir ] ) }`.
A comment about that would be helpful. Reading the code I had to go back to this a lot of times to remind myself what thte dictionary looks like.

---

*[ycmd/completers/general/filename_completer.py, line 170 at r2](https://reviewable.io:443/reviews/valloric/ycmd/873#-L-3yijpo8SoN2xkeLPY:-L-3yijq-mxldd5QOaRC:bo2w9g7) ([raw file](https://github.com/valloric/ycmd/blob/054cf68c8fdab2366506fc6f4fc6fa611f61840f/ycmd/completers/general/filename_completer.py#L170)):*
> ```Python
>       pass
> 
>   return entries
> ```

Is there a reason this is now returning a list instead of a generator object?

If not then I think we should kee[ the original:
```python
  return ( ( relative_path, GetPathType( absolute_path ) )
           for relative_path in relative_paths )
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/873#-:-L-41PkozA_IEDjjyBtL:b8ta16j)*

**Comment by davits** [comment]
Thanks for the review. Waiting for @puremourning to test this out.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[ycmd/completers/cpp/clang_completer.py, line 188 at r2](https://reviewable.io:443/reviews/valloric/ycmd/873#-L-4-61VNYroPa3pSIwS:-L-FzEifnW3lqE7ue-mU:b-6sbmov) ([raw file](https://github.com/valloric/ycmd/blob/054cf68c8fdab2366506fc6f4fc6fa611f61840f/ycmd/completers/cpp/clang_completer.py#L188)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Do we need the new subcommand with the `mtime` logic in place?
</blockquote></details>

There might be some corner cases when system include folders are not re-created during nightly builds but, files added/removed to them, which will not change mtime.

---

*[ycmd/completers/general/filename_completer.py, line 170 at r2](https://reviewable.io:443/reviews/valloric/ycmd/873#-L-3yijpo8SoN2xkeLPY:-L-FxzDcYaL_vslLFVYb:by9mmg) ([raw file](https://github.com/valloric/ycmd/blob/054cf68c8fdab2366506fc6f4fc6fa611f61840f/ycmd/completers/general/filename_completer.py#L170)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Is there a reason this is now returning a list instead of a generator object?

If not then I think we should kee[ the original:
```python
  return ( ( relative_path, GetPathType( absolute_path ) )
           for relative_path in relative_paths )
```
</blockquote></details>

My coding/thinking style is somewhat C++-ish :)
What happens when there is an exception during generation? I met such case when LANG wasn't set to UTF-8 on my system.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/873#-:-L-FzYnFUfQ-g-3ZBhQ8:b-ykcze0)*

**Comment by bstaletic** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[ycmd/completers/general/filename_completer.py, line 170 at r2](https://reviewable.io:443/reviews/valloric/ycmd/873#-L-3yijpo8SoN2xkeLPY:-L-JTX_Kv89FMRY3PcrX:b-vxl94d) ([raw file](https://github.com/valloric/ycmd/blob/054cf68c8fdab2366506fc6f4fc6fa611f61840f/ycmd/completers/general/filename_completer.py#L170)):*
<details><summary><i>Previously, davits (Davit Samvelyan) wrote…</i></summary><blockquote>

My coding/thinking style is somewhat C++-ish :)
What happens when there is an exception during generation? I met such case when LANG wasn't set to UTF-8 on my system.
</blockquote></details>

You can also do something like:

```python
try:
    return expected_object
except Exception:
    return default_because_there_was_an_exception
```
But with this change, I think your solution is more readable and thus favourable. So feel free to implement it either way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/873)*

**Comment by Valloric** [comment]
@puremourning This PR appears to be blocked on you taking a look. :)

**Comment by puremourning** [comment]
Oh Sorry, I saw `[WIP]` in the title and somewhat, err, filed it under 'to be looked at later'

I will add it to the 'to be looked at asap' pile in my brain :)

IIRC my comment was about invalidating the cache, but as this only looks at _system_ headers (`-isystem`) that seems reasonable to essentially "never" invalidate the cache.

**Comment by puremourning** [comment]
OK I took a look. Thanks a _bunch_ for working on this and thanks _even more_ for your saint-like patience.

I guess there are two points in addition to some nits:

1. Now that we are invalidating the cache based on the directory mtime, is there any reason not to go whole hog and cache _every_ include dir? That would be _fantastic_ for me, who has _huge_ dependencies which are included by `-I` and on remote SAN

2. I feel like the PR needs more tests; there's quite a lot of new code and new behaviours and I am sceptical that the updated tests really cover it functionally.

---

Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[ycmd/completers/cpp/clang_completer.py, line 132 at r2](https://reviewable.io:443/reviews/valloric/ycmd/873#-L1KZl-q0fm8rM1yZqvN:-L1KZl-q0fm8rM1yZqvO:bmb3zu8) ([raw file](https://github.com/valloric/ycmd/blob/054cf68c8fdab2366506fc6f4fc6fa611f61840f/ycmd/completers/cpp/clang_completer.py#L132)):*
> ```Python
>     includes = IncludeList()
>     for include in include_paths:
>       unicode_path = ToUnicode( os.path.join( include[ 0 ], path_dir ) )
> ```

Is there any way here to avoid naked use of `[ 0 ]` and `[ 1 ]` ? It's not self-documenting what these things are. Can we either use a dict, object or simply assign some local vars in the loop like:

```python
thing_one = include[ 0 ]
other_thing = include[ 1 ]

... use them
```

---

*[ycmd/completers/cpp/clang_completer.py, line 581 at r2](https://reviewable.io:443/reviews/valloric/ycmd/873#-L1K_fplI5yEdRtiCYmC:-L1K_fplI5yEdRtiCYmD:b-eovtn0) ([raw file](https://github.com/valloric/ycmd/blob/054cf68c8fdab2366506fc6f4fc6fa611f61840f/ycmd/completers/cpp/clang_completer.py#L581)):*
> ```Python
> def _GetAbsolutePath( include_file_name, includes ):
>   for include in includes:
>     include_file_path = os.path.join( include[ 0 ], include_file_name )
> ```

same here, could we give `include[ 0 ]` a name ?

---

*[ycmd/completers/cpp/flags.py, line 592 at r2](https://reviewable.io:443/reviews/valloric/ycmd/873#-L1K_rdst6w8yY95oEbY:-L1K_rdst6w8yY95oEbZ:b-s6r1o8) ([raw file](https://github.com/valloric/ycmd/blob/054cf68c8fdab2366506fc6f4fc6fa611f61840f/ycmd/completers/cpp/flags.py#L592)):*
> ```Python
> 
> 
> def UserIncludePaths( user_flags, filename ):
> ```

Can we write a doctoring which describes what this returns now? Previously it was simply a list of paths. Now it is al list of tuples. Tuples are a pain because they contain untagged arbitrary data. We need to document what the tuple contains.

---

*[ycmd/completers/cpp/flags.py, line 597 at r2](https://reviewable.io:443/reviews/valloric/ycmd/873#-L1KaiAXsx0FKvWi9fIP:-L1KaiAXsx0FKvWi9fIQ:b-z6tpo) ([raw file](https://github.com/valloric/ycmd/blob/054cf68c8fdab2366506fc6f4fc6fa611f61840f/ycmd/completers/cpp/flags.py#L597)):*
> ```Python
> 
>   if user_flags:
>     include_flags = { '-iquote':  ( quoted_include_paths, False ),
> ```

this looks like yet-another-place where we have a list of flags which are "include flags". There are others at the top of this file. Should would consider consolidating them? If it makes the rest of the code unnecessarily complex then perhaps not, but I worry that we might forget to update this list when, for example adding support for `driver-mode=cl`

---

*[ycmd/completers/cpp/flags.py, line 605 at r2](https://reviewable.io:443/reviews/valloric/ycmd/873#-L1KaN4dJeqLiP8sNBSb:-L1KaN4dJeqLiP8sNBSc:b-4tyq27) ([raw file](https://github.com/valloric/ycmd/blob/054cf68c8fdab2366506fc6f4fc6fa611f61840f/ycmd/completers/cpp/flags.py#L605)):*
> ```Python
>       for user_flag in it:
>         user_flag_len = len( user_flag )
>         for flag in include_flags:
> ```

shouldn't this use `iterkeys` ?

---

*[ycmd/completers/cpp/include_cache.py, line 48 at r2](https://reviewable.io:443/reviews/valloric/ycmd/873#-L1Kblz7lvaNRubbqkkU:-L1Kblz8P67peawuiF_I:b-bgxys4) ([raw file](https://github.com/valloric/ycmd/blob/054cf68c8fdab2366506fc6f4fc6fa611f61840f/ycmd/completers/cpp/include_cache.py#L48)):*
> ```Python
> 
> class IncludeList( object ):
>   """ Helper class fo combining include completion candidates from
> ```

fo -> for

---

*[ycmd/completers/cpp/include_cache.py, line 78 at r2](https://reviewable.io:443/reviews/valloric/ycmd/873#-L1Kc9a_zEXiGl1axVrG:-L1Kc9a_zEXiGl1axVrH:b6pm7bn) ([raw file](https://github.com/valloric/ycmd/blob/054cf68c8fdab2366506fc6f4fc6fa611f61840f/ycmd/completers/cpp/include_cache.py#L78)):*
> ```Python
> 
> 
>   def GetIncludes( self, path, cache ):
> ```

should `cache` really be called `use_cache` ? And if so, is there merit in defaulting to `True` ?

---

*[ycmd/completers/cpp/include_cache.py, line 102 at r2](https://reviewable.io:443/reviews/valloric/ycmd/873#-L1KcifPLYE8J_gSKE_r:-L1KcifPLYE8J_gSKE_s:bm1cqh3) ([raw file](https://github.com/valloric/ycmd/blob/054cf68c8fdab2366506fc6f4fc6fa611f61840f/ycmd/completers/cpp/include_cache.py#L102)):*
> ```Python
>       mtime = _GetModificationTime( path )
>       if mtime > cache_entry[ 0 ]:
>         del self._cache[ path ]
> ```

any way we can just update the cache ? This saves on one call to `_GetModificationTime` which is a filesystem metadata call, so it isn't free.

---

*[ycmd/completers/cpp/include_cache.py, line 112 at r2](https://reviewable.io:443/reviews/valloric/ycmd/873#-L1Kd1o3dJenHdDcokVs:-L1Kd1o3dJenHdDcokVt:b7cnh18) ([raw file](https://github.com/valloric/ycmd/blob/054cf68c8fdab2366506fc6f4fc6fa611f61840f/ycmd/completers/cpp/include_cache.py#L112)):*
> ```Python
>     try:
>       names = os.listdir( path )
>     except Exception:
> ```

can we catch the proper exceptions by name, rather than bare `Exception` ?

---

*[ycmd/completers/cpp/include_cache.py, line 117 at r2](https://reviewable.io:443/reviews/valloric/ycmd/873#-L1KdCF7CKmVa0B2fWkD:-L1KdCF7CKmVa0B2fWkE:b-yh9bgw) ([raw file](https://github.com/valloric/ycmd/blob/054cf68c8fdab2366506fc6f4fc6fa611f61840f/ycmd/completers/cpp/include_cache.py#L117)):*
> ```Python
>     includes = []
>     for name in names:
>       inc_path = os.path.join(path, name)
> ```

spaces inside `(` and `)`

---

*[ycmd/completers/cpp/include_cache.py, line 121 at r2](https://reviewable.io:443/reviews/valloric/ycmd/873#-L1Kd6uX9yBNG9HuT3y8:-L1Kd6uX9yBNG9HuT3y9:b9cxq6q) ([raw file](https://github.com/valloric/ycmd/blob/054cf68c8fdab2366506fc6f4fc6fa611f61840f/ycmd/completers/cpp/include_cache.py#L121)):*
> ```Python
>         entry_type = GetPathType( inc_path )
>         includes.append( IncludeEntry( name, entry_type ) )
>       except Exception:
> ```

Prefer actual exception type

---

*[ycmd/completers/cpp/include_cache.py, line 130 at r2](https://reviewable.io:443/reviews/valloric/ycmd/873#-L1KcOEap8wqJKwrYgmG:-L1KcOEap8wqJKwrYgmH:b-k9gmwt) ([raw file](https://github.com/valloric/ycmd/blob/054cf68c8fdab2366506fc6f4fc6fa611f61840f/ycmd/completers/cpp/include_cache.py#L130)):*
> ```Python
>   try:
>     return os.path.getmtime( path )
>   except Exception:
> ```

we strongly avoid catching bare `Exception`. If `os.path.getmtime` throws `OSError`, then catch that explicitly and let any other random exception bubble.

---

*[ycmd/completers/general/filename_completer.py, line 37 at r2](https://reviewable.io:443/reviews/valloric/ycmd/873#-L1KdOlThs5npVGVbSji:-L1KdOlThs5npVGVbSjj:bb6zqix) ([raw file](https://github.com/valloric/ycmd/blob/054cf68c8fdab2366506fc6f4fc6fa611f61840f/ycmd/completers/general/filename_completer.py#L37)):*
> ```Python
> DIR = 2
> # This mapping is also used for the #include completion.
> # We have option N3, because when using Qt with specific include paths
> ```

N3 ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/873#-:-L1KdW0AUFYEnA353U_8:b-80ovcm)*

**Comment by bstaletic** [comment]
> I feel like the PR needs more tests;

Now I'm wondering how would we even test if something is cached properly.

---

Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[ycmd/completers/cpp/include_cache.py, line 112 at r2](https://reviewable.io:443/reviews/valloric/ycmd/873#-L1Kd1o3dJenHdDcokVs:-L1LqWXngL51m-mMfFc3:b-58epy8) ([raw file](https://github.com/valloric/ycmd/blob/054cf68c8fdab2366506fc6f4fc6fa611f61840f/ycmd/completers/cpp/include_cache.py#L112)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

can we catch the proper exceptions by name, rather than bare `Exception` ?
</blockquote></details>

This should be `OSError`, if I'm not mistaken.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/873#-:-L1LpW7RA1H_6r3HEy3g:byvikmj)*

**Comment by bstaletic** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[ycmd/completers/general/filename_completer.py, line 37 at r2](https://reviewable.io:443/reviews/valloric/ycmd/873#-L1KdOlThs5npVGVbSji:-L1QamkI0qHFAUKXJGVV:b-74yofl) ([raw file](https://github.com/valloric/ycmd/blob/054cf68c8fdab2366506fc6f4fc6fa611f61840f/ycmd/completers/general/filename_completer.py#L37)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

N3 ?
</blockquote></details>

`option 3` I believe. Two lines below it says `3 : '[File&Dir]'`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/873)*

**Comment by davits** [comment]
Sorry guys I can't make up time to work on this :(
If anyone is interested, you can take it over from here.

**Pull request closed without merging**
