### PR TITLE
[READY] Fix Python 2 builds on Travis and CircleCI

### PR DESCRIPTION
**Pull request by micbou**
See PR https://github.com/Valloric/YouCompleteMe/pull/2986.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1001)

### CODE REVIEW

**Comment by bstaletic** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/1001#-:-LABhrwvESV9Pd9AHQcA:bnfp4nl)*

**Comment by micbou** [comment]
Finally found the root of the issue. pip 10 raises an exception when upgrading packages (and in particular pip itself) on Python 2.7.3 and older. We should use Python 2.7.4 to avoid the issue and (maybe) revert to 2.7.2 once this is fixed.

Also, I noticed that pip doesn't cache the packages in `~/.cache/pip` but `~/Library/caches/pip` on macOS.

---

Reviewed 2 of 3 files at r2, 3 of 4 files at r3, 1 of 1 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/1001#-:-LAE4ldA7SJVPpmyagSo:bkcgn8e)*

**Comment by bstaletic** [comment]
The Python2 build on CircleCI failed. Is it relevanat to this issue?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/1001#-:-LAE2fhB4RpAE8XSNFUc:busjuhs)*

**Comment by micbou** [comment]
No, this time it's because of a PyPI outage. We'll have to wait.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/1001#-:-LAEArUR7hSyaI8V78tM:b-ofmhqk)*

**Comment by puremourning** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/1001#-:-LAFRLMf6-YXBwiMhXlj:bnfp4nl)*

**Comment by micbou** [comment]
@zzbot r+

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/1001#-:-LAEivVM1yoZ0k0rca3T:bi59kwd)*

**Pull request merged**
