### PR TITLE
Note TypeScript support in README

### PR DESCRIPTION
**Pull request by icholy**
TypeScript 1.5 was finally released. I've been using this completer on a daily basis without any issues.

### CODE REVIEW

**Comment by Valloric** [comment]
@homu r+

**Comment by TsumiNa** [comment]
Hi! I'm new with ycmd. how can use a tsconfig.json-file to configure the tsserver. In typescript@1.6.2 now, there are no need to write `/// <reference path="xxx/xxx">`s.

**Comment by puremourning** [comment]
I think we may need to update YCM's README.md. for now, take a look at our test data directory in `ycmd/tests/testdata`. I thing there is example in there.

**Comment by icholy** [comment]
@TsumiNa https://github.com/Microsoft/TypeScript/wiki/tsconfig.json

**Comment by Valloric** [comment]
Agreed with @puremourning, seems like we need some more docs in the README. Maybe a bit of info including a link to the doc @icholy provided?

**Pull request merged**
