### PR TITLE
TypeScript: Allow concurrent requests

### PR DESCRIPTION
**Pull request by icholy**
The way it currently works, each sequence of requests/responses acquire a global lock. This restricts the usage of tsserver commands/functionality that can take a bit of time to complete (syntax checking / compilation errors).

**I need help with naming things**

[Review on Reviewable](https://reviewable.io/reviews/valloric/ycmd/344)

### CODE REVIEW

**Comment by icholy** [comment]
@puremourning @micbou hey, you've both worked on this completer. Can you take a look and give me some feedback?

**Comment by Valloric** [comment]
I haven't yet looked at the code, but I was under the impression that this can't really be done because of the way tsserver works. We communicate with it over stdin/stdout and there's no way to multiplex requests, so we're stuck with a serial interface. Yes it's _immensely_ shitty; I don't know why the tsserver devs couldn't just go with HTTP+JSON like every other decent completion server on the planet.

My understanding could of course be entirely wrong and it might be possible to handle parallel requests.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/344#-:-K9j8r8RAH3iZcQG9sTv:447333909)*

**Comment by icholy** [comment]
@Valloric writes to stdin need to be serialized. But once they're in tsserver's court, they're processed asynchronously.

So you can do:



The way it's working now is:

**Comment by Valloric** [comment]
Nice, happy to see it's possible. Thanks for working on it!

But all of these problems would disappear if tsserver was a goddamn HTTP+JSON server like everything else ycmd talks to.

**Comment by icholy** [comment]
@Valloric preaching to the choir.

**Comment by icholy** [comment]
@Valloric okie, I think it's ready for review!

**Comment by Valloric** [comment]
Good code! With minor comments resolved, :lgtm:.

It involves some tricky multithreading so I'd like to get additional eyes on it. @puremourning @micbou @vheon 

---

Reviewed 1 of 3 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[ycmd/completers/typescript/typescript_completer.py, line 121 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9mSI_nLmzc0lsyHSax:-K9mSI_nLmzc0lsyHSay:-733202905) ([raw file](https://github.com/valloric/ycmd/blob/525aea4772471d2b5905bca0a9af5da040c595ff/ycmd/completers/typescript/typescript_completer.py#L121)):*
Dicts (in anly language) should in general have comments explaining what is mapped to what. I don't mean types (though that too), but semantically. For instance, I _think_ you're mapping sequence IDs to DefferedResponse objects so that you can track which response from tsserver should go to what object. Something like it should be in the comment; makes reading the code clearer.

---

*[ycmd/completers/typescript/typescript_completer.py, line 158 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9mSlomgyvuWXSZVUbd:-K9mSlomgyvuWXSZVUbe:-871351948) ([raw file](https://github.com/valloric/ycmd/blob/525aea4772471d2b5905bca0a9af5da040c595ff/ycmd/completers/typescript/typescript_completer.py#L158)):*
Spaces inside `[]` and `()`

---

*[ycmd/completers/typescript/typescript_completer.py, line 189 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9mT2eLEQMgIA5w-qSH:-K9mT2eLEQMgIA5w-qSI:-1397762086) ([raw file](https://github.com/valloric/ycmd/blob/525aea4772471d2b5905bca0a9af5da040c595ff/ycmd/completers/typescript/typescript_completer.py#L189)):*
No need to lock-protect the `next()` call?

---

*[ycmd/completers/typescript/typescript_completer.py, line 201 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9mUJf7bUKoNuCoZVVu:-K9mUJf7bUKoNuCoZVVv:295082340) ([raw file](https://github.com/valloric/ycmd/blob/525aea4772471d2b5905bca0a9af5da040c595ff/ycmd/completers/typescript/typescript_completer.py#L201)):*
I think `SendCommand` is a fine name, but the comment here should also mention that this function is to be used when we don't care about the response to the message that is sent.

---

*[ycmd/completers/typescript/typescript_completer.py, line 209 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9mUb1ygTWJOVj-g1No:-K9mUb1ygTWJOVj-g1Np:1696250457) ([raw file](https://github.com/valloric/ycmd/blob/525aea4772471d2b5905bca0a9af5da040c595ff/ycmd/completers/typescript/typescript_completer.py#L209)):*
Is this 80 chars?

---

*[ycmd/completers/typescript/typescript_completer.py, line 211 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9mUXQyoWAqshM3R-6S:-K9mUXQyoWAqshM3R-6T:47342413) ([raw file](https://github.com/valloric/ycmd/blob/525aea4772471d2b5905bca0a9af5da040c595ff/ycmd/completers/typescript/typescript_completer.py#L211)):*
Why wrap here? Seems like more could fit in the first line

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/344#-:-K9mUieCfg6OuHwEz-MN:2012573420)*

**Comment by icholy** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[ycmd/completers/typescript/typescript_completer.py, line 189 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9mT2eLEQMgIA5w-qSH:-K9mbschtCKUwfDg3wNA:-1386376326) ([raw file](https://github.com/valloric/ycmd/blob/525aea4772471d2b5905bca0a9af5da040c595ff/ycmd/completers/typescript/typescript_completer.py#L189)):*
http://stackoverflow.com/a/27062830/215969 maybe relying on the GIL isn't a good idea ...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/344)*

**Comment by icholy** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[ycmd/completers/typescript/typescript_completer.py, line 121 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9mSI_nLmzc0lsyHSax:-K9mfaUcKSZ_NhC3R3Rb:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/525aea4772471d2b5905bca0a9af5da040c595ff/ycmd/completers/typescript/typescript_completer.py#L121)):*
Done.

---

*[ycmd/completers/typescript/typescript_completer.py, line 158 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9mSlomgyvuWXSZVUbd:-K9mfeFq0_Tr9j-hLw-1:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/525aea4772471d2b5905bca0a9af5da040c595ff/ycmd/completers/typescript/typescript_completer.py#L158)):*
Done.

---

*[ycmd/completers/typescript/typescript_completer.py, line 201 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9mUJf7bUKoNuCoZVVu:-K9mfgdiUuqwYlRWNb8l:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/525aea4772471d2b5905bca0a9af5da040c595ff/ycmd/completers/typescript/typescript_completer.py#L201)):*
Done.

---

*[ycmd/completers/typescript/typescript_completer.py, line 209 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9mUb1ygTWJOVj-g1No:-K9mfi0S-NrLakw3v2gy:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/525aea4772471d2b5905bca0a9af5da040c595ff/ycmd/completers/typescript/typescript_completer.py#L209)):*
Done.

---

*[ycmd/completers/typescript/typescript_completer.py, line 211 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9mUXQyoWAqshM3R-6S:-K9mfkOMZ0a2AUd46U6i:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/525aea4772471d2b5905bca0a9af5da040c595ff/ycmd/completers/typescript/typescript_completer.py#L211)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/344)*

**Comment by icholy** [comment]
I have no idea how to use reviewable ...

**Comment by icholy** [comment]
@Valloric what's the standard mechanism for reporting syntax/compilation errors? Should it just be implemented as a subcommand? `GoToErrors` ?

**Comment by mispencer** [comment]
Return them from the `OnFileReadyToParse` - see the [cpp completer](https://github.com/Valloric/ycmd/blob/master/ycmd/completers/cpp/clang_completer.py#L302) and the [cs completer](https://github.com/Valloric/ycmd/blob/master/ycmd/completers/cs/cs_completer.py#L199) for example.

But also see number 3 from [Creating good pull requests in CONTRIBUTING](https://github.com/Valloric/ycmd/blob/master/CONTRIBUTING.md#creating-good-pull-requests).

**Comment by icholy** [comment]
@mispencer got rid of the extra subcommands.

**Comment by vheon** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[ycmd/completers/typescript/typescript_completer.py, line 158 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9mSlomgyvuWXSZVUbd:-K9n9EM_GKql3ctiwMgQ:833497094) ([raw file](https://github.com/valloric/ycmd/blob/525aea4772471d2b5905bca0a9af5da040c595ff/ycmd/completers/typescript/typescript_completer.py#L158)):*
you missed the spaces inside `[]` and also on the line below.

---

*[ycmd/completers/typescript/typescript_completer.py, line 189 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9mT2eLEQMgIA5w-qSH:-K9n8oi5OaajZgkUxdzk:1282295250) ([raw file](https://github.com/valloric/ycmd/blob/525aea4772471d2b5905bca0a9af5da040c595ff/ycmd/completers/typescript/typescript_completer.py#L189)):*
I would use the lock; is better to be explicit than relying on the GIL.

---

*[ycmd/completers/typescript/typescript_completer.py, line 201 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9mUJf7bUKoNuCoZVVu:-K9nC2Ob9LbpZzR0yBnC:1608386205) ([raw file](https://github.com/valloric/ycmd/blob/525aea4772471d2b5905bca0a9af5da040c595ff/ycmd/completers/typescript/typescript_completer.py#L201)):*
> this function is to be used when we don't care about the response to the message that is sent

this part is missing.

---

*[ycmd/completers/typescript/typescript_completer.py, line 227 \[r5\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9nCMxFzuSzehaAKQ9Y:-K9nCMxGSj1JauJluZau:441811340) ([raw file](https://github.com/valloric/ycmd/blob/c57fdf895c1f6a6b1980c215298cc81fa62e07c4/ycmd/completers/typescript/typescript_completer.py#L227)):*
From this block of code here to me it seems that the `_pending` dictionary would love a little more abstraction with a method which would allow to push request into the queue and return the `DeferredResponse`, like:

```python
request = self._BuildRequest( command, arguments )
deferred = self._pending.PushRequest( request )
return deferred.result()
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/344)*

**Comment by icholy** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[ycmd/completers/typescript/typescript_completer.py, line 158 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9mSlomgyvuWXSZVUbd:-K9nI0ECclCs4B4_1eCB:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/525aea4772471d2b5905bca0a9af5da040c595ff/ycmd/completers/typescript/typescript_completer.py#L158)):*
Done.

---

*[ycmd/completers/typescript/typescript_completer.py, line 189 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9mT2eLEQMgIA5w-qSH:-K9nGteg5og6bpkYWHDP:805916826) ([raw file](https://github.com/valloric/ycmd/blob/525aea4772471d2b5905bca0a9af5da040c595ff/ycmd/completers/typescript/typescript_completer.py#L189)):*
I added another lock for it.

---

*[ycmd/completers/typescript/typescript_completer.py, line 201 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9mUJf7bUKoNuCoZVVu:-K9nH6WelH1seZFWdCfV:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/525aea4772471d2b5905bca0a9af5da040c595ff/ycmd/completers/typescript/typescript_completer.py#L201)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/344)*

**Comment by Valloric** [comment]
> I have no idea how to use reviewable ...

You're in luck then! You get to learn a new skill today! :D

Reviewable takes a bit of up-front work to get to know, but it's an excellent tool for code reviews. You want to have it in your toolbox.

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[ycmd/completers/typescript/typescript_completer.py, line 227 \[r5\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9nCMxFzuSzehaAKQ9Y:-K9nIusm5pKEsCA2YgiC:59308144) ([raw file](https://github.com/valloric/ycmd/blob/c57fdf895c1f6a6b1980c215298cc81fa62e07c4/ycmd/completers/typescript/typescript_completer.py#L227)):*
@vheon That doesn't seem like a bad idea! :)

---

*[ycmd/completers/typescript/typescript_completer.py, line 193 \[r6\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9nIa-LcbExaJvKbnRD:-K9nIa-LcbExaJvKbnRE:-511233934) ([raw file](https://github.com/valloric/ycmd/blob/8b3d9956e0dcad49ea0dd0388cb3724fc9316683/ycmd/completers/typescript/typescript_completer.py#L193)):*
Seems like `_sequenceid_lock` would be a better name.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/344#-:-K9nIFX_Pp7VubUXl3PL:-245825211)*

**Comment by Valloric** [comment]
@icholy Like @mispencer implied, handling diagnostics sounds like a new PR. I'd love to see that implemented though! 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/344#-:-K9nJ1nkTidZlHNmPG5R:-1391671520)*

**Comment by icholy** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[ycmd/completers/typescript/typescript_completer.py, line 227 \[r5\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9nCMxFzuSzehaAKQ9Y:-K9nJ4IfmGN3mpVy1h0N:-1474726947) ([raw file](https://github.com/valloric/ycmd/blob/c57fdf895c1f6a6b1980c215298cc81fa62e07c4/ycmd/completers/typescript/typescript_completer.py#L227)):*
I don't like the idea of introducing a class just to cut down 8 lines to 3 (in one spot). 
How about we hold off until this pattern is needed elsewhere in the code?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/344)*

**Comment by vheon** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/typescript/typescript_completer.py, line 227 \[r5\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9nCMxFzuSzehaAKQ9Y:-K9nNbhLRcQYg_sHVJbv:998705108) ([raw file](https://github.com/valloric/ycmd/blob/c57fdf895c1f6a6b1980c215298cc81fa62e07c4/ycmd/completers/typescript/typescript_completer.py#L227)):*
The idea is not to cut down the line counts, but to express a concept and the algorithm in a more comprehensive way. If you think about it there will be more lines of code actually...

>How about we hold off until this pattern is needed elsewhere in the code?

I see actually  more uses of this hypothetical class, but if you don't like the idea we could do it in another PR.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/344)*

**Comment by vheon** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/344)*

**Comment by icholy** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/typescript/typescript_completer.py, line 227 \[r5\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9nCMxFzuSzehaAKQ9Y:-K9nP3Mhh9FtEBOtjTiu:-2012532239) ([raw file](https://github.com/valloric/ycmd/blob/c57fdf895c1f6a6b1980c215298cc81fa62e07c4/ycmd/completers/typescript/typescript_completer.py#L227)):*
I'd prefer it to happen in another PR.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/344)*

**Comment by vheon** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/typescript/typescript_completer.py, line 227 \[r5\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9nCMxFzuSzehaAKQ9Y:-K9nSdKtJTHBQWByciP_:1930200565) ([raw file](https://github.com/valloric/ycmd/blob/c57fdf895c1f6a6b1980c215298cc81fa62e07c4/ycmd/completers/typescript/typescript_completer.py#L227)):*
Is Ok, can I do it? could be fun :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/344)*

**Comment by Valloric** [comment]
Looks great! I'm happy with merging this when @vheon is happy.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/344#-:-K9nU8nGyKcIVwozvK3A:-36082189)*

**Comment by icholy** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/typescript/typescript_completer.py, line 227 \[r5\]](https://reviewable.io:443/reviews/valloric/ycmd/344#-K9nCMxFzuSzehaAKQ9Y:-K9nUP87daVUPBFwSWa6:-1813078112) ([raw file](https://github.com/valloric/ycmd/blob/c57fdf895c1f6a6b1980c215298cc81fa62e07c4/ycmd/completers/typescript/typescript_completer.py#L227)):*
Go for it, I'm just lazy.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/344)*

**Comment by vheon** [comment]
:lgtm: too :+1:  @homu r+

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/344#-:-K9nUmzW7H2Ilr-NrVRt:1308524831)*

**Pull request merged**
