### PR TITLE
[Windows support] Add AppVeyor configuration

### PR DESCRIPTION
**Pull request by micbou**
@Valloric You can create an AppVeyor account or we can use mine. I will update the badge accordingly.

### CODE REVIEW

**Comment by Valloric** [comment]
@micbou I should probably create one. Let me figure out how to do that.

**Comment by Valloric** [comment]
OK, Appveyor account created. I also created a ycmd project, connecting it to the ycmd repo here. Do I need any custom settings? What's the next step?

**Comment by micbou** [comment]
The `appveyor.yml` file should be enough. I just need the code for the badge. You can found it in `Settings` then `Badges`.

**Comment by Valloric** [comment]
OK, I added you as a collaborator to: https://ci.appveyor.com/project/Valloric/ycmd

I've given you permissions to change settings, so you should be able to do that if necessary.

**Comment by Valloric** [comment]
Badge link: https://ci.appveyor.com/api/projects/status/6fetp5xwb0kkuv2w/branch/master?svg=true

**Comment by micbou** [comment]
Badge updated.

**Comment by Valloric** [comment]
Nice; let's wait for the appveyor build to complete.

**Comment by micbou** [comment]
It will fail. PRs #223, #227, and #230 are needed.

**Comment by Valloric** [comment]
Ah, ok. Let's merge this then.

For something like #223, you need to post a comment when you push a new commit. Github won't send me a notification for new commits on PRs.

**Comment by Valloric** [comment]
@homu r+

**Pull request merged**
