### PR TITLE
Fetch correct clang package for AArch64.

### PR DESCRIPTION
**Pull request by fhahn**
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/698)

### CODE REVIEW

**Comment by fhahn** [comment]
Currently the x86_64-opensuse13.2 build of clang is used on AArch64, which cannot be used to build ycmd on AArch64.

**Comment by vheon** [comment]
I can't test it right now but I trust that you need it and have tested this yourself. The code :lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/698#-:-KblI-r1JzjzFejXY8WL:bapydio)*

**Comment by Valloric** [comment]
This seems reasonable. Thanks for the PR!

@homu r=vheon

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/698#-:-KbmRcbJBxbq9-ZohnDM:b-2s8bcw)*

**Comment by fhahn** [comment]
Great, thanks for the quick review!

**Pull request merged**
