### PR TITLE
[READY] Enforce YCM coding style

### PR DESCRIPTION
**Pull request by micbou**
Add [the `flake8-ycm` plugin](https://github.com/micbou/flake8-ycm) to enforce the following rules:

| Code       | Description |
| --------- | -------- |
| YCM111 | indentation is not a multiple of two spaces
| YCM112 | expected an indented block of `n` spaces
| YCM114 | indentation is not a multiple of two spaces (comment)
| YCM115 | expected an indented block of `n` spaces (comment)
| YCM201 | exactly one space required after a left bracket
| YCM202 | exactly one space required before a right bracket
| YCM204 | no spaces between brackets for empty content

More rules will be added with time. The goal is to stop spending time discussing coding style on contributions.

Also, remove the E211 rule from Flake8 since I don't see a situation where putting spaces before a left parenthesis improve readability.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1047)

### CODE REVIEW

**Comment by bstaletic** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1047#-:-LDkcxo-1qKxd5zpDfPa:bg7igkv)*

**Comment by puremourning** [comment]
:lgtm: @zzbot r+

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1047#-:-LE-kQxr67XQnoBwQ6_f:by5ago3)*

**Comment by bstaletic** [comment]
@zzbot retry

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1047#-:-LE0PaIO7zpft7P0u6mJ:b-kc0oa4)*

**Comment by Valloric** [comment]
Ha, a flake8-ycm plugin! Fantastic work @micbou, this is awesome.

**Pull request merged**
