### PR TITLE
[READY] Fix missing matcher in Java GoTo tests

### PR DESCRIPTION
**Pull request by micbou**
The Java GoTo tests were always passing because the response was not a matcher object. Use the `has_entries` matcher and fix the class test by actually positioning the cursor on a class (and not on a constructor).

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/916)

### CODE REVIEW

**Comment by bstaletic** [comment]
Codecov is talking utter nonsense, but this is :lgtm:.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/916#-:-L4XsDxDcS1NgFp-Soad:b-tmhyt8)*

**Comment by puremourning** [comment]
:lgtm: Thanks for fixing!

@zzbot r+

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/916#-:-L4a3wcfJ6QGBEwHbdPJ:b-nehin7)*

**Comment by bstaletic** [comment]
@zzbot retry

**Comment by bstaletic** [comment]
@zzbot retry

**Pull request merged**
