### PR TITLE
[READY] Remove executable mode from test files

### PR DESCRIPTION
**Pull request by micbou**
Found three test files incorrectly set as executable.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/985)

### CODE REVIEW

**Comment by bstaletic** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/985#-:-L9J8j7OCCmb_CpdEdHC:bnfp4nl)*

**Comment by puremourning** [comment]
:lgtm:
@zzbot r+

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/985#-:-L9oohjP2N3p4DFUC3FS:bym5o3d)*

**Comment by micbou** [comment]
@zzbot retry

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/985#-:-L9r2pfUC-ChJ2i0w1Gr:b-kc0oa4)*

**Comment by micbou** [comment]
@zzbot retry

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/985#-:-L9t7RNB8XOZ1ikQb2t2:b-kc0oa4)*

**Comment by micbou** [comment]
@zzbot retry

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/985#-:-L9tzDn97Pt70Hml7WbF:b-kc0oa4)*

**Comment by micbou** [comment]
This is fun.

@zzbot retry

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/985#-:-L9ui_MxElWjUSdIpQ3N:bfenoaf)*

**Comment by bstaletic** [comment]
I'll try this time.
@zzbot retry

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/985#-:-L9vQJaW0moUwdwWYaMn:b-ckzmh4)*

**Pull request merged**
