### PR TITLE
[READY] Use ToUnicode for HMAC secret in Python completer

### PR DESCRIPTION
**Pull request by micbou**
This is what we do when starting the ycmd server in YCM.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/438)

### CODE REVIEW

**Comment by vheon** [comment]
Will this fix #432? I still didn't find the time to look into this (I'm swamped with work lately :sob: )

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/438#-:-KD_Cx-XEnI-D4R9VZGD:1441313086)*

**Comment by micbou** [comment]
I don't think so: `ToUnicode()` should be identical to `str( . , 'utf8' )` in this situation. 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/438#-:-KD_ENvjM33cY2KQgYOl:324188311)*

**Comment by puremourning** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/438#-:-KD_hMIfOJCk8D9Onyn4:1417088721)*

**Comment by vheon** [comment]
:lgtm: @homu r=puremourning

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/438#-:-KDeMuDsRdli-vaOyl5C:327595638)*

**Pull request merged**
