### PR TITLE
 [OS X support] [Windows support] Do not depend on std::string implementation specifics

### PR DESCRIPTION
**Pull request by micbou**
Since it was the same issue, I merged the OS X fix from @puremourning and my Windows fix to this PR. Thanks to him.

Fix 3 tests (3 failures) on OS X and Windows.

### CODE REVIEW

**Comment by onuraslan** [comment]
I think this test needs improvements. LLVM in debian/ubuntu is also returning: `std::string => std::__cxx11::basic_string<char>`

**Comment by puremourning** [comment]
Yeah. I suspect we should change the  test to exercise the behaviour without implementation specifics.

**Comment by micbou** [comment]
I don't think this is an issue because we support only one version of Clang for each platform. That said, I agree that tests not depending on implementation will be easier to maintain.

**Comment by Valloric** [comment]
I agree that we shouldn't have the test depend on platform specifics.

**Comment by micbou** [comment]
So how do we solve this? I see the following approachs:
 - removing those tests;
 - replacing them by ones testing platform-independent types;
 - testing that the result contains `basic_string` which is common to all platforms.

**Comment by puremourning** [comment]
I think the second. We can replicate the sort of equivalent with something like this:

```c++
namespace Test {
  template< typename T >
  struct _Test
  {
      _Test ( const char * );
      T test;
  };

  typedef _Test< int > Test;

  std::ostream& operator << ( std::ostream& o, const Test& test );
};
```

and

```c++
  Test::Test a = "hello";
  std::cout << a;
```

The tedious part is that all the offsets in the test will need tweaking

**Comment by oblitum** [comment]
just for sake of information, beware of naming: http://stackoverflow.com/a/228797/1000282.

**Comment by micbou** [comment]
So I followed @puremourning proposition. Seems to work fine.
Could someone check if the C++ code makes sense? I don't know much of C++.

**Comment by puremourning** [comment]
@micbou nice work. LGTM

**Comment by vheon** [comment]
@micbou LGTM too :+1:

**Comment by puremourning** [comment]
@homu r+

**Comment by Valloric** [comment]
Hm, homu seems to have not triggered on puremourning's comment. I need to figure out why.

**Comment by Valloric** [comment]
OK, I think I figured it out and fixed it. @puremourning could you try the whole homu r+ thing again so we can test out it works?

**Comment by puremourning** [comment]
Sure. 

@homu r+

**Pull request merged**
