### PR TITLE
Fix condition in build script

### PR DESCRIPTION
**Pull request by ptrv**

### CODE REVIEW

**Comment by ptrv** [comment]
Without the patch I get the following error
```
./build.sh: line 147: [: too many arguments
```
You can see the line also in the Travis log.

The solution is to quote the $cmake_args within the square brackets. The second problem is the condition. `=` and `!=` do not work with pattern matching. The condition won't be true. You can try it by running this: `./build.sh --system-libclang`, which should call `usage` and exit, but doesn't.

**Comment by Valloric** [comment]
You need to state you signed the Google CLA.

**Comment by Valloric** [comment]
Ah, I saw on a different pull request that you said you signed it. In the future though, you always need to state you signed it in every PR.

**Comment by Valloric** [comment]
Thanks for the PR!

**Comment by ptrv** [comment]
> In the future though, you always need to state you signed it in every PR.

Ok, got it

**Pull request merged**
