### PR TITLE
Update boost to boost-1.61.0

### PR DESCRIPTION
**Pull request by c-nixon**
Boost 1.61 was released today.

This release fixes a long-standing build error on cygwin64

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/490)

### CODE REVIEW

**Comment by Valloric** [comment]
I've made a terrible error in clicking "Files Changed" in the GitHub UI.

If you used the update_boost.sh script from our repo, I'll take your word for it. :)

Appveyor is failing though. Does not look like a flake. :lgtm:  if that's fixed.

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6171506)
> 
> Coverage remained the same at 84.957% when pulling **c32056e6d0fa8cd5461d904783a80c1973902bb2 on c-nixon:master** into **c17133357481c57607b93dab5bf86d4088bd22d7 on Valloric:master**.
> </details>


---

Review status: 0 of 278 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/490#-:-KHf2aOJNIQ3lZ6BB6dG:-2023763815)*

**Comment by vheon** [comment]
:lgtm: as long as @c-nixon used the update_boost.sh script ;)

<details><summary><i>Previously, Valloric (Val Markovic) wrote…</i></summary>
> I've made a terrible error in clicking "Files Changed" in the GitHub UI.
> 
> If you used the update_boost.sh script from our repo, I'll take your word for it. :)
> 
> Appveyor is failing though. Does not look like a flake. :lgtm:  if that's fixed.</details>


---

Review status: 0 of 278 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/490#-:-KHtXFoBx2Ab_olLHr3g:282263884)*

**Comment by c-nixon** [comment]
I did use the update_boost.sh script, yeh.

I'm having difficulty working out where the faulty parameter is being passed in as I don't have a windows machine to test.

Can anyone with access to msvc take a look? I might be able to find one somewhere, but it could be a while...

**Comment by vheon** [comment]
> Can anyone with access to msvc take a look? I might be able to find one somewhere, but it could be a while...

I'm pretty sure @micbou has a Windows machine 😜

**Comment by micbou** [comment]
I'll look into it.

**Pull request closed without merging**
