### PR TITLE
[READY] Add 'first_filetype' to RequestWrap

### PR DESCRIPTION
**Pull request by vheon**
I've noticed that the same snippet was found in more than one place so I think it deserves a name even though I'm not certain on the name itself but a more suitable didn't came to mind. I think next I'm going to tackle the `TODO` in `request_wrap.py` 👍

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/631)

### CODE REVIEW

**Comment by micbou** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/all/identifier_completer.py, line 57 at r1](https://reviewable.io:443/reviews/valloric/ycmd/631#-KUxli1kgFiGwKdLHKw3:-KUxli1l0tr_7BJu0mIj:b-2kwrtd) ([raw file](https://github.com/valloric/ycmd/blob/9554a6b7a9d9602aa9e93b97730ebf50187352b2/ycmd/completers/all/identifier_completer.py#L57)):*
> ```Python
>     completions = self._completer.CandidatesForQueryAndType(
>       ToCppStringCompatible( _SanitizeQuery( request_data[ 'query' ] ) ),
>       ToCppStringCompatible( request_data[ 'filetypes' ][ 0 ] ) )
> ```

We can use `first_filetype` here.

---

*[ycmd/completers/all/identifier_completer.py, line 164 at r1](https://reviewable.io:443/reviews/valloric/ycmd/631#-KUxmzamfZbuMyDS8EPk:-KUxmzano8KvlKqNLme1:b60g4in) ([raw file](https://github.com/valloric/ycmd/blob/9554a6b7a9d9602aa9e93b97730ebf50187352b2/ycmd/completers/all/identifier_completer.py#L164)):*
> ```Python
>     if 'syntax_keywords' in request_data:
>       self.AddIdentifiersFromSyntax( request_data[ 'syntax_keywords' ],
>                                      request_data[ 'filetypes' ] )
> ```

Looking at the `AddIdentifiersFromSyntax` function, we could directly pass `first_filetype` instead of `filetypes`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/631)*

**Comment by vheon** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/all/identifier_completer.py, line 57 at r1](https://reviewable.io:443/reviews/valloric/ycmd/631#-KUxli1kgFiGwKdLHKw3:-KUxwqug8dv5PMgbhCLi:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/9554a6b7a9d9602aa9e93b97730ebf50187352b2/ycmd/completers/all/identifier_completer.py#L57)):*
<details><summary><i>Previously, micbou wrote…</i></summary>
> We can use `first_filetype` here.
</details>
Done.

---

*[ycmd/completers/all/identifier_completer.py, line 164 at r1](https://reviewable.io:443/reviews/valloric/ycmd/631#-KUxmzamfZbuMyDS8EPk:-KUxwrmkVB3eHYX7pldg:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/9554a6b7a9d9602aa9e93b97730ebf50187352b2/ycmd/completers/all/identifier_completer.py#L164)):*
<details><summary><i>Previously, micbou wrote…</i></summary>
> Looking at the `AddIdentifiersFromSyntax` function, we could directly pass `first_filetype` instead of `filetypes`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/631)*

**Comment by micbou** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ycmd/completers/all/identifier_completer.py, line 198 at r3](https://reviewable.io:443/reviews/valloric/ycmd/631#-KV4JLAHD093SuyOdimj:-KV4JLAHD093SuyOdimk:bc11ato) ([raw file](https://github.com/valloric/ycmd/blob/06d560b80cf1a5677e6c71bb82d3e6f44917d94f/ycmd/completers/all/identifier_completer.py#L198)):*
> ```Python
>     filetype = request_data[ 'filetypes' ][ 0 ]
>   except KeyError:
>     filetype = None
> ```

You can't remove `filetype` here because it is used in local function `PreviousIdentifierOnLine`. We should probably add it as a parameter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/631)*

**Comment by Valloric** [comment]
:lgtm:

Thanks!

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/631#-:-KV60PsS5WwvpvIWRMbE:b9benhj)*

**Comment by micbou** [comment]
:lgtm:

@homu r+

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/631#-:-KV6lUD-qH5i6b2ExICM:b33slzv)*

**Pull request merged**
