### PR TITLE
[READY] Prevent (for good) multiple starts of OmniSharp server for same solution

### PR DESCRIPTION
**Pull request by micbou**
This PR adds locks to C♯ completer. One in `GetSolutionCompleter` to prevent multiple creation of the same solution completer and another in `StartServer` to prevent multiple starts of the OmniSharp server for the same solution.

Both locks are needed because if one is used for `GetSolutionCompleter` and none for `StartServer`, `StartServer` may be called by two threads inside the same `CsharpSolutionCompleter` object. Conversely (none for `GetSolutionCompleter` and one for `StartServer`), two distincts `CsharpSolutionCompleter` objects using the same solution may be created by two threads and each object will start its own server.

[Review on Reviewable](https://reviewable.io/reviews/valloric/ycmd/315)

### CODE REVIEW

**Comment by micbou** [comment]
Updated to use basic lock instead of reentrant lock.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/315#-:-K8RPLouflc-t9ee5d7s:-1551321420)*

**Comment by mispencer** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[ycmd/completers/cs/cs_completer.py, line 243 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/315#-K8RNAIvCv9K7iXIgc4o:-K8RNAIvCv9K7iXIgc4p:1509841165) ([raw file](https://github.com/valloric/ycmd/blob/6b64e2a9b6081e4eb998fc054f66dda5e3400ba5/ycmd/completers/cs/cs_completer.py#L243)):*
Why are we returning the result of `_StartServer`? Seeing this, my assumption as a reader of the code would be that `_StartServer` is returning something meaningful, but `_StartServer` never returns anything. Having the return separated from the `_StartServer` call communicates this clearer.

---

*[ycmd/completers/cs/cs_completer.py, line 365 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/315#-K8RNbNIw571bjxjIBCe:-K8RNbNIw571bjxjIBCf:-1602819549) ([raw file](https://github.com/valloric/ycmd/blob/6b64e2a9b6081e4eb998fc054f66dda5e3400ba5/ycmd/completers/cs/cs_completer.py#L365)):*
I would like to see a notice if ycmd is ignoring my completion command.

---

*[ycmd/completers/cs/cs_completer.py, line 406 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/315#-K8RPgp7oGbDw-fprU3u:-K8RPgp7oGbDw-fprU3v:-176205291) ([raw file](https://github.com/valloric/ycmd/blob/6b64e2a9b6081e4eb998fc054f66dda5e3400ba5/ycmd/completers/cs/cs_completer.py#L406)):*
`_StopServer` should probably be wrapped in the lock too?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/315)*

**Comment by puremourning** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[ycmd/completers/cs/cs_completer.py, line 365 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/315#-K8RNbNIw571bjxjIBCe:-K8RRkLOIJKWl8avMcA2:-1313036613) ([raw file](https://github.com/valloric/ycmd/blob/6b64e2a9b6081e4eb998fc054f66dda5e3400ba5/ycmd/completers/cs/cs_completer.py#L365)):*
I think this behaviour is roughly consistent with the other completers. Start server being idempotent i mean

---

*[ycmd/completers/cs/cs_completer.py, line 406 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/315#-K8RPgp7oGbDw-fprU3u:-K8RSPFlso0XL_CuBDhf:931772262) ([raw file](https://github.com/valloric/ycmd/blob/6b64e2a9b6081e4eb998fc054f66dda5e3400ba5/ycmd/completers/cs/cs_completer.py#L406)):*
I think you're right. We have to synchronise changes to all shared state.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/315)*

**Comment by micbou** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[ycmd/completers/cs/cs_completer.py, line 243 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/315#-K8RNAIvCv9K7iXIgc4o:-K8RcK0dysPE80kBuSfp:1203862950) ([raw file](https://github.com/valloric/ycmd/blob/6b64e2a9b6081e4eb998fc054f66dda5e3400ba5/ycmd/completers/cs/cs_completer.py#L243)):*
You are right. I reverted this change.

---

*[ycmd/completers/cs/cs_completer.py, line 365 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/315#-K8RNbNIw571bjxjIBCe:-K8RWrbr2uPu42asI1Ut:-852806129) ([raw file](https://github.com/valloric/ycmd/blob/6b64e2a9b6081e4eb998fc054f66dda5e3400ba5/ycmd/completers/cs/cs_completer.py#L365)):*
In both cases, the server is started which is what the user wants, no?

---

*[ycmd/completers/cs/cs_completer.py, line 406 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/315#-K8RPgp7oGbDw-fprU3u:-K8RSzEPfUlGp00GMfSN:-888452086) ([raw file](https://github.com/valloric/ycmd/blob/6b64e2a9b6081e4eb998fc054f66dda5e3400ba5/ycmd/completers/cs/cs_completer.py#L406)):*
Done even if I don't see a scenario where it could be harmful to have two threads simultaneously stopping the server.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/315)*

**Comment by puremourning** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[ycmd/completers/cs/cs_completer.py, line 406 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/315#-K8RPgp7oGbDw-fprU3u:-K8RegZbm-nf5lE6F-F_:-182515672) ([raw file](https://github.com/valloric/ycmd/blob/6b64e2a9b6081e4eb998fc054f66dda5e3400ba5/ycmd/completers/cs/cs_completer.py#L406)):*
But you could have 1 starting it and 1 stopping it simultaneously. So the left hand destroys what the right hand creates.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/315)*

**Comment by micbou** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[ycmd/completers/cs/cs_completer.py, line 406 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/315#-K8RPgp7oGbDw-fprU3u:-K8Rf-fQyG7HNcIj-82I:731413235) ([raw file](https://github.com/valloric/ycmd/blob/6b64e2a9b6081e4eb998fc054f66dda5e3400ba5/ycmd/completers/cs/cs_completer.py#L406)):*
Yes, I guess this is possible.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/315)*

**Comment by vheon** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[ycmd/completers/cs/cs_completer.py, line 448 \[r3\]](https://reviewable.io:443/reviews/valloric/ycmd/315#-K8VCddg5FCup9bdxJTa:-K8VCddg5FCup9bdxJTb:-1433633041) ([raw file](https://github.com/valloric/ycmd/blob/88854201fad1865364e96ee576b0a0afcb25beae/ycmd/completers/cs/cs_completer.py#L448)):*
Are we sure we don't need the lock here also? If so then we should use the reentrant lock.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/315)*

**Comment by micbou** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[ycmd/completers/cs/cs_completer.py, line 448 \[r3\]](https://reviewable.io:443/reviews/valloric/ycmd/315#-K8VCddg5FCup9bdxJTa:-K8WR3vOGtYGsWW77WgJ:251137552) ([raw file](https://github.com/valloric/ycmd/blob/88854201fad1865364e96ee576b0a0afcb25beae/ycmd/completers/cs/cs_completer.py#L448)):*
Better be safe than sorry. I added the (reentrant) lock. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/315)*

**Comment by vheon** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/315#-:-K8WXaYFTS7ma3jsHHOV:980077423)*

**Comment by puremourning** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[ycmd/completers/cs/cs_completer.py, line 365 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/315#-K8RNbNIw571bjxjIBCe:-K8npMXUkrsalQ32sdu1:-1804773369) ([raw file](https://github.com/valloric/ycmd/blob/6b64e2a9b6081e4eb998fc054f66dda5e3400ba5/ycmd/completers/cs/cs_completer.py#L365)):*
Exactly

---

*[ycmd/completers/cs/cs_completer.py, line 406 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/315#-K8RPgp7oGbDw-fprU3u:-K8npRZUbzfs9_mxQq-_:-1940772880) ([raw file](https://github.com/valloric/ycmd/blob/6b64e2a9b6081e4eb998fc054f66dda5e3400ba5/ycmd/completers/cs/cs_completer.py#L406)):*
Someone once said "I have a problem" and decided to use threads. Thte heyn 2 hprobad lems.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/315)*

**Comment by puremourning** [comment]
:lgtm: 

@homu r+

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/315#-:-K8nqB5F8lzouzYGJLSP:902839417)*

**Comment by puremourning** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/315)*

**Pull request merged**
