### PR TITLE
Add GetDoc command for rust completer

### PR DESCRIPTION
**Pull request by dpzmick**
I've updated `racerd` (https://github.com/jwilm/racerd/commit/e4731aaa5af6f972ae49ed84a7f570ad4ac5f4e5) to include the docs in its response, so we can now easily add this to ycmd.

Are there any docs which I should also update with this change when if it can be merged?

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/628)

### CODE REVIEW

**Comment by dpzmick** [comment]
I've made a remark about one line I have a concern about after reading through the code here. Let me take a look at it again before merging (if anyone gets to this before I do)

**Comment by Valloric** [comment]
Thanks for the PR!

@jwilm Could you take a look at this?

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/628#-:-KUOp2QNDyzhKI8s2OUX:b-ivgpvr)*

**Comment by jwilm** [comment]
LGTM aside from a couple of nits

---

Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[ycmd/completers/rust/rust_completer.py, line 384 at r1](https://reviewable.io:443/reviews/valloric/ycmd/628#-KUOsinC60cwJjs9OIib:-KUOsinC60cwJjs9OIic:bf0u7eo) ([raw file](https://github.com/valloric/ycmd/blob/fac15873336d3ed1bc82c1cffaff743c9810734e/ycmd/completers/rust/rust_completer.py#L384)):*
> ```Python
>                            self._RestartServer() ),
>       'GetDoc' : ( lambda self, request_data, args:
>                            self._GetDoc(request_data) ),
> ```

nit: spaces around `request_data`

---

*[ycmd/completers/rust/rust_completer.py, line 405 at r1](https://reviewable.io:443/reviews/valloric/ycmd/628#-KUOsnvaOLdGM8sjjNfs:-KUOsnvaOLdGM8sjjNft:bxpesib) ([raw file](https://github.com/valloric/ycmd/blob/fac15873336d3ed1bc82c1cffaff743c9810734e/ycmd/completers/rust/rust_completer.py#L405)):*
> ```Python
> 
>       docs = [definitions['context'], definitions['docs']]
>       return responses.BuildDetailedInfoResponse('\n---\n'.join(docs))
> ```

nit: need spaces within parens braces on these couple of lines

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/628#-:-KUOssOT5F7sUcnHHsje:b-bmca0n)*

**Comment by dpzmick** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/rust/rust_completer.py, line 384 at r1](https://reviewable.io:443/reviews/valloric/ycmd/628#-KUOsinC60cwJjs9OIib:-KUPXzZbDbpD5wiY9ZAZ:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/fac15873336d3ed1bc82c1cffaff743c9810734e/ycmd/completers/rust/rust_completer.py#L384)):*
<details><summary><i>Previously, jwilm (Joe Wilm) wrote…</i></summary>
> nit: spaces around `request_data`
</details>
Done.

---

*[ycmd/completers/rust/rust_completer.py, line 405 at r1](https://reviewable.io:443/reviews/valloric/ycmd/628#-KUOsnvaOLdGM8sjjNfs:-KUPXyfcs1Ez04AX5k0_:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/fac15873336d3ed1bc82c1cffaff743c9810734e/ycmd/completers/rust/rust_completer.py#L405)):*
<details><summary><i>Previously, jwilm (Joe Wilm) wrote…</i></summary>
> nit: need spaces within parens braces on these couple of lines
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/628)*

**Comment by Valloric** [comment]
:lgtm:

Agreed, this looks nice. Thanks for doing this!

@micbou @vheon @puremourning Could one of you provide another review? Ty!

---

Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[ycmd/tests/rust/subcommands_test.py, line 68 at r2](https://reviewable.io:443/reviews/valloric/ycmd/628#-KUQPn3vRdoWC7YFXaN9:-KUQPn3vRdoWC7YFXaNA:bqxjudc) ([raw file](https://github.com/valloric/ycmd/blob/44a9b726745b9f2886aa5296f6d7d5a707f449f8/ycmd/tests/rust/subcommands_test.py#L68)):*
> ```Python
> @SharedYcmd
> def Subcommands_GetDoc_Method_test( app ):
>   # Testcase1
> ```

Do we need this comment? I don't see much benefit to it...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/628#-:-KUQPu9iv5BiaE8F3h8x:b4h46cu)*

**Comment by Valloric** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/628)*

**Comment by micbou** [comment]
Is it possible to write a test that cover the `except` part of `_GetDoc`?

---

Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/628#-:-KUQSV2Gk-iidRvQnOxc:b-r2l8fc)*

**Comment by Valloric** [comment]
> Is it possible to write a test that cover the except part of _GetDoc?

Excellent point. I just noticed Coveralls is saying the coverage for the diff is 62.50%. It needs to be >95%.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/628#-:-KUQW7KNjFrUC-ie8U9O:b6gpihu)*

**Comment by dpzmick** [comment]
The failing travis build seems to be unrelated to the code I've changed. Do I need to do something about this?

**Comment by dpzmick** [comment]
I'm not sure this additional testing is the best kind of testing I can do here. I've copied the exception handling from the code for the go to definition subcommand in the rust file, so its just catching Exception.

There's lots of cases here that are not being tested, but I can easily bump up the code coverage.

---

Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/628#-:-KUQTanMrMkVKEKmNDWJ:b-dzvzig)*

**Comment by puremourning** [comment]
:lgtm:

Thanks!

---

Reviewed 1 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/628#-:-KUW8vLzwlHdFjd60hNZ:b9benhj)*

**Comment by micbou** [comment]
> I'm not sure this additional testing is the best kind of testing I can do here. I've copied the exception handling from the code for the go to definition subcommand in the rust file, so its just catching Exception.
> 
> There's lots of cases here that are not being tested, but I can easily bump up the code coverage.

It's good enough for me.

:lgtm:

@homu r+

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/628#-:-KUWI7WnRfs3BixuEYRZ:b-cxyrfv)*

**Pull request merged**
