### PR TITLE
Make use of CXTranslationUnit_CreatePreambleOnFirstParse.

### PR DESCRIPTION
**Pull request by d0k**
This significantly speeds up the first parse of a C++ file because it
now builds the precompiled preamble immediately instead of depending on
another reparse step. This is a new feature that's only available in
Clang trunk so far (r255635), but older libclangs will just ignore the
flag.

The unnecessary reparse is still in place for backwards compatibility
but since the preamble is available it is much faster. It should be
removed after ycmd moves to Clang 3.8.

[Review on Reviewable](https://reviewable.io/reviews/valloric/ycmd/275)

### CODE REVIEW

**Comment by vheon** [comment]
I don't know if it make sense to merge this right now instead of waiting for libclang 3.8 to come out :confused: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/275#-:-K5gWC0xFgpJ82-ykmu8:170452682)*

**Comment by r4nt** [comment]
As this is completely backwards compatible, it seems like it would be a strict improvement for people already using newer libclangs?

**Comment by Valloric** [comment]
If it's backwards compatible, I say we go for it.

@d0k @r4nt Can I rely on one of you sending a cleanup PR when libclang 3.8 goes out?  ycmd usually updates to latest libclang a day or so after it's released. The rest of us are likely to forget about this hack.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/275#-:-K5n-YCBLoMD0r0dtp1T:-1670879293)*

**Comment by Valloric** [comment]
Oh, and thanks for fixing the underlying libclang issue!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/275#-:-K5n0_YDLsB4HoT-1QRQ:-2074084376)*

**Comment by Valloric** [comment]
This PR also needs to bump the version in CORE_VERSION so that users recompile ycmd.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/275#-:-K5n0ti3bRwcj_-Qsq_U:1870724988)*

**Comment by d0k** [comment]
Patch updated with CORE_VERSION bump. I'll clean up the TODOs when libclang 3.8 is out and ycmd adopted it.

**Comment by Valloric** [comment]
Thanks! 

@homu r+

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/275#-:-K5sWrEnBX6bGeen9Jdz:231695447)*

**Pull request merged**
