### PR TITLE
[READY] Migrate to GOPLS

### PR DESCRIPTION
**Pull request by bstaletic**
It took a while, but it should work now. The gopls commit is pinned, because `go get -u` breaks daily.

Supports:

- Completion
- Diagnostics
- Format (but only whole file)
- GoTo
- GoToDefintion
- GoToDeclaration (via GoToDefinition)
- GoToType
- RestartServer
- FixIt\*

Limitations:

- If any parent directory is named `test_data`, gopls doesn't work. This is a feature!
- If the file being edited isn't in a module or in the `$GOPATH`, gopls won't be able to parse it.
- If the file is inside a module directory or inside `$GOPATH` but doesn't obey `domain/owner/project` directory hierarchy, gopls won't work.
- If the hierarchy is correct, but the file that declares `package foo` isn't in directory `domain/owner/project/foo`, gopls won't work. 

This is all in line with the standard golang project structure, but it means that a quick `vim foo.go` is impossible.

Fixes https://github.com/Valloric/ycmd/issues/1217

\* Fixits behave od. `gopls` really wants to format the code even if it is unrelated to the actual FixIt reported. (check what the `Subocommands_FixIt_Simple_test()` is doing).

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1243)

### CODE REVIEW

**Comment by bstaletic** [comment]
Turns out `gopls` supports `FixIts`, so added support for that.

Though, it behaves weird. It really wants to format the code even if it is unrelated to the actual FixIt reported. (check what the `Subocommands_FixIt_Simple_test()` is doing).

**Comment by rajathagasthya** [comment]
Any ETA on this? Looking forward to trying out Gopls with YCM.

**Comment by bstaletic** [comment]
You can always merge it locally. ETA is whenver it gets reviewed.

To merge it locally, you need to do the following:

- `cd YouCompleteMe/third_party/ycmd`
- `git fetch origin +refs/pull/1243/merge:gopls`
- `git submodule update --init --recursive`
- `./build.py --skip-build --go-completer`

**Comment by orlangure** [comment]
> To merge it locally, you need to do the following:

@bstaletic, this does not seem to work, I'm still seeing `gocode` processes started by the plugin. Do I need to add anything to configuration to make the switch?

**Comment by mjolk** [comment]
@orlangure after git fetch ... you need to run git checkout gopls, then run git submodule update ... etc
@bstaletic great work! thanks!

**Comment by orlangure** [comment]
> after git fetch ... you need to run git checkout gopls, then run git submodule update

@mjolk, thanks, I see now that the original comment was also edited.
@bstaletic works great, thank you!

**Comment by preslavmihaylov** [comment]
This is great. I just ran into the problem fixed by this MR and was about to open a new issue.

Can't wait for the final LGTM to approve this and get it merged.

**Comment by puremourning** [comment]
Ship It.

Multiple users have expressed interest in this PR and I have reviewed it. It net reduces our code and thus liability and increases functionality for users.

**Comment by bstaletic** [comment]
For everyone watching this thread... I messed up the rebase and we have merged a broken completer. #1257 fixes this and it's literally a two character fix.

**Pull request merged**
