### PR TITLE
[READY] Clang-tidy - readability checks

### PR DESCRIPTION
**Pull request by bstaletic**
- Prohibits implicit cast to bool
- vector::empty() instead of vector::size() for checking empty vectors

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/992)

### CODE REVIEW

**Comment by micbou** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[cpp/ycm/CandidateRepository.h, line 62 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/992#-L9kLwVWBY3ad-HcYJWQ:-L9kLwVWBY3ad-HcYJWR:b-bsd2hr) ([raw file](https://github.com/valloric/ycmd/blob/373503a857fc018353f8de7fc3c4b859289a14de/cpp/ycm/CandidateRepository.h#L62)):*
> ```objc
>   ~CandidateRepository() = default;
> 
>   const std::string &ValidatedCandidateText( const std::string &candidate_text );
> ```

80 characters.

---

*[cpp/ycm/CodePoint.cpp, line 64 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/992#-L9kKtuCCVp0y6cIwXso:-L9kKtuCCVp0y6cIwXsp:b-yw3b6k) ([raw file](https://github.com/valloric/ycmd/blob/373503a857fc018353f8de7fc3c4b859289a14de/cpp/ycm/CodePoint.cpp#L64)):*
> ```cpp
>     if ( cmp == 0 ) {
>       return *it;
> }
> ```

Missing indentation.

---

*[cpp/ycm/CodePoint.cpp, line 70 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/992#-L9kKv4t-R3Rb_HQjTDO:-L9kKv4t-R3Rb_HQjTDP:b-yw3b6k) ([raw file](https://github.com/valloric/ycmd/blob/373503a857fc018353f8de7fc3c4b859289a14de/cpp/ycm/CodePoint.cpp#L70)):*
> ```cpp
>     } else {
>       count = step;
> }
> ```

Missing indentation.

---

*[cpp/ycm/IdentifierDatabase.cpp, line 96 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/992#-L9kKxcb4x7VB_ay0wIL:-L9kKxcb4x7VB_ay0wIM:bsk41j6) ([raw file](https://github.com/valloric/ycmd/blob/373503a857fc018353f8de7fc3c4b859289a14de/cpp/ycm/IdentifierDatabase.cpp#L96)):*
> ```cpp
>         } 
>           seen_candidates.insert( candidate );
>         
> ```

Trailing spaces.

---

*[cpp/ycm/Result.cpp, line 107 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/992#-L9kL3x00diinqNJ8Nh6:-L9kL3x00diinqNJ8Nh7:b-yw3b6k) ([raw file](https://github.com/valloric/ycmd/blob/373503a857fc018353f8de7fc3c4b859289a14de/cpp/ycm/Result.cpp#L107)):*
> ```cpp
>          other.first_char_same_in_query_and_text_ ) {
>       return first_char_same_in_query_and_text_;
> }
> ```

Missing indentation.

---

*[cpp/ycm/Word.cpp, line 42 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/992#-L9kL6927LxwInpqKXCc:-L9kL6927LxwInpqKXCd:b-yw3b6k) ([raw file](https://github.com/valloric/ycmd/blob/373503a857fc018353f8de7fc3c4b859289a14de/cpp/ycm/Word.cpp#L42)):*
> ```cpp
>   if ( code_point_pos == code_points.end() ) {
>     return characters;
> }
> ```

Missing indentation.

---

*[cpp/ycm/ClangCompleter/ClangCompleter.cpp, line 42 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/992#-L9knXAWE00d_nClFsWu:-L9knXAWE00d_nClFsWv:b-s8oom1) ([raw file](https://github.com/valloric/ycmd/blob/373503a857fc018353f8de7fc3c4b859289a14de/cpp/ycm/ClangCompleter/ClangCompleter.cpp#L42)):*
> ```cpp
>   // I'm pretty sure it's turned on by default, but I'm not going to take any
>   // chances.
>   clang_toggleCrashRecovery( 1u );
> ```

Does clang-tidy complain if the `u` is missing?

---

*[cpp/ycm/ClangCompleter/ClangHelpers.cpp, line 218 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/992#-L9kLUxz50Z7eF3ltGfm:-L9kLUxz50Z7eF3ltGfn:b-brwl1e) ([raw file](https://github.com/valloric/ycmd/blob/373503a857fc018353f8de7fc3c4b859289a14de/cpp/ycm/ClangCompleter/ClangHelpers.cpp#L218)):*
> ```cpp
>   std::vector< CompletionData > completions;
> 
>   if ( (results == nullptr) || (results->Results == nullptr) ) {
> ```

I don't think the parentheses are needed.

---

*[cpp/ycm/ClangCompleter/ClangUtils.cpp, line 36 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/992#-L9kLZahCO1DVGQbX2Z-:-L9kLZahCO1DVGQbX2Z0:b1ak36s) ([raw file](https://github.com/valloric/ycmd/blob/373503a857fc018353f8de7fc3c4b859289a14de/cpp/ycm/ClangCompleter/ClangUtils.cpp#L36)):*
> ```cpp
> bool CursorIsValid( CXCursor cursor ) {
>   return (clang_Cursor_isNull( cursor ) == 0) &&
>          (clang_isInvalid( clang_getCursorKind( cursor ) ) == 0u);
> ```

Same comment.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/992)*

**Comment by bstaletic** [comment]
Review status: 6 of 15 files reviewed at latest revision, 9 unresolved discussions.

---

*[cpp/ycm/CandidateRepository.h, line 62 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/992#-L9kLwVWBY3ad-HcYJWQ:-L9kvuwEEptLDJjQn2GW:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/373503a857fc018353f8de7fc3c4b859289a14de/cpp/ycm/CandidateRepository.h#L62)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

80 characters.
</blockquote></details>

Done.

---

*[cpp/ycm/CodePoint.cpp, line 64 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/992#-L9kKtuCCVp0y6cIwXso:-L9kv3vNCGHmZyODri-2:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/373503a857fc018353f8de7fc3c4b859289a14de/cpp/ycm/CodePoint.cpp#L64)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Missing indentation.
</blockquote></details>

Done.

---

*[cpp/ycm/CodePoint.cpp, line 70 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/992#-L9kKv4t-R3Rb_HQjTDO:-L9kv4RSCtWG4BIry_DV:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/373503a857fc018353f8de7fc3c4b859289a14de/cpp/ycm/CodePoint.cpp#L70)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Missing indentation.
</blockquote></details>

Done.

---

*[cpp/ycm/IdentifierDatabase.cpp, line 96 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/992#-L9kKxcb4x7VB_ay0wIL:-L9kvH1N7vq2rzdDbEfx:bpa5nx5) ([raw file](https://github.com/valloric/ycmd/blob/373503a857fc018353f8de7fc3c4b859289a14de/cpp/ycm/IdentifierDatabase.cpp#L96)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Trailing spaces.
</blockquote></details>

Real smart of clang-tidy.

Done.

---

*[cpp/ycm/Result.cpp, line 107 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/992#-L9kL3x00diinqNJ8Nh6:-L9kvRt-6OP37_EQzsID:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/373503a857fc018353f8de7fc3c4b859289a14de/cpp/ycm/Result.cpp#L107)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Missing indentation.
</blockquote></details>

Done.

---

*[cpp/ycm/Word.cpp, line 42 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/992#-L9kL6927LxwInpqKXCc:-L9kvaVP2Gfec_r4Dr_L:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/373503a857fc018353f8de7fc3c4b859289a14de/cpp/ycm/Word.cpp#L42)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Missing indentation.
</blockquote></details>

Done.

---

*[cpp/ycm/ClangCompleter/ClangCompleter.cpp, line 42 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/992#-L9knXAWE00d_nClFsWu:-L9kwNIAA05155LYW_yj:bxaab2p) ([raw file](https://github.com/valloric/ycmd/blob/373503a857fc018353f8de7fc3c4b859289a14de/cpp/ycm/ClangCompleter/ClangCompleter.cpp#L42)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Does clang-tidy complain if the `u` is missing?
</blockquote></details>

It doesn't! It's just what is in its FixIt.
Removed here and in other places.

---

*[cpp/ycm/ClangCompleter/ClangHelpers.cpp, line 218 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/992#-L9kLUxz50Z7eF3ltGfm:-L9kxDjH3p-HvJQc-ahl:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/373503a857fc018353f8de7fc3c4b859289a14de/cpp/ycm/ClangCompleter/ClangHelpers.cpp#L218)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

I don't think the parentheses are needed.
</blockquote></details>

Done.

---

*[cpp/ycm/ClangCompleter/ClangUtils.cpp, line 36 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/992#-L9kLZahCO1DVGQbX2Z-:-L9kxNK_Esgdm_xM0-sJ:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/373503a857fc018353f8de7fc3c4b859289a14de/cpp/ycm/ClangCompleter/ClangUtils.cpp#L36)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Same comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/992)*

**Comment by micbou** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cpp/ycm/IdentifierDatabase.cpp, line 96 at r1](https://beta.reviewable.io/reviews/valloric/ycmd/992#-L9kKxcb4x7VB_ay0wIL:-L9kyYRv2UElETyFQD6v:b-2bsmc7) ([raw file](https://github.com/valloric/ycmd/blob/373503a857fc018353f8de7fc3c4b859289a14de/cpp/ycm/IdentifierDatabase.cpp#L96)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Real smart of clang-tidy.

Done.
</blockquote></details>

One blank line is enough.

---

*[cpp/ycm/ClangCompleter/ClangHelpers.cpp, line 218 at r2](https://beta.reviewable.io/reviews/valloric/ycmd/992#-L9kyi8G1TqAg98NrS8Y:-L9kyi8G1TqAg98NrS8Z:bg81q56) ([raw file](https://github.com/valloric/ycmd/blob/9628d7e923e8dbaa2b9a0dd3ec09636ae1310966/cpp/ycm/ClangCompleter/ClangHelpers.cpp#L218)):*
> ```cpp
>   std::vector< CompletionData > completions;
> 
>   if ( results == nullptr || results->Results == nullptr) {
> ```

Missing space before the closing parenthesis.

---

*[cpp/ycm/ClangCompleter/ClangUtils.cpp, line 36 at r2](https://beta.reviewable.io/reviews/valloric/ycmd/992#-L9kyqJ6CBxdyYjgQ6KQ:-L9kyqJ6CBxdyYjgQ6KR:bvo68kd) ([raw file](https://github.com/valloric/ycmd/blob/9628d7e923e8dbaa2b9a0dd3ec09636ae1310966/cpp/ycm/ClangCompleter/ClangUtils.cpp#L36)):*
> ```cpp
> bool CursorIsValid( CXCursor cursor ) {
>   return clang_Cursor_isNull( cursor ) == 0 &&
>          clang_isInvalid( clang_getCursorKind( cursor ) ) == 0u;
> ```

`0` instead of `0u`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/992)*

**Comment by micbou** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/992#-:-L9nHWvxBeOhQU0HLCmD:bnfp4nl)*

**Comment by puremourning** [comment]
Generally, I think the `nullptr` and `== 0` checks are net worse in practice and I would vote to disable them.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[cpp/ycm/ClangCompleter/ClangHelpers.cpp, line 108 at r3](https://beta.reviewable.io/reviews/valloric/ycmd/992#-LA4RdUdBo8M3g2e7WZi:-LA4RdUdBo8M3g2e7WZj:b-nudq9u) ([raw file](https://github.com/valloric/ycmd/blob/f49c3260c6c902840f7817d9690ed2b96b1b7851/cpp/ycm/ClangCompleter/ClangHelpers.cpp#L108)):*
> ```cpp
>   CXDiagnosticSet diag_set = clang_getChildDiagnostics( diagnostic );
> 
>   if ( diag_set == nullptr ) {
> ```

This one seems wrong. We don't know that CXDiagnosticSet is even a pointer (semantically). It could be changed upstream, as its type is opaque to us.

---

*[cpp/ycm/ClangCompleter/ClangHelpers.cpp, line 121 at r3](https://beta.reviewable.io/reviews/valloric/ycmd/992#-LA4RxgH5EvpFKQnkX5K:-LA4RxgH5EvpFKQnkX5L:bo8y2lt) ([raw file](https://github.com/valloric/ycmd/blob/f49c3260c6c902840f7817d9690ed2b96b1b7851/cpp/ycm/ClangCompleter/ClangHelpers.cpp#L121)):*
> ```cpp
>     CXDiagnostic child_diag = clang_getDiagnosticInSet( diag_set, i );
> 
>     if( child_diag == nullptr ) {
> ```

Ditto here.

If I'm honest, I don't like this rule at all. It makes the logic for the checks backwards and it requires unnecessary verbosity (IMO).

---

*[cpp/ycm/ClangCompleter/ClangHelpers.cpp, line 138 at r3](https://beta.reviewable.io/reviews/valloric/ycmd/992#-LA4S6xr9hQYR-SgAAmi:-LA4S6xr9hQYR-SgAAmj:bkkjs1q) ([raw file](https://github.com/valloric/ycmd/blob/f49c3260c6c902840f7817d9690ed2b96b1b7851/cpp/ycm/ClangCompleter/ClangHelpers.cpp#L138)):*
> ```cpp
> // deprecated etc.
> bool CompletionStringAvailable( CXCompletionString completion_string ) {
>   if ( completion_string == nullptr ) {
> ```

And here

---

*[cpp/ycm/ClangCompleter/ClangUtils.cpp, line 35 at r3](https://beta.reviewable.io/reviews/valloric/ycmd/992#-LA4SDrW3e42e7ee8MEi:-LA4SDrW3e42e7ee8MEj:b5uj4qh) ([raw file](https://github.com/valloric/ycmd/blob/f49c3260c6c902840f7817d9690ed2b96b1b7851/cpp/ycm/ClangCompleter/ClangUtils.cpp#L35)):*
> ```cpp
> 
> bool CursorIsValid( CXCursor cursor ) {
>   return clang_Cursor_isNull( cursor ) == 0 &&
> ```

Not a fan of this change. The API dearly intends to be used like a bool. Either that or it should define a constant "OK" value. I suspect this is just a poor API which we shouldn't have to pay for in unnecessary and awkward verbosity and reversed logic. It's not like this is a strcmp-like interface, right?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/992#-:-LA4S_s_5EAiMRlkjXje:b-1ql6u2)*

**Comment by bstaletic** [comment]
Sure, I can revert `nullptr` and `== 0` - I too feel it's a little too verbose.
As for the clang-tidy check, it basically prohibits all implicit bool conversions. In other words, we either keep them all or skip the check completely.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/992#-:-LA4TfQY7AEAhDUkYy6v:bo18n0v)*

**Comment by bstaletic** [comment]
I've reverted the implicit bool check except  for `.empty()` instead of `.size() > 0`, which I do think reads better.

---

Review status: 7 of 9 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/992#-:-LABpG4u4Kp81jOO-Ijg:b-rh7kis)*

**Comment by micbou** [comment]
Reviewed 3 of 8 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[cpp/ycm/ClangCompleter/TranslationUnit.cpp, line 94 at r4](https://beta.reviewable.io/reviews/valloric/ycmd/992#-LAGIhnP0GbqZDfyxdPL:-LAGIhnP0GbqZDfyxdPM:bi8oyok) ([raw file](https://github.com/valloric/ycmd/blob/ae95ae3f34de20363659dcb27c3e9e45e002ba0d/cpp/ycm/ClangCompleter/TranslationUnit.cpp#L94)):*
> ```cpp
>     ToCXUnsavedFiles( unsaved_files );
>   const CXUnsavedFile *unsaved = !cxunsaved_files.empty()
>                                  ? &cxunsaved_files[ 0 ] : nullptr;
> ```

We could drop the `!` by rewriting it as
```c++
cxunsaved_files.empty() ? nullptr : &cxunsaved_files[ 0 ];
```
Same comment for the other changes in that file.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/992)*

**Comment by bstaletic** [comment]
Review status: 8 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[cpp/ycm/ClangCompleter/TranslationUnit.cpp, line 94 at r4](https://beta.reviewable.io/reviews/valloric/ycmd/992#-LAGIhnP0GbqZDfyxdPL:-LAHDu9G6ANm8iqJZLDz:b-896fix) ([raw file](https://github.com/valloric/ycmd/blob/ae95ae3f34de20363659dcb27c3e9e45e002ba0d/cpp/ycm/ClangCompleter/TranslationUnit.cpp#L94)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

We could drop the `!` by rewriting it as
```c++
cxunsaved_files.empty() ? nullptr : &cxunsaved_files[ 0 ];
```
Same comment for the other changes in that file.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/992)*

**Comment by micbou** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/992#-:-LAIPtnY6qvH9o1oDCbg:b-jbsf8z)*

**Comment by puremourning** [comment]
:lgtm: though the tests failed?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/992#-:-LAhZChy3lUrQXdyPiw9:bpreu0u)*

**Comment by micbou** [comment]
@zzbot r+

---

Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/992#-:-LAllkchCH4qx6FVti6E:bi59kwd)*

**Comment by micbou** [comment]
@zzbot r+

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/valloric/ycmd/992#-:-LAm_YisD2pBNoFWyaia:bi59kwd)*

**Pull request merged**
