### PR TITLE
[READY] Rust completer debug info uses unicode host

### PR DESCRIPTION
**Pull request by Valloric**
cc @puremourning

[Review on Reviewable](https://reviewable.io/reviews/valloric/ycmd/408)

### CODE REVIEW

**Comment by micbou** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[ycmd/completers/rust/rust_completer.py, line 292 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/408#-KBgxA6RbpNKoWNm_KuF:-KBgxA6RbpNKoWNm_KuG:488698198) ([raw file](https://github.com/valloric/ycmd/blob/abe2e1c1145bcf865a5d0c265214f871576644ec/ycmd/completers/rust/rust_completer.py#L292)):*
Instead of converting `_racerd_host` here, we should convert it in `_GetResponse`. This way, no need to use `ToUnicode` or `ToBytes` in other places.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/408)*

**Comment by Valloric** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/completers/rust/rust_completer.py, line 292 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/408#-KBgxA6RbpNKoWNm_KuF:-KBiWfiA-EgWMwosu7La:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/abe2e1c1145bcf865a5d0c265214f871576644ec/ycmd/completers/rust/rust_completer.py#L292)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/408)*

**Comment by micbou** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/408#-:-KBiYxoBW6MtR1plscG6:1417088721)*

**Comment by vheon** [comment]
:lgtm: @homu r+

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/408#-:-KBjCoRjH-ypEAcKd3x5:-141632775)*

**Pull request merged**
