### PR TITLE
Bump Tern to version 0.20

### LINKED ISSUE #638: Tern 0.20 update
Are there any blockers for bumping up from 0.19?

### PR DESCRIPTION
**Pull request by mixedCase**
Closes #638.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/639)

### CODE REVIEW

**Comment by micbou** [comment]
Thanks.

:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/639#-:-KVidTH3qNkTHmGFntqi:bvbpn64)*

**Comment by vheon** [comment]
:lgtm: @homu r=micbou

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/639#-:-KViuo02xnzdj2_Lgl0W:b-v6qh3o)*

**Comment by vheon** [comment]
Looks like a spurious fail. @homu retry

**Comment by mixedCase** [comment]
That's another timeout.

**Comment by puremourning** [comment]
@homu retry

**Comment by puremourning** [comment]
@homu r=micbou

**Pull request merged**
