### PR TITLE
[READY] Make python binary specifiable by the user

### PR DESCRIPTION
**Pull request by vheon**
I'm starting this PR as WIP because it lacks tests and I wanted to ask for suggestion about that. What do you think would be the best approach? I was thinking about configuring the `user_option` and check how the `utils.SafePopen` was called but in general I'm not a fan of this kind of tests, so I'm open to suggestion :smiley:

[Review on Reviewable](https://reviewable.io/reviews/valloric/ycmd/295)

### CODE REVIEW

**Comment by Valloric** [comment]
I don't see anything wrong with this approach. :)

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[ycmd/completers/python/jedi_completer.py, line 75 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/295#-K7ZKWIgl_yzAIWj4J2z:-K7ZKWIgl_yzAIWj4J3-:217846983) ([raw file](https://github.com/valloric/ycmd/blob/97dacdc262155d2417ecb1fcb4a9bfff35a8c622/ycmd/completers/python/jedi_completer.py#L75)):*
`binary_path` is a bit too generic. Perhaps `_python_binary_path`? Similar for `binary` variable in other function params/locals.

---

*[ycmd/completers/python/jedi_completer.py, line 78 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/295#-K7ZKHR2xzaBdj4VkZoo:-K7ZKHR2xzaBdj4VkZop:1093233815) ([raw file](https://github.com/valloric/ycmd/blob/97dacdc262155d2417ecb1fcb4a9bfff35a8c622/ycmd/completers/python/jedi_completer.py#L78)):*
Why not just `self._UpdatePythonBinary( user_options.get(...) )`

---

*[ycmd/completers/python/jedi_completer.py, line 91 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/295#-K7ZKhDw0Y4e2X3JM4ib:-K7ZKhDw0Y4e2X3JM4ic:275040289) ([raw file](https://github.com/valloric/ycmd/blob/97dacdc262155d2417ecb1fcb4a9bfff35a8c622/ycmd/completers/python/jedi_completer.py#L91)):*
This isn't binary specific; maybe `CheckFileExists`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295#-:-K7ZL89Ax-TT0tnFiP0v:-1476090519)*

**Comment by vheon** [comment]
Ok, then I will try it.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[ycmd/completers/python/jedi_completer.py, line 91 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/295#-K7ZKhDw0Y4e2X3JM4ib:-K7aEO76au9DbkNxFM1b:-494473069) ([raw file](https://github.com/valloric/ycmd/blob/97dacdc262155d2417ecb1fcb4a9bfff35a8c622/ycmd/completers/python/jedi_completer.py#L91)):*
IIRC the Tern completer have the same function for the same purpose (mocking it during the test), what do you think of refactor it into a common module? maybe the `utils` module.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295#-:-K7a9OvWX5-v2ATjCbu5:-1985678347)*

**Comment by vheon** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[ycmd/completers/python/jedi_completer.py, line 75 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/295#-K7ZKWIgl_yzAIWj4J2z:-K7aF39w246j4lJdZkL-:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/97dacdc262155d2417ecb1fcb4a9bfff35a8c622/ycmd/completers/python/jedi_completer.py#L75)):*
Done.

---

*[ycmd/completers/python/jedi_completer.py, line 78 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/295#-K7ZKHR2xzaBdj4VkZoo:-K7aF3sh09fRQFIQvcOn:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/97dacdc262155d2417ecb1fcb4a9bfff35a8c622/ycmd/completers/python/jedi_completer.py#L78)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295)*

**Comment by renstrom** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[ycmd/completers/python/jedi_completer.py, line 38 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/295#-K7aLpmFgMB3gW1IiQyS:-K7aLpmFgMB3gW1IiQyT:-1032364532) ([raw file](https://github.com/valloric/ycmd/blob/959bfcb8f8ce5cd0299eeee61e7b8e471dd85841/ycmd/completers/python/jedi_completer.py#L38)):*
*interpreter
*specify

---

*[ycmd/completers/python/jedi_completer.py, line 91 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/295#-K7aMOFQjE1vphWAbZad:-K7aMOFQjE1vphWAbZae:949604011) ([raw file](https://github.com/valloric/ycmd/blob/959bfcb8f8ce5cd0299eeee61e7b8e471dd85841/ycmd/completers/python/jedi_completer.py#L91)):*
*testing

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295)*

**Comment by vheon** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[ycmd/completers/python/jedi_completer.py, line 38 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/295#-K7aLpmFgMB3gW1IiQyS:-K7aStem_QqtPVYgEOJE:-966229609) ([raw file](https://github.com/valloric/ycmd/blob/959bfcb8f8ce5cd0299eeee61e7b8e471dd85841/ycmd/completers/python/jedi_completer.py#L38)):*
ops, thanks!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295)*

**Comment by vheon** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[ycmd/completers/python/jedi_completer.py, line 91 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/295#-K7aMOFQjE1vphWAbZad:-K7aU8VSklYCrQwjQ2rf:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/959bfcb8f8ce5cd0299eeee61e7b8e471dd85841/ycmd/completers/python/jedi_completer.py#L91)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295)*

**Comment by Valloric** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/completers/python/jedi_completer.py, line 91 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/295#-K7ZKhDw0Y4e2X3JM4ib:-K7bMfH1wco6oLdMsSqg:-485110604) ([raw file](https://github.com/valloric/ycmd/blob/97dacdc262155d2417ecb1fcb4a9bfff35a8c622/ycmd/completers/python/jedi_completer.py#L91)):*
Sure.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295)*

**Comment by vheon** [comment]
I've added the tests for the user defined python binary path. I will add the tests for `RestartServer` tomorrow (it is pretty late here :stuck_out_tongue_closed_eyes: ).

A note: to test the user defined option I created the `UserOption` function which will clean itself up after the test is done (supporting the strategy suggested by @puremourning in https://github.com/Valloric/ycmd/pull/246#issuecomment-168314027) and I liked how it would read in the test, so I went and replace the only usage of `ChangeSpecificOption` with that, I hope you agree with me on this.

---

Review status: 1 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/completers/python/jedi_completer.py, line 91 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/295#-K7ZKhDw0Y4e2X3JM4ib:-K7d3-TmBDckaxVP_OSF:-2110348591) ([raw file](https://github.com/valloric/ycmd/blob/97dacdc262155d2417ecb1fcb4a9bfff35a8c622/ycmd/completers/python/jedi_completer.py#L91)):*
I've actually change my mind about because the purpose of that method is to be patched in the tests, so I believe it has to be as clear as possible what is going on during the test; if I change it to `CheckFileExists` then from the test I could not know that that method is actually called only for checking if a passed binary path exists. The same would be true if I move the method into the `utils` module: would it be clear that that method is only called for my purpose? I am certain that I will not mock things that I shouldn't? So for said reasons I would prefer to keep it as it is.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295#-:-K7d1nPTzkblJHRFIk3A:302149509)*

**Comment by Valloric** [comment]
:lgtm: Thanks for doing this!

---

Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[ycmd/tests/handlers_test.py, line 54 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/295#-K7d9idE2HZ9__Duejki:-K7d9idE2HZ9__Duejkj:-468748506) ([raw file](https://github.com/valloric/ycmd/blob/c6d2617e2cdc8cb3b642ca8f5117a2b142d96498/ycmd/tests/handlers_test.py#L54)):*
I like this, good idea!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295#-:-K7d9ypkoT-krWSPYPeW:-1560765061)*

**Comment by puremourning** [comment]
Reviewable is failing for me, so can't make line comments, but had 2 thoughts: 

- could the option be confused with the the other 'path to Python executable' that's used by Vim client? Should we prefix it with JeditHTTP ?
- in the message, it's worth including the value if even just in the log file, it just helps debugging :)

---

Reviewed 1 of 2 files at r1, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295#-:-K7d7WKmif0Q2XAQ9XxJ:-217275238)*

**Comment by puremourning** [comment]
Also. Csharp tests are failing :/

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295#-:-K7dEiECAubKovErge3k:95527703)*

**Comment by vheon** [comment]
> Also. Csharp tests are failing :/

There were a test in Csharp subcommands and in clang get_completion which used `_ChangeSpecificOption`. I used the new `GoToReferences` to get all usage of if but apparently it didn't work as I expected :(

> could the option be confused with the the other 'path to Python executable' that's used by Vim client? Should we prefix it with JeditHTTP ?

I was thinking about it myself, and you may be right :confused: I didn't want to mention JediHTTP since is an implementation detail but could be the most sensible solution.

> in the message, it's worth including the value if even just in the log file, it just helps debugging :)

You mean the value the user gives us which is not an existing one?

---

Review status: 8 of 10 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295#-:-K7fmwojDL2-LPUCOLsm:1745199942)*

**Comment by puremourning** [comment]
> You mean the value the user gives us which is not an existing one?

Yeah, sorry to be clear, i've added a line comment now

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ycmd/completers/python/jedi_completer.py, line 85 \[r5\]](https://reviewable.io:443/reviews/valloric/ycmd/295#-K7g1F1Q4wS1zqon1xvY:-K7g1F1Q4wS1zqon1xvZ:-1434965245) ([raw file](https://github.com/valloric/ycmd/blob/634ba3fba6ec4feba5c9e21c12af042eadd36330/ycmd/completers/python/jedi_completer.py#L85)):*
It might be useful to include the value of `binary` in this message for debugging purposes.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295#-:-K7g0ztiwN3MOj5mi4gr:-1202007992)*

**Comment by puremourning** [comment]
Anyway, LGTM with those small comments. :)

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295#-:-K7g1TRiHpNbusuoeISQ:-764543669)*

**Comment by micbou** [comment]
`UserOption` should be renamed `UserOptions` and take a dictionary instead of only one key/value pair (like the `ChangeSpecificOptions` function that it replaces). This way, we avoid nested `with` blocks if we need to set multiple options. I would also prefer if it could be used as a decorator to avoid the `with` indentation but it's a matter of taste.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295#-:-K7gR7sg_pZk5VQojcse:-532814040)*

**Comment by vheon** [comment]
> UserOption should be renamed UserOptions and take a dictionary instead of only one key/value pair (like the ChangeSpecificOptions function that it replaces). This way, we avoid nested with blocks if we need to set multiple options. I would also prefer if it could be used as a decorator to avoid the with indentation but it's a matter of taste.

I agree that the "with" vs. "decorator" approach is a matter of taste. For the `UserOptions` I don't really like the dictionary approach, maybe play with a kwargs and make it like:

```python
with self.UserOptions( user_option_one = 'one_value', user_option_two = 'two_value' ):
  ...
```

But I think it doesn't make sense to make it accept multiple user_options until we actually need it.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295#-:-K7hO03tRNl1QQnGmGEU:-1246297496)*

**Comment by puremourning** [comment]
> But I think it doesn't make sense to make it accept multiple user_options until we actually need it.
Agreed. No YAGNI :)

> I agree that the "with" vs. "decorator" approach
Me too, though I also prefer decorator (for the same reasons as @micbou), but in order to support that easily without pain, you have to require `contextlib2` in python 2.6. I did this a while back if you remember but we ditched it because we replaced it with `setUp/tearDown` methods.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295#-:-K7hPVOLnHAsECVo_3P4:1112570026)*

**Comment by puremourning** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295#-:-K7hQPueNtDY5B_6QMXH:1417088721)*

**Comment by vheon** [comment]
> Me too, though I also prefer decorator (for the same reasons as @micbou), but in order to support that easily without pain, you have to require contextlib2 in python 2.6. I did this a while back if you remember but we ditched it because we replaced it with setUp/tearDown methods.

Yes I remember and for me depends of the usage of it; for this particular case I prefer the `with` approach because it reads better: "with those user options the behaviour is ....". Anyway if it will bother us in the future we can still change it.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295#-:-K7hQLOAsOcLlI4QM9w4:2146474173)*

**Comment by vheon** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/completers/python/jedi_completer.py, line 85 \[r5\]](https://reviewable.io:443/reviews/valloric/ycmd/295#-K7g1F1Q4wS1zqon1xvY:-K7hQi33wqA6CjeDM7xV:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/634ba3fba6ec4feba5c9e21c12af042eadd36330/ycmd/completers/python/jedi_completer.py#L85)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295)*

**Comment by puremourning** [comment]
Yeh, this is totally fine :)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295#-:-K7hQsFjKQEaBs-alACK:1292311591)*

**Comment by puremourning** [comment]
is this [ready] now ?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295#-:-K7hTwgY-st-bU0M0T4E:2018136473)*

**Comment by vheon** [comment]
I wanted to add the tests for the `RestartServer`, but I don't know If I'm able to do it tonight.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295#-:-K7hUs7UIXMw0TXY1nHF:-483686188)*

**Comment by vheon** [comment]
I've pushed the tests for the `RestartServer`. I would love if someone else could test this.

@reinhrst if you some spare time to test this would be great! Basically there is a user option for specify which python should be used to spawn the JediHTTP server to get completion from. We still have the problem that you specified with https://github.com/reinhrst/jedi-working-directory-example but that was a pre-existing problem so I think it would be one of the next things to tackle.

When this is merged I'm going to update the YCM docs.

**Comment by puremourning** [comment]
:LGTM:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295#-:-K8LX3QDBH7GHOHdFsiP:1386550993)*

**Comment by puremourning** [comment]
Fail, Jackson. Try again: :lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295#-:-K8LX63AXa2VDroj-1QI:-1791949313)*

**Comment by micbou** [comment]
I tested `g:ycm_python_binary_path` option and `:YcmCompleter RestartServer` command. It works like expected. With this PR, we have now Python3 support in ycmd. Excellent work!

I just added a (pedantic) comment but this is :lgtm:

---

Reviewed 5 of 7 files at r4, 2 of 2 files at r5, 1 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[ycmd/tests/python/user_defined_python_test.py, line 40 \[r7\]](https://reviewable.io:443/reviews/valloric/ycmd/295#-K8LqLsvpICxIm2zFsAt:-K8LqLsw_v4XJEbwjLHu:598963345) ([raw file](https://github.com/valloric/ycmd/blob/cf9bbb3933e21b0077ac4719b6086d92a87a8a64/ycmd/tests/python/user_defined_python_test.py#L40)):*
Missing capital letter.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295#-:-K8Lpt1ZOoP3sqGAMQ20:-343169800)*

**Comment by vheon** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/tests/python/user_defined_python_test.py, line 40 \[r7\]](https://reviewable.io:443/reviews/valloric/ycmd/295#-K8LqLsvpICxIm2zFsAt:-K8LuhGYeiE1dXgMTBCV:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/cf9bbb3933e21b0077ac4719b6086d92a87a8a64/ycmd/tests/python/user_defined_python_test.py#L40)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295)*

**Comment by puremourning** [comment]
Woo! Python 3 in ycmd.

@homu r+

Nice one! A lot went into getting here, so thanks @vheon. I think python 3 support is one of (if not, the) most requested feature 

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/295#-:-K8LuoD2Wgqc2Lngjbdw:1412345694)*

**Comment by vheon** [comment]
Apparently in my fork one of the test failed due to the typescript `Request sequence mismatch` error. We should look into that :cry:

**Comment by puremourning** [comment]
that's been happening a bit recently - we're still not sure if it is a bug in the completer or in `tsserver`. all we know is that it only started happening recently and we don't fix the version of `tsserver` in travis

**Comment by reinhrst** [comment]
Very cool to see this working :+1: 

Would be nice to search the PATH for the executable. That way one could just use `python` as executable (perhaps this should just be the default), and it will automatically get the one in the virtualenv you were in when you started vim. Right now I need to put this in my `.vimrc` to achieve this: `let g:ycm_python_binary_path=substitute(system("which python"), "\n$", "", "")`

When testing (in a python3 virtualenv), it worked partly.
```
import urllib
urllib.
```
indeed only gives me the completions for python3.

However
```
import asyncio
asyncio.
```
results in a crash. Didn't really have time to dive into it, but these are the logs (this is with master (d05bf551a6) of YouCompleteMe, master (bf256b210) or ycmd, all dependencies on the suggested version):

ycmd stderr:
```
2016-01-23 14:01:50,975 - INFO - Received event notification
2016-01-23 14:01:50,978 - INFO - Received completion request
2016-01-23 14:01:50,979 - INFO - Starting new HTTP connection (1): 127.0.0.1
2016-01-23 14:01:50,985 - ERROR - Exception from semantic completer (using general): Traceback (most recent call last):
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/handlers.py", line 104, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 168, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 184, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/python/jedi_completer.py", line 240, in ComputeCandidatesInner
    for completion in self._JediCompletions( request_data ) ]
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/python/jedi_completer.py", line 244, in _JediCompletions
    return self._GetResponse( '/completions', request_data )[ 'completions' ]
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/python/jedi_completer.py", line 191, in _GetResponse
    response.raise_for_status()
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/requests/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:49973/completions
```

jedihttp stderr:
```
Traceback (most recent call last):
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/cache.py", line 200, in load_parser
    parser_cache_item = parser_cache[path]
KeyError: '/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/__init__.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/bottle/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/bottle/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/jedihttp/hmac_plugin.py", line 58, in wrapper
    body = callback( *args, **kwargs )
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/jedihttp/handlers.py", line 63, in completions
    } for completion in script.completions() ]
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/api/__init__.py", line 188, in completions
    completion_names = get_completions(user_stmt, b)
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/api/__init__.py", line 174, in get_completions
    completion_names += self._simple_complete(path, dot, like)
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/api/__init__.py", line 250, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/api/__init__.py", line 294, in _prepare_goto
    scopes = self._evaluator.eval_element(eval_stmt)
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/finder.py", line 282, in _name_to_types
    types += imports.ImportWrapper(evaluator, name).follow()
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/imports.py", line 94, in follow
    types = importer.follow()
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/imports.py", line 252, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/imports.py", line 347, in _do_import
    module = _load_module(self._evaluator, module_path, source, sys_path)
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/imports.py", line 449, in _load_module
    cached = cache.load_parser(path)
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/cache.py", line 210, in load_parser
    return ParserPickling.load_parser(path, p_time)
  File "/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/cache.py", line 267, in load_parser
    parser_cache_item = pickle.load(f)
AttributeError: Can't get attribute 'ParserWithRecovery' on <module 'jedi.parser' from '/Users/reinoud/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/parser/__init__.py'>
```

Python executable is `/Users/reinoud/Envs/tmp-c195d4c4ce39463/bin/python`, which is a symlink to `python3.4`

**Comment by vheon** [comment]
> Would be nice to search the PATH for the executable

We could think of passing the PATH env to the Popen; it should work then :+1: 

> When testing (in a python3 virtualenv), it worked partly.

I don't like the crash, but from the logs it appears to be a jedi issue, am I wrong? maybe I need to use the dev branch instead of master?

**Comment by reinhrst** [comment]
> We could think of passing the PATH env to the Popen; it should work then :+1:
It seems to do that automatically but there are some issues (especially on Windows): http://stackoverflow.com/a/5659249/1207489 . In addition, `_CheckBinaryExists()` needs some work then.
> I don't like the crash, but from the logs it appears to be a jedi issue, am I wrong? maybe I need to use the dev branch instead of master?
I just checked, indeed it crashes on master of jedi. @davdhalter, which branch/tag/sha makes most sense to use?

**Comment by vheon** [comment]
> It seems to do that automatically but there are some issues (especially on Windows): http://stackoverflow.com/a/5659249/1207489 . In addition, _CheckBinaryExists() needs some work then.

So is more complicated than I thought :confused:

**Comment by reinhrst** [comment]
This may do the trick, e.g. making `_CheckBinaryExists()` into `_FindBinary()` : http://stackoverflow.com/a/377028/1207489

**Comment by reinhrst** [comment]
Just for reference, using the following 2 lines give a really nice experience
```
let g:ycm_python_binary_path=substitute(system("which python"), "\n$", "", "")
let $PYTHONPATH=getcwd() . ":" . $PYTHONPATH
```

First makes sure the python is used from the current virtual env. Seconds adds the directory in which vim was started to the pythonpath, allowing completions from files and packages in that directory.

**Comment by vheon** [comment]
> Just for reference, using the following 2 lines give a really nice experience

I'm glad that we could finally improve (even if slightly) the python experience :smiley: 

> First makes sure the python is used from the current virtual env. Seconds adds the directory in which vim was started to the pythonpath, allowing completions from files and packages in that directory.

I will try to came up with a solution for those two problems.

- The first one could simply be making `_CheckBinaryExists()` into `_CheckBinaryIsPython()` in which we do something similar to https://github.com/Valloric/YouCompleteMe/pull/1896 and spawn the "alleged" python checking its version to be sure is a python interpreter.
- For the second one I should switch to the dev branch of jedi and pass the python path directly into jedi.

**Comment by puremourning** [comment]
Does `which` work/exist in Windows?

**Comment by reinhrst** [comment]
> Does `which` work/exist in Windows?

Don't know. I'm not suggesting my line to be a generic solution, just might help some people testing / adapting this to their own situation. I agree with @vheon that this should be solved in some generic way.

**Comment by micbou** [comment]
> Does `which` work/exist in Windows?

Not natively. However, there is the `where` command.

**Pull request merged**
