### PR TITLE
Update Python version in CI environments to 3.6

### PR DESCRIPTION
**Pull request by hexchain**
This is the follow up of https://github.com/Valloric/ycmd/pull/686#issuecomment-271075945.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/687)

### CODE REVIEW

**Comment by Valloric** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 30 at r1](https://reviewable.io:443/reviews/valloric/ycmd/687#-K_uKPJIJrZYpQpm5vi5:-K_uKPJIJrZYpQpm5vi6:b-wr8zro) ([raw file](https://github.com/valloric/ycmd/blob/1bb78bc67c5c297cde37f3e068ff0e088aa58e67/.travis.yml#L30)):*
> ```YAML
>     - USE_CLANG_COMPLETER=true YCMD_PYTHON_VERSION=2.6
>     - USE_CLANG_COMPLETER=true YCMD_PYTHON_VERSION=2.7
>     - USE_CLANG_COMPLETER=true YCMD_PYTHON_VERSION=3.6
> ```

Not sure this is the best approach; the minimum py3 version we support is 3.3 and we want to ensure we work with that.

I believe @micbou was talking about bumping the Windows Python version for appveyor, not travis.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/687)*

**Comment by micbou** [comment]
> Python 3.6 extensions does not build with MSVC 11 so it is removed from build matrix.

Let's keep it in the build matrix with Python 3.5 for now. We'll remove it when we decide to drop its support. We should just leave a comment explaining why we don't test it with Python 3.6.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 30 at r1](https://reviewable.io:443/reviews/valloric/ycmd/687#-K_uKPJIJrZYpQpm5vi5:-K_uVgA7HeGNd8EHze_h:b9kfqkm) ([raw file](https://github.com/valloric/ycmd/blob/1bb78bc67c5c297cde37f3e068ff0e088aa58e67/.travis.yml#L30)):*
<details><summary><i>Previously, Valloric (Val Markovic) wrote…</i></summary><blockquote>

Not sure this is the best approach; the minimum py3 version we support is 3.3 and we want to ensure we work with that.

I believe @micbou was talking about bumping the Windows Python version for appveyor, not travis.
</blockquote></details>

Yes, the reason we prefer testing against the last version of Python on Windows is that, since there is no default version of Python installed on this platform, users are likely to download and install the last one so we want to be sure that it works on this version.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/687#-:-K_ujHvkl3KUYfG5-f2-:bymstnc)*

**Comment by Valloric** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 30 at r1](https://reviewable.io:443/reviews/valloric/ycmd/687#-K_uKPJIJrZYpQpm5vi5:-K_voO7ks6uPhgA-Ff4i:b-k2cgk7) ([raw file](https://github.com/valloric/ycmd/blob/1bb78bc67c5c297cde37f3e068ff0e088aa58e67/.travis.yml#L30)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

Yes, the reason we prefer testing against the last version of Python on Windows is that, since there is no default version of Python installed on this platform, users are likely to download and install the last one so we want to be sure that it works on this version.
</blockquote></details>

That makes sense. So we're on the same page that the travis file shouldn't be changed then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/687)*

**Comment by micbou** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/687#-:-K_yAPeRGUSbSfVIiumo:bnfp4nl)*

**Comment by puremourning** [comment]
:lgtm: Thanks again!

@homu r+

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/687#-:-K_zFbwLNlz13X5hNRVM:b-5om8j1)*

**Comment by puremourning** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/687)*

**Pull request merged**
