### PR TITLE
[RFC] Move macOS builds to CircleCI

### PR DESCRIPTION
**Pull request by micbou**
A few months ago, [Travis decided to limit the number of concurrent builds for macOS](https://blog.travis-ci.com/2017-09-22-macos-update). Since then, macOS builds take forever to complete. The last few days have been even worse as the builds are not starting at all.

With this PR, I am proposing to move the macOS builds to [CircleCI](https://circleci.com/). I tested it on my fork and it looks promising. [The builds are completing way faster than Travis](https://circleci.com/gh/micbou/ycmd/tree/circleci). The platform offers [the seed plan](https://circleci.com/pricing/#build-os-x) for macOS open-source projects. We just need to contact them. They also informed me that there is no minutes limitation for open-source projects. Only issue I see is that zzbot does not support CircleCI.

@Valloric If we agree on that decision, you'll need to sign in with your GitHub account on the CircleCI website, add the YCM and ycmd repositories as projects, and contact the CircleCI team to get the seed plan. Then, we'll merge the PR.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/901)

### CODE REVIEW

**Comment by micbou** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 7 at r1](https://reviewable.io:443/reviews/valloric/ycmd/901#-L3BIbfcEEdOb_-fJPUg:-L3BIbfcEEdOb_-fJPUh:b-umfmcu) ([raw file](https://github.com/valloric/ycmd/blob/758374114ecd42c7fa7001fe9645dd18bb0b10bc/README.md#L7)):*
> ```Markdown
> [macOS build status](https://circleci.com/gh/Valloric/ycmd)
> [Windows build status](https://ci.appveyor.com/project/Valloric/ycmd)
> [Coverage status](https://codecov.io/gh/Valloric/ycmd)
> ```

These changes update the badges with CircleCI and make them look more consistent:
ycmd-badges-after

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/901)*

**Comment by bstaletic** [comment]
I'd be glad to see this merged. Travis on MacOS is unusable.

I see no report from CircleCI and `OnMac()` parts are not covered any more. Will that be fixed once @valloric enables CircleCI for ycmd?

---

Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.circleci/config.yml, line 76 at r2](https://reviewable.io:443/reviews/valloric/ycmd/901#-L3C8NVZ_TUIG5JOEwFz:-L3C8NVZ_TUIG5JOEwG-:bgf83cy) ([raw file](https://github.com/valloric/ycmd/blob/877f421be121a6c8c454725eb0233799458a840e/.circleci/config.yml#L76)):*
> ```YAML
>       YCMD_PYTHON_VERSION: 3.3
> workflows:
>   version: 2
> ```

Version 2 means what exactly? Is it just telling CircleCI to not use some legacy/backward compatibility/deprecated stuff?

Also, correct me if I'm wrong, but MacOS builds are sequential, not parallel. Correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/901#-:-L3C0EgCwtKSHQstW6yW:batxmm5)*

**Comment by puremourning** [comment]
> Only issue I see is that zzbot does not support CircleCI.

This would be a little disappointing. What would you propose as our sort of operational procedure under this model?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/901#-:-L3CnP8t03we1qOn3V5W:b-34cnjr)*

**Comment by bstaletic** [comment]
But we'll have CircleCI run the tests after every commit/push and we're not merging anything non-trivial before we see the CI green anyway.

So how big of a loss is @zzbot not running CircleCI?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/901#-:-L3Cuzuelf68z2yisB4v:b-2fnh53)*

**Comment by bstaletic** [comment]
I personally think this is fine. :lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.circleci/config.yml, line 76 at r2](https://reviewable.io:443/reviews/valloric/ycmd/901#-L3C8NVZ_TUIG5JOEwFz:-L3D9-VuoQPe_F03FPRY:brxp9sq) ([raw file](https://github.com/valloric/ycmd/blob/877f421be121a6c8c454725eb0233799458a840e/.circleci/config.yml#L76)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

> Version 2 means what exactly? Is it just telling CircleCI to not use some legacy/backward compatibility/deprecated stuff?

Yes, [this tells CircleCI to use version 2 of the workflows feature](https://circleci.com/docs/2.0/workflows/).

> Also, correct me if I'm wrong, but MacOS builds are sequential, not parallel. Correct?

The builds are parallel up to 2 concurrent builds with the seed plan.
</blockquote></details>

Sounds good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/901#-:-L3DAyE9FNnMqOxFMDbf:b-mjl0ep)*

**Comment by Valloric** [comment]
The biggest loss is zzbot not supporting it, as @puremourning pointed out. But like @micbou, we've lived in a similar world before and it wasn't an issue. So while not ideal, I think we'll manage.

So :lgtm: from me (code changes look fine too). Let me set up the account stuff etc. and reach out to them.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/901#-:-L3EoQreEynuQeh8LFoj:b-mzaaok)*

**Comment by Valloric** [comment]
@micbou I sent the Circle CI folks an email and CC'd all the YCM core devs.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/901#-:-L3F4YDTK3NMWKdGRoVP:b-lgdfc8)*

**Comment by Valloric** [comment]
@micbou I think you need to "follow" the CircleCI projects I set up (check your email for links) before I can give you permissions to manage it. Could you try that and ping me? If it works with you, we can set it up with the rest of the core devs as well.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/901#-:-L3F4qdzGxdQpVoysOqd:b-f7a54f)*

**Comment by micbou** [comment]
@Valloric Done.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/901#-:-L3F65JBoZ7h-m8QEEuc:brec80f)*

**Comment by Valloric** [comment]
@micbou It added you as a team member automatically, probably by noticing that your are a contributor on the github projects. Can you change any settings?

The CircleCI folks are also saying they've enabled mac builds for us, but it doesn't appear to be the case. I'm following up with them.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/901#-:-L3FQYSbS851Zf-U8eOm:bm8hxrv)*

**Comment by micbou** [comment]
@Valloric I can change project-related settings but not organization ones. Maybe we need to merge the PR to make CircleCI detect that the project is a macOS one (through the `config.yml` file). It currently assumes that it's a Linux project.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/901#-:-L3FRqhxYL0sVqo8cw0k:b-sseb4m)*

**Comment by Valloric** [comment]
@micbou That's exactly the issue I'm chatting with CircleCI folks about; they said they enabled the mac stuff, but I don't see it. But if you can tweak the linux stuff, then once they sort out the mac stuff, you should be able to change that too.

So I think the permission stuff works.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/901#-:-L3FvOMlkuTItAalJM9w:bfgdet5)*

**Comment by Valloric** [comment]
@micbou Here's what I got from them just now:

> Nope; you should be able to build just fine from here on out! I just double-checked to be sure. (This isn't reflected on the Org Settings page in the UI, however; I've just filed an internal ticket so we can look at fixing that. Thanks for bringing it up!)

So it looks like a UI bug? I was able to turn on Mac builds for the project (both ycmd and YCM) even though the settings page for the "organization" (which is just my username) says that I have "no macOs plan selected."

In other words, I think it should work after merging the PR.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/901#-:-L3Fvpo0eoec8IhfHpKj:b-mul01c)*

**Comment by micbou** [comment]
Let's see.

@zzbot r+

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/901#-:-L3G1eYIXbmTQQ3BI2wC:b52zybd)*

**Pull request merged**
