### PR TITLE
[READY] Make GoTo and GoToImprecise subcommands jump to declaration if cursor on definition

### PR DESCRIPTION
**Pull request by micbou**
This is based on PR https://github.com/Valloric/ycmd/pull/179. When the cursor is already on a definition, the `GoTo` and `GoToImprecise` commands jump at the start of the definition which is not really what the user would expect. These commands should jump to the declaration in that case. Here's a demo:

clang-completer-goto

The implementation is different from https://github.com/Valloric/ycmd/pull/179 in that instead of doing the work in the Python layer, we do everything in C++ to be as efficient as possible.

Updated the tests and removed the comment saying that the semantics of `GoToDeclaration` versus `GoToDefinition` look wrong; they make sense to me.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/952)

### CODE REVIEW

**Comment by micbou** [comment]
Forgot to bump the core version.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/952#-:-L7Gi3ed7hDO5srNAzW7:b518yh7)*

**Comment by micbou** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cpp/ycm/ClangCompleter/TranslationUnit.cpp, line 207 at r1](https://reviewable.io:443/reviews/valloric/ycmd/952#-L7KcTDJTQKHM1CfBjJw:-L7KuK-Rfvam4R4noK82:b-fwe8my) ([raw file](https://github.com/valloric/ycmd/blob/ecd207582a79015a0f6cc907281c2ce7a3bbe428/cpp/ycm/ClangCompleter/TranslationUnit.cpp#L207)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Do we need the "old" `GetDeclarationLocation` and `GetDefinitionLocation` along with `GetDefinitionOrDeclarationLocation`?
</blockquote></details>

Yes, we need them for `GoToDeclaration` and `GoToDefinition` respectively.

---

*[cpp/ycm/ClangCompleter/TranslationUnit.cpp, line 299 at r1](https://reviewable.io:443/reviews/valloric/ycmd/952#-L7KbEB61yFV8BxAw0mv:-L7KuUegsmpBgBIJEECc:b9s36t1) ([raw file](https://github.com/valloric/ycmd/blob/ecd207582a79015a0f6cc907281c2ce7a3bbe428/cpp/ycm/ClangCompleter/TranslationUnit.cpp#L299)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Shouldn't this return `location`?
If I'm reading the code correctly, at this point `location` already has the value of `GetDeclarationLocationForCursor( cursor )`.
</blockquote></details>

No, it's the definition's location. If it can't find a definition, it falls back to the declaration. This follows the old behavior:
 - go to the definition;
 - if no definition found, go to the declaration.

while the new behavior is:
 - if on definition, go to the declaration;
 - otherwise, go to the definition;
 - if no definition found, go to the declaration.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/952)*

**Comment by puremourning** [comment]
:lgtm: nice one.

I tested this out and it works well!

Thanks!

---

Reviewed 8 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cpp/ycm/ClangCompleter/TranslationUnit.cpp, line 299 at r1](https://reviewable.io:443/reviews/valloric/ycmd/952#-L7KbEB61yFV8BxAw0mv:-L7LODi0t8M-tRnuHGQi:b-yfqbuf) ([raw file](https://github.com/valloric/ycmd/blob/ecd207582a79015a0f6cc907281c2ce7a3bbe428/cpp/ycm/ClangCompleter/TranslationUnit.cpp#L299)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

No, it's the definition's location. If it can't find a definition, it falls back to the declaration. This follows the old behavior:
 - go to the definition;
 - if no definition found, go to the declaration.

while the new behavior is:
 - if on definition, go to the declaration;
 - otherwise, go to the definition;
 - if no definition found, go to the declaration.
</blockquote></details>

I think we should add the latter part of this response in a comment here. Reason is that I was mildly confused by this logic too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/952#-:-L7LQzuzKjHcp8GFEwEF:b-rsqzu1)*

**Comment by puremourning** [comment]
Reviewed 1 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/952)*

**Comment by micbou** [comment]
Marking this as ready.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cpp/ycm/ClangCompleter/TranslationUnit.cpp, line 299 at r1](https://reviewable.io:443/reviews/valloric/ycmd/952#-L7KbEB61yFV8BxAw0mv:-L7LcUrhnC4CNzRaD7Nv:b-f8sf1p) ([raw file](https://github.com/valloric/ycmd/blob/ecd207582a79015a0f6cc907281c2ce7a3bbe428/cpp/ycm/ClangCompleter/TranslationUnit.cpp#L299)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I think we should add the latter part of this response in a comment here. Reason is that I was mildly confused by this logic too.
</blockquote></details>

Added a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/952#-:-L7Lci8rTJ1S-vXn4bzA:bdr911j)*

**Comment by puremourning** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/952)*

**Comment by bstaletic** [comment]
:lgtm:
@zzbot r=puremourning

**Comment by micbou** [comment]
Added GoTo tests when the cursor is on an invalid position. This should improve coverage.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/952#-:-L7P3QaBB5YNioNfHWK4:bd76q43)*

**Comment by puremourning** [comment]
:lgtm: still

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/952#-:-L7Pmo_yRXNSngpPrCPY:b-7w0pd3)*

**Comment by micbou** [comment]
Okay, the GoTo functions are now fully covered (except when getting an invalid canonical cursor from a reference but I have no idea how to raise this one). Let's merge.

@zzbot r+

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/952#-:-L7PqfCKdWL4M810O3ay:b-k06yc6)*

**Pull request merged**
