### PR TITLE
[READY] Ignore identifiers from comments and strings on InsertLeave and CurrentIdentifierFinished events

### PR DESCRIPTION
**Pull request by micbou**
When `collect_identifiers_from_comments_and_strings` is `0`, we should also ignore identifiers from comments and strings on the `InsertLeave` and `CurrentIdentifierFinished` events.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/745)

### CODE REVIEW

**Comment by Valloric** [comment]
:lgtm:

Thanks!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/745#-:-KiMPnsJwSoGbb8rwG5N:b9benhj)*

**Comment by micbou** [comment]
PR #746 should be merged first since it adds a new parameter to `RemoveIdentifierFreeText`.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/745#-:-KiOqw4yE_5qvJ46yJ8e:bl3sxjb)*

**Comment by micbou** [comment]
This is now ready to be merged.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/745#-:-KiWHrEFEkLse_EmUsHV:bwv94kq)*

**Comment by vheon** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/completers/all/identifier_completer.py, line 230 at r2](https://reviewable.io:443/reviews/valloric/ycmd/745#-KiW_Q6bF1-V5hHI72Aj:-KiW_Q6bF1-V5hHI72Ak:bb152i0) ([raw file](https://github.com/valloric/ycmd/blob/45a636ca5d3e33ca4cfdbff121cefbed22002aa4/ycmd/completers/all/identifier_completer.py#L230)):*
> ```Python
> 
> 
> def _GetCursorIdentifier( collect_from_comments_and_strings,
> ```

inverting the order of the parameters and making `collect_from_comments_and_strings` a parameter with a default value of `False` we could've avoid to change all the tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/745)*

**Comment by micbou** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/completers/all/identifier_completer.py, line 230 at r2](https://reviewable.io:443/reviews/valloric/ycmd/745#-KiW_Q6bF1-V5hHI72Aj:-KiWvbgOA5HnmmlQKANL:b8ggw38) ([raw file](https://github.com/valloric/ycmd/blob/45a636ca5d3e33ca4cfdbff121cefbed22002aa4/ycmd/completers/all/identifier_completer.py#L230)):*
<details><summary><i>Previously, vheon (Andrea Cedraro) wrote…</i></summary><blockquote>

inverting the order of the parameters and making `collect_from_comments_and_strings` a parameter with a default value of `False` we could've avoid to change all the tests.
</blockquote></details>

I picked this order to be consistent with `_PreviousIdentifier` where `request_data` is the last parameter.  Also, I don't think it's a good idea to set a default value because we never want to override this option.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/745)*

**Comment by vheon** [comment]
:lgtm: @homu r=Valloric

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/completers/all/identifier_completer.py, line 230 at r2](https://reviewable.io:443/reviews/valloric/ycmd/745#-KiW_Q6bF1-V5hHI72Aj:-KiZdVzCvpnrYZ0ejvuo:bjzdvpy) ([raw file](https://github.com/valloric/ycmd/blob/45a636ca5d3e33ca4cfdbff121cefbed22002aa4/ycmd/completers/all/identifier_completer.py#L230)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

I picked this order to be consistent with `_PreviousIdentifier` where `request_data` is the last parameter.  Also, I don't think it's a good idea to set a default value because we never want to override this option.
</blockquote></details>

fair enough :wink: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/745#-:-KiZdaAHgwFd-CBS4y2L:b9nem37)*

**Pull request merged**
