### PR TITLE
Pass full argv to libclang, including argv[0]

### PR DESCRIPTION
**Pull request by d0k**
Pass full argv to libclang, including argv[0]. Fixes some long standing issues with finding the standard library on some configurations when using compilation databases.

[Review on Reviewable](https://reviewable.io/reviews/valloric/ycmd/276)

### CODE REVIEW

**Comment by Valloric** [comment]
Thanks for the PR! Happy to see more libclang bugs getting fixed.

I'm fine with #278 landing before libclang 3.8, but this PR involves quite a bit of nasty hackery to remain backwards compatible. It should in all likelihood wait until 3.8 goes out. So let's hold off on this until then.

---

Review status: 0 of 83 files reviewed at latest revision, 1 unresolved discussion.

---

*[ycmd/completers/cpp/clang_helpers.py, line 21 \[r1\]](https://reviewable.io:443/reviews/valloric/ycmd/276#-K5n36-ptsAM5csf-dFB:-K5n36-quiylEUHNEiWW:-1912185709) ([raw file](https://github.com/valloric/ycmd/blob/68edd9dfd2eef2c961a98f016e1efe4145494af9/ycmd/completers/cpp/clang_helpers.py#L21)):*
While you're at this, mind adding a comment here stating that this function is around for the sake of backwards compatibility with old ycm_extra_conf files? We can never remove it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/276#-:-K5n2RWlUyclPnKIByKS:142721971)*

**Comment by d0k** [comment]
Okay, I removed all the version detection hacks and only left the flag handling changes in place to push argv[0] through until we actually hit libclang, making the post-3.8 patch much smaller.

**Comment by Valloric** [comment]
Review status: 0 of 82 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[cpp/ycm/ClangCompleter/TranslationUnit.cpp, line 91 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/276#-K5sY3MFqjsKuxkir9yX:-K5sY3MFqjsKuxkir9yY:786895892) ([raw file](https://github.com/valloric/ycmd/blob/aea5180bc13c1b02893e408b2fabf4102e2c8406/cpp/ycm/ClangCompleter/TranslationUnit.cpp#L91)):*
I must be missing something here; what's the point in ensuring that the first flag is the compiler name when you then only pass the flags after that one?

---

*[ycmd/completers/cpp/flags.py, line 245 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/276#-K5sYycGyBTTjmrHW1wt:-K5sYycGyBTTjmrHW1wu:-2000719952) ([raw file](https://github.com/valloric/ycmd/blob/aea5180bc13c1b02893e408b2fabf4102e2c8406/ycmd/completers/cpp/flags.py#L245)):*
This isn't entirely clear to me; could you perhaps pull it out into a separate function and include an example in the doc comment?

Also, this likely needs tests (this module has plenty).

---

*[ycmd/completers/cpp/flags.py, line 310 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/276#-K5sZOxzpgorL9ZZcC1_:-K5sZOxzpgorL9ZZcC1a:168114878) ([raw file](https://github.com/valloric/ycmd/blob/aea5180bc13c1b02893e408b2fabf4102e2c8406/ycmd/completers/cpp/flags.py#L310)):*
A test for this would be lovely.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/276)*

**Comment by puremourning** [comment]
Does this fix #250 ? If so we should add it to the PR description so that it get's automatically closed by homu :)

**Comment by d0k** [comment]
#250 won't be fixed until libclang 3.8 is out and ycmd starts using it. This PR is just preparation for that (when I finally get around to polish it up for merging)

**Comment by puremourning** [comment]
Understood. Thanks.

**Comment by d0k** [comment]
Review status: 0 of 82 files reviewed at latest revision, 3 unresolved discussions.

---

*[cpp/ycm/ClangCompleter/TranslationUnit.cpp, line 91 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/276#-K5sY3MFqjsKuxkir9yX:-K7k273xJB-i9QOs_fWp:1171536444) ([raw file](https://github.com/valloric/ycmd/blob/aea5180bc13c1b02893e408b2fabf4102e2c8406/cpp/ycm/ClangCompleter/TranslationUnit.cpp#L91)):*
We can't do that with libclang 3.7, however with this patch in places the move to libclang 3.8 with full argv only has to change this call, as this is the point where argv[0] gets stripped. Added TODO comment.

---

*[ycmd/completers/cpp/flags.py, line 245 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/276#-K5sYycGyBTTjmrHW1wt:-K7k1cuD1hxhzrS-i1tb:1873159009) ([raw file](https://github.com/valloric/ycmd/blob/aea5180bc13c1b02893e408b2fabf4102e2c8406/ycmd/completers/cpp/flags.py#L245)):*
This is merely preprocessing the flag list so the loop below (which strips all non-flag arguments) doesn't remove argv[0]. Updated comment. This is also covered by the test modifications I made to flags_test.py, I don't think more coverage is necessary.

---

*[ycmd/completers/cpp/flags.py, line 310 \[r2\]](https://reviewable.io:443/reviews/valloric/ycmd/276#-K5sZOxzpgorL9ZZcC1_:-K7k20dt5en63qY3FGAD:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/aea5180bc13c1b02893e408b2fabf4102e2c8406/ycmd/completers/cpp/flags.py#L310)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/276)*

**Comment by Valloric** [comment]
Review status: 0 of 82 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[cpp/ycm/ClangCompleter/TranslationUnit.cpp, line 83 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/276#-K7njZdJuUEtd3qlxOtH:-K7njZdJuUEtd3qlxOtI:-1094722152) ([raw file](https://github.com/valloric/ycmd/blob/5ec7763602b1095f9000aeb9dc5c8a4336c1a8e7/cpp/ycm/ClangCompleter/TranslationUnit.cpp#L83)):*
You can rewrite this in a way that makes the comment unnecessary. Pull this out into an `EnsureCompilerNamePresent(&flags)` function in an anon namespace and then also pull out the second part of the condition into a named bool: 

```c++
bool no_compiler_name_set = !flags.empty() && !flags.front().empty() && flags.front().front() == '-';

if (flags.empty() || no_compiler_name_set)
```

And no comment needed, code clear as day.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/276)*

**Comment by d0k** [comment]
Review status: 0 of 82 files reviewed at latest revision, 3 unresolved discussions.

---

*[cpp/ycm/ClangCompleter/TranslationUnit.cpp, line 83 \[r4\]](https://reviewable.io:443/reviews/valloric/ycmd/276#-K7njZdJuUEtd3qlxOtH:-K7pAQr5JEWkOQCaI_1O:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/5ec7763602b1095f9000aeb9dc5c8a4336c1a8e7/cpp/ycm/ClangCompleter/TranslationUnit.cpp#L83)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/276)*

**Comment by Valloric** [comment]
This is :lgtm: from me (though of course it needs to wait until libclang 3.8). Thanks for sending it in! :)

---

Review status: 0 of 82 files reviewed at latest revision, 3 unresolved discussions.

---

*[cpp/ycm/ClangCompleter/TranslationUnit.cpp, line 57 \[r5\]](https://reviewable.io:443/reviews/valloric/ycmd/276#-K7siAizUezGaYVx_zhM:-K7siAizUezGaYVx_zhN:1426297346) ([raw file](https://github.com/valloric/ycmd/blob/1c68fd4d22fdfab704dc30d1fe50829cc97c834e/cpp/ycm/ClangCompleter/TranslationUnit.cpp#L57)):*
I just noticed that this function and the ones above it start with a lowercase letter; functions in our C++ code always start with an uppercase letter.

Could you capitalize all four of them? Thanks!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/276#-:-K7siV3iYwr4kzYlk9Hs:1126934316)*

**Comment by d0k** [comment]
Thanks for the review. As all of this is completely independent of libclang 3.8 and works fine with 3.7, would you mind merging it already?

---

Review status: 0 of 82 files reviewed at latest revision, 3 unresolved discussions.

---

*[cpp/ycm/ClangCompleter/TranslationUnit.cpp, line 57 \[r5\]](https://reviewable.io:443/reviews/valloric/ycmd/276#-K7siAizUezGaYVx_zhM:-K7uHtKYjAOjTShO8RAH:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/1c68fd4d22fdfab704dc30d1fe50829cc97c834e/cpp/ycm/ClangCompleter/TranslationUnit.cpp#L57)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/276#-:-K7uHuSxh24IFYXhGGNQ:-1803732472)*

**Comment by Valloric** [comment]
> As all of this is completely independent of libclang 3.8 and works fine with 3.7, would you mind merging it already?

Wait, I don't get it. This PR originally had some version detection hackery in the C++ code for symbol compatibility that was removed because we were only merging this when libclang 3.8 came out, no? How is this compatible with libclang 3.7 without that version detection stuff?

If the patch as it currently stands works with vanilla libclang 3.7, then I'm fine with merging it now.

---

Review status: 0 of 82 files reviewed at latest revision, 5 unresolved discussions.

---

*[ycmd/completers/cpp/tests/flags_test.py, line 225 \[r6\]](https://reviewable.io:443/reviews/valloric/ycmd/276#-K7xzbe8tnkfK63OiLlS:-K7xzbe8tnkfK63OiLlT:1518212488) ([raw file](https://github.com/valloric/ycmd/blob/ea4e592a92f962cf9ed70588d267dd3c37bf3354/ycmd/completers/cpp/tests/flags_test.py#L225)):*
`ok_()` from nose is what we'd normally use here.

---

*[ycmd/completers/cpp/tests/flags_test.py, line 228 \[r6\]](https://reviewable.io:443/reviews/valloric/ycmd/276#-K7xzXgov5PtFsLJLh9s:-K7xzXgov5PtFsLJLh9t:1408525070) ([raw file](https://github.com/valloric/ycmd/blob/ea4e592a92f962cf9ed70588d267dd3c37bf3354/ycmd/completers/cpp/tests/flags_test.py#L228)):*
`eq_()` from nose would be a better choice here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/276#-:-K7xymHYyDEedWWefEgD:-204733855)*

**Comment by d0k** [comment]
I removed everything specific to libclang 3.8 in this patch, this just refactors the flag handling. When libclang 3.8 lands I still need to change the call to clang_parseTranslationUnit2 as we now strip argv[0] at that point. At the current revision this PR shouldn't change any user-visible behavior and work with 3.7 as it did before.

---

Review status: 0 of 82 files reviewed at latest revision, 5 unresolved discussions.

---

*[ycmd/completers/cpp/tests/flags_test.py, line 225 \[r6\]](https://reviewable.io:443/reviews/valloric/ycmd/276#-K7xzbe8tnkfK63OiLlS:-K7zMsSyRO7tfFyHDDyT:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/ea4e592a92f962cf9ed70588d267dd3c37bf3354/ycmd/completers/cpp/tests/flags_test.py#L225)):*
Done.

---

*[ycmd/completers/cpp/tests/flags_test.py, line 228 \[r6\]](https://reviewable.io:443/reviews/valloric/ycmd/276#-K7xzXgov5PtFsLJLh9s:-K7zMxrTQivEzY5Vk0BP:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/ea4e592a92f962cf9ed70588d267dd3c37bf3354/ycmd/completers/cpp/tests/flags_test.py#L228)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/276#-:-K7zLzG-zJYeMJTyweUZ:481049171)*

**Comment by vheon** [comment]
:lgtm: except the minor comment

---

Reviewed 156 of 161 files at r1, 1 of 3 files at r2, 1 of 3 files at r3, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[cpp/ycm/ClangCompleter/TranslationUnit.cpp, line 60 \[r7\]](https://reviewable.io:443/reviews/valloric/ycmd/276#-K80irRrjrrO0DCqcjKw:-K80irRrjrrO0DCqcjKx:1210212743) ([raw file](https://github.com/valloric/ycmd/blob/51cf2dc337d822f3ed36381fbf8572fc2dd15c2e/cpp/ycm/ClangCompleter/TranslationUnit.cpp#L60)):*
spaces inside the parentesis

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/276#-:-K80jEBOfoZWu4k9kSPg:-1121711443)*

**Comment by d0k** [comment]
Review status: 81 of 82 files reviewed at latest revision, 6 unresolved discussions.

---

*[cpp/ycm/ClangCompleter/TranslationUnit.cpp, line 60 \[r7\]](https://reviewable.io:443/reviews/valloric/ycmd/276#-K80irRrjrrO0DCqcjKw:-K80oafC5Mbm0S6HllXb:-499146009) ([raw file](https://github.com/valloric/ycmd/blob/51cf2dc337d822f3ed36381fbf8572fc2dd15c2e/cpp/ycm/ClangCompleter/TranslationUnit.cpp#L60)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/valloric/ycmd/276)*

**Comment by Valloric** [comment]
Ok, let's go with it then. :)

Thanks for the PR!

@homu r+

**Pull request merged**
