### PR TITLE
[READY] Boost clean up and update

### PR DESCRIPTION
**Pull request by bstaletic**
After merging #719 the only thing left to do is update boost and clean up `BoostParts`.
This PR takes care of that.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/741)

### CODE REVIEW

**Comment by micbou** [comment]
Thanks. LGTM.

**Comment by bstaletic** [comment]
Review status: 0 of 1054 files reviewed at latest revision, 1 unresolved discussion.

---

*[update_boost.py, line 33 at r1](https://reviewable.io:443/reviews/valloric/ycmd/741#-Ki7Iaoz2hFxXBHl0GHR:-Ki7Iap-9-TNONXCyigy:b64h76z) ([raw file](https://github.com/valloric/ycmd/blob/1119178de23364e09c222fe44f41be38accfed67/update_boost.py#L33)):*
> ```Python
> BOOST_VERSION_REGEX = re.compile( 'Version (\d+\.\d+\.\d+)' )
> BOOST_URL = ( 'https://sourceforge.net/projects/boost/files/boost/'
>               '{version}/{archive}/download' )
> ```

The new url targets the link provided on boost.org. It's a link to the latest boost beersion. It is updated a few days before sourceforge, but doesn't contain previous versions. Should I change it back to the original sourceforge url?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/741)*

**Comment by micbou** [comment]
> The new url targets the link provided on boost.org. It's a link to the latest boost beersion. It is updated a few days before sourceforge, but doesn't contain previous versions. Should I change it back to the original sourceforge url?

Let's keep the old url. 1.64.0 is already available on sourceforge.

**Comment by bstaletic** [comment]
I pushed the commit that reverts the url to the sourceforge one.

**Comment by vheon** [comment]
Reviewed 3 of 1054 files at r1, 1 of 1 files at r2.
Review status: 4 of 1054 files reviewed at latest revision, 3 unresolved discussions.

---

*[update_boost.py, line 33 at r2](https://reviewable.io:443/reviews/valloric/ycmd/741#-KiB7_A8HMfoqb-WyGDP:-KiB7_A97tv-HCCUZDhl:b-fyztvc) ([raw file](https://github.com/valloric/ycmd/blob/9f920d6104a73d98ef86b4f221a2cdb9010b01b3/update_boost.py#L33)):*
> ```Python
> BOOST_VERSION_REGEX = re.compile( 'Version (\d+\.\d+\.\d+)' )
> BOOST_URL = ( 'https://sourceforge.net/projects/boost/files/boost/'
>                       '{version}/{archive}/download' )
> ```

can you fix the indentation here?

---

*[cpp/ycm/CMakeLists.txt, line 215 at r2](https://reviewable.io:443/reviews/valloric/ycmd/741#-KiB8bWhWWCfRwjBeXT2:-KiB8bWilFnR9psdEWFD:b-ufwqr4) ([raw file](https://github.com/valloric/ycmd/blob/1119178de23364e09c222fe44f41be38accfed67/cpp/ycm/CMakeLists.txt#L215)):*
> ```CMake
> 
> if ( USE_SYSTEM_BOOST )
>   set( Boost_COMPONENTS filesystem system regex thread )
> ```

Do we still need `system`? We removed it from `BOOST_PARTS` in `update_boost.py`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/741)*

**Comment by Valloric** [comment]
:lgtm:



Thanks for putting in all this work! It was a long road, but we're at the end of it. :)

---

Review status: 4 of 1054 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/741#-:-KiBLxrrK9AKwSlEW9U0:b-cn8hge)*

**Comment by bstaletic** [comment]
Guys, sorry for not using Reviewable. It's unsuably slow on my machine on PR this big.

@vheon 
We still need `system`, because it's a dependency of `filesystem`.
The indentation is kept as it always was. I have no trouble changing it, but how should I change it exactly?

@Valloric 
It was my pleasure working on this piece of code. Though some bugs were annoying.
All in all, I get the feeling.

**Comment by micbou** [comment]
> Guys, sorry for not using Reviewable. It's unsuably slow on my machine on PR this big.

You are not alone.

> The indentation is kept as it always was. I have no trouble changing it, but how should I change it exactly?

Single quotes should be aligned:
```python
BOOST_URL = ( 'https://sourceforge.net/projects/boost/files/boost/'
              '{version}/{archive}/download' )
```

**Comment by bstaletic** [comment]
> Single quotes should be aligned:

Done.

**Comment by vheon** [comment]
:lgtm: @homu r=micbou

---

Reviewed 1 of 1 files at r3.
Review status: 4 of 1054 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/valloric/ycmd/741#-:-KiXCDfqjfg09j5QsF2A:b-v6qh3o)*

**Pull request merged**
